# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadEmpresa.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroEmpresa(object):
    def setupUi(self, frmCadastroEmpresa):
        frmCadastroEmpresa.setObjectName(_fromUtf8("frmCadastroEmpresa"))
        frmCadastroEmpresa.resize(890, 529)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroEmpresa.setFont(font)
        frmCadastroEmpresa.setSizeGripEnabled(True)
        frmCadastroEmpresa.setModal(True)

        self.grbDadosPessoaJuridica = QtGui.QGroupBox(frmCadastroEmpresa)
        self.grbDadosPessoaJuridica.setEnabled(False)
        self.grbDadosPessoaJuridica.setGeometry(QtCore.QRect(10, 3, 871, 161))
        self.grbDadosPessoaJuridica.setObjectName(_fromUtf8("grbDadosPessoaJuridica"))

        self.txtCnpj = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtCnpj.setEnabled(False)
        self.txtCnpj.setGeometry(QtCore.QRect(142, 38, 182, 25))
        self.txtCnpj.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpj.setText(_fromUtf8("../-"))
        self.txtCnpj.setCursorPosition(0)
        self.txtCnpj.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpj.setObjectName(_fromUtf8("txtCnpj"))

        self.lblRazaoSocial = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblRazaoSocial.setGeometry(QtCore.QRect(10, 64, 81, 19))
        self.lblRazaoSocial.setObjectName(_fromUtf8("lblRazaoSocial"))

        self.lblCnpj = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblCnpj.setGeometry(QtCore.QRect(142, 18, 41, 19))
        self.lblCnpj.setObjectName(_fromUtf8("lblCnpj"))

        self.txtRazaoSocial = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtRazaoSocial.setEnabled(False)
        self.txtRazaoSocial.setGeometry(QtCore.QRect(10, 84, 841, 25))
        self.txtRazaoSocial.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocial.setMaxLength(70)
        self.txtRazaoSocial.setObjectName(_fromUtf8("txtRazaoSocial"))

        self.lblNomeFantasia = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblNomeFantasia.setGeometry(QtCore.QRect(8, 108, 101, 19))
        self.lblNomeFantasia.setObjectName(_fromUtf8("lblNomeFantasia"))

        self.txtInscricaoEstadua = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtInscricaoEstadua.setEnabled(False)
        self.txtInscricaoEstadua.setGeometry(QtCore.QRect(330, 38, 178, 25))
        self.txtInscricaoEstadua.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadua.setMaxLength(8)
        self.txtInscricaoEstadua.setObjectName(_fromUtf8("txtInscricaoEstadua"))

        self.txtFantasia = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtFantasia.setEnabled(False)
        self.txtFantasia.setGeometry(QtCore.QRect(8, 128, 841, 25))
        self.txtFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasia.setMaxLength(70)
        self.txtFantasia.setObjectName(_fromUtf8("txtFantasia"))

        self.lblInscricaoEstadual = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblInscricaoEstadual.setGeometry(QtCore.QRect(330, 18, 121, 19))
        self.lblInscricaoEstadual.setObjectName(_fromUtf8("lblInscricaoEstadual"))

        self.lblCodigo = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblCodigo.setGeometry(QtCore.QRect(10, 18, 71, 19))
        self.lblCodigo.setObjectName(_fromUtf8("lblCodigo"))

        self.txtCodigo = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtCodigo.setGeometry(QtCore.QRect(10, 38, 121, 25))
        self.txtCodigo.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCodigo.setMaxLength(8)
        self.txtCodigo.setObjectName(_fromUtf8("txtCodigo"))

        self.btnPesquisarEmpresa = QtGui.QPushButton(self.grbDadosPessoaJuridica)
        self.btnPesquisarEmpresa.setGeometry(QtCore.QRect(123, 50, 16, 16))
        self.btnPesquisarEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarEmpresa.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search_mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarEmpresa.setIcon(icon)
        self.btnPesquisarEmpresa.setFlat(True)
        self.btnPesquisarEmpresa.setObjectName(_fromUtf8("btnPesquisarEmpresa"))

        self.tabWiAdicionais = QtGui.QTabWidget(frmCadastroEmpresa)
        self.tabWiAdicionais.setEnabled(False)
        self.tabWiAdicionais.setGeometry(QtCore.QRect(10, 180, 871, 281))
        self.tabWiAdicionais.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWiAdicionais.setDocumentMode(True)
        self.tabWiAdicionais.setObjectName(_fromUtf8("tabWiAdicionais"))

        self.geral = QtGui.QWidget()
        self.geral.setObjectName(_fromUtf8("geral"))

        self.cBoxTipoEmpresa = QtGui.QComboBox(self.geral)
        self.cBoxTipoEmpresa.setGeometry(QtCore.QRect(10, 40, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.cBoxTipoEmpresa.setPalette(palette)
        self.cBoxTipoEmpresa.setObjectName(_fromUtf8("cBoxTipoEmpresa"))

        self.lblInscricaoMunicipal = QtGui.QLabel(self.geral)
        self.lblInscricaoMunicipal.setGeometry(QtCore.QRect(200, 20, 141, 19))
        self.lblInscricaoMunicipal.setObjectName(_fromUtf8("lblInscricaoMunicipal"))

        self.lblTipoEmpresa = QtGui.QLabel(self.geral)
        self.lblTipoEmpresa.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.lblTipoEmpresa.setObjectName(_fromUtf8("lblTipoEmpresa"))

        self.txtInscricaoMunicipal = QtGui.QLineEdit(self.geral)
        self.txtInscricaoMunicipal.setGeometry(QtCore.QRect(200, 40, 171, 25))
        self.txtInscricaoMunicipal.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoMunicipal.setMaxLength(8)
        self.txtInscricaoMunicipal.setObjectName(_fromUtf8("txtInscricaoMunicipal"))

        self.grbAtivo = QtGui.QGroupBox(self.geral)
        self.grbAtivo.setEnabled(False)
        self.grbAtivo.setGeometry(QtCore.QRect(400, 10, 120, 61))
        self.grbAtivo.setObjectName(_fromUtf8("grbAtivo"))

        self.radBtnAtivo = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnAtivo.setGeometry(QtCore.QRect(20, 20, 61, 17))
        self.radBtnAtivo.setObjectName(_fromUtf8("radBtnAtivo"))

        self.radBtnDesativo = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnDesativo.setGeometry(QtCore.QRect(20, 40, 81, 17))
        self.radBtnDesativo.setObjectName(_fromUtf8("radBtnDesativo"))

        self.tabWiAdicionais.addTab(self.geral, _fromUtf8(""))
        self.contatos = QtGui.QWidget()
        self.contatos.setObjectName(_fromUtf8("contatos"))

        self.tabContatoTelefone = QtGui.QTableWidget(self.contatos)
        self.tabContatoTelefone.setGeometry(QtCore.QRect(13, 84, 361, 141))
        self.tabContatoTelefone.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabContatoTelefone.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabContatoTelefone.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabContatoTelefone.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabContatoTelefone.setObjectName(_fromUtf8("tabContatoTelefone"))

        self.tabContatoTelefone.setColumnCount(2)
        self.tabContatoTelefone.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabContatoTelefone.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabContatoTelefone.setHorizontalHeaderItem(1, item)
        self.tabContatoTelefone.horizontalHeader().setStretchLastSection(True)
        self.tabContatoTelefone.verticalHeader().setVisible(False)
        self.btnRemoverTelefone = QtGui.QPushButton(self.contatos)
        self.btnRemoverTelefone.setGeometry(QtCore.QRect(343, 230, 31, 27))
        self.btnRemoverTelefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverTelefone.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoverTelefone.setIcon(icon1)
        self.btnRemoverTelefone.setObjectName(_fromUtf8("btnRemoverTelefone"))

        self.btnAddEmail = QtGui.QPushButton(self.contatos)
        self.btnAddEmail.setGeometry(QtCore.QRect(823, 39, 31, 27))
        self.btnAddEmail.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddEmail.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddEmail.setIcon(icon2)
        self.btnAddEmail.setObjectName(_fromUtf8("btnAddEmail"))

        self.lblContatoTelefone = QtGui.QLabel(self.contatos)
        self.lblContatoTelefone.setGeometry(QtCore.QRect(13, 27, 53, 13))
        self.lblContatoTelefone.setObjectName(_fromUtf8("lblContatoTelefone"))

        self.lblContatoEmail = QtGui.QLabel(self.contatos)
        self.lblContatoEmail.setGeometry(QtCore.QRect(493, 16, 53, 13))
        self.lblContatoEmail.setObjectName(_fromUtf8("lblContatoEmail"))

        self.btnAddTelefone = QtGui.QPushButton(self.contatos)
        self.btnAddTelefone.setGeometry(QtCore.QRect(343, 50, 31, 27))
        self.btnAddTelefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddTelefone.setText(_fromUtf8(""))
        self.btnAddTelefone.setIcon(icon2)
        self.btnAddTelefone.setObjectName(_fromUtf8("btnAddTelefone"))

        self.txtNumeroTelefone = QtGui.QLineEdit(self.contatos)
        self.txtNumeroTelefone.setGeometry(QtCore.QRect(73, 51, 261, 25))
        self.txtNumeroTelefone.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtNumeroTelefone.setMaxLength(15)
        self.txtNumeroTelefone.setObjectName(_fromUtf8("txtNumeroTelefone"))

        self.txtEnderecoEmail = QtGui.QLineEdit(self.contatos)
        self.txtEnderecoEmail.setGeometry(QtCore.QRect(553, 40, 261, 25))
        self.txtEnderecoEmail.setMaxLength(50)
        self.txtEnderecoEmail.setObjectName(_fromUtf8("txtEnderecoEmail"))

        self.txtContatoEmail = QtGui.QLineEdit(self.contatos)
        self.txtContatoEmail.setGeometry(QtCore.QRect(553, 10, 261, 25))
        self.txtContatoEmail.setMaxLength(25)
        self.txtContatoEmail.setObjectName(_fromUtf8("txtContatoEmail"))

        self.tabContatoEmail = QtGui.QTableWidget(self.contatos)
        self.tabContatoEmail.setGeometry(QtCore.QRect(493, 73, 361, 151))
        self.tabContatoEmail.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabContatoEmail.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabContatoEmail.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabContatoEmail.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabContatoEmail.setObjectName(_fromUtf8("tabContatoEmail"))

        self.tabContatoEmail.setColumnCount(2)
        self.tabContatoEmail.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabContatoEmail.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabContatoEmail.setHorizontalHeaderItem(1, item)
        self.tabContatoEmail.horizontalHeader().setStretchLastSection(True)
        self.tabContatoEmail.verticalHeader().setVisible(False)
        self.txtContatoTelefone = QtGui.QLineEdit(self.contatos)
        self.txtContatoTelefone.setGeometry(QtCore.QRect(73, 21, 261, 25))
        self.txtContatoTelefone.setMaxLength(25)
        self.txtContatoTelefone.setObjectName(_fromUtf8("txtContatoTelefone"))

        self.lblEmail = QtGui.QLabel(self.contatos)
        self.lblEmail.setGeometry(QtCore.QRect(493, 44, 61, 16))
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))

        self.btnRemoverEmail = QtGui.QPushButton(self.contatos)
        self.btnRemoverEmail.setGeometry(QtCore.QRect(823, 230, 31, 27))
        self.btnRemoverEmail.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverEmail.setText(_fromUtf8(""))
        self.btnRemoverEmail.setIcon(icon1)
        self.btnRemoverEmail.setObjectName(_fromUtf8("btnRemoverEmail"))

        self.lblTelefone = QtGui.QLabel(self.contatos)
        self.lblTelefone.setGeometry(QtCore.QRect(13, 55, 61, 16))
        self.lblTelefone.setObjectName(_fromUtf8("lblTelefone"))

        self.tabWiAdicionais.addTab(self.contatos, _fromUtf8(""))
        self.cadastroSetores = QtGui.QWidget()
        self.cadastroSetores.setObjectName(_fromUtf8("cadastroSetores"))

        self.txtCadSetoresSetor = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresSetor.setGeometry(QtCore.QRect(60, 21, 291, 25))
        self.txtCadSetoresSetor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadSetoresSetor.setMaxLength(50)
        self.txtCadSetoresSetor.setObjectName(_fromUtf8("txtCadSetoresSetor"))

        self.lblCadSetoresSetor = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresSetor.setGeometry(QtCore.QRect(10, 23, 41, 19))
        self.lblCadSetoresSetor.setObjectName(_fromUtf8("lblCadSetoresSetor"))

        self.tabSetores = QtGui.QTableWidget(self.cadastroSetores)
        self.tabSetores.setGeometry(QtCore.QRect(10, 61, 391, 141))
        self.tabSetores.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabSetores.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabSetores.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabSetores.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabSetores.setObjectName(_fromUtf8("tabSetores"))

        self.tabSetores.setColumnCount(1)
        self.tabSetores.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabSetores.setHorizontalHeaderItem(0, item)
        self.tabSetores.horizontalHeader().setStretchLastSection(True)
        self.tabSetores.verticalHeader().setVisible(False)
        self.btnAddSetor = QtGui.QPushButton(self.cadastroSetores)
        self.btnAddSetor.setGeometry(QtCore.QRect(370, 20, 31, 27))
        self.btnAddSetor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddSetor.setText(_fromUtf8(""))
        self.btnAddSetor.setIcon(icon2)
        self.btnAddSetor.setObjectName(_fromUtf8("btnAddSetor"))

        self.btnRemoverSetor = QtGui.QPushButton(self.cadastroSetores)
        self.btnRemoverSetor.setGeometry(QtCore.QRect(370, 210, 31, 27))
        self.btnRemoverSetor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverSetor.setText(_fromUtf8(""))
        self.btnRemoverSetor.setIcon(icon1)
        self.btnRemoverSetor.setObjectName(_fromUtf8("btnRemoverSetor"))

        self.lblCadCargoCargo = QtGui.QLabel(self.cadastroSetores)
        self.lblCadCargoCargo.setGeometry(QtCore.QRect(460, 23, 41, 19))
        self.lblCadCargoCargo.setObjectName(_fromUtf8("lblCadCargoCargo"))

        self.btnRemoverCargos = QtGui.QPushButton(self.cadastroSetores)
        self.btnRemoverCargos.setGeometry(QtCore.QRect(820, 210, 31, 27))
        self.btnRemoverCargos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverCargos.setText(_fromUtf8(""))
        self.btnRemoverCargos.setIcon(icon1)
        self.btnRemoverCargos.setObjectName(_fromUtf8("btnRemoverCargos"))

        self.txtCadCargoCargo = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadCargoCargo.setGeometry(QtCore.QRect(510, 21, 291, 25))
        self.txtCadCargoCargo.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadCargoCargo.setMaxLength(50)
        self.txtCadCargoCargo.setObjectName(_fromUtf8("txtCadCargoCargo"))

        self.btnAddCargos = QtGui.QPushButton(self.cadastroSetores)
        self.btnAddCargos.setGeometry(QtCore.QRect(820, 20, 31, 27))
        self.btnAddCargos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddCargos.setText(_fromUtf8(""))
        self.btnAddCargos.setIcon(icon2)
        self.btnAddCargos.setObjectName(_fromUtf8("btnAddCargos"))

        self.tabCargos = QtGui.QTableWidget(self.cadastroSetores)
        self.tabCargos.setGeometry(QtCore.QRect(460, 61, 391, 141))
        self.tabCargos.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabCargos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabCargos.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabCargos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabCargos.setObjectName(_fromUtf8("tabCargos"))
        self.tabCargos.setColumnCount(1)
        self.tabCargos.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabCargos.setHorizontalHeaderItem(0, item)
        self.tabCargos.horizontalHeader().setStretchLastSection(True)
        self.tabCargos.verticalHeader().setVisible(False)
        self.tabWiAdicionais.addTab(self.cadastroSetores, _fromUtf8(""))
        self.grbBotoes = QtGui.QGroupBox(frmCadastroEmpresa)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 470, 871, 51))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(360, 12, 88, 27))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon3)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(460, 12, 88, 27))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon4)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(660, 12, 88, 27))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon5)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(760, 10, 88, 27))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/critical.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeletar.setIcon(icon6)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(560, 12, 88, 27))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/Save-as_37111.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon7)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.lblPesquisar = QtGui.QLabel(self.grbBotoes)
        self.lblPesquisar.setGeometry(QtCore.QRect(10, 20, 111, 19))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblPesquisar.setPalette(palette)
        self.lblPesquisar.setObjectName(_fromUtf8("lblPesquisar"))

        self.lblRazaoSocial.setBuddy(self.txtRazaoSocial)
        self.lblCnpj.setBuddy(self.txtCnpj)
        self.lblNomeFantasia.setBuddy(self.txtFantasia)
        self.lblInscricaoEstadual.setBuddy(self.txtInscricaoEstadua)
        self.lblCodigo.setBuddy(self.txtCodigo)
        self.lblInscricaoMunicipal.setBuddy(self.txtInscricaoMunicipal)
        self.lblTipoEmpresa.setBuddy(self.cBoxTipoEmpresa)
        self.lblCadSetoresSetor.setBuddy(self.txtCadSetoresSetor)
        self.lblCadCargoCargo.setBuddy(self.txtCadCargoCargo)

        self.retranslateUi(frmCadastroEmpresa)
        self.tabWiAdicionais.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroEmpresa)
        frmCadastroEmpresa.setTabOrder(self.txtCodigo, self.txtCnpj)
        frmCadastroEmpresa.setTabOrder(self.txtCnpj, self.txtInscricaoEstadua)
        frmCadastroEmpresa.setTabOrder(self.txtInscricaoEstadua, self.txtRazaoSocial)
        frmCadastroEmpresa.setTabOrder(self.txtRazaoSocial, self.txtFantasia)
        frmCadastroEmpresa.setTabOrder(self.txtFantasia, self.tabWiAdicionais)
        frmCadastroEmpresa.setTabOrder(self.tabWiAdicionais, self.cBoxTipoEmpresa)
        frmCadastroEmpresa.setTabOrder(self.cBoxTipoEmpresa, self.txtInscricaoMunicipal)
        frmCadastroEmpresa.setTabOrder(self.txtInscricaoMunicipal, self.radBtnAtivo)
        frmCadastroEmpresa.setTabOrder(self.radBtnAtivo, self.radBtnDesativo)
        frmCadastroEmpresa.setTabOrder(self.radBtnDesativo, self.txtContatoTelefone)
        frmCadastroEmpresa.setTabOrder(self.txtContatoTelefone, self.txtNumeroTelefone)
        frmCadastroEmpresa.setTabOrder(self.txtNumeroTelefone, self.txtContatoEmail)
        frmCadastroEmpresa.setTabOrder(self.txtContatoEmail, self.txtEnderecoEmail)
        frmCadastroEmpresa.setTabOrder(self.txtEnderecoEmail, self.txtCadSetoresSetor)
        frmCadastroEmpresa.setTabOrder(self.txtCadSetoresSetor, self.txtCadCargoCargo)

    def retranslateUi(self, frmCadastroEmpresa):
        frmCadastroEmpresa.setWindowTitle(_translate("frmCadastroEmpresa", "Cadastro Empresa", None))
        self.grbDadosPessoaJuridica.setWhatsThis(_translate("frmCadastroEmpresa", "Grupo de Dados para cadastro e edição de empresas", None))
        self.grbDadosPessoaJuridica.setTitle(_translate("frmCadastroEmpresa", "Dados Pessoa Juridica", None))
        self.txtCnpj.setToolTip(_translate("frmCadastroEmpresa", "CNPJ", None))
        self.txtCnpj.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do numero do CNPJ da empresa", None))
        self.txtCnpj.setInputMask(_translate("frmCadastroEmpresa", "00.000.000/0000-00; ", None))
        self.lblRazaoSocial.setText(_translate("frmCadastroEmpresa", "Razão Social", None))
        self.lblCnpj.setText(_translate("frmCadastroEmpresa", "CNPJ", None))
        self.txtRazaoSocial.setToolTip(_translate("frmCadastroEmpresa", "Razão Social", None))
        self.txtRazaoSocial.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do nome da razão social da empresa", None))
        self.lblNomeFantasia.setText(_translate("frmCadastroEmpresa", "Fantasia", None))
        self.txtInscricaoEstadua.setToolTip(_translate("frmCadastroEmpresa", "Inscrição Estadual", None))
        self.txtInscricaoEstadua.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do numero do inscrição estadual da empresa", None))
        self.txtFantasia.setToolTip(_translate("frmCadastroEmpresa", "Nome Fantasia", None))
        self.txtFantasia.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do nome fantasia da empresa", None))
        self.lblInscricaoEstadual.setText(_translate("frmCadastroEmpresa", "Incrição Estadual", None))
        self.lblCodigo.setText(_translate("frmCadastroEmpresa", "Codigo", None))
        self.txtCodigo.setToolTip(_translate("frmCadastroEmpresa", "Inscrição Estadual", None))
        self.txtCodigo.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Campo do numero de identificação da pessoa juridica</p></body></html>", None))
        self.btnPesquisarEmpresa.setWhatsThis(_translate("frmCadastroEmpresa", "Botão para pesquisar dados de empresa", None))
        self.tabWiAdicionais.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão adicionar um novo cargo a lista</p></body></html>", None))
        self.cBoxTipoEmpresa.setToolTip(_translate("frmCadastroEmpresa", "Tipo de Empresa", None))
        self.cBoxTipoEmpresa.setWhatsThis(_translate("frmCadastroEmpresa", "Campo de escolha qual é  o tipo da empresa", None))
        self.lblInscricaoMunicipal.setText(_translate("frmCadastroEmpresa", "Inscrição Municipal", None))
        self.lblTipoEmpresa.setText(_translate("frmCadastroEmpresa", "Tipo de Empresa", None))
        self.txtInscricaoMunicipal.setToolTip(_translate("frmCadastroEmpresa", "Inscrição Municipal", None))
        self.txtInscricaoMunicipal.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do numero do inscrição municipal da empresa", None))
        self.grbAtivo.setTitle(_translate("frmCadastroEmpresa", "Situação", None))
        self.radBtnAtivo.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Item de seleção para empresa ativa e operante</p></body></html>", None))
        self.radBtnAtivo.setText(_translate("frmCadastroEmpresa", "Ativo", None))
        self.radBtnDesativo.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Item de seleção para empresa desativado e inoperante</p></body></html>", None))
        self.radBtnDesativo.setText(_translate("frmCadastroEmpresa", "Desativo", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.geral), _translate("frmCadastroEmpresa", "Geral", None))
        self.tabContatoTelefone.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Tabela de informações de contato de telefone</p></body></html>", None))
        item = self.tabContatoTelefone.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroEmpresa", "Contato", None))
        item = self.tabContatoTelefone.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroEmpresa", "Telefone", None))
        self.btnRemoverTelefone.setToolTip(_translate("frmCadastroEmpresa", "Remover", None))
        self.btnRemoverTelefone.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão remover um contato  de telefone a lista</p></body></html>", None))
        self.btnAddEmail.setToolTip(_translate("frmCadastroEmpresa", "Adicionar", None))
        self.btnAddEmail.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão adicionar um contato de e-mail a lista</p></body></html>", None))
        self.lblContatoTelefone.setText(_translate("frmCadastroEmpresa", "Contato", None))
        self.lblContatoEmail.setText(_translate("frmCadastroEmpresa", "Contato", None))
        self.btnAddTelefone.setToolTip(_translate("frmCadastroEmpresa", "Adicionar", None))
        self.btnAddTelefone.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão adicionar um contato de telefone a lista</p></body></html>", None))
        self.txtNumeroTelefone.setToolTip(_translate("frmCadastroEmpresa", "Telefone", None))
        self.txtNumeroTelefone.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Campo do numero de telefone do contato</p></body></html>", None))
        self.txtEnderecoEmail.setToolTip(_translate("frmCadastroEmpresa", "E-mail", None))
        self.txtEnderecoEmail.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Campo do endereço de e-mail do contato</p></body></html>", None))
        self.txtContatoEmail.setToolTip(_translate("frmCadastroEmpresa", "Contato", None))
        self.txtContatoEmail.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Campo do nome do contato</p></body></html>", None))
        self.tabContatoEmail.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Tabela de informações de endereço de e-mail</p></body></html>", None))
        item = self.tabContatoEmail.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroEmpresa", "Contato", None))
        item = self.tabContatoEmail.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroEmpresa", "E-mail", None))
        self.txtContatoTelefone.setToolTip(_translate("frmCadastroEmpresa", "Contato", None))
        self.txtContatoTelefone.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Campo do nome do contato</p></body></html>", None))
        self.lblEmail.setText(_translate("frmCadastroEmpresa", "E-mail", None))
        self.btnRemoverEmail.setToolTip(_translate("frmCadastroEmpresa", "Remover", None))
        self.btnRemoverEmail.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão remover um contato de e-mail da lista</p></body></html>", None))
        self.lblTelefone.setText(_translate("frmCadastroEmpresa", "Telefone", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.contatos), _translate("frmCadastroEmpresa", "Contato", None))
        self.txtCadSetoresSetor.setToolTip(_translate("frmCadastroEmpresa", "Setor", None))
        self.txtCadSetoresSetor.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do nome do setor", None))
        self.lblCadSetoresSetor.setText(_translate("frmCadastroEmpresa", "Setor", None))
        self.tabSetores.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Tabela de informação dos setores</p></body></html>", None))
        item = self.tabSetores.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroEmpresa", "Setor", None))
        self.btnAddSetor.setToolTip(_translate("frmCadastroEmpresa", "Adicionar", None))
        self.btnAddSetor.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão adicionar um novo setor a lista</p></body></html>", None))
        self.btnRemoverSetor.setToolTip(_translate("frmCadastroEmpresa", "Remover", None))
        self.btnRemoverSetor.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão remover um setor da lista</p></body></html>", None))
        self.lblCadCargoCargo.setText(_translate("frmCadastroEmpresa", "Cargo", None))
        self.btnRemoverCargos.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão remover um cargo da lista</p></body></html>", None))
        self.txtCadCargoCargo.setToolTip(_translate("frmCadastroEmpresa", "Cargo", None))
        self.txtCadCargoCargo.setWhatsThis(_translate("frmCadastroEmpresa", "Campo do nome do cargo", None))
        self.tabCargos.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Tabela de informação dos cargos</p></body></html>", None))
        item = self.tabCargos.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroEmpresa", "Cargo", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.cadastroSetores), _translate("frmCadastroEmpresa", "Adicionar Setores / Cargos", None))
        self.btnNovo.setToolTip(_translate("frmCadastroEmpresa", "Novo", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão para cadastrar uma novo registro da pessoa jurídica</p></body></html>", None))
        self.btnNovo.setText(_translate("frmCadastroEmpresa", "Novo", None))
        self.btnSalvar.setToolTip(_translate("frmCadastroEmpresa", "Salvar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão para salvar um novo registro da pessoa jurídica</p></body></html>", None))
        self.btnSalvar.setText(_translate("frmCadastroEmpresa", "Salvar", None))
        self.btnCancelar.setToolTip(_translate("frmCadastroEmpresa", "Cancelar", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroEmpresa", "Botão para cancelar a operação ", None))
        self.btnCancelar.setText(_translate("frmCadastroEmpresa", "Cancelar", None))
        self.btnDeletar.setToolTip(_translate("frmCadastroEmpresa", "Deletar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão de deletar o registro da pessoa jurídica</p></body></html>", None))
        self.btnDeletar.setText(_translate("frmCadastroEmpresa", "Deletar", None))
        self.btnEditar.setToolTip(_translate("frmCadastroEmpresa", "Editar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroEmpresa", "<html><head/><body><p>Botão para salvar o registo editado da pessoa jurídica</p></body></html>", None))
        self.btnEditar.setText(_translate("frmCadastroEmpresa", "Editar", None))
        self.lblPesquisar.setText(_translate("frmCadastroEmpresa", "[F12] Pesquisar", None))

