# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroFuncionario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

import datetime
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroFuncionario(object):
    def setupUi(self, frmCadastroFuncionario):
        frmCadastroFuncionario.setObjectName(_fromUtf8("frmCadastroFuncionario"))
        frmCadastroFuncionario.resize(850, 653)
        frmCadastroFuncionario.setMinimumSize(QtCore.QSize(850, 653))
        frmCadastroFuncionario.setMaximumSize(QtCore.QSize(850, 653))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroFuncionario.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/funcionario.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCadastroFuncionario.setWindowIcon(icon)
        frmCadastroFuncionario.setSizeGripEnabled(False)
        frmCadastroFuncionario.setModal(True)

        self.txtIdEmpresa = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtIdEmpresa.setEnabled(False)
        self.txtIdEmpresa.setGeometry(QtCore.QRect(12, 20, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresa.setPalette(palette)
        self.txtIdEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdEmpresa.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdEmpresa.setMaxLength(11)
        self.txtIdEmpresa.setObjectName(_fromUtf8("txtIdEmpresa"))

        self.lblNomeFantasia = QtGui.QLabel(frmCadastroFuncionario)
        self.lblNomeFantasia.setGeometry(QtCore.QRect(162, 0, 101, 19))
        self.lblNomeFantasia.setObjectName(_fromUtf8("lblNomeFantasia"))

        self.lblRazaoSocial = QtGui.QLabel(frmCadastroFuncionario)
        self.lblRazaoSocial.setGeometry(QtCore.QRect(12, 45, 91, 19))
        self.lblRazaoSocial.setObjectName(_fromUtf8("lblRazaoSocial"))

        self.txtInscricaoEstadua = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtInscricaoEstadua.setEnabled(False)
        self.txtInscricaoEstadua.setGeometry(QtCore.QRect(658, 65, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstadua.setPalette(palette)
        self.txtInscricaoEstadua.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstadua.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtInscricaoEstadua.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadua.setMaxLength(8)
        self.txtInscricaoEstadua.setObjectName(_fromUtf8("txtInscricaoEstadua"))

        self.lblInscricaoEstadual = QtGui.QLabel(frmCadastroFuncionario)
        self.lblInscricaoEstadual.setGeometry(QtCore.QRect(658, 45, 121, 19))
        self.lblInscricaoEstadual.setObjectName(_fromUtf8("lblInscricaoEstadual"))

        self.lblCodigoEmpresa = QtGui.QLabel(frmCadastroFuncionario)
        self.lblCodigoEmpresa.setGeometry(QtCore.QRect(12, 0, 111, 19))
        self.lblCodigoEmpresa.setObjectName(_fromUtf8("lblCodigoEmpresa"))

        self.lblCnpj = QtGui.QLabel(frmCadastroFuncionario)
        self.lblCnpj.setGeometry(QtCore.QRect(452, 45, 41, 19))
        self.lblCnpj.setObjectName(_fromUtf8("lblCnpj"))

        self.txtCnpj = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtCnpj.setEnabled(False)
        self.txtCnpj.setGeometry(QtCore.QRect(450, 65, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpj.setPalette(palette)
        self.txtCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCnpj.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpj.setText(_fromUtf8("../-"))
        self.txtCnpj.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpj.setObjectName(_fromUtf8("txtCnpj"))

        self.txtRazaoSocial = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtRazaoSocial.setEnabled(False)
        self.txtRazaoSocial.setGeometry(QtCore.QRect(12, 65, 431, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocial.setPalette(palette)
        self.txtRazaoSocial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRazaoSocial.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocial.setMaxLength(70)
        self.txtRazaoSocial.setObjectName(_fromUtf8("txtRazaoSocial"))

        self.txtFantasia = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtFantasia.setEnabled(False)
        self.txtFantasia.setGeometry(QtCore.QRect(162, 20, 471, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasia.setPalette(palette)
        self.txtFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasia.setMaxLength(70)
        self.txtFantasia.setObjectName(_fromUtf8("txtFantasia"))

        self.btnPesquisar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnPesquisar.setEnabled(False)
        self.btnPesquisar.setGeometry(QtCore.QRect(644, 20, 31, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisar.setIcon(icon)
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.grbFuncionario = QtGui.QGroupBox(frmCadastroFuncionario)
        self.grbFuncionario.setEnabled(False)
        self.grbFuncionario.setGeometry(QtCore.QRect(5, 100, 841, 315))
        self.grbFuncionario.setTitle(_fromUtf8(""))
        self.grbFuncionario.setObjectName(_fromUtf8("grbFuncionario"))

        self.lblNomeFuncionario = QtGui.QLabel(self.grbFuncionario)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(178, 1, 121, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))

        self.txtNomeMae = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomeMae.setGeometry(QtCore.QRect(8, 108, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMae.setPalette(palette)
        self.txtNomeMae.setMaxLength(70)
        self.txtNomeMae.setObjectName(_fromUtf8("txtNomeMae"))

        self.txtExpeditor = QtGui.QLineEdit(self.grbFuncionario)
        self.txtExpeditor.setGeometry(QtCore.QRect(210, 64, 113, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtExpeditor.setPalette(palette)
        self.txtExpeditor.setMaxLength(5)
        self.txtExpeditor.setObjectName(_fromUtf8("txtExpeditor"))

        self.txtRg = QtGui.QLineEdit(self.grbFuncionario)
        self.txtRg.setGeometry(QtCore.QRect(6, 64, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRg.setPalette(palette)
        self.txtRg.setObjectName(_fromUtf8("txtRg"))

        self.lblDataNascimento = QtGui.QLabel(self.grbFuncionario)
        self.lblDataNascimento.setGeometry(QtCore.QRect(534, 44, 111, 19))
        self.lblDataNascimento.setObjectName(_fromUtf8("lblDataNascimento"))

        self.txtDataNascimento = QtGui.QDateEdit(self.grbFuncionario)
        self.txtDataNascimento.setDate(QDate.currentDate())
        self.txtDataNascimento.setGeometry(QtCore.QRect(534, 64, 119, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtDataNascimento.setPalette(palette)
        self.txtDataNascimento.setCalendarPopup(True)
        self.txtDataNascimento.setObjectName(_fromUtf8("txtDataNascimento"))

        self.lblCep = QtGui.QLabel(self.grbFuncionario)
        self.lblCep.setGeometry(QtCore.QRect(365, 176, 31, 19))
        self.lblCep.setObjectName(_fromUtf8("lblCep"))

        self.txtComplemento = QtGui.QLineEdit(self.grbFuncionario)
        self.txtComplemento.setGeometry(QtCore.QRect(610, 151, 221, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplemento.setPalette(palette)
        self.txtComplemento.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtComplemento.setMaxLength(50)
        self.txtComplemento.setObjectName(_fromUtf8("txtComplemento"))

        self.lblNomePai = QtGui.QLabel(self.grbFuncionario)
        self.lblNomePai.setGeometry(QtCore.QRect(440, 88, 71, 19))
        self.lblNomePai.setObjectName(_fromUtf8("lblNomePai"))

        self.txtCidades = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCidades.setEnabled(False)
        self.txtCidades.setGeometry(QtCore.QRect(523, 196, 306, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidades.setPalette(palette)
        self.txtCidades.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidades.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidades.setMaxLength(70)
        self.txtCidades.setObjectName(_fromUtf8("txtCidades"))

        self.lblCpf = QtGui.QLabel(self.grbFuncionario)
        self.lblCpf.setGeometry(QtCore.QRect(328, 44, 31, 19))
        self.lblCpf.setObjectName(_fromUtf8("lblCpf"))

        self.txtNomePai = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomePai.setGeometry(QtCore.QRect(440, 108, 391, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomePai.setPalette(palette)
        self.txtNomePai.setMaxLength(70)
        self.txtNomePai.setObjectName(_fromUtf8("txtNomePai"))

        self.txtEstados = QtGui.QLineEdit(self.grbFuncionario)
        self.txtEstados.setEnabled(False)
        self.txtEstados.setGeometry(QtCore.QRect(10, 240, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstados.setPalette(palette)
        self.txtEstados.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstados.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstados.setMaxLength(50)
        self.txtEstados.setObjectName(_fromUtf8("txtEstados"))

        self.txtEndereco = QtGui.QLineEdit(self.grbFuncionario)
        self.txtEndereco.setGeometry(QtCore.QRect(8, 152, 431, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEndereco.setPalette(palette)
        self.txtEndereco.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEndereco.setMaxLength(50)
        self.txtEndereco.setObjectName(_fromUtf8("txtEndereco"))

        self.lblExpeditor = QtGui.QLabel(self.grbFuncionario)
        self.lblExpeditor.setGeometry(QtCore.QRect(210, 44, 66, 19))
        self.lblExpeditor.setObjectName(_fromUtf8("lblExpeditor"))

        self.txtNumero = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNumero.setGeometry(QtCore.QRect(445, 152, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumero.setPalette(palette)
        self.txtNumero.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNumero.setMaxLength(11)
        self.txtNumero.setObjectName(_fromUtf8("txtNumero"))

        self.lblRg = QtGui.QLabel(self.grbFuncionario)
        self.lblRg.setGeometry(QtCore.QRect(6, 44, 31, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))

        self.lblTelefoene = QtGui.QLabel(self.grbFuncionario)
        self.lblTelefoene.setGeometry(QtCore.QRect(190, 220, 61, 19))
        self.lblTelefoene.setObjectName(_fromUtf8("lblTelefoene"))

        self.txtBairro = QtGui.QLineEdit(self.grbFuncionario)
        self.txtBairro.setGeometry(QtCore.QRect(10, 196, 351, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairro.setPalette(palette)
        self.txtBairro.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtBairro.setMaxLength(50)
        self.txtBairro.setObjectName(_fromUtf8("txtBairro"))

        self.txtCelular = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCelular.setGeometry(QtCore.QRect(390, 240, 191, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCelular.setPalette(palette)
        self.txtCelular.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCelular.setObjectName(_fromUtf8("txtCelular"))

        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(178, 21, 653, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeFuncionario.setPalette(palette)
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))

        self.lblComplemento = QtGui.QLabel(self.grbFuncionario)
        self.lblComplemento.setGeometry(QtCore.QRect(610, 131, 101, 16))
        self.lblComplemento.setObjectName(_fromUtf8("lblComplemento"))

        self.lblEstados = QtGui.QLabel(self.grbFuncionario)
        self.lblEstados.setGeometry(QtCore.QRect(12, 220, 51, 19))
        self.lblEstados.setObjectName(_fromUtf8("lblEstados"))

        self.txtCpf = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCpf.setGeometry(QtCore.QRect(328, 64, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCpf.setPalette(palette)
        self.txtCpf.setObjectName(_fromUtf8("txtCpf"))

        self.lblBairro = QtGui.QLabel(self.grbFuncionario)
        self.lblBairro.setGeometry(QtCore.QRect(10, 176, 41, 19))
        self.lblBairro.setObjectName(_fromUtf8("lblBairro"))

        self.lblCerlular = QtGui.QLabel(self.grbFuncionario)
        self.lblCerlular.setGeometry(QtCore.QRect(390, 220, 61, 19))
        self.lblCerlular.setObjectName(_fromUtf8("lblCerlular"))

        self.lblNumero = QtGui.QLabel(self.grbFuncionario)
        self.lblNumero.setGeometry(QtCore.QRect(445, 132, 51, 19))
        self.lblNumero.setObjectName(_fromUtf8("lblNumero"))

        self.lblCidades = QtGui.QLabel(self.grbFuncionario)
        self.lblCidades.setGeometry(QtCore.QRect(522, 176, 51, 19))
        self.lblCidades.setObjectName(_fromUtf8("lblCidades"))

        self.txtidFuncionario = QtGui.QLineEdit(self.grbFuncionario)
        self.txtidFuncionario.setEnabled(False)
        self.txtidFuncionario.setGeometry(QtCore.QRect(6, 21, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))

        self.lblCodigoFuncionario = QtGui.QLabel(self.grbFuncionario)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(6, 1, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))

        self.lblEndereco = QtGui.QLabel(self.grbFuncionario)
        self.lblEndereco.setGeometry(QtCore.QRect(8, 132, 66, 19))
        self.lblEndereco.setObjectName(_fromUtf8("lblEndereco"))

        self.txtCep = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCep.setGeometry(QtCore.QRect(365, 196, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCep.setPalette(palette)
        self.txtCep.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCep.setInputMask(_fromUtf8("00000-000; "))

        self.txtCep.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCep.setObjectName(_fromUtf8("txtCep"))

        self.lblNomeMae = QtGui.QLabel(self.grbFuncionario)
        self.lblNomeMae.setGeometry(QtCore.QRect(8, 88, 81, 19))
        self.lblNomeMae.setObjectName(_fromUtf8("lblNomeMae"))

        self.txtTelefone = QtGui.QLineEdit(self.grbFuncionario)
        self.txtTelefone.setGeometry(QtCore.QRect(190, 240, 191, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTelefone.setPalette(palette)
        self.txtTelefone.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtTelefone.setObjectName(_fromUtf8("txtTelefone"))

        self.txtSetor = QtGui.QComboBox(self.grbFuncionario)
        self.txtSetor.setGeometry(QtCore.QRect(10, 284, 231, 25))
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))

        self.txtCargo = QtGui.QComboBox(self.grbFuncionario)
        self.txtCargo.setGeometry(QtCore.QRect(250, 284, 231, 25))
        self.txtCargo.setObjectName(_fromUtf8("txtCargo"))

        self.lblSetor = QtGui.QLabel(self.grbFuncionario)
        self.lblSetor.setGeometry(QtCore.QRect(10, 264, 66, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))

        self.lblCargo = QtGui.QLabel(self.grbFuncionario)
        self.lblCargo.setGeometry(QtCore.QRect(250, 264, 66, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))

        self.grbSexo = QtGui.QGroupBox(self.grbFuncionario)
        self.grbSexo.setGeometry(QtCore.QRect(655, 44, 176, 45))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.grbSexo.setPalette(palette)
        self.grbSexo.setObjectName(_fromUtf8("grbSexo"))

        self.radBtnMasculino = QtGui.QRadioButton(self.grbSexo)
        self.radBtnMasculino.setGeometry(QtCore.QRect(6, 20, 82, 17))
        self.radBtnMasculino.setObjectName(_fromUtf8("radBtnMasculino"))

        self.radBtnFeminino = QtGui.QRadioButton(self.grbSexo)
        self.radBtnFeminino.setGeometry(QtCore.QRect(96, 20, 82, 17))
        self.radBtnFeminino.setObjectName(_fromUtf8("radBtnFeminino"))

        self.lblNomeFuncionario.raise_()
        self.txtNomeMae.raise_()
        self.txtExpeditor.raise_()
        self.txtRg.raise_()
        self.lblDataNascimento.raise_()
        self.txtDataNascimento.raise_()
        self.lblCep.raise_()
        self.txtComplemento.raise_()
        self.lblNomePai.raise_()
        self.txtCidades.raise_()
        self.lblCpf.raise_()
        self.txtNomePai.raise_()
        self.txtEstados.raise_()
        self.txtEndereco.raise_()
        self.lblExpeditor.raise_()
        self.txtNumero.raise_()
        self.lblRg.raise_()
        self.lblTelefoene.raise_()
        self.txtBairro.raise_()
        self.txtCelular.raise_()
        self.txtNomeFuncionario.raise_()
        self.lblComplemento.raise_()
        self.lblEstados.raise_()
        self.txtCpf.raise_()
        self.lblBairro.raise_()
        self.lblCerlular.raise_()
        self.lblNumero.raise_()
        self.lblCidades.raise_()
        self.txtidFuncionario.raise_()
        self.lblCodigoFuncionario.raise_()
        self.lblEndereco.raise_()
        self.txtCep.raise_()
        self.lblNomeMae.raise_()
        self.txtTelefone.raise_()
        self.txtSetor.raise_()
        self.txtCargo.raise_()
        self.lblSetor.raise_()
        self.lblCargo.raise_()
        self.grbSexo.raise_()
        self.radBtnMasculino.raise_()

        self.btnCadCancelar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadCancelar.setEnabled(False)
        self.btnCadCancelar.setGeometry(QtCore.QRect(660, 585, 81, 61))
        self.btnCadCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadCancelar.setObjectName(_fromUtf8("btnCadCancelar"))

        self.btnCadEditar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadEditar.setEnabled(False)
        self.btnCadEditar.setGeometry(QtCore.QRect(560, 585, 81, 61))
        self.btnCadEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadEditar.setObjectName(_fromUtf8("btnCadEditar"))

        self.btnCadDeletar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadDeletar.setEnabled(False)
        self.btnCadDeletar.setGeometry(QtCore.QRect(760, 585, 81, 61))
        self.btnCadDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadDeletar.setObjectName(_fromUtf8("btnCadDeletar"))

        self.btnCadSalvar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadSalvar.setEnabled(False)
        self.btnCadSalvar.setGeometry(QtCore.QRect(460, 585, 81, 61))
        self.btnCadSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadSalvar.setObjectName(_fromUtf8("btnCadSalvar"))

        self.btnCadNovo = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadNovo.setGeometry(QtCore.QRect(360, 585, 81, 61))
        self.btnCadNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadNovo.setObjectName(_fromUtf8("btnCadNovo"))

        self.tbPesquisaFuncionario = QtGui.QTableWidget(frmCadastroFuncionario)
        self.tbPesquisaFuncionario.horizontalHeader().setStretchLastSection(True)
        self.tbPesquisaFuncionario.verticalHeader().setVisible(False)
        self.tbPesquisaFuncionario.setColumnCount(24)
        self.tbPesquisaFuncionario.setHorizontalHeaderLabels(['COD.', 'Funcionario', 'RG', 'Expeditor', 'CPF', 'Data Nasc.', 'Sexo', 'Mae', 'Pai', 'Endereço', 'Numero', 'Complemento', 'Bairro', 'Cep', 'Cidade', 'Estado', 'Telefone', 'Celular', 'Setor', 'Cargo', 'Fantasia', 'Razão Social', 'CNPJ', 'Ins. Estadual'])
        self.tbPesquisaFuncionario.setGeometry(QtCore.QRect(5, 454, 840, 121))
        self.tbPesquisaFuncionario.setEditTriggers(self.tbPesquisaFuncionario.NoEditTriggers)
        self.tbPesquisaFuncionario.setSelectionBehavior(self.tbPesquisaFuncionario.SelectRows)
        self.tbPesquisaFuncionario.setSelectionMode(self.tbPesquisaFuncionario.SingleSelection)
        self.tbPesquisaFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbPesquisaFuncionario.setObjectName(_fromUtf8("tbPesquisaFuncionario"))

        self.grbDadosPesquisa = QtGui.QGroupBox(frmCadastroFuncionario)
        self.grbDadosPesquisa.setGeometry(QtCore.QRect(10, 416, 481, 36))
        self.grbDadosPesquisa.setObjectName(_fromUtf8("grbDadosPesquisa"))

        self.radBtnNomeFuncionario = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnNomeFuncionario.setGeometry(QtCore.QRect(97, 17, 91, 17))
        self.radBtnNomeFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnNomeFuncionario.setObjectName(_fromUtf8("radBtnNomeFuncionario"))

        self.radBtnRg = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnRg.setGeometry(QtCore.QRect(194, 17, 41, 17))
        self.radBtnRg.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnRg.setObjectName(_fromUtf8("radBtnRg"))

        self.radBtnCpf = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCpf.setGeometry(QtCore.QRect(238, 17, 51, 17))
        self.radBtnCpf.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCpf.setObjectName(_fromUtf8("radBtnCpf"))

        self.radBtnFantasia = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnFantasia.setGeometry(QtCore.QRect(291, 17, 71, 17))
        self.radBtnFantasia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnFantasia.setObjectName(_fromUtf8("radBtnFantasia"))

        self.radBtnCodigoFuncionario = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCodigoFuncionario.setGeometry(QtCore.QRect(8, 17, 82, 17))
        self.radBtnCodigoFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCodigoFuncionario.setObjectName(_fromUtf8("radBtnCodigoFuncionario"))

        self.radBtnRazaoSocial = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnRazaoSocial.setGeometry(QtCore.QRect(371, 16, 101, 17))
        self.radBtnRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnRazaoSocial.setObjectName(_fromUtf8("radBtnRazaoSocial"))

        self.txtPesquisaFuncionario = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtPesquisaFuncionario.setGeometry(QtCore.QRect(496, 426, 308, 25))
        self.txtPesquisaFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPesquisaFuncionario.setObjectName(_fromUtf8("txtPesquisaFuncionario"))

        self.btnPesquisarFuncionario = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnPesquisarFuncionario.setGeometry(QtCore.QRect(810, 423, 31, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarFuncionario.setIcon(icon)
        self.btnPesquisarFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarFuncionario.setText(_fromUtf8(""))
        self.btnPesquisarFuncionario.setObjectName(_fromUtf8("btnPesquisarFuncionario"))

        self.lblNomeFantasia.setBuddy(self.txtFantasia)
        self.lblRazaoSocial.setBuddy(self.txtRazaoSocial)
        self.lblInscricaoEstadual.setBuddy(self.txtInscricaoEstadua)
        self.lblCodigoEmpresa.setBuddy(self.txtIdEmpresa)
        self.lblCnpj.setBuddy(self.txtCnpj)
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblDataNascimento.setBuddy(self.txtDataNascimento)
        self.lblCep.setBuddy(self.txtCep)
        self.lblNomePai.setBuddy(self.txtNomePai)
        self.lblCpf.setBuddy(self.txtCpf)
        self.lblExpeditor.setBuddy(self.txtExpeditor)
        self.lblRg.setBuddy(self.txtRg)
        self.lblTelefoene.setBuddy(self.txtTelefone)
        self.lblComplemento.setBuddy(self.txtComplemento)
        self.lblEstados.setBuddy(self.txtEstados)
        self.lblBairro.setBuddy(self.txtBairro)
        self.lblCerlular.setBuddy(self.txtCelular)
        self.lblNumero.setBuddy(self.txtNumero)
        self.lblCidades.setBuddy(self.txtCidades)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)
        self.lblEndereco.setBuddy(self.txtEndereco)
        self.lblNomeMae.setBuddy(self.txtNomeMae)
        self.lblSetor.setBuddy(self.txtSetor)
        self.lblCargo.setBuddy(self.txtCargo)

        self.retranslateUi(frmCadastroFuncionario)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroFuncionario)
        frmCadastroFuncionario.setTabOrder(self.txtIdEmpresa, self.txtFantasia)
        frmCadastroFuncionario.setTabOrder(self.txtFantasia, self.txtNomeFuncionario)
        frmCadastroFuncionario.setTabOrder(self.txtNomeFuncionario, self.txtRg)
        frmCadastroFuncionario.setTabOrder(self.txtRg, self.txtExpeditor)
        frmCadastroFuncionario.setTabOrder(self.txtExpeditor, self.txtCpf)
        frmCadastroFuncionario.setTabOrder(self.txtCpf, self.txtDataNascimento)
        frmCadastroFuncionario.setTabOrder(self.txtDataNascimento, self.radBtnMasculino)
        frmCadastroFuncionario.setTabOrder(self.radBtnMasculino, self.radBtnFeminino)
        frmCadastroFuncionario.setTabOrder(self.radBtnFeminino, self.txtNomeMae)
        frmCadastroFuncionario.setTabOrder(self.txtNomeMae, self.txtNomePai)
        frmCadastroFuncionario.setTabOrder(self.txtNomePai, self.txtEndereco)
        frmCadastroFuncionario.setTabOrder(self.txtEndereco, self.txtNumero)
        frmCadastroFuncionario.setTabOrder(self.txtNumero, self.txtComplemento)
        frmCadastroFuncionario.setTabOrder(self.txtComplemento, self.txtBairro)
        frmCadastroFuncionario.setTabOrder(self.txtBairro, self.txtCep)
        frmCadastroFuncionario.setTabOrder(self.txtCep, self.txtCidades)
        frmCadastroFuncionario.setTabOrder(self.txtCidades, self.txtEstados)
        frmCadastroFuncionario.setTabOrder(self.txtEstados, self.txtTelefone)
        frmCadastroFuncionario.setTabOrder(self.txtTelefone, self.txtCelular)
        frmCadastroFuncionario.setTabOrder(self.txtCelular, self.txtSetor)
        frmCadastroFuncionario.setTabOrder(self.txtSetor, self.txtCargo)
        frmCadastroFuncionario.setTabOrder(self.txtCargo, self.radBtnCodigoFuncionario)
        frmCadastroFuncionario.setTabOrder(self.radBtnCodigoFuncionario, self.radBtnNomeFuncionario)
        frmCadastroFuncionario.setTabOrder(self.radBtnNomeFuncionario, self.radBtnRg)
        frmCadastroFuncionario.setTabOrder(self.radBtnRg, self.radBtnCpf)
        frmCadastroFuncionario.setTabOrder(self.radBtnCpf, self.radBtnFantasia)
        frmCadastroFuncionario.setTabOrder(self.radBtnFantasia, self.radBtnRazaoSocial)
        frmCadastroFuncionario.setTabOrder(self.radBtnRazaoSocial, self.txtPesquisaFuncionario)
        frmCadastroFuncionario.setTabOrder(self.txtPesquisaFuncionario, self.tbPesquisaFuncionario)

    def retranslateUi(self, frmCadastroFuncionario):
        frmCadastroFuncionario.setWindowTitle(_translate("frmCadastroFuncionario", "Cadastro de Funcionario", None))
        self.txtIdEmpresa.setToolTip(_translate("frmCadastroFuncionario", "Codigo", None))
        self.txtIdEmpresa.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do codigo de identificação da empresa", None))
        self.lblNomeFantasia.setText(_translate("frmCadastroFuncionario", "Nome Fantasia", None))
        self.lblRazaoSocial.setText(_translate("frmCadastroFuncionario", "Razão Social", None))
        self.txtInscricaoEstadua.setToolTip(_translate("frmCadastroFuncionario", "Inscrição Estadual", None))
        self.txtInscricaoEstadua.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do inscrição estadual da empresa", None))
        self.lblInscricaoEstadual.setText(_translate("frmCadastroFuncionario", "Incrição Estadual", None))
        self.lblCodigoEmpresa.setText(_translate("frmCadastroFuncionario", "Codigo Empresa", None))
        self.lblCnpj.setText(_translate("frmCadastroFuncionario", "CNPJ", None))
        self.txtCnpj.setToolTip(_translate("frmCadastroFuncionario", "CNPJ", None))
        self.txtCnpj.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do CNPJ da empresa", None))
        self.txtCnpj.setInputMask(_translate("frmCadastroFuncionario", "00.000.000/0000-00; ", None))
        self.txtRazaoSocial.setToolTip(_translate("frmCadastroFuncionario", "Razão Social", None))
        self.txtRazaoSocial.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da razão social da empresa", None))
        self.txtFantasia.setToolTip(_translate("frmCadastroFuncionario", "Nome Fantasia", None))
        self.txtFantasia.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome fantasia da empresa", None))
        self.lblNomeFuncionario.setText(_translate("frmCadastroFuncionario", "Nome Funcionario", None))
        self.txtNomeMae.setToolTip(_translate("frmCadastroFuncionario", "Nome Mãe", None))
        self.txtNomeMae.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da mãe do funcionario", None))
        self.txtExpeditor.setToolTip(_translate("frmCadastroFuncionario", "Expeditor", None))
        self.txtExpeditor.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do orgão expeditor do RG</p></body></html>", None))
        self.txtRg.setToolTip(_translate("frmCadastroFuncionario", "Rg", None))
        self.txtRg.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do RG do funcionario", None))
        self.txtRg.setInputMask(_translate("frmCadastroFuncionario", "0000000-0; ", None))
        self.lblDataNascimento.setText(_translate("frmCadastroFuncionario", "Data Nascimento", None))
        self.txtDataNascimento.setToolTip(_translate("frmCadastroFuncionario", "Data Nascimento", None))
        self.txtDataNascimento.setWhatsThis(_translate("frmCadastroFuncionario", "Campo da data de nacimento do funcionario", None))
        self.lblCep.setText(_translate("frmCadastroFuncionario", "CEP", None))
        self.txtComplemento.setToolTip(_translate("frmCadastroFuncionario", "Complemento", None))
        self.txtComplemento.setWhatsThis(_translate("frmCadastroFuncionario", "Campo complementar do endereço", None))
        self.lblNomePai.setText(_translate("frmCadastroFuncionario", "Nome Pai", None))
        self.txtCidades.setToolTip(_translate("frmCadastroFuncionario", "Cidade", None))
        self.txtCidades.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblCpf.setText(_translate("frmCadastroFuncionario", "CPF", None))
        self.txtNomePai.setToolTip(_translate("frmCadastroFuncionario", "Nome Pai", None))
        self.txtNomePai.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do pai do funcionario", None))
        self.txtEstados.setToolTip(_translate("frmCadastroFuncionario", "Estado", None))
        self.txtEstados.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do estado de localização do endereço", None))
        self.txtEndereco.setToolTip(_translate("frmCadastroFuncionario", "Endereço", None))
        self.txtEndereco.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de descrição do endereço", None))
        self.lblExpeditor.setText(_translate("frmCadastroFuncionario", "Expeditor", None))
        self.txtNumero.setToolTip(_translate("frmCadastroFuncionario", "Numero", None))
        self.txtNumero.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de numero referente ao numero do endereço", None))
        self.lblRg.setText(_translate("frmCadastroFuncionario", "RG", None))
        self.lblTelefoene.setText(_translate("frmCadastroFuncionario", "Telefone", None))
        self.txtBairro.setToolTip(_translate("frmCadastroFuncionario", "Bairro", None))
        self.txtBairro.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do bairro referente ao endereço", None))
        self.txtCelular.setToolTip(_translate("frmCadastroFuncionario", "Celular", None))
        self.txtCelular.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero de cantato de celular do funcionario", None))
        self.txtCelular.setInputMask(_translate("frmCadastroFuncionario", "(00) 00000-0000; ", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmCadastroFuncionario", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do funcionario", None))
        self.lblComplemento.setText(_translate("frmCadastroFuncionario", "Complemento", None))
        self.lblEstados.setText(_translate("frmCadastroFuncionario", "Estado", None))
        self.txtCpf.setToolTip(_translate("frmCadastroFuncionario", "CPF", None))
        self.txtCpf.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do CPF do funcionario", None))
        self.txtCpf.setInputMask(_translate("frmCadastroFuncionario", "000.000.000-00; ", None))
        self.lblBairro.setText(_translate("frmCadastroFuncionario", "Bairro", None))
        self.lblCerlular.setText(_translate("frmCadastroFuncionario", "Celular", None))
        self.lblNumero.setText(_translate("frmCadastroFuncionario", "Numero", None))
        self.lblCidades.setText(_translate("frmCadastroFuncionario", "Cidade", None))
        self.txtidFuncionario.setToolTip(_translate("frmCadastroFuncionario", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do Codigo de identificação do Funcionario", None))
        self.lblCodigoFuncionario.setText(_translate("frmCadastroFuncionario", "Codigo Funcionario", None))
        self.lblEndereco.setText(_translate("frmCadastroFuncionario", "Endereço", None))
        self.txtCep.setToolTip(_translate("frmCadastroFuncionario", "CEP", None))
        self.txtCep.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.lblNomeMae.setText(_translate("frmCadastroFuncionario", "Nome Mãe", None))
        self.txtTelefone.setToolTip(_translate("frmCadastroFuncionario", "Telefone", None))
        self.txtTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero de cantato de telefone da funcionario", None))
        self.txtTelefone.setInputMask(_translate("frmCadastroFuncionario", "(00) 0000-0000; ", None))
        self.txtSetor.setToolTip(_translate("frmCadastroFuncionario", "Setor", None))
        self.txtSetor.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de escolha do setor de trabalho do funcionario", None))
        self.txtCargo.setToolTip(_translate("frmCadastroFuncionario", "Cargo", None))
        self.txtCargo.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de escolha do cargo de trabalho do funcionario", None))
        self.lblSetor.setText(_translate("frmCadastroFuncionario", "Setor", None))
        self.lblCargo.setText(_translate("frmCadastroFuncionario", "Cargo", None))
        self.grbSexo.setTitle(_translate("frmCadastroFuncionario", "Sexo", None))
        self.radBtnMasculino.setText(_translate("frmCadastroFuncionario", "Masculino", None))
        self.radBtnFeminino.setText(_translate("frmCadastroFuncionario", "Feminino", None))
        self.btnCadCancelar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão de cancelar a operação iniciada", None))
        self.btnCadCancelar.setText(_translate("frmCadastroFuncionario", "Cancelar", None))
        self.btnCadEditar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão para salvar edição de um registro existente", None))
        self.btnCadEditar.setText(_translate("frmCadastroFuncionario", "Editar", None))
        self.btnCadDeletar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão de deleção de um registro existente", None))
        self.btnCadDeletar.setText(_translate("frmCadastroFuncionario", "Deletar", None))
        self.btnCadSalvar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão para salvar um novo registro", None))
        self.btnCadSalvar.setText(_translate("frmCadastroFuncionario", "Salvar", None))
        self.btnCadNovo.setWhatsThis(_translate("frmCadastroFuncionario", "Botão de Criação de um novo registro", None))
        self.btnCadNovo.setText(_translate("frmCadastroFuncionario", "Novo", None))
        self.grbDadosPesquisa.setTitle(_translate("frmCadastroFuncionario", "Dados Pesquisa", None))
        self.radBtnNomeFuncionario.setText(_translate("frmCadastroFuncionario", "Nome Fun.", None))
        self.radBtnRg.setText(_translate("frmCadastroFuncionario", "RG", None))
        self.radBtnCpf.setText(_translate("frmCadastroFuncionario", "CPF", None))
        self.radBtnFantasia.setText(_translate("frmCadastroFuncionario", "Fantasia", None))
        self.radBtnCodigoFuncionario.setText(_translate("frmCadastroFuncionario", "Cod. Fun.", None))
        self.radBtnRazaoSocial.setText(_translate("frmCadastroFuncionario", "Razão Social", None))

