# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroSetoresCargos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroSetoresCargos(object):
    def setupUi(self, frmCadastroSetoresCargos):
        frmCadastroSetoresCargos.setObjectName(_fromUtf8("frmCadastroSetoresCargos"))
        frmCadastroSetoresCargos.resize(874, 487)
        frmCadastroSetoresCargos.setMinimumSize(QtCore.QSize(874, 487))
        frmCadastroSetoresCargos.setMaximumSize(QtCore.QSize(874, 487))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroSetoresCargos.setFont(font)
        frmCadastroSetoresCargos.setSizeGripEnabled(False)
        frmCadastroSetoresCargos.setModal(True)

        self.tabwiCadastroSetoresCargos = QtGui.QTabWidget(frmCadastroSetoresCargos)
        self.tabwiCadastroSetoresCargos.setGeometry(QtCore.QRect(-1, 0, 881, 491))
        self.tabwiCadastroSetoresCargos.setWhatsThis(_fromUtf8(""))
        self.tabwiCadastroSetoresCargos.setObjectName(_fromUtf8("tabwiCadastroSetoresCargos"))

        self.cadastroSetores = QtGui.QWidget()
        self.cadastroSetores.setObjectName(_fromUtf8("cadastroSetores"))

        self.txtCadSetoresNomeFantasia = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresNomeFantasia.setEnabled(False)
        self.txtCadSetoresNomeFantasia.setGeometry(QtCore.QRect(146, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresNomeFantasia.setPalette(palette)
        self.txtCadSetoresNomeFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadSetoresNomeFantasia.setMaxLength(70)
        self.txtCadSetoresNomeFantasia.setObjectName(_fromUtf8("txtCadSetoresNomeFantasia"))

        self.txtCadSetoresCodigo = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresCodigo.setEnabled(False)
        self.txtCadSetoresCodigo.setGeometry(QtCore.QRect(2, 50, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresCodigo.setPalette(palette)
        self.txtCadSetoresCodigo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresCodigo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadSetoresCodigo.setMaxLength(11)
        self.txtCadSetoresCodigo.setObjectName(_fromUtf8("txtCadSetoresCodigo"))

        self.txtCadSetoresTipoEmpresa = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresTipoEmpresa.setEnabled(False)
        self.txtCadSetoresTipoEmpresa.setGeometry(QtCore.QRect(1, 102, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresTipoEmpresa.setPalette(palette)
        self.txtCadSetoresTipoEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresTipoEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadSetoresTipoEmpresa.setMaxLength(50)
        self.txtCadSetoresTipoEmpresa.setObjectName(_fromUtf8("txtCadSetoresTipoEmpresa"))

        self.txtCadSetoresSetor = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresSetor.setEnabled(False)
        self.txtCadSetoresSetor.setGeometry(QtCore.QRect(2, 160, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresSetor.setPalette(palette)
        self.txtCadSetoresSetor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadSetoresSetor.setMaxLength(50)
        self.txtCadSetoresSetor.setObjectName(_fromUtf8("txtCadSetoresSetor"))

        self.btnCadSetoresPesquisar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresPesquisar.setEnabled(False)
        self.btnCadSetoresPesquisar.setGeometry(QtCore.QRect(835, 48, 31, 27))
        self.btnCadSetoresPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresPesquisar.setText(_fromUtf8(""))
        self.btnCadSetoresPesquisar.setObjectName(_fromUtf8("btnCadSetoresPesquisar"))

        self.lblCadSetoresCodigo = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresCodigo.setGeometry(QtCore.QRect(5, 30, 51, 19))
        self.lblCadSetoresCodigo.setObjectName(_fromUtf8("lblCadSetoresCodigo"))

        self.lblCadSetoresNomeFantasia = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresNomeFantasia.setGeometry(QtCore.QRect(146, 30, 111, 19))
        self.lblCadSetoresNomeFantasia.setObjectName(_fromUtf8("lblCadSetoresNomeFantasia"))

        self.lblCadSetoresTipoEmpresa = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresTipoEmpresa.setGeometry(QtCore.QRect(3, 82, 131, 19))
        self.lblCadSetoresTipoEmpresa.setObjectName(_fromUtf8("lblCadSetoresTipoEmpresa"))

        self.lblCadSetoresCnpj = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresCnpj.setGeometry(QtCore.QRect(165, 82, 66, 19))
        self.lblCadSetoresCnpj.setObjectName(_fromUtf8("lblCadSetoresCnpj"))

        self.txtCadSetoresCnpj = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresCnpj.setEnabled(False)
        self.txtCadSetoresCnpj.setGeometry(QtCore.QRect(165, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresCnpj.setPalette(palette)
        self.txtCadSetoresCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresCnpj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadSetoresCnpj.setObjectName(_fromUtf8("txtCadSetoresCnpj"))

        self.lblCadSetoresIncricaoEstadual = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresIncricaoEstadual.setGeometry(QtCore.QRect(349, 82, 131, 19))
        self.lblCadSetoresIncricaoEstadual.setObjectName(_fromUtf8("lblCadSetoresIncricaoEstadual"))

        self.txtCadSetoresInscricaoEstadual = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresInscricaoEstadual.setEnabled(False)
        self.txtCadSetoresInscricaoEstadual.setGeometry(QtCore.QRect(349, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresInscricaoEstadual.setPalette(palette)
        self.txtCadSetoresInscricaoEstadual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresInscricaoEstadual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadSetoresInscricaoEstadual.setMaxLength(8)
        self.txtCadSetoresInscricaoEstadual.setObjectName(_fromUtf8("txtCadSetoresInscricaoEstadual"))

        self.lblCadSetoresSetor = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresSetor.setGeometry(QtCore.QRect(2, 140, 41, 19))
        self.lblCadSetoresSetor.setObjectName(_fromUtf8("lblCadSetoresSetor"))

        self.btnCadSetoresEditar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresEditar.setEnabled(False)
        self.btnCadSetoresEditar.setGeometry(QtCore.QRect(571, 381, 81, 61))
        self.btnCadSetoresEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresEditar.setObjectName(_fromUtf8("btnCadSetoresEditar"))

        self.btnCadSetoresDeletar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresDeletar.setEnabled(False)
        self.btnCadSetoresDeletar.setGeometry(QtCore.QRect(771, 381, 81, 61))
        self.btnCadSetoresDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresDeletar.setObjectName(_fromUtf8("btnCadSetoresDeletar"))

        self.btnCadSetoresCancelar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresCancelar.setEnabled(False)
        self.btnCadSetoresCancelar.setGeometry(QtCore.QRect(671, 381, 81, 61))
        self.btnCadSetoresCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresCancelar.setObjectName(_fromUtf8("btnCadSetoresCancelar"))

        self.btnCadSetoresSalvar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresSalvar.setEnabled(False)
        self.btnCadSetoresSalvar.setGeometry(QtCore.QRect(471, 381, 81, 61))
        self.btnCadSetoresSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresSalvar.setObjectName(_fromUtf8("btnCadSetoresSalvar"))

        self.btnCadSetoresNovo = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresNovo.setGeometry(QtCore.QRect(371, 381, 81, 61))
        self.btnCadSetoresNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresNovo.setObjectName(_fromUtf8("btnCadSetoresNovo"))
        self.grbSetorPesquisa = QtGui.QGroupBox(self.cadastroSetores)
        self.grbSetorPesquisa.setGeometry(QtCore.QRect(0, 190, 871, 178))
        self.grbSetorPesquisa.setTitle(_fromUtf8(""))
        self.grbSetorPesquisa.setObjectName(_fromUtf8("grbSetorPesquisa"))

        self.tbSetorPesquisa = QtGui.QTableWidget(self.grbSetorPesquisa)
        self.tbSetorPesquisa.setGeometry(QtCore.QRect(4, 50, 860, 121))
        self.tbSetorPesquisa.setColumnCount(7)
        self.tbSetorPesquisa.setHorizontalHeaderLabels(['COD.', 'Setor', 'Fantasia', 'Razao Socil', 'CNPJ', 'Ins. Estadual', 'Tipo Empresa'])
        self.tbSetorPesquisa.setEditTriggers(self.tbSetorPesquisa.NoEditTriggers)
        self.tbSetorPesquisa.setSelectionBehavior(self.tbSetorPesquisa.SelectRows)
        self.tbSetorPesquisa.setSelectionMode(self.tbSetorPesquisa.SingleSelection)
        self.tbSetorPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbSetorPesquisa.setObjectName(_fromUtf8("tbSetorPesquisa"))

        self.btnSetorPesquisar = QtGui.QPushButton(self.grbSetorPesquisa)
        self.btnSetorPesquisar.setGeometry(QtCore.QRect(823, 8, 41, 31))
        self.btnSetorPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSetorPesquisar.setText(_fromUtf8(""))
        self.btnSetorPesquisar.setObjectName(_fromUtf8("btnSetorPesquisar"))
        self.txtSetorPesquisa = QtGui.QLineEdit(self.grbSetorPesquisa)
        self.txtSetorPesquisa.setGeometry(QtCore.QRect(500, 10, 318, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetorPesquisa.setPalette(palette)
        self.txtSetorPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSetorPesquisa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtSetorPesquisa.setMaxLength(50)
        self.txtSetorPesquisa.setObjectName(_fromUtf8("txtSetorPesquisa"))

        self.grbSetorDadosPesquisa = QtGui.QGroupBox(self.grbSetorPesquisa)
        self.grbSetorDadosPesquisa.setGeometry(QtCore.QRect(3, 0, 491, 44))
        self.grbSetorDadosPesquisa.setObjectName(_fromUtf8("grbSetorDadosPesquisa"))

        self.radSetorBtnCodigo = QtGui.QRadioButton(self.grbSetorDadosPesquisa)
        self.radSetorBtnCodigo.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radSetorBtnCodigo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorBtnCodigo.setObjectName(_fromUtf8("radSetorBtnCodigo"))

        self.radSetorBtnFantasia = QtGui.QRadioButton(self.grbSetorDadosPesquisa)
        self.radSetorBtnFantasia.setGeometry(QtCore.QRect(80, 20, 71, 17))
        self.radSetorBtnFantasia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorBtnFantasia.setObjectName(_fromUtf8("radSetorBtnFantasia"))

        self.radSetorBtnRazaoSocial = QtGui.QRadioButton(self.grbSetorDadosPesquisa)
        self.radSetorBtnRazaoSocial.setGeometry(QtCore.QRect(160, 20, 101, 17))
        self.radSetorBtnRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorBtnRazaoSocial.setObjectName(_fromUtf8("radSetorBtnRazaoSocial"))

        self.radSetorBtnCnpj = QtGui.QRadioButton(self.grbSetorDadosPesquisa)
        self.radSetorBtnCnpj.setGeometry(QtCore.QRect(270, 20, 51, 17))
        self.radSetorBtnCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorBtnCnpj.setObjectName(_fromUtf8("radSetorBtnCnpj"))

        self.radSetorBtnInsEstadual = QtGui.QRadioButton(self.grbSetorDadosPesquisa)
        self.radSetorBtnInsEstadual.setGeometry(QtCore.QRect(330, 20, 91, 17))
        self.radSetorBtnInsEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorBtnInsEstadual.setObjectName(_fromUtf8("radSetorBtnInsEstadual"))

        self.radSetorBtnSetor = QtGui.QRadioButton(self.grbSetorDadosPesquisa)
        self.radSetorBtnSetor.setGeometry(QtCore.QRect(420, 20, 61, 17))
        self.radSetorBtnSetor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorBtnSetor.setObjectName(_fromUtf8("radSetorBtnSetor"))

        self.lblCadSetoresRazaoSocial = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresRazaoSocial.setGeometry(QtCore.QRect(490, 30, 111, 19))
        self.lblCadSetoresRazaoSocial.setObjectName(_fromUtf8("lblCadSetoresRazaoSocial"))

        self.txtCadSetoresRazaoSocial = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresRazaoSocial.setEnabled(False)
        self.txtCadSetoresRazaoSocial.setGeometry(QtCore.QRect(490, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresRazaoSocial.setPalette(palette)
        self.txtCadSetoresRazaoSocial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresRazaoSocial.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadSetoresRazaoSocial.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadSetoresRazaoSocial.setMaxLength(70)
        self.txtCadSetoresRazaoSocial.setObjectName(_fromUtf8("txtCadSetoresRazaoSocial"))

        self.tabwiCadastroSetoresCargos.addTab(self.cadastroSetores, _fromUtf8(""))
        self.cadastroCargos = QtGui.QWidget()
        self.cadastroCargos.setObjectName(_fromUtf8("cadastroCargos"))

        self.lblCadCargoIncricaoEstadual = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoIncricaoEstadual.setGeometry(QtCore.QRect(349, 82, 131, 19))
        self.lblCadCargoIncricaoEstadual.setObjectName(_fromUtf8("lblCadCargoIncricaoEstadual"))

        self.lblCadCargoCargo = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoCargo.setGeometry(QtCore.QRect(2, 140, 41, 19))
        self.lblCadCargoCargo.setObjectName(_fromUtf8("lblCadCargoCargo"))

        self.btnCadCargoEditar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoEditar.setEnabled(False)
        self.btnCadCargoEditar.setGeometry(QtCore.QRect(571, 381, 81, 61))
        self.btnCadCargoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoEditar.setObjectName(_fromUtf8("btnCadCargoEditar"))

        self.btnCadCargoDeletar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoDeletar.setEnabled(False)
        self.btnCadCargoDeletar.setGeometry(QtCore.QRect(771, 381, 81, 61))
        self.btnCadCargoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoDeletar.setObjectName(_fromUtf8("btnCadCargoDeletar"))

        self.txtCadCargoTipoEmpresa = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoTipoEmpresa.setEnabled(False)
        self.txtCadCargoTipoEmpresa.setGeometry(QtCore.QRect(1, 102, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoTipoEmpresa.setPalette(palette)
        self.txtCadCargoTipoEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoTipoEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadCargoTipoEmpresa.setMaxLength(50)
        self.txtCadCargoTipoEmpresa.setObjectName(_fromUtf8("txtCadCargoTipoEmpresa"))

        self.txtCadCargoCodigo = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoCodigo.setEnabled(False)
        self.txtCadCargoCodigo.setGeometry(QtCore.QRect(2, 50, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoCodigo.setPalette(palette)
        self.txtCadCargoCodigo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoCodigo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadCargoCodigo.setMaxLength(11)
        self.txtCadCargoCodigo.setObjectName(_fromUtf8("txtCadCargoCodigo"))

        self.lblCadCargoCodigo = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoCodigo.setGeometry(QtCore.QRect(5, 30, 51, 19))
        self.lblCadCargoCodigo.setObjectName(_fromUtf8("lblCadCargoCodigo"))

        self.lblCadCargoTipoEmpresa = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoTipoEmpresa.setGeometry(QtCore.QRect(3, 82, 131, 19))
        self.lblCadCargoTipoEmpresa.setObjectName(_fromUtf8("lblCadCargoTipoEmpresa"))

        self.txtCadCargoNomeFantasia = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoNomeFantasia.setEnabled(False)
        self.txtCadCargoNomeFantasia.setGeometry(QtCore.QRect(146, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoNomeFantasia.setPalette(palette)
        self.txtCadCargoNomeFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadCargoNomeFantasia.setMaxLength(70)
        self.txtCadCargoNomeFantasia.setObjectName(_fromUtf8("txtCadCargoNomeFantasia"))

        self.lblCadCargoNomeFantasia = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoNomeFantasia.setGeometry(QtCore.QRect(146, 30, 111, 19))
        self.lblCadCargoNomeFantasia.setObjectName(_fromUtf8("lblCadCargoNomeFantasia"))

        self.btnCadCargoSalvar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoSalvar.setEnabled(False)
        self.btnCadCargoSalvar.setGeometry(QtCore.QRect(471, 381, 81, 61))
        self.btnCadCargoSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoSalvar.setObjectName(_fromUtf8("btnCadCargoSalvar"))

        self.btnCadCargoPesquisar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoPesquisar.setEnabled(False)
        self.btnCadCargoPesquisar.setGeometry(QtCore.QRect(835, 48, 31, 27))
        self.btnCadCargoPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoPesquisar.setText(_fromUtf8(""))
        self.btnCadCargoPesquisar.setObjectName(_fromUtf8("btnCadCargoPesquisar"))

        self.txtCadCargoInscricaoEstadual = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoInscricaoEstadual.setEnabled(False)
        self.txtCadCargoInscricaoEstadual.setGeometry(QtCore.QRect(349, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoInscricaoEstadual.setPalette(palette)
        self.txtCadCargoInscricaoEstadual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoInscricaoEstadual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadCargoInscricaoEstadual.setMaxLength(8)
        self.txtCadCargoInscricaoEstadual.setObjectName(_fromUtf8("txtCadCargoInscricaoEstadual"))

        self.txtCadCargoCnpj = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoCnpj.setEnabled(False)
        self.txtCadCargoCnpj.setGeometry(QtCore.QRect(165, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoCnpj.setPalette(palette)
        self.txtCadCargoCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoCnpj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadCargoCnpj.setObjectName(_fromUtf8("txtCadCargoCnpj"))

        self.btnCadCargoNovo = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoNovo.setGeometry(QtCore.QRect(371, 381, 81, 61))
        self.btnCadCargoNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoNovo.setObjectName(_fromUtf8("btnCadCargoNovo"))

        self.btnCadCargoCancelar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoCancelar.setEnabled(False)
        self.btnCadCargoCancelar.setGeometry(QtCore.QRect(671, 381, 81, 61))
        self.btnCadCargoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoCancelar.setObjectName(_fromUtf8("btnCadCargoCancelar"))

        self.txtCadCargoCargo = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoCargo.setEnabled(False)
        self.txtCadCargoCargo.setGeometry(QtCore.QRect(2, 160, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoCargo.setPalette(palette)
        self.txtCadCargoCargo.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadCargoCargo.setMaxLength(50)
        self.txtCadCargoCargo.setObjectName(_fromUtf8("txtCadCargoCargo"))

        self.lblCadCargoCnpj = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoCnpj.setGeometry(QtCore.QRect(165, 82, 66, 19))
        self.lblCadCargoCnpj.setObjectName(_fromUtf8("lblCadCargoCnpj"))

        self.grbCargoPesquisa = QtGui.QGroupBox(self.cadastroCargos)
        self.grbCargoPesquisa.setGeometry(QtCore.QRect(0, 190, 871, 178))
        self.grbCargoPesquisa.setTitle(_fromUtf8(""))
        self.grbCargoPesquisa.setObjectName(_fromUtf8("grbCargoPesquisa"))

        self.tbCargoPesquisa = QtGui.QTableWidget(self.grbCargoPesquisa)
        self.tbCargoPesquisa.setGeometry(QtCore.QRect(4, 50, 860, 121))
        self.tbCargoPesquisa.setColumnCount(7)
        self.tbCargoPesquisa.setHorizontalHeaderLabels(['COD.', 'Cargo', 'Fantasia', 'Razao Socil', 'CNPJ', 'Ins. Estadual', 'Tipo Empresa'])
        self.tbCargoPesquisa.setEditTriggers(self.tbCargoPesquisa.NoEditTriggers)
        self.tbCargoPesquisa.setSelectionBehavior(self.tbCargoPesquisa.SelectRows)
        self.tbCargoPesquisa.setSelectionMode(self.tbCargoPesquisa.SingleSelection)
        self.tbCargoPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbCargoPesquisa.setObjectName(_fromUtf8("tbCargoPesquisa"))

        self.btnCargoPesquisar = QtGui.QPushButton(self.grbCargoPesquisa)
        self.btnCargoPesquisar.setGeometry(QtCore.QRect(823, 8, 41, 31))
        self.btnCargoPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCargoPesquisar.setText(_fromUtf8(""))
        self.btnCargoPesquisar.setObjectName(_fromUtf8("btnCargoPesquisar"))

        self.txtCargoPesquisa = QtGui.QLineEdit(self.grbCargoPesquisa)
        self.txtCargoPesquisa.setGeometry(QtCore.QRect(500, 10, 318, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCargoPesquisa.setPalette(palette)
        self.txtCargoPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCargoPesquisa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCargoPesquisa.setMaxLength(50)
        self.txtCargoPesquisa.setObjectName(_fromUtf8("txtCargoPesquisa"))

        self.grbCargoDadosPesquisa = QtGui.QGroupBox(self.grbCargoPesquisa)
        self.grbCargoDadosPesquisa.setGeometry(QtCore.QRect(3, 0, 491, 44))
        self.grbCargoDadosPesquisa.setObjectName(_fromUtf8("grbCargoDadosPesquisa"))

        self.radCargoBtnCodigo = QtGui.QRadioButton(self.grbCargoDadosPesquisa)
        self.radCargoBtnCodigo.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radCargoBtnCodigo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radCargoBtnCodigo.setObjectName(_fromUtf8("radCargoBtnCodigo"))

        self.radCargoBtnFantasia = QtGui.QRadioButton(self.grbCargoDadosPesquisa)
        self.radCargoBtnFantasia.setGeometry(QtCore.QRect(80, 20, 71, 17))
        self.radCargoBtnFantasia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radCargoBtnFantasia.setObjectName(_fromUtf8("radCargoBtnFantasia"))

        self.radCargoBtnRazaoSocial = QtGui.QRadioButton(self.grbCargoDadosPesquisa)
        self.radCargoBtnRazaoSocial.setGeometry(QtCore.QRect(160, 20, 101, 17))
        self.radCargoBtnRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radCargoBtnRazaoSocial.setObjectName(_fromUtf8("radCargoBtnRazaoSocial"))

        self.radCargoBtnCnpj = QtGui.QRadioButton(self.grbCargoDadosPesquisa)
        self.radCargoBtnCnpj.setGeometry(QtCore.QRect(270, 20, 51, 17))
        self.radCargoBtnCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radCargoBtnCnpj.setObjectName(_fromUtf8("radCargoBtnCnpj"))

        self.radCargoBtnInsEstadual = QtGui.QRadioButton(self.grbCargoDadosPesquisa)
        self.radCargoBtnInsEstadual.setGeometry(QtCore.QRect(330, 20, 91, 17))
        self.radCargoBtnInsEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radCargoBtnInsEstadual.setObjectName(_fromUtf8("radCargoBtnInsEstadual"))

        self.radCargoBtnSetor = QtGui.QRadioButton(self.grbCargoDadosPesquisa)
        self.radCargoBtnSetor.setGeometry(QtCore.QRect(420, 20, 61, 17))
        self.radCargoBtnSetor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radCargoBtnSetor.setObjectName(_fromUtf8("radCargoBtnSetor"))
        self.lblCadCargoRazaoSocial = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoRazaoSocial.setGeometry(QtCore.QRect(490, 30, 111, 19))
        self.lblCadCargoRazaoSocial.setObjectName(_fromUtf8("lblCadCargoRazaoSocial"))

        self.txtCadCargoRazaoSocial = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoRazaoSocial.setEnabled(False)
        self.txtCadCargoRazaoSocial.setGeometry(QtCore.QRect(490, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoRazaoSocial.setPalette(palette)
        self.txtCadCargoRazaoSocial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoRazaoSocial.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCadCargoRazaoSocial.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadCargoRazaoSocial.setMaxLength(70)
        self.txtCadCargoRazaoSocial.setObjectName(_fromUtf8("txtCadCargoRazaoSocial"))

        self.tabwiCadastroSetoresCargos.addTab(self.cadastroCargos, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lblRelacaoCodigo = QtGui.QLabel(self.tab)
        self.lblRelacaoCodigo.setGeometry(QtCore.QRect(5, 30, 51, 19))
        self.lblRelacaoCodigo.setObjectName(_fromUtf8("lblRelacaoCodigo"))

        self.btnRelacaoCancelar = QtGui.QPushButton(self.tab)
        self.btnRelacaoCancelar.setEnabled(False)
        self.btnRelacaoCancelar.setGeometry(QtCore.QRect(671, 381, 81, 61))
        self.btnRelacaoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoCancelar.setObjectName(_fromUtf8("btnRelacaoCancelar"))

        self.txtRelacaoCnpj = QtGui.QLineEdit(self.tab)
        self.txtRelacaoCnpj.setEnabled(False)
        self.txtRelacaoCnpj.setGeometry(QtCore.QRect(165, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoCnpj.setPalette(palette)
        self.txtRelacaoCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoCnpj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRelacaoCnpj.setObjectName(_fromUtf8("txtRelacaoCnpj"))

        self.btnRelacaoDeletar = QtGui.QPushButton(self.tab)
        self.btnRelacaoDeletar.setEnabled(False)
        self.btnRelacaoDeletar.setGeometry(QtCore.QRect(771, 381, 81, 61))
        self.btnRelacaoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoDeletar.setObjectName(_fromUtf8("btnRelacaoDeletar"))

        self.lblRelacaoIncricaoEstadual = QtGui.QLabel(self.tab)
        self.lblRelacaoIncricaoEstadual.setGeometry(QtCore.QRect(349, 82, 131, 19))
        self.lblRelacaoIncricaoEstadual.setObjectName(_fromUtf8("lblRelacaoIncricaoEstadual"))

        self.btnRelacaoPesquisar = QtGui.QPushButton(self.tab)
        self.btnRelacaoPesquisar.setEnabled(False)
        self.btnRelacaoPesquisar.setGeometry(QtCore.QRect(835, 48, 31, 27))
        self.btnRelacaoPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoPesquisar.setText(_fromUtf8(""))
        self.btnRelacaoPesquisar.setObjectName(_fromUtf8("btnRelacaoPesquisar"))

        self.btnRelacaoSalvar = QtGui.QPushButton(self.tab)
        self.btnRelacaoSalvar.setEnabled(False)
        self.btnRelacaoSalvar.setGeometry(QtCore.QRect(471, 381, 81, 61))
        self.btnRelacaoSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoSalvar.setObjectName(_fromUtf8("btnRelacaoSalvar"))

        self.txtRelacaoCodigo = QtGui.QLineEdit(self.tab)
        self.txtRelacaoCodigo.setEnabled(False)
        self.txtRelacaoCodigo.setGeometry(QtCore.QRect(2, 50, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoCodigo.setPalette(palette)
        self.txtRelacaoCodigo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoCodigo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRelacaoCodigo.setMaxLength(11)
        self.txtRelacaoCodigo.setObjectName(_fromUtf8("txtRelacaoCodigo"))

        self.btnRelacaoNovo = QtGui.QPushButton(self.tab)
        self.btnRelacaoNovo.setGeometry(QtCore.QRect(371, 381, 81, 61))
        self.btnRelacaoNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoNovo.setObjectName(_fromUtf8("btnRelacaoNovo"))

        self.btnRelacaoEditar = QtGui.QPushButton(self.tab)
        self.btnRelacaoEditar.setEnabled(False)
        self.btnRelacaoEditar.setGeometry(QtCore.QRect(571, 381, 81, 61))
        self.btnRelacaoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoEditar.setObjectName(_fromUtf8("btnRelacaoEditar"))

        self.lblRelacaoTipoEmpresa = QtGui.QLabel(self.tab)
        self.lblRelacaoTipoEmpresa.setGeometry(QtCore.QRect(3, 82, 131, 19))
        self.lblRelacaoTipoEmpresa.setObjectName(_fromUtf8("lblRelacaoTipoEmpresa"))

        self.lblRelacaoCnpj = QtGui.QLabel(self.tab)
        self.lblRelacaoCnpj.setGeometry(QtCore.QRect(165, 82, 66, 19))
        self.lblRelacaoCnpj.setObjectName(_fromUtf8("lblRelacaoCnpj"))

        self.txtRelacaoNomeFantasia = QtGui.QLineEdit(self.tab)
        self.txtRelacaoNomeFantasia.setEnabled(False)
        self.txtRelacaoNomeFantasia.setGeometry(QtCore.QRect(146, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoNomeFantasia.setPalette(palette)
        self.txtRelacaoNomeFantasia.setMaxLength(70)
        self.txtRelacaoNomeFantasia.setObjectName(_fromUtf8("txtRelacaoNomeFantasia"))

        self.txtRelacaoTipoEmpresa = QtGui.QLineEdit(self.tab)
        self.txtRelacaoTipoEmpresa.setEnabled(False)
        self.txtRelacaoTipoEmpresa.setGeometry(QtCore.QRect(1, 102, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoTipoEmpresa.setPalette(palette)
        self.txtRelacaoTipoEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoTipoEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRelacaoTipoEmpresa.setMaxLength(50)
        self.txtRelacaoTipoEmpresa.setObjectName(_fromUtf8("txtRelacaoTipoEmpresa"))

        self.txtRelacaoInscricaoEstadual = QtGui.QLineEdit(self.tab)
        self.txtRelacaoInscricaoEstadual.setEnabled(False)
        self.txtRelacaoInscricaoEstadual.setGeometry(QtCore.QRect(349, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoInscricaoEstadual.setPalette(palette)
        self.txtRelacaoInscricaoEstadual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoInscricaoEstadual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRelacaoInscricaoEstadual.setMaxLength(8)
        self.txtRelacaoInscricaoEstadual.setObjectName(_fromUtf8("txtRelacaoInscricaoEstadual"))

        self.lblRelacaoNomeFantasia = QtGui.QLabel(self.tab)
        self.lblRelacaoNomeFantasia.setGeometry(QtCore.QRect(146, 30, 111, 19))
        self.lblRelacaoNomeFantasia.setObjectName(_fromUtf8("lblRelacaoNomeFantasia"))

        self.txtRelacaoSetor = QtGui.QComboBox(self.tab)
        self.txtRelacaoSetor.setEnabled(False)
        self.txtRelacaoSetor.setGeometry(QtCore.QRect(2, 160, 361, 25))
        self.txtRelacaoSetor.setObjectName(_fromUtf8("txtRelacaoSetor"))

        self.txtRelacaoCargo = QtGui.QComboBox(self.tab)
        self.txtRelacaoCargo.setEnabled(False)
        self.txtRelacaoCargo.setGeometry(QtCore.QRect(380, 160, 361, 25))
        self.txtRelacaoCargo.setObjectName(_fromUtf8("txtRelacaoCargo"))

        self.lblRelacaoSetor = QtGui.QLabel(self.tab)
        self.lblRelacaoSetor.setGeometry(QtCore.QRect(2, 140, 66, 19))
        self.lblRelacaoSetor.setObjectName(_fromUtf8("lblRelacaoSetor"))

        self.lblRelacaoCargo = QtGui.QLabel(self.tab)
        self.lblRelacaoCargo.setGeometry(QtCore.QRect(380, 140, 66, 19))
        self.lblRelacaoCargo.setObjectName(_fromUtf8("lblRelacaoCargo"))

        self.lblRelacaoRazaoSocial = QtGui.QLabel(self.tab)
        self.lblRelacaoRazaoSocial.setGeometry(QtCore.QRect(490, 30, 111, 19))
        self.lblRelacaoRazaoSocial.setObjectName(_fromUtf8("lblRelacaoRazaoSocial"))

        self.txtRelacaoRazaoSocial = QtGui.QLineEdit(self.tab)
        self.txtRelacaoRazaoSocial.setEnabled(False)
        self.txtRelacaoRazaoSocial.setGeometry(QtCore.QRect(490, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoRazaoSocial.setPalette(palette)
        self.txtRelacaoRazaoSocial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoRazaoSocial.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRelacaoRazaoSocial.setMaxLength(70)
        self.txtRelacaoRazaoSocial.setObjectName(_fromUtf8("txtRelacaoRazaoSocial"))

        self.grbSetorCargoPesquisa = QtGui.QGroupBox(self.tab)
        self.grbSetorCargoPesquisa.setGeometry(QtCore.QRect(0, 190, 871, 178))
        self.grbSetorCargoPesquisa.setTitle(_fromUtf8(""))
        self.grbSetorCargoPesquisa.setObjectName(_fromUtf8("grbSetorCargoPesquisa"))

        self.tbSetorCargoPesquisa = QtGui.QTableWidget(self.grbSetorCargoPesquisa)
        self.tbSetorCargoPesquisa.setGeometry(QtCore.QRect(4, 50, 860, 121))
        self.tbSetorCargoPesquisa.setColumnCount(8)
        self.tbSetorCargoPesquisa.setHorizontalHeaderLabels(['COD.', 'Setor', 'Cargo', 'Fantasia', 'Razao Socil', 'CNPJ', 'Ins. Estadual', 'Tipo Empresa'])
        self.tbSetorCargoPesquisa.setEditTriggers(self.tbSetorPesquisa.NoEditTriggers)
        self.tbSetorCargoPesquisa.setSelectionBehavior(self.tbSetorPesquisa.SelectRows)
        self.tbSetorCargoPesquisa.setSelectionMode(self.tbSetorPesquisa.SingleSelection)
        self.tbSetorCargoPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbSetorCargoPesquisa.setObjectName(_fromUtf8("tbSetorCargoPesquisa"))


        self.btnSetorCargoPesquisar = QtGui.QPushButton(self.grbSetorCargoPesquisa)
        self.btnSetorCargoPesquisar.setGeometry(QtCore.QRect(823, 8, 41, 31))
        self.btnSetorCargoPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSetorCargoPesquisar.setText(_fromUtf8(""))
        self.btnSetorCargoPesquisar.setObjectName(_fromUtf8("btnSetorCargoPesquisar"))

        self.txtSetorCargoPesquisa = QtGui.QLineEdit(self.grbSetorCargoPesquisa)
        self.txtSetorCargoPesquisa.setGeometry(QtCore.QRect(500, 10, 318, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetorCargoPesquisa.setPalette(palette)
        self.txtSetorCargoPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSetorCargoPesquisa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtSetorCargoPesquisa.setMaxLength(50)
        self.txtSetorCargoPesquisa.setObjectName(_fromUtf8("txtSetorCargoPesquisa"))

        self.grbSetorCargoDadosPesquisa = QtGui.QGroupBox(self.grbSetorCargoPesquisa)
        self.grbSetorCargoDadosPesquisa.setGeometry(QtCore.QRect(3, 0, 491, 44))
        self.grbSetorCargoDadosPesquisa.setObjectName(_fromUtf8("grbSetorCargoDadosPesquisa"))

        self.radSetorCargoBtnCodigo = QtGui.QRadioButton(self.grbSetorCargoDadosPesquisa)
        self.radSetorCargoBtnCodigo.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radSetorCargoBtnCodigo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorCargoBtnCodigo.setObjectName(_fromUtf8("radSetorCargoBtnCodigo"))

        self.radSetorCargoBtnFantasia = QtGui.QRadioButton(self.grbSetorCargoDadosPesquisa)
        self.radSetorCargoBtnFantasia.setGeometry(QtCore.QRect(80, 20, 71, 17))
        self.radSetorCargoBtnFantasia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorCargoBtnFantasia.setObjectName(_fromUtf8("radSetorCargoBtnFantasia"))

        self.radSetorCargoBtnRazaoSocial = QtGui.QRadioButton(self.grbSetorCargoDadosPesquisa)
        self.radSetorCargoBtnRazaoSocial.setGeometry(QtCore.QRect(160, 20, 101, 17))
        self.radSetorCargoBtnRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorCargoBtnRazaoSocial.setObjectName(_fromUtf8("radSetorCargoBtnRazaoSocial"))

        self.radSetorCargoBtnCnpj = QtGui.QRadioButton(self.grbSetorCargoDadosPesquisa)
        self.radSetorCargoBtnCnpj.setGeometry(QtCore.QRect(270, 20, 51, 17))
        self.radSetorCargoBtnCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorCargoBtnCnpj.setObjectName(_fromUtf8("radSetorCargoBtnCnpj"))

        self.radSetorCargoBtnSetor = QtGui.QRadioButton(self.grbSetorCargoDadosPesquisa)
        self.radSetorCargoBtnSetor.setGeometry(QtCore.QRect(330, 20, 61, 17))
        self.radSetorCargoBtnSetor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorCargoBtnSetor.setObjectName(_fromUtf8("radSetorCargoBtnSetor"))

        self.radSetorCargoBtnCargo = QtGui.QRadioButton(self.grbSetorCargoDadosPesquisa)
        self.radSetorCargoBtnCargo.setGeometry(QtCore.QRect(390, 20, 61, 17))
        self.radSetorCargoBtnCargo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radSetorCargoBtnCargo.setObjectName(_fromUtf8("radSetorCargoBtnCargo"))

        self.tabwiCadastroSetoresCargos.addTab(self.tab, _fromUtf8(""))
        self.lblCadSetoresCodigo.setBuddy(self.txtCadSetoresCodigo)
        self.lblCadSetoresNomeFantasia.setBuddy(self.txtCadSetoresNomeFantasia)
        self.lblCadSetoresTipoEmpresa.setBuddy(self.txtCadSetoresTipoEmpresa)
        self.lblCadSetoresCnpj.setBuddy(self.txtCadSetoresCnpj)
        self.lblCadSetoresIncricaoEstadual.setBuddy(self.txtCadSetoresInscricaoEstadual)
        self.lblCadSetoresSetor.setBuddy(self.txtCadSetoresSetor)
        self.lblCadSetoresRazaoSocial.setBuddy(self.txtCadSetoresRazaoSocial)
        self.lblCadCargoIncricaoEstadual.setBuddy(self.txtCadCargoInscricaoEstadual)
        self.lblCadCargoCargo.setBuddy(self.txtCadCargoCargo)
        self.lblCadCargoCodigo.setBuddy(self.txtCadCargoCodigo)
        self.lblCadCargoTipoEmpresa.setBuddy(self.txtCadCargoTipoEmpresa)
        self.lblCadCargoNomeFantasia.setBuddy(self.txtCadCargoNomeFantasia)
        self.lblCadCargoCnpj.setBuddy(self.txtCadCargoCnpj)
        self.lblCadCargoRazaoSocial.setBuddy(self.txtCadCargoRazaoSocial)
        self.lblRelacaoCodigo.setBuddy(self.txtRelacaoCodigo)
        self.lblRelacaoIncricaoEstadual.setBuddy(self.txtRelacaoInscricaoEstadual)
        self.lblRelacaoTipoEmpresa.setBuddy(self.txtRelacaoTipoEmpresa)
        self.lblRelacaoCnpj.setBuddy(self.txtRelacaoCnpj)
        self.lblRelacaoNomeFantasia.setBuddy(self.txtRelacaoNomeFantasia)
        self.lblRelacaoSetor.setBuddy(self.txtRelacaoSetor)
        self.lblRelacaoCargo.setBuddy(self.txtRelacaoCargo)
        self.lblRelacaoRazaoSocial.setBuddy(self.txtRelacaoRazaoSocial)

        self.retranslateUi(frmCadastroSetoresCargos)
        self.tabwiCadastroSetoresCargos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroSetoresCargos)
        frmCadastroSetoresCargos.setTabOrder(self.tabwiCadastroSetoresCargos, self.txtCadSetoresCodigo)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresCodigo, self.txtCadSetoresNomeFantasia)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresNomeFantasia, self.txtCadSetoresRazaoSocial)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresRazaoSocial, self.txtCadSetoresSetor)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresSetor, self.tbSetorPesquisa)
        frmCadastroSetoresCargos.setTabOrder(self.tbSetorPesquisa, self.txtCadCargoCodigo)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoCodigo, self.txtCadCargoNomeFantasia)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoNomeFantasia, self.txtCadCargoRazaoSocial)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoRazaoSocial, self.txtCadCargoCargo)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoCargo, self.tbCargoPesquisa)
        frmCadastroSetoresCargos.setTabOrder(self.tbCargoPesquisa, self.txtRelacaoCodigo)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoCodigo, self.txtRelacaoNomeFantasia)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoNomeFantasia, self.txtRelacaoRazaoSocial)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoRazaoSocial, self.txtRelacaoSetor)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoSetor, self.txtRelacaoCargo)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoCargo, self.tbSetorCargoPesquisa)

    def retranslateUi(self, frmCadastroSetoresCargos):
        frmCadastroSetoresCargos.setWindowTitle(_translate("frmCadastroSetoresCargos", "Cadastro Setores e Cargos", None))
        self.txtCadSetoresNomeFantasia.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtCadSetoresNomeFantasia.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.txtCadSetoresCodigo.setToolTip(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.txtCadSetoresCodigo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do Codigo de identificação da empresa", None))
        self.txtCadSetoresTipoEmpresa.setToolTip(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtCadSetoresTipoEmpresa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do tipo da empresa", None))
        self.txtCadSetoresSetor.setToolTip(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.txtCadSetoresSetor.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome do setor", None))
        self.lblCadSetoresCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.lblCadSetoresNomeFantasia.setText(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.lblCadSetoresTipoEmpresa.setText(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.lblCadSetoresCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCadSetoresCnpj.setToolTip(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCadSetoresCnpj.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo numero do CNPJ da empresa", None))
        self.txtCadSetoresCnpj.setInputMask(_translate("frmCadastroSetoresCargos", "00.000.000/0000-00; ", None))
        self.lblCadSetoresIncricaoEstadual.setText(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.txtCadSetoresInscricaoEstadual.setToolTip(_translate("frmCadastroSetoresCargos", "Incrição Estadual", None))
        self.txtCadSetoresInscricaoEstadual.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do numero da iscrição estadual da empresa", None))
        self.lblCadSetoresSetor.setText(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.btnCadSetoresEditar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar edição de um registro existente", None))
        self.btnCadSetoresEditar.setText(_translate("frmCadastroSetoresCargos", "Editar", None))
        self.btnCadSetoresDeletar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de deleção de um registro existente", None))
        self.btnCadSetoresDeletar.setText(_translate("frmCadastroSetoresCargos", "Deletar", None))
        self.btnCadSetoresCancelar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de cancelar a operação iniciada", None))
        self.btnCadSetoresCancelar.setText(_translate("frmCadastroSetoresCargos", "Cancelar", None))
        self.btnCadSetoresSalvar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar um novo registro", None))
        self.btnCadSetoresSalvar.setText(_translate("frmCadastroSetoresCargos", "Salvar", None))
        self.btnCadSetoresNovo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de Criação de um novo registro", None))
        self.btnCadSetoresNovo.setText(_translate("frmCadastroSetoresCargos", "Novo", None))
        self.txtSetorPesquisa.setToolTip(_translate("frmCadastroSetoresCargos", "Pesquisa", None))
        self.txtSetorPesquisa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo pra inserir dados da pesquisa", None))
        self.grbSetorDadosPesquisa.setTitle(_translate("frmCadastroSetoresCargos", "Dados Pesquisa", None))
        self.radSetorBtnCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.radSetorBtnFantasia.setText(_translate("frmCadastroSetoresCargos", "Fantasia", None))
        self.radSetorBtnRazaoSocial.setText(_translate("frmCadastroSetoresCargos", "Razão Social", None))
        self.radSetorBtnCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.radSetorBtnInsEstadual.setText(_translate("frmCadastroSetoresCargos", "Ins. Esta.", None))
        self.radSetorBtnSetor.setText(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.lblCadSetoresRazaoSocial.setText(_translate("frmCadastroSetoresCargos", "Razão Social", None))
        self.txtCadSetoresRazaoSocial.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtCadSetoresRazaoSocial.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.tabwiCadastroSetoresCargos.setTabText(self.tabwiCadastroSetoresCargos.indexOf(self.cadastroSetores), _translate("frmCadastroSetoresCargos", "Cadastro Setores", None))
        self.lblCadCargoIncricaoEstadual.setText(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.lblCadCargoCargo.setText(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.btnCadCargoEditar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar edição de um registro existente", None))
        self.btnCadCargoEditar.setText(_translate("frmCadastroSetoresCargos", "Editar", None))
        self.btnCadCargoDeletar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de deleção de um registro existente", None))
        self.btnCadCargoDeletar.setText(_translate("frmCadastroSetoresCargos", "Deletar", None))
        self.txtCadCargoTipoEmpresa.setToolTip(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtCadCargoTipoEmpresa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do tipo da empresa", None))
        self.txtCadCargoCodigo.setToolTip(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.txtCadCargoCodigo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do Codigo de identificação da empresa", None))
        self.lblCadCargoCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.lblCadCargoTipoEmpresa.setText(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtCadCargoNomeFantasia.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtCadCargoNomeFantasia.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.lblCadCargoNomeFantasia.setText(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.btnCadCargoSalvar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar um novo registro", None))
        self.btnCadCargoSalvar.setText(_translate("frmCadastroSetoresCargos", "Salvar", None))
        self.txtCadCargoInscricaoEstadual.setToolTip(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.txtCadCargoInscricaoEstadual.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do numero da iscrição estadual da empresa", None))
        self.txtCadCargoCnpj.setToolTip(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCadCargoCnpj.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo numero do CNPJ da empresa", None))
        self.txtCadCargoCnpj.setInputMask(_translate("frmCadastroSetoresCargos", "00.000.000/0000-00; ", None))
        self.btnCadCargoNovo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de Criação de um novo registro", None))
        self.btnCadCargoNovo.setText(_translate("frmCadastroSetoresCargos", "Novo", None))
        self.btnCadCargoCancelar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de cancelar a operação iniciada", None))
        self.btnCadCargoCancelar.setText(_translate("frmCadastroSetoresCargos", "Cancelar", None))
        self.txtCadCargoCargo.setToolTip(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.txtCadCargoCargo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome do cargo", None))
        self.lblCadCargoCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCargoPesquisa.setToolTip(_translate("frmCadastroSetoresCargos", "Pesquisa", None))
        self.txtCargoPesquisa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo pra inserir dados da pesquisa", None))
        self.grbCargoDadosPesquisa.setTitle(_translate("frmCadastroSetoresCargos", "Dados Pesquisa", None))
        self.radCargoBtnCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.radCargoBtnFantasia.setText(_translate("frmCadastroSetoresCargos", "Fantasia", None))
        self.radCargoBtnRazaoSocial.setText(_translate("frmCadastroSetoresCargos", "Razão Social", None))
        self.radCargoBtnCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.radCargoBtnInsEstadual.setText(_translate("frmCadastroSetoresCargos", "Ins. Esta.", None))
        self.radCargoBtnSetor.setText(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.lblCadCargoRazaoSocial.setText(_translate("frmCadastroSetoresCargos", "Razão Social", None))
        self.txtCadCargoRazaoSocial.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtCadCargoRazaoSocial.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.tabwiCadastroSetoresCargos.setTabText(self.tabwiCadastroSetoresCargos.indexOf(self.cadastroCargos), _translate("frmCadastroSetoresCargos", "Cadastro Cargos", None))
        self.lblRelacaoCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.btnRelacaoCancelar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de cancelar a operação iniciada", None))
        self.btnRelacaoCancelar.setText(_translate("frmCadastroSetoresCargos", "Cancelar", None))
        self.txtRelacaoCnpj.setToolTip(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtRelacaoCnpj.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo numero do CNPJ da empresa", None))
        self.txtRelacaoCnpj.setInputMask(_translate("frmCadastroSetoresCargos", "00.000.000/0000-00; ", None))
        self.btnRelacaoDeletar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de deleção de um registro existente", None))
        self.btnRelacaoDeletar.setText(_translate("frmCadastroSetoresCargos", "Deletar", None))
        self.lblRelacaoIncricaoEstadual.setText(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.btnRelacaoSalvar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar um novo registro", None))
        self.btnRelacaoSalvar.setText(_translate("frmCadastroSetoresCargos", "Salvar", None))
        self.txtRelacaoCodigo.setToolTip(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.txtRelacaoCodigo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do Codigo de identificação da empresa", None))
        self.btnRelacaoNovo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de Criação de um novo registro", None))
        self.btnRelacaoNovo.setText(_translate("frmCadastroSetoresCargos", "Novo", None))
        self.btnRelacaoEditar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar edição de um registro existente", None))
        self.btnRelacaoEditar.setText(_translate("frmCadastroSetoresCargos", "Editar", None))
        self.lblRelacaoTipoEmpresa.setText(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.lblRelacaoCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtRelacaoNomeFantasia.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtRelacaoNomeFantasia.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.txtRelacaoTipoEmpresa.setToolTip(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtRelacaoTipoEmpresa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do tipo da empresa", None))
        self.txtRelacaoInscricaoEstadual.setToolTip(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.txtRelacaoInscricaoEstadual.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do numero da iscrição estadual da empresa", None))
        self.lblRelacaoNomeFantasia.setText(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtRelacaoSetor.setToolTip(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.txtRelacaoSetor.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo com o nome do setores", None))
        self.txtRelacaoCargo.setToolTip(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.txtRelacaoCargo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo com o tipo de cargos", None))
        self.lblRelacaoSetor.setText(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.lblRelacaoCargo.setText(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.lblRelacaoRazaoSocial.setText(_translate("frmCadastroSetoresCargos", "Razão Social", None))
        self.txtRelacaoRazaoSocial.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtRelacaoRazaoSocial.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.txtSetorCargoPesquisa.setToolTip(_translate("frmCadastroSetoresCargos", "Pesquisa", None))
        self.txtSetorCargoPesquisa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo pra inserir dados da pesquisa", None))
        self.grbSetorCargoDadosPesquisa.setTitle(_translate("frmCadastroSetoresCargos", "Dados Pesquisa", None))
        self.radSetorCargoBtnCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.radSetorCargoBtnFantasia.setText(_translate("frmCadastroSetoresCargos", "Fantasia", None))
        self.radSetorCargoBtnRazaoSocial.setText(_translate("frmCadastroSetoresCargos", "Razão Social", None))
        self.radSetorCargoBtnCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.radSetorCargoBtnSetor.setText(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.radSetorCargoBtnCargo.setText(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.tabwiCadastroSetoresCargos.setTabText(self.tabwiCadastroSetoresCargos.indexOf(self.tab), _translate("frmCadastroSetoresCargos", "Relação Setores e Cargos", None))

