# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroUsuarios.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroUsuarios(object):
    def setupUi(self, frmCadastroUsuarios):
        frmCadastroUsuarios.setObjectName(_fromUtf8("frmCadastroUsuarios"))
        frmCadastroUsuarios.resize(598, 418)
        frmCadastroUsuarios.setMinimumSize(QtCore.QSize(598, 418))
        frmCadastroUsuarios.setMaximumSize(QtCore.QSize(598, 418))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroUsuarios.setFont(font)
        self.tabwCadPermUsuario = QtGui.QTabWidget(frmCadastroUsuarios)
        self.tabwCadPermUsuario.setGeometry(QtCore.QRect(0, 0, 601, 421))
        self.tabwCadPermUsuario.setObjectName(_fromUtf8("tabwCadPermUsuario"))
        self.cadUsuario = QtGui.QWidget()
        self.cadUsuario.setObjectName(_fromUtf8("cadUsuario"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(187, 42, 351, 25))
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.txtCpfFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtCpfFuncionario.setEnabled(False)
        self.txtCpfFuncionario.setGeometry(QtCore.QRect(227, 88, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCpfFuncionario.setPalette(palette)
        self.txtCpfFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCpfFuncionario.setObjectName(_fromUtf8("txtCpfFuncionario"))
        self.lblSenhaFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblSenhaFuncionario.setGeometry(QtCore.QRect(17, 178, 41, 19))
        self.lblSenhaFuncionario.setObjectName(_fromUtf8("lblSenhaFuncionario"))
        self.lblRgFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblRgFuncionario.setGeometry(QtCore.QRect(15, 68, 31, 19))
        self.lblRgFuncionario.setObjectName(_fromUtf8("lblRgFuncionario"))
        self.grbBotoes = QtGui.QGroupBox(self.cadUsuario)
        self.grbBotoes.setGeometry(QtCore.QRect(5, 300, 585, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(90, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setGeometry(QtCore.QRect(390, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setGeometry(QtCore.QRect(490, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setGeometry(QtCore.QRect(190, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setGeometry(QtCore.QRect(290, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        self.lblNomeFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(187, 22, 121, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))
        self.lblCpfFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblCpfFuncionario.setGeometry(QtCore.QRect(227, 68, 31, 19))
        self.lblCpfFuncionario.setObjectName(_fromUtf8("lblCpfFuncionario"))
        self.lblCodigoFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(15, 22, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))
        self.lblLoginFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblLoginFuncionario.setGeometry(QtCore.QRect(17, 128, 41, 19))
        self.lblLoginFuncionario.setObjectName(_fromUtf8("lblLoginFuncionario"))
        self.txtidFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtidFuncionario.setGeometry(QtCore.QRect(15, 42, 161, 25))
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.txtSenhaFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtSenhaFuncionario.setGeometry(QtCore.QRect(17, 198, 211, 25))
        self.txtSenhaFuncionario.setMaxLength(50)
        self.txtSenhaFuncionario.setObjectName(_fromUtf8("txtSenhaFuncionario"))
        self.txtLoginFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtLoginFuncionario.setGeometry(QtCore.QRect(17, 148, 211, 25))
        self.txtLoginFuncionario.setMaxLength(20)
        self.txtLoginFuncionario.setObjectName(_fromUtf8("txtLoginFuncionario"))
        self.txtRgFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtRgFuncionario.setEnabled(False)
        self.txtRgFuncionario.setGeometry(QtCore.QRect(15, 88, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRgFuncionario.setPalette(palette)
        self.txtRgFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRgFuncionario.setObjectName(_fromUtf8("txtRgFuncionario"))
        self.btnCadUsuariosPesquisar = QtGui.QPushButton(self.cadUsuario)
        self.btnCadUsuariosPesquisar.setGeometry(QtCore.QRect(547, 40, 31, 27))
        self.btnCadUsuariosPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadUsuariosPesquisar.setText(_fromUtf8(""))
        self.btnCadUsuariosPesquisar.setObjectName(_fromUtf8("btnCadUsuariosPesquisar"))
        self.tabwCadPermUsuario.addTab(self.cadUsuario, _fromUtf8(""))
        self.permiUsuarios = QtGui.QWidget()
        self.permiUsuarios.setObjectName(_fromUtf8("permiUsuarios"))
        self.tabFuncioariosPermissoes = QtGui.QTableWidget(self.permiUsuarios)
        self.tabFuncioariosPermissoes.setGeometry(QtCore.QRect(10, 60, 251, 321))
        self.tabFuncioariosPermissoes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabFuncioariosPermissoes.setObjectName(_fromUtf8("tabFuncioariosPermissoes"))
        self.tabFuncioariosPermissoes.setColumnCount(0)
        self.tabFuncioariosPermissoes.setRowCount(0)
        self.btnCadPermiPesquisar = QtGui.QPushButton(self.permiUsuarios)
        self.btnCadPermiPesquisar.setGeometry(QtCore.QRect(230, 30, 31, 27))
        self.btnCadPermiPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadPermiPesquisar.setText(_fromUtf8(""))
        self.btnCadPermiPesquisar.setObjectName(_fromUtf8("btnCadPermiPesquisar"))
        self.txtNomeFuncionarioPermissoes = QtGui.QLineEdit(self.permiUsuarios)
        self.txtNomeFuncionarioPermissoes.setGeometry(QtCore.QRect(10, 30, 211, 25))
        self.txtNomeFuncionarioPermissoes.setObjectName(_fromUtf8("txtNomeFuncionarioPermissoes"))
        self.txtidFuncionarioPermissoes = QtGui.QLineEdit(self.permiUsuarios)
        self.txtidFuncionarioPermissoes.setEnabled(False)
        self.txtidFuncionarioPermissoes.setGeometry(QtCore.QRect(290, 30, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionarioPermissoes.setPalette(palette)
        self.txtidFuncionarioPermissoes.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionarioPermissoes.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtidFuncionarioPermissoes.setMaxLength(11)
        self.txtidFuncionarioPermissoes.setObjectName(_fromUtf8("txtidFuncionarioPermissoes"))
        self.tabTelasLiberadasPermissoes = QtGui.QTableWidget(self.permiUsuarios)
        self.tabTelasLiberadasPermissoes.setGeometry(QtCore.QRect(290, 130, 291, 251))
        self.tabTelasLiberadasPermissoes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabTelasLiberadasPermissoes.setObjectName(_fromUtf8("tabTelasLiberadasPermissoes"))
        self.tabTelasLiberadasPermissoes.setColumnCount(0)
        self.tabTelasLiberadasPermissoes.setRowCount(0)
        self.txtTelas = QtGui.QComboBox(self.permiUsuarios)
        self.txtTelas.setGeometry(QtCore.QRect(440, 30, 141, 30))
        self.txtTelas.setObjectName(_fromUtf8("txtTelas"))
        self.btnBloquear = QtGui.QPushButton(self.permiUsuarios)
        self.btnBloquear.setGeometry(QtCore.QRect(490, 90, 91, 23))
        self.btnBloquear.setObjectName(_fromUtf8("btnBloquear"))
        self.btnLiberar = QtGui.QPushButton(self.permiUsuarios)
        self.btnLiberar.setGeometry(QtCore.QRect(490, 64, 91, 23))
        self.btnLiberar.setObjectName(_fromUtf8("btnLiberar"))
        self.lblTelasPermissoes = QtGui.QLabel(self.permiUsuarios)
        self.lblTelasPermissoes.setGeometry(QtCore.QRect(440, 10, 41, 19))
        self.lblTelasPermissoes.setObjectName(_fromUtf8("lblTelasPermissoes"))
        self.lblCodigoFuncionarioPermissoes = QtGui.QLabel(self.permiUsuarios)
        self.lblCodigoFuncionarioPermissoes.setGeometry(QtCore.QRect(290, 10, 121, 19))
        self.lblCodigoFuncionarioPermissoes.setObjectName(_fromUtf8("lblCodigoFuncionarioPermissoes"))
        self.lblNomePermissoes = QtGui.QLabel(self.permiUsuarios)
        self.lblNomePermissoes.setGeometry(QtCore.QRect(10, 10, 121, 19))
        self.lblNomePermissoes.setObjectName(_fromUtf8("lblNomePermissoes"))
        self.tabwCadPermUsuario.addTab(self.permiUsuarios, _fromUtf8(""))
        self.lblSenhaFuncionario.setBuddy(self.txtSenhaFuncionario)
        self.lblRgFuncionario.setBuddy(self.txtRgFuncionario)
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblCpfFuncionario.setBuddy(self.txtCpfFuncionario)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)
        self.lblLoginFuncionario.setBuddy(self.txtLoginFuncionario)
        self.lblTelasPermissoes.setBuddy(self.txtTelas)
        self.lblCodigoFuncionarioPermissoes.setBuddy(self.txtidFuncionarioPermissoes)
        self.lblNomePermissoes.setBuddy(self.txtNomeFuncionarioPermissoes)

        self.retranslateUi(frmCadastroUsuarios)
        self.tabwCadPermUsuario.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroUsuarios)
        frmCadastroUsuarios.setTabOrder(self.tabwCadPermUsuario, self.txtidFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtidFuncionario, self.txtNomeFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtNomeFuncionario, self.txtRgFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtRgFuncionario, self.txtCpfFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtCpfFuncionario, self.txtLoginFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtLoginFuncionario, self.txtSenhaFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtSenhaFuncionario, self.txtNomeFuncionarioPermissoes)
        frmCadastroUsuarios.setTabOrder(self.txtNomeFuncionarioPermissoes, self.tabFuncioariosPermissoes)
        frmCadastroUsuarios.setTabOrder(self.tabFuncioariosPermissoes, self.txtTelas)
        frmCadastroUsuarios.setTabOrder(self.txtTelas, self.btnLiberar)
        frmCadastroUsuarios.setTabOrder(self.btnLiberar, self.btnBloquear)
        frmCadastroUsuarios.setTabOrder(self.btnBloquear, self.tabTelasLiberadasPermissoes)

    def retranslateUi(self, frmCadastroUsuarios):
        frmCadastroUsuarios.setWindowTitle(_translate("frmCadastroUsuarios", "Cadastro de Usuarios", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do nome do funcionario", None))
        self.txtCpfFuncionario.setToolTip(_translate("frmCadastroUsuarios", "CPF", None))
        self.txtCpfFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do numero do CPF do funcionario", None))
        self.txtCpfFuncionario.setInputMask(_translate("frmCadastroUsuarios", "000.000.000-00; ", None))
        self.lblSenhaFuncionario.setText(_translate("frmCadastroUsuarios", "Senha", None))
        self.lblRgFuncionario.setText(_translate("frmCadastroUsuarios", "RG", None))
        self.grbBotoes.setWhatsThis(_translate("frmCadastroUsuarios", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroUsuarios", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmCadastroUsuarios", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroUsuarios", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroUsuarios", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroUsuarios", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmCadastroUsuarios", "Salvar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroUsuarios", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.lblNomeFuncionario.setText(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.lblCpfFuncionario.setText(_translate("frmCadastroUsuarios", "CPF", None))
        self.lblCodigoFuncionario.setText(_translate("frmCadastroUsuarios", "Codigo Funcionario", None))
        self.lblLoginFuncionario.setText(_translate("frmCadastroUsuarios", "Login", None))
        self.txtidFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do Codigo de identificação do Funcionario", None))
        self.txtSenhaFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Senha", None))
        self.txtSenhaFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo de senha para autenticar o usuario", None))
        self.txtLoginFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Login", None))
        self.txtLoginFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo de login para autenticar o usuario", None))
        self.txtRgFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Rg", None))
        self.txtRgFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do numero do RG do funcionario", None))
        self.txtRgFuncionario.setInputMask(_translate("frmCadastroUsuarios", "000000-0; ", None))
        self.tabwCadPermUsuario.setTabText(self.tabwCadPermUsuario.indexOf(self.cadUsuario), _translate("frmCadastroUsuarios", "Cadastro de Usuario", None))
        self.tabFuncioariosPermissoes.setToolTip(_translate("frmCadastroUsuarios", "Tabela de usuarios", None))
        self.txtNomeFuncionarioPermissoes.setToolTip(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.txtNomeFuncionarioPermissoes.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do nome do funcionario", None))
        self.txtidFuncionarioPermissoes.setToolTip(_translate("frmCadastroUsuarios", "Codigo Funcionario", None))
        self.txtidFuncionarioPermissoes.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do Codigo de identificação do Funcionario", None))
        self.tabTelasLiberadasPermissoes.setToolTip(_translate("frmCadastroUsuarios", "Tabela de telas Liberadas", None))
        self.txtTelas.setToolTip(_translate("frmCadastroUsuarios", "Telas", None))
        self.txtTelas.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do nomes das telas para serem liberados ou bloqueados", None))
        self.btnBloquear.setText(_translate("frmCadastroUsuarios", "BLOQUEAR", None))
        self.btnLiberar.setText(_translate("frmCadastroUsuarios", "LIBERAR", None))
        self.lblTelasPermissoes.setText(_translate("frmCadastroUsuarios", "Tela", None))
        self.lblCodigoFuncionarioPermissoes.setText(_translate("frmCadastroUsuarios", "Codigo Funcionario", None))
        self.lblNomePermissoes.setText(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.tabwCadPermUsuario.setTabText(self.tabwCadPermUsuario.indexOf(self.permiUsuarios), _translate("frmCadastroUsuarios", "Permissões de Usuario", None))

