# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadFornecedor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroClienteFornecedor(object):
    def setupUi(self, frmCadastroClienteFornecedor):
        frmCadastroClienteFornecedor.setObjectName(_fromUtf8("frmCadastroClienteFornecedor"))
        frmCadastroClienteFornecedor.resize(890, 544)
        frmCadastroClienteFornecedor.setMinimumSize(QtCore.QSize(890, 544))
        frmCadastroClienteFornecedor.setMaximumSize(QtCore.QSize(890, 544))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroClienteFornecedor.setFont(font)
        frmCadastroClienteFornecedor.setSizeGripEnabled(True)
        frmCadastroClienteFornecedor.setModal(True)
        
        self.grbDadosPessoaFisicaJuridica = QtGui.QGroupBox(frmCadastroClienteFornecedor)
        self.grbDadosPessoaFisicaJuridica.setEnabled(False)
        self.grbDadosPessoaFisicaJuridica.setGeometry(QtCore.QRect(10, 53, 871, 161))
        self.grbDadosPessoaFisicaJuridica.setObjectName(_fromUtf8("grbDadosPessoaFisicaJuridica"))
        
        self.txtCnpj = QtGui.QLineEdit(self.grbDadosPessoaFisicaJuridica)
        self.txtCnpj.setEnabled(False)
        self.txtCnpj.setGeometry(QtCore.QRect(142, 38, 182, 25))
        self.txtCnpj.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpj.setText(_fromUtf8("../-"))
        self.txtCnpj.setCursorPosition(0)
        self.txtCnpj.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpj.setObjectName(_fromUtf8("txtCnpj"))
        
        self.lblRazaoSocial = QtGui.QLabel(self.grbDadosPessoaFisicaJuridica)
        self.lblRazaoSocial.setGeometry(QtCore.QRect(10, 64, 141, 19))
        self.lblRazaoSocial.setObjectName(_fromUtf8("lblRazaoSocial"))
        
        self.lblCnpj = QtGui.QLabel(self.grbDadosPessoaFisicaJuridica)
        self.lblCnpj.setGeometry(QtCore.QRect(142, 18, 81, 19))
        self.lblCnpj.setObjectName(_fromUtf8("lblCnpj"))
        
        self.txtRazaoSocial = QtGui.QLineEdit(self.grbDadosPessoaFisicaJuridica)
        self.txtRazaoSocial.setEnabled(False)
        self.txtRazaoSocial.setGeometry(QtCore.QRect(10, 84, 841, 25))
        self.txtRazaoSocial.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocial.setMaxLength(70)
        self.txtRazaoSocial.setObjectName(_fromUtf8("txtRazaoSocial"))
        
        self.lblNomeFantasia = QtGui.QLabel(self.grbDadosPessoaFisicaJuridica)
        self.lblNomeFantasia.setGeometry(QtCore.QRect(8, 108, 101, 19))
        self.lblNomeFantasia.setObjectName(_fromUtf8("lblNomeFantasia"))
        
        self.txtInscricaoEstadua = QtGui.QLineEdit(self.grbDadosPessoaFisicaJuridica)
        self.txtInscricaoEstadua.setEnabled(False)
        self.txtInscricaoEstadua.setGeometry(QtCore.QRect(330, 38, 178, 25))
        self.txtInscricaoEstadua.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadua.setMaxLength(8)
        self.txtInscricaoEstadua.setObjectName(_fromUtf8("txtInscricaoEstadua"))
        
        self.txtFantasia = QtGui.QLineEdit(self.grbDadosPessoaFisicaJuridica)
        self.txtFantasia.setEnabled(False)
        self.txtFantasia.setGeometry(QtCore.QRect(8, 128, 841, 25))
        self.txtFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasia.setMaxLength(70)
        self.txtFantasia.setObjectName(_fromUtf8("txtFantasia"))
        
        self.lblInscricaoEstadual = QtGui.QLabel(self.grbDadosPessoaFisicaJuridica)
        self.lblInscricaoEstadual.setGeometry(QtCore.QRect(330, 18, 121, 19))
        self.lblInscricaoEstadual.setObjectName(_fromUtf8("lblInscricaoEstadual"))
        
        self.lblCodigo = QtGui.QLabel(self.grbDadosPessoaFisicaJuridica)
        self.lblCodigo.setGeometry(QtCore.QRect(10, 18, 71, 19))
        self.lblCodigo.setObjectName(_fromUtf8("lblCodigo"))
        
        self.txtCodigo = QtGui.QLineEdit(self.grbDadosPessoaFisicaJuridica)
        self.txtCodigo.setGeometry(QtCore.QRect(10, 38, 121, 25))
        self.txtCodigo.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCodigo.setMaxLength(8)
        self.txtCodigo.setObjectName(_fromUtf8("txtCodigo"))
        
        self.btnPesquisarEmpresa = QtGui.QPushButton(self.grbDadosPessoaFisicaJuridica)
        self.btnPesquisarEmpresa.setGeometry(QtCore.QRect(123, 50, 16, 16))
        self.btnPesquisarEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarEmpresa.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search_mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarEmpresa.setIcon(icon)
        self.btnPesquisarEmpresa.setFlat(True)
        self.btnPesquisarEmpresa.setObjectName(_fromUtf8("btnPesquisarEmpresa"))
        
        self.tabWiAdicionais = QtGui.QTabWidget(frmCadastroClienteFornecedor)
        self.tabWiAdicionais.setEnabled(False)
        self.tabWiAdicionais.setGeometry(QtCore.QRect(10, 230, 871, 251))
        self.tabWiAdicionais.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWiAdicionais.setDocumentMode(True)
        self.tabWiAdicionais.setObjectName(_fromUtf8("tabWiAdicionais"))
        
        self.geral = QtGui.QWidget()
        self.geral.setObjectName(_fromUtf8("geral"))
        
        self.grbAtivo = QtGui.QGroupBox(self.geral)
        self.grbAtivo.setEnabled(False)
        self.grbAtivo.setGeometry(QtCore.QRect(0, 10, 341, 61))
        self.grbAtivo.setObjectName(_fromUtf8("grbAtivo"))
        
        self.radBtnAtivoCliente = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnAtivoCliente.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.radBtnAtivoCliente.setObjectName(_fromUtf8("radBtnAtivoCliente"))
        
        self.radBtnDesativoCliente = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnDesativoCliente.setGeometry(QtCore.QRect(20, 40, 131, 17))
        self.radBtnDesativoCliente.setObjectName(_fromUtf8("radBtnDesativoCliente"))
        
        self.radBtnAtivoFornecedor = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnAtivoFornecedor.setGeometry(QtCore.QRect(170, 20, 131, 17))
        self.radBtnAtivoFornecedor.setObjectName(_fromUtf8("radBtnAtivoFornecedor"))
        
        self.radBtnDesativoFornecedor = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnDesativoFornecedor.setGeometry(QtCore.QRect(170, 40, 161, 17))
        self.radBtnDesativoFornecedor.setObjectName(_fromUtf8("radBtnDesativoFornecedor"))
        
        self.tabWiAdicionais.addTab(self.geral, _fromUtf8(""))
        self.contatos = QtGui.QWidget()
        self.contatos.setObjectName(_fromUtf8("contatos"))
        
        self.tabContatoTelefone = QtGui.QTableWidget(self.contatos)
        self.tabContatoTelefone.setGeometry(QtCore.QRect(13, 84, 361, 111))
        self.tabContatoTelefone.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabContatoTelefone.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabContatoTelefone.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabContatoTelefone.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabContatoTelefone.setObjectName(_fromUtf8("tabContatoTelefone"))
        
        self.tabContatoTelefone.setColumnCount(2)
        self.tabContatoTelefone.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabContatoTelefone.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabContatoTelefone.setHorizontalHeaderItem(1, item)
        self.tabContatoTelefone.horizontalHeader().setStretchLastSection(True)
        self.tabContatoTelefone.verticalHeader().setVisible(False)
        self.btnRemoverTelefone = QtGui.QPushButton(self.contatos)
        self.btnRemoverTelefone.setGeometry(QtCore.QRect(343, 200, 31, 27))
        self.btnRemoverTelefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverTelefone.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoverTelefone.setIcon(icon1)
        self.btnRemoverTelefone.setObjectName(_fromUtf8("btnRemoverTelefone"))
        
        self.btnAddEmail = QtGui.QPushButton(self.contatos)
        self.btnAddEmail.setGeometry(QtCore.QRect(823, 39, 31, 27))
        self.btnAddEmail.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddEmail.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddEmail.setIcon(icon2)
        self.btnAddEmail.setObjectName(_fromUtf8("btnAddEmail"))
        
        self.lblContatoTelefone = QtGui.QLabel(self.contatos)
        self.lblContatoTelefone.setGeometry(QtCore.QRect(13, 27, 53, 13))
        self.lblContatoTelefone.setObjectName(_fromUtf8("lblContatoTelefone"))
        
        self.lblContatoEmail = QtGui.QLabel(self.contatos)
        self.lblContatoEmail.setGeometry(QtCore.QRect(493, 16, 53, 13))
        self.lblContatoEmail.setObjectName(_fromUtf8("lblContatoEmail"))
        
        self.btnAddTelefone = QtGui.QPushButton(self.contatos)
        self.btnAddTelefone.setGeometry(QtCore.QRect(343, 50, 31, 27))
        self.btnAddTelefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddTelefone.setText(_fromUtf8(""))
        self.btnAddTelefone.setIcon(icon2)
        self.btnAddTelefone.setObjectName(_fromUtf8("btnAddTelefone"))

        self.txtNumeroTelefone = QtGui.QLineEdit(self.contatos)
        self.txtNumeroTelefone.setGeometry(QtCore.QRect(73, 51, 261, 25))
        self.txtNumeroTelefone.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtNumeroTelefone.setMaxLength(15)
        self.txtNumeroTelefone.setObjectName(_fromUtf8("txtNumeroTelefone"))
        
        self.txtEnderecoEmail = QtGui.QLineEdit(self.contatos)
        self.txtEnderecoEmail.setGeometry(QtCore.QRect(553, 40, 261, 25))
        self.txtEnderecoEmail.setMaxLength(50)
        self.txtEnderecoEmail.setObjectName(_fromUtf8("txtEnderecoEmail"))
        
        self.txtContatoEmail = QtGui.QLineEdit(self.contatos)
        self.txtContatoEmail.setGeometry(QtCore.QRect(553, 10, 261, 25))
        self.txtContatoEmail.setMaxLength(25)
        self.txtContatoEmail.setObjectName(_fromUtf8("txtContatoEmail"))
        
        self.tabContatoEmail = QtGui.QTableWidget(self.contatos)
        self.tabContatoEmail.setGeometry(QtCore.QRect(493, 73, 361, 121))
        self.tabContatoEmail.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabContatoEmail.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabContatoEmail.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabContatoEmail.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabContatoEmail.setObjectName(_fromUtf8("tabContatoEmail"))
        
        self.tabContatoEmail.setColumnCount(2)
        self.tabContatoEmail.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabContatoEmail.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabContatoEmail.setHorizontalHeaderItem(1, item)
        self.tabContatoEmail.horizontalHeader().setStretchLastSection(True)
        self.tabContatoEmail.verticalHeader().setVisible(False)
        self.txtContatoTelefone = QtGui.QLineEdit(self.contatos)
        self.txtContatoTelefone.setGeometry(QtCore.QRect(73, 21, 261, 25))
        self.txtContatoTelefone.setMaxLength(25)
        self.txtContatoTelefone.setObjectName(_fromUtf8("txtContatoTelefone"))
        
        self.lblEmail = QtGui.QLabel(self.contatos)
        self.lblEmail.setGeometry(QtCore.QRect(493, 44, 61, 16))
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        
        self.btnRemoverEmail = QtGui.QPushButton(self.contatos)
        self.btnRemoverEmail.setGeometry(QtCore.QRect(823, 200, 31, 27))
        self.btnRemoverEmail.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverEmail.setText(_fromUtf8(""))
        self.btnRemoverEmail.setIcon(icon1)
        self.btnRemoverEmail.setObjectName(_fromUtf8("btnRemoverEmail"))
        
        self.lblTelefone = QtGui.QLabel(self.contatos)
        self.lblTelefone.setGeometry(QtCore.QRect(13, 55, 61, 16))
        self.lblTelefone.setObjectName(_fromUtf8("lblTelefone"))
        
        self.tabWiAdicionais.addTab(self.contatos, _fromUtf8(""))
        self.grbBotoes = QtGui.QGroupBox(frmCadastroClienteFornecedor)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 490, 871, 51))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(360, 12, 88, 27))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon3)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(460, 12, 88, 27))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon4)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(660, 12, 88, 27))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon5)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(760, 10, 88, 27))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/critical.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeletar.setIcon(icon6)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(560, 12, 88, 27))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/Save-as_37111.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon7)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        
        self.lblPesquisar = QtGui.QLabel(self.grbBotoes)
        self.lblPesquisar.setGeometry(QtCore.QRect(10, 20, 111, 19))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblPesquisar.setPalette(palette)
        self.lblPesquisar.setObjectName(_fromUtf8("lblPesquisar"))
        
        self.grbTipoPessoa = QtGui.QGroupBox(frmCadastroClienteFornecedor)
        self.grbTipoPessoa.setEnabled(False)
        self.grbTipoPessoa.setGeometry(QtCore.QRect(10, 3, 261, 42))
        self.grbTipoPessoa.setObjectName(_fromUtf8("grbTipoPessoa"))
        
        self.radBtnPessoaFisica = QtGui.QRadioButton(self.grbTipoPessoa)
        self.radBtnPessoaFisica.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.radBtnPessoaFisica.setObjectName(_fromUtf8("radBtnPessoaFisica"))
        
        self.radBtnPessoaJuridica = QtGui.QRadioButton(self.grbTipoPessoa)
        self.radBtnPessoaJuridica.setGeometry(QtCore.QRect(130, 20, 121, 17))
        self.radBtnPessoaJuridica.setObjectName(_fromUtf8("radBtnPessoaJuridica"))
        
        self.grbTipoCadastro = QtGui.QGroupBox(frmCadastroClienteFornecedor)
        self.grbTipoCadastro.setEnabled(False)
        self.grbTipoCadastro.setGeometry(QtCore.QRect(280, 4, 201, 40))
        self.grbTipoCadastro.setObjectName(_fromUtf8("grbTipoCadastro"))
        
        self.checkBoxCliente = QtGui.QCheckBox(self.grbTipoCadastro)
        self.checkBoxCliente.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBoxCliente.setObjectName(_fromUtf8("checkBoxCliente"))
        
        self.checkBoxFornecedor = QtGui.QCheckBox(self.grbTipoCadastro)
        self.checkBoxFornecedor.setGeometry(QtCore.QRect(90, 20, 101, 17))
        self.checkBoxFornecedor.setObjectName(_fromUtf8("checkBoxFornecedor"))
        
        self.lblRazaoSocial.setBuddy(self.txtRazaoSocial)
        self.lblCnpj.setBuddy(self.txtCnpj)
        self.lblNomeFantasia.setBuddy(self.txtFantasia)
        self.lblInscricaoEstadual.setBuddy(self.txtInscricaoEstadua)
        self.lblCodigo.setBuddy(self.txtCodigo)

        self.retranslateUi(frmCadastroClienteFornecedor)
        self.tabWiAdicionais.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroClienteFornecedor)
        frmCadastroClienteFornecedor.setTabOrder(self.txtCodigo, self.txtCnpj)
        frmCadastroClienteFornecedor.setTabOrder(self.txtCnpj, self.txtInscricaoEstadua)
        frmCadastroClienteFornecedor.setTabOrder(self.txtInscricaoEstadua, self.txtRazaoSocial)
        frmCadastroClienteFornecedor.setTabOrder(self.txtRazaoSocial, self.txtFantasia)
        frmCadastroClienteFornecedor.setTabOrder(self.txtFantasia, self.tabWiAdicionais)
        frmCadastroClienteFornecedor.setTabOrder(self.tabWiAdicionais, self.radBtnAtivoCliente)
        frmCadastroClienteFornecedor.setTabOrder(self.radBtnAtivoCliente, self.radBtnDesativoCliente)
        frmCadastroClienteFornecedor.setTabOrder(self.radBtnDesativoCliente, self.txtContatoTelefone)
        frmCadastroClienteFornecedor.setTabOrder(self.txtContatoTelefone, self.txtNumeroTelefone)
        frmCadastroClienteFornecedor.setTabOrder(self.txtNumeroTelefone, self.txtContatoEmail)
        frmCadastroClienteFornecedor.setTabOrder(self.txtContatoEmail, self.txtEnderecoEmail)

    def retranslateUi(self, frmCadastroClienteFornecedor):
        frmCadastroClienteFornecedor.setWindowTitle(_translate("frmCadastroClienteFornecedor", "Cadastro Cliente / Fornecedor", None))
        self.grbDadosPessoaFisicaJuridica.setWhatsThis(_translate("frmCadastroClienteFornecedor", "Grupo de Dados para cadastro e edição de empresas", None))
        self.grbDadosPessoaFisicaJuridica.setTitle(_translate("frmCadastroClienteFornecedor", "Dados Pessoa Fisica / Juridica", None))
        self.txtCnpj.setToolTip(_translate("frmCadastroClienteFornecedor", "CNPJ", None))
        self.txtCnpj.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do numero do CNPJ ou CPF do cliente / fornecedor</p></body></html>", None))
        self.txtCnpj.setInputMask(_translate("frmCadastroClienteFornecedor", "00.000.000/0000-00; ", None))
        self.lblRazaoSocial.setText(_translate("frmCadastroClienteFornecedor", "Razão Social / Nome", None))
        self.lblCnpj.setText(_translate("frmCadastroClienteFornecedor", "CNPJ / CPF", None))
        self.txtRazaoSocial.setToolTip(_translate("frmCadastroClienteFornecedor", "Razão Social", None))
        self.txtRazaoSocial.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do nome da razão social ou nome do cliente / fornecedor</p></body></html>", None))
        self.lblNomeFantasia.setText(_translate("frmCadastroClienteFornecedor", "Fantasia", None))
        self.txtInscricaoEstadua.setToolTip(_translate("frmCadastroClienteFornecedor", "Inscrição Estadual", None))
        self.txtInscricaoEstadua.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do numero do inscrição estadual ou RG do cliente / fornecedor</p></body></html>", None))
        self.txtFantasia.setToolTip(_translate("frmCadastroClienteFornecedor", "Nome Fantasia", None))
        self.txtFantasia.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do nome fantasia ou apelido do cliente / fornecedor</p></body></html>", None))
        self.lblInscricaoEstadual.setText(_translate("frmCadastroClienteFornecedor", "Incr. Esta. / RG", None))
        self.lblCodigo.setText(_translate("frmCadastroClienteFornecedor", "Codigo", None))
        self.txtCodigo.setToolTip(_translate("frmCadastroClienteFornecedor", "Inscrição Estadual", None))
        self.txtCodigo.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do numero de identificação do cliente / fornecedor</p></body></html>", None))
        self.btnPesquisarEmpresa.setWhatsThis(_translate("frmCadastroClienteFornecedor", "Botão para pesquisar dados de empresa", None))
        self.tabWiAdicionais.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão adicionar um novo cargo a lista</p></body></html>", None))
        self.grbAtivo.setTitle(_translate("frmCadastroClienteFornecedor", "Situação", None))
        self.radBtnAtivoCliente.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para cliente ativa e operante</p></body></html>", None))
        self.radBtnAtivoCliente.setText(_translate("frmCadastroClienteFornecedor", "Ativo Cliente", None))
        self.radBtnDesativoCliente.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para cliente desativado e inoperante</p></body></html>", None))
        self.radBtnDesativoCliente.setText(_translate("frmCadastroClienteFornecedor", "Desativo Cliente", None))
        self.radBtnAtivoFornecedor.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para fornecedor ativa e operante</p></body></html>", None))
        self.radBtnAtivoFornecedor.setText(_translate("frmCadastroClienteFornecedor", "Ativo Fornecedor", None))
        self.radBtnDesativoFornecedor.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para fornecedor desativado e inoperante</p></body></html>", None))
        self.radBtnDesativoFornecedor.setText(_translate("frmCadastroClienteFornecedor", "Desativo Fornecedor", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.geral), _translate("frmCadastroClienteFornecedor", "Geral", None))
        self.tabContatoTelefone.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Tabela de informações de contato de telefone</p></body></html>", None))
        item = self.tabContatoTelefone.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroClienteFornecedor", "Contato", None))
        item = self.tabContatoTelefone.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroClienteFornecedor", "Telefone", None))
        self.btnRemoverTelefone.setToolTip(_translate("frmCadastroClienteFornecedor", "Remover", None))
        self.btnRemoverTelefone.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão remover um contato  de telefone a lista</p></body></html>", None))
        self.btnAddEmail.setToolTip(_translate("frmCadastroClienteFornecedor", "Adicionar", None))
        self.btnAddEmail.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão adicionar um contato de e-mail a lista</p></body></html>", None))
        self.lblContatoTelefone.setText(_translate("frmCadastroClienteFornecedor", "Contato", None))
        self.lblContatoEmail.setText(_translate("frmCadastroClienteFornecedor", "Contato", None))
        self.btnAddTelefone.setToolTip(_translate("frmCadastroClienteFornecedor", "Adicionar", None))
        self.btnAddTelefone.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão adicionar um contato de telefone a lista</p></body></html>", None))
        self.txtNumeroTelefone.setToolTip(_translate("frmCadastroClienteFornecedor", "Telefone", None))
        self.txtNumeroTelefone.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do numero de telefone do contato</p></body></html>", None))
        self.txtEnderecoEmail.setToolTip(_translate("frmCadastroClienteFornecedor", "E-mail", None))
        self.txtEnderecoEmail.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do endereço de e-mail do contato</p></body></html>", None))
        self.txtContatoEmail.setToolTip(_translate("frmCadastroClienteFornecedor", "Contato", None))
        self.txtContatoEmail.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do nome do contato</p></body></html>", None))
        self.tabContatoEmail.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Tabela de informações de endereço de e-mail</p></body></html>", None))
        item = self.tabContatoEmail.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroClienteFornecedor", "Contato", None))
        item = self.tabContatoEmail.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroClienteFornecedor", "E-mail", None))
        self.txtContatoTelefone.setToolTip(_translate("frmCadastroClienteFornecedor", "Contato", None))
        self.txtContatoTelefone.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Campo do nome do contato</p></body></html>", None))
        self.lblEmail.setText(_translate("frmCadastroClienteFornecedor", "E-mail", None))
        self.btnRemoverEmail.setToolTip(_translate("frmCadastroClienteFornecedor", "Remover", None))
        self.btnRemoverEmail.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão remover um contato de e-mail da lista</p></body></html>", None))
        self.lblTelefone.setText(_translate("frmCadastroClienteFornecedor", "Telefone", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.contatos), _translate("frmCadastroClienteFornecedor", "Contato", None))
        self.btnNovo.setToolTip(_translate("frmCadastroClienteFornecedor", "Novo", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão para cadastrar uma novo registro da pessoa jurídica</p></body></html>", None))
        self.btnNovo.setText(_translate("frmCadastroClienteFornecedor", "Novo", None))
        self.btnSalvar.setToolTip(_translate("frmCadastroClienteFornecedor", "Salvar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão para salvar um novo registro da pessoa jurídica</p></body></html>", None))
        self.btnSalvar.setText(_translate("frmCadastroClienteFornecedor", "Salvar", None))
        self.btnCancelar.setToolTip(_translate("frmCadastroClienteFornecedor", "Cancelar", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroClienteFornecedor", "Botão para cancelar a operação ", None))
        self.btnCancelar.setText(_translate("frmCadastroClienteFornecedor", "Cancelar", None))
        self.btnDeletar.setToolTip(_translate("frmCadastroClienteFornecedor", "Deletar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão de deletar o registro da pessoa jurídica</p></body></html>", None))
        self.btnDeletar.setText(_translate("frmCadastroClienteFornecedor", "Deletar", None))
        self.btnEditar.setToolTip(_translate("frmCadastroClienteFornecedor", "Editar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Botão para salvar o registo editado da pessoa jurídica</p></body></html>", None))
        self.btnEditar.setText(_translate("frmCadastroClienteFornecedor", "Editar", None))
        self.lblPesquisar.setText(_translate("frmCadastroClienteFornecedor", "[F12] Pesquisar", None))
        self.grbTipoPessoa.setTitle(_translate("frmCadastroClienteFornecedor", "Tipo de Pessoa", None))
        self.radBtnPessoaFisica.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para cadastro de cliente / fornecedor Pessoa Fisica</p></body></html>", None))
        self.radBtnPessoaFisica.setText(_translate("frmCadastroClienteFornecedor", "Pessoa Fisica", None))
        self.radBtnPessoaJuridica.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para cadastro de cliente / fornecedor Pessoa Juridica</p></body></html>", None))
        self.radBtnPessoaJuridica.setText(_translate("frmCadastroClienteFornecedor", "Pessoa Juridica", None))
        self.grbTipoCadastro.setTitle(_translate("frmCadastroClienteFornecedor", "Tipo do Cadastro", None))
        self.checkBoxCliente.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para cadastro de cliente </p></body></html>", None))
        self.checkBoxCliente.setText(_translate("frmCadastroClienteFornecedor", "Cliente", None))
        self.checkBoxFornecedor.setWhatsThis(_translate("frmCadastroClienteFornecedor", "<html><head/><body><p>Item de seleção para cadastro de fornecedor </p></body></html>", None))
        self.checkBoxFornecedor.setText(_translate("frmCadastroClienteFornecedor", "Fornecedor", None))

