# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadUsuarios.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroUsuarios(object):
    def setupUi(self, frmCadastroUsuarios):
        frmCadastroUsuarios.setObjectName(_fromUtf8("frmCadastroUsuarios"))
        frmCadastroUsuarios.setMinimumSize(QtCore.QSize(822, 554))
        frmCadastroUsuarios.setMaximumSize(QtCore.QSize(822, 554))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroUsuarios.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/tag_user_card.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCadastroUsuarios.setWindowIcon(icon)
        frmCadastroUsuarios.setSizeGripEnabled(True)
        frmCadastroUsuarios.setModal(True)

        self.tabwCadPermUsuario = QtGui.QTabWidget(frmCadastroUsuarios)
        self.tabwCadPermUsuario.setEnabled(False)
        self.tabwCadPermUsuario.setGeometry(QtCore.QRect(10, 130, 805, 361))
        self.tabwCadPermUsuario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabwCadPermUsuario.setObjectName(_fromUtf8("tabwCadPermUsuario"))
        self.cadUsuario = QtGui.QWidget()
        self.cadUsuario.setObjectName(_fromUtf8("cadUsuario"))
        self.lblSenhaFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblSenhaFuncionario.setGeometry(QtCore.QRect(10, 70, 41, 19))
        self.lblSenhaFuncionario.setObjectName(_fromUtf8("lblSenhaFuncionario"))
        self.lblLoginFuncionario = QtGui.QLabel(self.cadUsuario)
        self.lblLoginFuncionario.setGeometry(QtCore.QRect(10, 20, 41, 19))
        self.lblLoginFuncionario.setObjectName(_fromUtf8("lblLoginFuncionario"))
        self.txtSenhaFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtSenhaFuncionario.setGeometry(QtCore.QRect(10, 90, 471, 25))
        self.txtSenhaFuncionario.setMaxLength(20)
        self.txtSenhaFuncionario.setObjectName(_fromUtf8("txtSenhaFuncionario"))
        self.txtLoginFuncionario = QtGui.QLineEdit(self.cadUsuario)
        self.txtLoginFuncionario.setGeometry(QtCore.QRect(10, 40, 471, 25))
        self.txtLoginFuncionario.setMaxLength(12)
        self.txtLoginFuncionario.setObjectName(_fromUtf8("txtLoginFuncionario"))
        self.tabwCadPermUsuario.addTab(self.cadUsuario, _fromUtf8(""))
        self.permiUsuarios = QtGui.QWidget()
        self.permiUsuarios.setObjectName(_fromUtf8("permiUsuarios"))
        self.stackedWidget = QtGui.QStackedWidget(self.permiUsuarios)
        self.stackedWidget.setGeometry(QtCore.QRect(7, 10, 784, 311))
        self.stackedWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pg1 = QtGui.QWidget()
        self.pg1.setObjectName(_fromUtf8("pg1"))
        self.grbPessoaFisica = QtGui.QGroupBox(self.pg1)
        self.grbPessoaFisica.setGeometry(QtCore.QRect(10, 20, 101, 131))
        self.grbPessoaFisica.setObjectName(_fromUtf8("grbPessoaFisica"))
        self.cBoxPessoaFisicaCadastro = QtGui.QCheckBox(self.grbPessoaFisica)
        self.cBoxPessoaFisicaCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxPessoaFisicaCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaFisicaCadastro.setObjectName(_fromUtf8("cBoxPessoaFisicaCadastro"))
        self.cBoxPessoaFisicaEditar = QtGui.QCheckBox(self.grbPessoaFisica)
        self.cBoxPessoaFisicaEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxPessoaFisicaEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaFisicaEditar.setObjectName(_fromUtf8("cBoxPessoaFisicaEditar"))
        self.cBoxPessoaFisicaCancelar = QtGui.QCheckBox(self.grbPessoaFisica)
        self.cBoxPessoaFisicaCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxPessoaFisicaCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaFisicaCancelar.setObjectName(_fromUtf8("cBoxPessoaFisicaCancelar"))
        self.cBoxPessoaFisicaDeletar = QtGui.QCheckBox(self.grbPessoaFisica)
        self.cBoxPessoaFisicaDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxPessoaFisicaDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaFisicaDeletar.setObjectName(_fromUtf8("cBoxPessoaFisicaDeletar"))
        self.cBoxPessoaFisica = QtGui.QCheckBox(self.grbPessoaFisica)
        self.cBoxPessoaFisica.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxPessoaFisica.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaFisica.setObjectName(_fromUtf8("cBoxPessoaFisica"))
        self.grbFornecedor = QtGui.QGroupBox(self.pg1)
        self.grbFornecedor.setGeometry(QtCore.QRect(450, 20, 101, 131))
        self.grbFornecedor.setObjectName(_fromUtf8("grbFornecedor"))
        self.cBoxFornecedorCadastro = QtGui.QCheckBox(self.grbFornecedor)
        self.cBoxFornecedorCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxFornecedorCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFornecedorCadastro.setObjectName(_fromUtf8("cBoxFornecedorCadastro"))
        self.cBoxFornecedorEditar = QtGui.QCheckBox(self.grbFornecedor)
        self.cBoxFornecedorEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxFornecedorEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFornecedorEditar.setObjectName(_fromUtf8("cBoxFornecedorEditar"))
        self.cBoxFornecedorCancelar = QtGui.QCheckBox(self.grbFornecedor)
        self.cBoxFornecedorCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxFornecedorCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFornecedorCancelar.setObjectName(_fromUtf8("cBoxFornecedorCancelar"))
        self.cBoxFornecedorDeletar = QtGui.QCheckBox(self.grbFornecedor)
        self.cBoxFornecedorDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxFornecedorDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFornecedorDeletar.setObjectName(_fromUtf8("cBoxFornecedorDeletar"))
        self.cBoxFornecedorAtivar = QtGui.QCheckBox(self.grbFornecedor)
        self.cBoxFornecedorAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxFornecedorAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFornecedorAtivar.setObjectName(_fromUtf8("cBoxFornecedorAtivar"))
        self.grbPessoaJuridica = QtGui.QGroupBox(self.pg1)
        self.grbPessoaJuridica.setGeometry(QtCore.QRect(120, 20, 101, 131))
        self.grbPessoaJuridica.setObjectName(_fromUtf8("grbPessoaJuridica"))
        self.cBoxPessoaJuridicaCadastro = QtGui.QCheckBox(self.grbPessoaJuridica)
        self.cBoxPessoaJuridicaCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxPessoaJuridicaCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaJuridicaCadastro.setObjectName(_fromUtf8("cBoxPessoaJuridicaCadastro"))
        self.cBoxPessoaJuridicaEditar = QtGui.QCheckBox(self.grbPessoaJuridica)
        self.cBoxPessoaJuridicaEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxPessoaJuridicaEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaJuridicaEditar.setObjectName(_fromUtf8("cBoxPessoaJuridicaEditar"))
        self.cBoxPessoaJuridicaCancelar = QtGui.QCheckBox(self.grbPessoaJuridica)
        self.cBoxPessoaJuridicaCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxPessoaJuridicaCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaJuridicaCancelar.setObjectName(_fromUtf8("cBoxPessoaJuridicaCancelar"))
        self.cBoxPessoaJuridicaDeletar = QtGui.QCheckBox(self.grbPessoaJuridica)
        self.cBoxPessoaJuridicaDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxPessoaJuridicaDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaJuridicaDeletar.setObjectName(_fromUtf8("cBoxPessoaJuridicaDeletar"))
        self.cBoxPessoaJuridicaAtivar = QtGui.QCheckBox(self.grbPessoaJuridica)
        self.cBoxPessoaJuridicaAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxPessoaJuridicaAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxPessoaJuridicaAtivar.setObjectName(_fromUtf8("cBoxPessoaJuridicaAtivar"))
        self.grbCliente = QtGui.QGroupBox(self.pg1)
        self.grbCliente.setGeometry(QtCore.QRect(560, 20, 101, 131))
        self.grbCliente.setObjectName(_fromUtf8("grbCliente"))
        self.cBoxClienteCadastro = QtGui.QCheckBox(self.grbCliente)
        self.cBoxClienteCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxClienteCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxClienteCadastro.setObjectName(_fromUtf8("cBoxClienteCadastro"))
        self.cBoxClienteEditar = QtGui.QCheckBox(self.grbCliente)
        self.cBoxClienteEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxClienteEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxClienteEditar.setObjectName(_fromUtf8("cBoxClienteEditar"))
        self.cBoxClienteCancelar = QtGui.QCheckBox(self.grbCliente)
        self.cBoxClienteCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxClienteCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxClienteCancelar.setObjectName(_fromUtf8("cBoxClienteCancelar"))
        self.cBoxClienteDeletar = QtGui.QCheckBox(self.grbCliente)
        self.cBoxClienteDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxClienteDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxClienteDeletar.setObjectName(_fromUtf8("cBoxClienteDeletar"))
        self.cBoxClienteAtivar = QtGui.QCheckBox(self.grbCliente)
        self.cBoxClienteAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxClienteAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxClienteAtivar.setObjectName(_fromUtf8("cBoxClienteAtivar"))
        self.grbEmpresa = QtGui.QGroupBox(self.pg1)
        self.grbEmpresa.setGeometry(QtCore.QRect(230, 20, 101, 131))
        self.grbEmpresa.setObjectName(_fromUtf8("grbEmpresa"))
        self.cBoxEmpresaCadastro = QtGui.QCheckBox(self.grbEmpresa)
        self.cBoxEmpresaCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxEmpresaCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxEmpresaCadastro.setObjectName(_fromUtf8("cBoxEmpresaCadastro"))
        self.cBoxEmpresaEditar = QtGui.QCheckBox(self.grbEmpresa)
        self.cBoxEmpresaEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxEmpresaEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxEmpresaEditar.setObjectName(_fromUtf8("cBoxEmpresaEditar"))
        self.cBoxEmpresaCancelar = QtGui.QCheckBox(self.grbEmpresa)
        self.cBoxEmpresaCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxEmpresaCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxEmpresaCancelar.setObjectName(_fromUtf8("cBoxEmpresaCancelar"))
        self.cBoxEmpresaDeletar = QtGui.QCheckBox(self.grbEmpresa)
        self.cBoxEmpresaDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxEmpresaDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxEmpresaDeletar.setObjectName(_fromUtf8("cBoxEmpresaDeletar"))
        self.cBoxEmpresaAtivar = QtGui.QCheckBox(self.grbEmpresa)
        self.cBoxEmpresaAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxEmpresaAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxEmpresaAtivar.setObjectName(_fromUtf8("cBoxEmpresaAtivar"))
        self.grbEntradaVeiculosCarregamento = QtGui.QGroupBox(self.pg1)
        self.grbEntradaVeiculosCarregamento.setGeometry(QtCore.QRect(450, 160, 101, 131))
        self.grbEntradaVeiculosCarregamento.setObjectName(_fromUtf8("grbEntradaVeiculosCarregamento"))
        self.cheBoxEntradaVeiculosCarregamentoCadastro = QtGui.QCheckBox(self.grbEntradaVeiculosCarregamento)
        self.cheBoxEntradaVeiculosCarregamentoCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxEntradaVeiculosCarregamentoCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosCarregamentoCadastro.setObjectName(_fromUtf8("cheBoxEntradaVeiculosCarregamentoCadastro"))
        self.cheBoxEntradaVeiculosCarregamentoEditar = QtGui.QCheckBox(self.grbEntradaVeiculosCarregamento)
        self.cheBoxEntradaVeiculosCarregamentoEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxEntradaVeiculosCarregamentoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosCarregamentoEditar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosCarregamentoEditar"))
        self.cheBoxEntradaVeiculosCarregamentoCancelar = QtGui.QCheckBox(self.grbEntradaVeiculosCarregamento)
        self.cheBoxEntradaVeiculosCarregamentoCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxEntradaVeiculosCarregamentoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosCarregamentoCancelar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosCarregamentoCancelar"))
        self.cheBoxEntradaVeiculosCarregamentoDeletar = QtGui.QCheckBox(self.grbEntradaVeiculosCarregamento)
        self.cheBoxEntradaVeiculosCarregamentoDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxEntradaVeiculosCarregamentoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosCarregamentoDeletar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosCarregamentoDeletar"))
        self.cheBoxEntradaVeiculosCarregamentoAtivar = QtGui.QCheckBox(self.grbEntradaVeiculosCarregamento)
        self.cheBoxEntradaVeiculosCarregamentoAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxEntradaVeiculosCarregamentoAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosCarregamentoAtivar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosCarregamentoAtivar"))
        self.grbUsuariosPermissao = QtGui.QGroupBox(self.pg1)
        self.grbUsuariosPermissao.setGeometry(QtCore.QRect(10, 160, 101, 131))
        self.grbUsuariosPermissao.setObjectName(_fromUtf8("grbUsuariosPermissao"))
        self.cBoxUsuPermCadastro = QtGui.QCheckBox(self.grbUsuariosPermissao)
        self.cBoxUsuPermCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxUsuPermCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxUsuPermCadastro.setObjectName(_fromUtf8("cBoxUsuPermCadastro"))
        self.cBoxUsuPermEditar = QtGui.QCheckBox(self.grbUsuariosPermissao)
        self.cBoxUsuPermEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxUsuPermEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxUsuPermEditar.setObjectName(_fromUtf8("cBoxUsuPermEditar"))
        self.cBoxUsuPermCancelar = QtGui.QCheckBox(self.grbUsuariosPermissao)
        self.cBoxUsuPermCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxUsuPermCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxUsuPermCancelar.setObjectName(_fromUtf8("cBoxUsuPermCancelar"))
        self.cBoxUsuPermDeletar = QtGui.QCheckBox(self.grbUsuariosPermissao)
        self.cBoxUsuPermDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxUsuPermDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxUsuPermDeletar.setObjectName(_fromUtf8("cBoxUsuPermDeletar"))
        self.cBoxUsuPermAtivar = QtGui.QCheckBox(self.grbUsuariosPermissao)
        self.cBoxUsuPermAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxUsuPermAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxUsuPermAtivar.setObjectName(_fromUtf8("cBoxUsuPermAtivar"))
        self.grbSaidaVeiculosDescarregamento = QtGui.QGroupBox(self.pg1)
        self.grbSaidaVeiculosDescarregamento.setGeometry(QtCore.QRect(340, 160, 101, 131))
        self.grbSaidaVeiculosDescarregamento.setObjectName(_fromUtf8("grbSaidaVeiculosDescarregamento"))
        self.cheBoxSaidaVeiculosDescarregamentoCadastro = QtGui.QCheckBox(self.grbSaidaVeiculosDescarregamento)
        self.cheBoxSaidaVeiculosDescarregamentoCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxSaidaVeiculosDescarregamentoCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosDescarregamentoCadastro.setObjectName(_fromUtf8("cheBoxSaidaVeiculosDescarregamentoCadastro"))
        self.cheBoxSaidaVeiculosDescarregamentoEditar = QtGui.QCheckBox(self.grbSaidaVeiculosDescarregamento)
        self.cheBoxSaidaVeiculosDescarregamentoEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxSaidaVeiculosDescarregamentoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosDescarregamentoEditar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosDescarregamentoEditar"))
        self.cheBoxSaidaVeiculosDescarregamentoCancelar = QtGui.QCheckBox(self.grbSaidaVeiculosDescarregamento)
        self.cheBoxSaidaVeiculosDescarregamentoCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxSaidaVeiculosDescarregamentoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosDescarregamentoCancelar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosDescarregamentoCancelar"))
        self.cheBoxSaidaVeiculosDescarregamentoDeletar = QtGui.QCheckBox(self.grbSaidaVeiculosDescarregamento)
        self.cheBoxSaidaVeiculosDescarregamentoDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxSaidaVeiculosDescarregamentoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosDescarregamentoDeletar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosDescarregamentoDeletar"))
        self.cheBoxSaidaVeiculosDescarregamentoAtivar = QtGui.QCheckBox(self.grbSaidaVeiculosDescarregamento)
        self.cheBoxSaidaVeiculosDescarregamentoAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxSaidaVeiculosDescarregamentoAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosDescarregamentoAtivar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosDescarregamentoAtivar"))
        self.grbEntradaVeiculosDescarregamento = QtGui.QGroupBox(self.pg1)
        self.grbEntradaVeiculosDescarregamento.setGeometry(QtCore.QRect(230, 160, 101, 131))
        self.grbEntradaVeiculosDescarregamento.setObjectName(_fromUtf8("grbEntradaVeiculosDescarregamento"))
        self.cheBoxEntradaVeiculosDescarregamentoCadastro = QtGui.QCheckBox(self.grbEntradaVeiculosDescarregamento)
        self.cheBoxEntradaVeiculosDescarregamentoCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxEntradaVeiculosDescarregamentoCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosDescarregamentoCadastro.setObjectName(_fromUtf8("cheBoxEntradaVeiculosDescarregamentoCadastro"))
        self.cheBoxEntradaVeiculosDescarregamentoEditar = QtGui.QCheckBox(self.grbEntradaVeiculosDescarregamento)
        self.cheBoxEntradaVeiculosDescarregamentoEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxEntradaVeiculosDescarregamentoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosDescarregamentoEditar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosDescarregamentoEditar"))
        self.cheBoxEntradaVeiculosDescarregamentoCancelar = QtGui.QCheckBox(self.grbEntradaVeiculosDescarregamento)
        self.cheBoxEntradaVeiculosDescarregamentoCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxEntradaVeiculosDescarregamentoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosDescarregamentoCancelar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosDescarregamentoCancelar"))
        self.cheBoxEntradaVeiculosDescarregamentoDeletar = QtGui.QCheckBox(self.grbEntradaVeiculosDescarregamento)
        self.cheBoxEntradaVeiculosDescarregamentoDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxEntradaVeiculosDescarregamentoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosDescarregamentoDeletar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosDescarregamentoDeletar"))
        self.cheBoxEntradaVeiculosDescarregamentoAtivar = QtGui.QCheckBox(self.grbEntradaVeiculosDescarregamento)
        self.cheBoxEntradaVeiculosDescarregamentoAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxEntradaVeiculosDescarregamentoAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntradaVeiculosDescarregamentoAtivar.setObjectName(_fromUtf8("cheBoxEntradaVeiculosDescarregamentoAtivar"))
        self.grbNotaFiscal = QtGui.QGroupBox(self.pg1)
        self.grbNotaFiscal.setGeometry(QtCore.QRect(120, 160, 101, 131))
        self.grbNotaFiscal.setObjectName(_fromUtf8("grbNotaFiscal"))
        self.cBoxNotaFiscalCadastro = QtGui.QCheckBox(self.grbNotaFiscal)
        self.cBoxNotaFiscalCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxNotaFiscalCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxNotaFiscalCadastro.setObjectName(_fromUtf8("cBoxNotaFiscalCadastro"))
        self.cBoxNotaFiscalEditar = QtGui.QCheckBox(self.grbNotaFiscal)
        self.cBoxNotaFiscalEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxNotaFiscalEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxNotaFiscalEditar.setObjectName(_fromUtf8("cBoxNotaFiscalEditar"))
        self.cBoxNotaFiscalCancelar = QtGui.QCheckBox(self.grbNotaFiscal)
        self.cBoxNotaFiscalCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxNotaFiscalCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxNotaFiscalCancelar.setObjectName(_fromUtf8("cBoxNotaFiscalCancelar"))
        self.cBoxNotaFiscalDeletar = QtGui.QCheckBox(self.grbNotaFiscal)
        self.cBoxNotaFiscalDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxNotaFiscalDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxNotaFiscalDeletar.setObjectName(_fromUtf8("cBoxNotaFiscalDeletar"))
        self.cBoxNotaFiscalAtivar = QtGui.QCheckBox(self.grbNotaFiscal)
        self.cBoxNotaFiscalAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxNotaFiscalAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxNotaFiscalAtivar.setObjectName(_fromUtf8("cBoxNotaFiscalAtivar"))
        self.grbMotorista = QtGui.QGroupBox(self.pg1)
        self.grbMotorista.setGeometry(QtCore.QRect(670, 20, 101, 131))
        self.grbMotorista.setObjectName(_fromUtf8("grbMotorista"))
        self.cBoxMotoristaCadastro = QtGui.QCheckBox(self.grbMotorista)
        self.cBoxMotoristaCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxMotoristaCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxMotoristaCadastro.setObjectName(_fromUtf8("cBoxMotoristaCadastro"))
        self.cBoxMotoristaEditar = QtGui.QCheckBox(self.grbMotorista)
        self.cBoxMotoristaEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxMotoristaEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxMotoristaEditar.setObjectName(_fromUtf8("cBoxMotoristaEditar"))
        self.cBoxMotoristaCancelar = QtGui.QCheckBox(self.grbMotorista)
        self.cBoxMotoristaCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxMotoristaCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxMotoristaCancelar.setObjectName(_fromUtf8("cBoxMotoristaCancelar"))
        self.cBoxMotoristaDeletar = QtGui.QCheckBox(self.grbMotorista)
        self.cBoxMotoristaDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxMotoristaDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxMotoristaDeletar.setObjectName(_fromUtf8("cBoxMotoristaDeletar"))
        self.cBoxMotoristaAtivar = QtGui.QCheckBox(self.grbMotorista)
        self.cBoxMotoristaAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxMotoristaAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxMotoristaAtivar.setObjectName(_fromUtf8("cBoxMotoristaAtivar"))
        self.grbFuncionario = QtGui.QGroupBox(self.pg1)
        self.grbFuncionario.setGeometry(QtCore.QRect(340, 20, 101, 131))
        self.grbFuncionario.setObjectName(_fromUtf8("grbFuncionario"))
        self.cBoxFuncionarioCadastrar = QtGui.QCheckBox(self.grbFuncionario)
        self.cBoxFuncionarioCadastrar.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cBoxFuncionarioCadastrar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFuncionarioCadastrar.setObjectName(_fromUtf8("cBoxFuncionarioCadastrar"))
        self.cBoxFuncionarioEditar = QtGui.QCheckBox(self.grbFuncionario)
        self.cBoxFuncionarioEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cBoxFuncionarioEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFuncionarioEditar.setObjectName(_fromUtf8("cBoxFuncionarioEditar"))
        self.cBoxFuncionarioCancelar = QtGui.QCheckBox(self.grbFuncionario)
        self.cBoxFuncionarioCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cBoxFuncionarioCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFuncionarioCancelar.setObjectName(_fromUtf8("cBoxFuncionarioCancelar"))
        self.cBoxFuncionarioDeletar = QtGui.QCheckBox(self.grbFuncionario)
        self.cBoxFuncionarioDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cBoxFuncionarioDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFuncionarioDeletar.setObjectName(_fromUtf8("cBoxFuncionarioDeletar"))
        self.cBoxFuncionarioAtivar = QtGui.QCheckBox(self.grbFuncionario)
        self.cBoxFuncionarioAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxFuncionarioAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxFuncionarioAtivar.setObjectName(_fromUtf8("cBoxFuncionarioAtivar"))
        self.btnAvacarPg1 = QtGui.QPushButton(self.pg1)
        self.btnAvacarPg1.setGeometry(QtCore.QRect(760, 0, 21, 16))
        self.btnAvacarPg1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAvacarPg1.setAutoDefault(False)
        self.btnAvacarPg1.setDefault(False)
        self.btnAvacarPg1.setFlat(True)
        self.btnAvacarPg1.setObjectName(_fromUtf8("btnAvacarPg1"))
        self.btnVoltarPg1 = QtGui.QPushButton(self.pg1)
        self.btnVoltarPg1.setGeometry(QtCore.QRect(0, 0, 21, 16))
        self.btnVoltarPg1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnVoltarPg1.setAutoDefault(False)
        self.btnVoltarPg1.setDefault(False)
        self.btnVoltarPg1.setFlat(True)
        self.btnVoltarPg1.setObjectName(_fromUtf8("btnVoltarPg1"))
        self.grbSaidaVeiculosCarregamento = QtGui.QGroupBox(self.pg1)
        self.grbSaidaVeiculosCarregamento.setGeometry(QtCore.QRect(560, 160, 101, 131))
        self.grbSaidaVeiculosCarregamento.setObjectName(_fromUtf8("grbSaidaVeiculosCarregamento"))
        self.cheBoxSaidaVeiculosCarregamentoCadastro = QtGui.QCheckBox(self.grbSaidaVeiculosCarregamento)
        self.cheBoxSaidaVeiculosCarregamentoCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxSaidaVeiculosCarregamentoCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosCarregamentoCadastro.setObjectName(_fromUtf8("cheBoxSaidaVeiculosCarregamentoCadastro"))
        self.cheBoxSaidaVeiculosCarregamentoEditar = QtGui.QCheckBox(self.grbSaidaVeiculosCarregamento)
        self.cheBoxSaidaVeiculosCarregamentoEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxSaidaVeiculosCarregamentoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosCarregamentoEditar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosCarregamentoEditar"))
        self.cheBoxSaidaVeiculosCarregamentoCancelar = QtGui.QCheckBox(self.grbSaidaVeiculosCarregamento)
        self.cheBoxSaidaVeiculosCarregamentoCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxSaidaVeiculosCarregamentoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosCarregamentoCancelar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosCarregamentoCancelar"))
        self.cheBoxSaidaVeiculosCarregamentoDeletar = QtGui.QCheckBox(self.grbSaidaVeiculosCarregamento)
        self.cheBoxSaidaVeiculosCarregamentoDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxSaidaVeiculosCarregamentoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosCarregamentoDeletar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosCarregamentoDeletar"))
        self.cheBoxSaidaVeiculosCarregamentoAtivar = QtGui.QCheckBox(self.grbSaidaVeiculosCarregamento)
        self.cheBoxSaidaVeiculosCarregamentoAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxSaidaVeiculosCarregamentoAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaVeiculosCarregamentoAtivar.setObjectName(_fromUtf8("cheBoxSaidaVeiculosCarregamentoAtivar"))
        self.grbEntrdaFuncionario = QtGui.QGroupBox(self.pg1)
        self.grbEntrdaFuncionario.setGeometry(QtCore.QRect(670, 160, 101, 131))
        self.grbEntrdaFuncionario.setObjectName(_fromUtf8("grbEntrdaFuncionario"))
        self.cheBoxEntrdaFuncionarioCadastro = QtGui.QCheckBox(self.grbEntrdaFuncionario)
        self.cheBoxEntrdaFuncionarioCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxEntrdaFuncionarioCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaFuncionarioCadastro.setObjectName(_fromUtf8("cheBoxEntrdaFuncionarioCadastro"))
        self.cheBoxEntrdaFuncionarioEditar = QtGui.QCheckBox(self.grbEntrdaFuncionario)
        self.cheBoxEntrdaFuncionarioEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxEntrdaFuncionarioEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaFuncionarioEditar.setObjectName(_fromUtf8("cheBoxEntrdaFuncionarioEditar"))
        self.cheBoxEntrdaFuncionarioCancelar = QtGui.QCheckBox(self.grbEntrdaFuncionario)
        self.cheBoxEntrdaFuncionarioCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxEntrdaFuncionarioCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaFuncionarioCancelar.setObjectName(_fromUtf8("cheBoxEntrdaFuncionarioCancelar"))
        self.cheBoxEntrdaFuncionarioDeletar = QtGui.QCheckBox(self.grbEntrdaFuncionario)
        self.cheBoxEntrdaFuncionarioDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxEntrdaFuncionarioDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaFuncionarioDeletar.setObjectName(_fromUtf8("cheBoxEntrdaFuncionarioDeletar"))
        self.cheBoxEntrdaFuncionarioAtivar = QtGui.QCheckBox(self.grbEntrdaFuncionario)
        self.cheBoxEntrdaFuncionarioAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxEntrdaFuncionarioAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaFuncionarioAtivar.setObjectName(_fromUtf8("cheBoxEntrdaFuncionarioAtivar"))
        self.stackedWidget.addWidget(self.pg1)
        self.pg2 = QtGui.QWidget()
        self.pg2.setObjectName(_fromUtf8("pg2"))
        self.grbSaidaFuncionario = QtGui.QGroupBox(self.pg2)
        self.grbSaidaFuncionario.setGeometry(QtCore.QRect(10, 20, 101, 131))
        self.grbSaidaFuncionario.setObjectName(_fromUtf8("grbSaidaFuncionario"))
        self.cheBoxSaidaFuncionarioCadastro = QtGui.QCheckBox(self.grbSaidaFuncionario)
        self.cheBoxSaidaFuncionarioCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxSaidaFuncionarioCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaFuncionarioCadastro.setObjectName(_fromUtf8("cheBoxSaidaFuncionarioCadastro"))
        self.cheBoxSaidaFuncionarioEditar = QtGui.QCheckBox(self.grbSaidaFuncionario)
        self.cheBoxSaidaFuncionarioEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxSaidaFuncionarioEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaFuncionarioEditar.setObjectName(_fromUtf8("cheBoxSaidaFuncionarioEditar"))
        self.cheBoxSaidaFuncionarioCancelar = QtGui.QCheckBox(self.grbSaidaFuncionario)
        self.cheBoxSaidaFuncionarioCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxSaidaFuncionarioCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaFuncionarioCancelar.setObjectName(_fromUtf8("cheBoxSaidaFuncionarioCancelar"))
        self.cheBoxSaidaFuncionarioDeletar = QtGui.QCheckBox(self.grbSaidaFuncionario)
        self.cheBoxSaidaFuncionarioDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxSaidaFuncionarioDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaFuncionarioDeletar.setObjectName(_fromUtf8("cheBoxSaidaFuncionarioDeletar"))
        self.cheBoxSaidaFuncionarioAtivar = QtGui.QCheckBox(self.grbSaidaFuncionario)
        self.cheBoxSaidaFuncionarioAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxSaidaFuncionarioAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaFuncionarioAtivar.setObjectName(_fromUtf8("cheBoxSaidaFuncionarioAtivar"))
        self.grbRelatorio = QtGui.QGroupBox(self.pg2)
        self.grbRelatorio.setGeometry(QtCore.QRect(340, 20, 101, 131))
        self.grbRelatorio.setObjectName(_fromUtf8("grbRelatorio"))
        self.cBoxRelatorioGerarCsv = QtGui.QCheckBox(self.grbRelatorio)
        self.cBoxRelatorioGerarCsv.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.cBoxRelatorioGerarCsv.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxRelatorioGerarCsv.setObjectName(_fromUtf8("cBoxRelatorioGerarCsv"))
        self.cBoxRelatorioGerarHtml = QtGui.QCheckBox(self.grbRelatorio)
        self.cBoxRelatorioGerarHtml.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.cBoxRelatorioGerarHtml.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxRelatorioGerarHtml.setObjectName(_fromUtf8("cBoxRelatorioGerarHtml"))
        self.cBoxRelatorioAtivar = QtGui.QCheckBox(self.grbRelatorio)
        self.cBoxRelatorioAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cBoxRelatorioAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cBoxRelatorioAtivar.setObjectName(_fromUtf8("cBoxRelatorioAtivar"))
        self.grbEntrdaMaquina = QtGui.QGroupBox(self.pg2)
        self.grbEntrdaMaquina.setGeometry(QtCore.QRect(120, 20, 101, 131))
        self.grbEntrdaMaquina.setObjectName(_fromUtf8("grbEntrdaMaquina"))
        self.cheBoxEntrdaMaquinaCadastro = QtGui.QCheckBox(self.grbEntrdaMaquina)
        self.cheBoxEntrdaMaquinaCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxEntrdaMaquinaCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaMaquinaCadastro.setObjectName(_fromUtf8("cheBoxEntrdaMaquinaCadastro"))
        self.cheBoxEntrdaMaquinaEditar = QtGui.QCheckBox(self.grbEntrdaMaquina)
        self.cheBoxEntrdaMaquinaEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxEntrdaMaquinaEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaMaquinaEditar.setObjectName(_fromUtf8("cheBoxEntrdaMaquinaEditar"))
        self.cheBoxEntrdaMaquinaCancelar = QtGui.QCheckBox(self.grbEntrdaMaquina)
        self.cheBoxEntrdaMaquinaCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxEntrdaMaquinaCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaMaquinaCancelar.setObjectName(_fromUtf8("cheBoxEntrdaMaquinaCancelar"))
        self.cheBoxEntrdaMaquinaDeletar = QtGui.QCheckBox(self.grbEntrdaMaquina)
        self.cheBoxEntrdaMaquinaDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxEntrdaMaquinaDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaMaquinaDeletar.setObjectName(_fromUtf8("cheBoxEntrdaMaquinaDeletar"))
        self.cheBoxEntrdaMaquinaAtivar = QtGui.QCheckBox(self.grbEntrdaMaquina)
        self.cheBoxEntrdaMaquinaAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxEntrdaMaquinaAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxEntrdaMaquinaAtivar.setObjectName(_fromUtf8("cheBoxEntrdaMaquinaAtivar"))
        self.grbSaidaMaquina = QtGui.QGroupBox(self.pg2)
        self.grbSaidaMaquina.setGeometry(QtCore.QRect(230, 20, 101, 131))
        self.grbSaidaMaquina.setObjectName(_fromUtf8("grbSaidaMaquina"))
        self.cheBoxSaidaMaquinaCadastro = QtGui.QCheckBox(self.grbSaidaMaquina)
        self.cheBoxSaidaMaquinaCadastro.setGeometry(QtCore.QRect(10, 40, 81, 23))
        self.cheBoxSaidaMaquinaCadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaMaquinaCadastro.setObjectName(_fromUtf8("cheBoxSaidaMaquinaCadastro"))
        self.cheBoxSaidaMaquinaEditar = QtGui.QCheckBox(self.grbSaidaMaquina)
        self.cheBoxSaidaMaquinaEditar.setGeometry(QtCore.QRect(10, 60, 61, 23))
        self.cheBoxSaidaMaquinaEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaMaquinaEditar.setObjectName(_fromUtf8("cheBoxSaidaMaquinaEditar"))
        self.cheBoxSaidaMaquinaCancelar = QtGui.QCheckBox(self.grbSaidaMaquina)
        self.cheBoxSaidaMaquinaCancelar.setGeometry(QtCore.QRect(10, 80, 74, 23))
        self.cheBoxSaidaMaquinaCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaMaquinaCancelar.setObjectName(_fromUtf8("cheBoxSaidaMaquinaCancelar"))
        self.cheBoxSaidaMaquinaDeletar = QtGui.QCheckBox(self.grbSaidaMaquina)
        self.cheBoxSaidaMaquinaDeletar.setGeometry(QtCore.QRect(10, 100, 71, 23))
        self.cheBoxSaidaMaquinaDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaMaquinaDeletar.setObjectName(_fromUtf8("cheBoxSaidaMaquinaDeletar"))
        self.cheBoxSaidaMaquinaAtivar = QtGui.QCheckBox(self.grbSaidaMaquina)
        self.cheBoxSaidaMaquinaAtivar.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.cheBoxSaidaMaquinaAtivar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheBoxSaidaMaquinaAtivar.setObjectName(_fromUtf8("cheBoxSaidaMaquinaAtivar"))
        self.btnVoltarPg2 = QtGui.QPushButton(self.pg2)
        self.btnVoltarPg2.setGeometry(QtCore.QRect(0, 0, 21, 16))
        self.btnVoltarPg2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnVoltarPg2.setAutoDefault(False)
        self.btnVoltarPg2.setFlat(True)
        self.btnVoltarPg2.setObjectName(_fromUtf8("btnVoltarPg2"))
        self.btnAvacarPg2 = QtGui.QPushButton(self.pg2)
        self.btnAvacarPg2.setGeometry(QtCore.QRect(760, 0, 21, 16))
        self.btnAvacarPg2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAvacarPg2.setAutoDefault(False)
        self.btnAvacarPg2.setDefault(False)
        self.btnAvacarPg2.setFlat(True)
        self.btnAvacarPg2.setObjectName(_fromUtf8("btnAvacarPg2"))
        self.stackedWidget.addWidget(self.pg2)
        self.tabwCadPermUsuario.addTab(self.permiUsuarios, _fromUtf8(""))
        self.grbBotoes = QtGui.QGroupBox(frmCadastroUsuarios)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 500, 802, 51))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(300, 12, 88, 27))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(400, 12, 88, 27))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon1)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(600, 12, 88, 27))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon2)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(700, 10, 88, 27))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/critical.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeletar.setIcon(icon3)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(500, 12, 88, 27))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/Save-as_37111.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon4)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        self.lblPesquisar = QtGui.QLabel(self.grbBotoes)
        self.lblPesquisar.setGeometry(QtCore.QRect(10, 20, 111, 19))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblPesquisar.setPalette(palette)
        self.lblPesquisar.setObjectName(_fromUtf8("lblPesquisar"))
        self.grbFuncionarioPesquisa = QtGui.QGroupBox(frmCadastroUsuarios)
        self.grbFuncionarioPesquisa.setEnabled(False)
        self.grbFuncionarioPesquisa.setGeometry(QtCore.QRect(10, 0, 801, 121))
        self.grbFuncionarioPesquisa.setObjectName(_fromUtf8("grbFuncionarioPesquisa"))
        self.txtCargo = QtGui.QLineEdit(self.grbFuncionarioPesquisa)
        self.txtCargo.setEnabled(False)
        self.txtCargo.setGeometry(QtCore.QRect(352, 86, 331, 25))
        self.txtCargo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCargo.setMaxLength(70)
        self.txtCargo.setObjectName(_fromUtf8("txtCargo"))
        self.lblNomeFuncionario = QtGui.QLabel(self.grbFuncionarioPesquisa)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(182, 20, 121, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))
        self.lblSetor = QtGui.QLabel(self.grbFuncionarioPesquisa)
        self.lblSetor.setGeometry(QtCore.QRect(12, 66, 121, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        self.lblCargo = QtGui.QLabel(self.grbFuncionarioPesquisa)
        self.lblCargo.setGeometry(QtCore.QRect(352, 66, 121, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))
        self.txtSetor = QtGui.QLineEdit(self.grbFuncionarioPesquisa)
        self.txtSetor.setEnabled(False)
        self.txtSetor.setGeometry(QtCore.QRect(12, 86, 331, 25))
        self.txtSetor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtSetor.setMaxLength(70)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbFuncionarioPesquisa)
        self.txtNomeFuncionario.setEnabled(False)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(182, 40, 608, 25))
        self.txtNomeFuncionario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbFuncionarioPesquisa)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 40, 161, 25))
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoFuncionario = QtGui.QLabel(self.grbFuncionarioPesquisa)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))
        self.btnPesquisarEmpresa = QtGui.QPushButton(self.grbFuncionarioPesquisa)
        self.btnPesquisarEmpresa.setGeometry(QtCore.QRect(161, 56, 16, 16))
        self.btnPesquisarEmpresa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarEmpresa.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search_mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarEmpresa.setIcon(icon5)
        self.btnPesquisarEmpresa.setFlat(True)
        self.btnPesquisarEmpresa.setObjectName(_fromUtf8("btnPesquisarEmpresa"))
        self.lblSenhaFuncionario.setBuddy(self.txtSenhaFuncionario)
        self.lblLoginFuncionario.setBuddy(self.txtLoginFuncionario)
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblSetor.setBuddy(self.txtSetor)
        self.lblCargo.setBuddy(self.txtCargo)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)

        self.retranslateUi(frmCadastroUsuarios)
        self.tabwCadPermUsuario.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroUsuarios)
        frmCadastroUsuarios.setTabOrder(self.tabwCadPermUsuario, self.txtLoginFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtLoginFuncionario, self.txtSenhaFuncionario)
        frmCadastroUsuarios.setTabOrder(self.txtSenhaFuncionario, self.btnVoltarPg1)
        frmCadastroUsuarios.setTabOrder(self.btnVoltarPg1, self.btnAvacarPg1)
        frmCadastroUsuarios.setTabOrder(self.btnAvacarPg1, self.btnVoltarPg2)
        frmCadastroUsuarios.setTabOrder(self.btnVoltarPg2, self.btnAvacarPg2)

    def retranslateUi(self, frmCadastroUsuarios):
        frmCadastroUsuarios.setWindowTitle(_translate("frmCadastroUsuarios", "Cadastro de Usuarios", None))
        self.lblSenhaFuncionario.setText(_translate("frmCadastroUsuarios", "Senha", None))
        self.lblLoginFuncionario.setText(_translate("frmCadastroUsuarios", "Login", None))
        self.txtSenhaFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Senha", None))
        self.txtSenhaFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo de senha para autenticar o usuario", None))
        self.txtLoginFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Login", None))
        self.txtLoginFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo de login para autenticar o usuario", None))
        self.tabwCadPermUsuario.setTabText(self.tabwCadPermUsuario.indexOf(self.cadUsuario), _translate("frmCadastroUsuarios", "Cadastro de Usuario", None))
        self.grbPessoaFisica.setTitle(_translate("frmCadastroUsuarios", "Pes. Fisico", None))
        self.cBoxPessoaFisicaCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxPessoaFisicaEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxPessoaFisicaCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxPessoaFisicaDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxPessoaFisica.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbFornecedor.setTitle(_translate("frmCadastroUsuarios", "Fornecedor", None))
        self.cBoxFornecedorCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxFornecedorEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxFornecedorCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxFornecedorDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxFornecedorAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbPessoaJuridica.setTitle(_translate("frmCadastroUsuarios", "Pes. Juridico", None))
        self.cBoxPessoaJuridicaCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxPessoaJuridicaEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxPessoaJuridicaCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxPessoaJuridicaDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxPessoaJuridicaAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbCliente.setTitle(_translate("frmCadastroUsuarios", "Cliente", None))
        self.cBoxClienteCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxClienteEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxClienteCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxClienteDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxClienteAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbEmpresa.setTitle(_translate("frmCadastroUsuarios", "Empresa", None))
        self.cBoxEmpresaCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxEmpresaEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxEmpresaCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxEmpresaDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxEmpresaAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbEntradaVeiculosCarregamento.setTitle(_translate("frmCadastroUsuarios", "Ent. Vei. Carr", None))
        self.cheBoxEntradaVeiculosCarregamentoCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxEntradaVeiculosCarregamentoEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxEntradaVeiculosCarregamentoCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxEntradaVeiculosCarregamentoDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxEntradaVeiculosCarregamentoAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbUsuariosPermissao.setTitle(_translate("frmCadastroUsuarios", "Usua. Perm.", None))
        self.cBoxUsuPermCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxUsuPermEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxUsuPermCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxUsuPermDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxUsuPermAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbSaidaVeiculosDescarregamento.setTitle(_translate("frmCadastroUsuarios", "Sai. Vei. Des.", None))
        self.cheBoxSaidaVeiculosDescarregamentoCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxSaidaVeiculosDescarregamentoEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxSaidaVeiculosDescarregamentoCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxSaidaVeiculosDescarregamentoDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxSaidaVeiculosDescarregamentoAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbEntradaVeiculosDescarregamento.setTitle(_translate("frmCadastroUsuarios", "Ent. Vei. Des.", None))
        self.cheBoxEntradaVeiculosDescarregamentoCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxEntradaVeiculosDescarregamentoEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxEntradaVeiculosDescarregamentoCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxEntradaVeiculosDescarregamentoDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxEntradaVeiculosDescarregamentoAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbNotaFiscal.setTitle(_translate("frmCadastroUsuarios", "Notas Fiscal", None))
        self.cBoxNotaFiscalCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxNotaFiscalEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxNotaFiscalCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxNotaFiscalDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxNotaFiscalAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbMotorista.setTitle(_translate("frmCadastroUsuarios", "Motorista", None))
        self.cBoxMotoristaCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxMotoristaEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxMotoristaCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxMotoristaDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxMotoristaAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbFuncionario.setTitle(_translate("frmCadastroUsuarios", "Funcionario", None))
        self.cBoxFuncionarioCadastrar.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cBoxFuncionarioEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cBoxFuncionarioCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cBoxFuncionarioDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cBoxFuncionarioAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.btnAvacarPg1.setText(_translate("frmCadastroUsuarios", ">", None))
        self.btnVoltarPg1.setText(_translate("frmCadastroUsuarios", "<", None))
        self.grbSaidaVeiculosCarregamento.setTitle(_translate("frmCadastroUsuarios", "Sai. Vei. Carr", None))
        self.cheBoxSaidaVeiculosCarregamentoCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxSaidaVeiculosCarregamentoEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxSaidaVeiculosCarregamentoCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxSaidaVeiculosCarregamentoDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxSaidaVeiculosCarregamentoAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbEntrdaFuncionario.setTitle(_translate("frmCadastroUsuarios", "Entr. Funcio.", None))
        self.cheBoxEntrdaFuncionarioCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxEntrdaFuncionarioEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxEntrdaFuncionarioCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxEntrdaFuncionarioDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxEntrdaFuncionarioAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbSaidaFuncionario.setTitle(_translate("frmCadastroUsuarios", "Said. Funcio.", None))
        self.cheBoxSaidaFuncionarioCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxSaidaFuncionarioEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxSaidaFuncionarioCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxSaidaFuncionarioDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxSaidaFuncionarioAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbRelatorio.setTitle(_translate("frmCadastroUsuarios", "Relatório", None))
        self.cBoxRelatorioGerarCsv.setText(_translate("frmCadastroUsuarios", "Ge. CSV", None))
        self.cBoxRelatorioGerarHtml.setText(_translate("frmCadastroUsuarios", "Ge. HTML", None))
        self.cBoxRelatorioAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbEntrdaMaquina.setTitle(_translate("frmCadastroUsuarios", "Entr. Maqui.", None))
        self.cheBoxEntrdaMaquinaCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxEntrdaMaquinaEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxEntrdaMaquinaCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxEntrdaMaquinaDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxEntrdaMaquinaAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.grbSaidaMaquina.setTitle(_translate("frmCadastroUsuarios", "Said. Maqui.", None))
        self.cheBoxSaidaMaquinaCadastro.setText(_translate("frmCadastroUsuarios", "Cadastrar", None))
        self.cheBoxSaidaMaquinaEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.cheBoxSaidaMaquinaCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.cheBoxSaidaMaquinaDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.cheBoxSaidaMaquinaAtivar.setText(_translate("frmCadastroUsuarios", "Ativar", None))
        self.btnVoltarPg2.setText(_translate("frmCadastroUsuarios", "<", None))
        self.btnAvacarPg2.setText(_translate("frmCadastroUsuarios", ">", None))
        self.tabwCadPermUsuario.setTabText(self.tabwCadPermUsuario.indexOf(self.permiUsuarios), _translate("frmCadastroUsuarios", "Permissões de Usuario", None))
        self.btnNovo.setToolTip(_translate("frmCadastroUsuarios", "Novo", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroUsuarios", "<html><head/><body><p>Botão para cadastrar uma novo registro da pessoa jurídica</p></body></html>", None))
        self.btnNovo.setText(_translate("frmCadastroUsuarios", "Novo", None))
        self.btnSalvar.setToolTip(_translate("frmCadastroUsuarios", "Salvar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroUsuarios", "<html><head/><body><p>Botão para salvar um novo registro da pessoa jurídica</p></body></html>", None))
        self.btnSalvar.setText(_translate("frmCadastroUsuarios", "Salvar", None))
        self.btnCancelar.setToolTip(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroUsuarios", "Botão para cancelar a operação ", None))
        self.btnCancelar.setText(_translate("frmCadastroUsuarios", "Cancelar", None))
        self.btnDeletar.setToolTip(_translate("frmCadastroUsuarios", "Deletar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroUsuarios", "<html><head/><body><p>Botão de deletar o registro da pessoa jurídica</p></body></html>", None))
        self.btnDeletar.setText(_translate("frmCadastroUsuarios", "Deletar", None))
        self.btnEditar.setToolTip(_translate("frmCadastroUsuarios", "Editar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroUsuarios", "<html><head/><body><p>Botão para salvar o registo editado da pessoa jurídica</p></body></html>", None))
        self.btnEditar.setText(_translate("frmCadastroUsuarios", "Editar", None))
        self.lblPesquisar.setText(_translate("frmCadastroUsuarios", "[F12] Pesquisar", None))
        self.grbFuncionarioPesquisa.setTitle(_translate("frmCadastroUsuarios", "Funcionario", None))
        self.txtCargo.setToolTip(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.txtCargo.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do nome do funcionario", None))
        self.lblNomeFuncionario.setText(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.lblSetor.setText(_translate("frmCadastroUsuarios", "Setor", None))
        self.lblCargo.setText(_translate("frmCadastroUsuarios", "Cargo", None))
        self.txtSetor.setToolTip(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.txtSetor.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do nome do funcionario", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do nome do funcionario", None))
        self.txtidFuncionario.setToolTip(_translate("frmCadastroUsuarios", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmCadastroUsuarios", "Campo do Codigo de identificação do Funcionario", None))
        self.lblCodigoFuncionario.setText(_translate("frmCadastroUsuarios", "Codigo Funcionario", None))
        self.btnPesquisarEmpresa.setWhatsThis(_translate("frmCadastroUsuarios", "Botão para pesquisar dados de empresa", None))

