# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadFuncionario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroFuncionario(object):
    def setupUi(self, frmCadastroFuncionario):
        frmCadastroFuncionario.setObjectName(_fromUtf8("frmCadastroFuncionario"))
        frmCadastroFuncionario.resize(890, 529)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroFuncionario.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/funcionario.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCadastroFuncionario.setWindowIcon(icon)
        frmCadastroFuncionario.setSizeGripEnabled(True)
        frmCadastroFuncionario.setModal(True)

        self.grbDadosPessoaJuridica = QtGui.QGroupBox(frmCadastroFuncionario)
        self.grbDadosPessoaJuridica.setEnabled(False)
        self.grbDadosPessoaJuridica.setGeometry(QtCore.QRect(10, 3, 871, 161))
        self.grbDadosPessoaJuridica.setObjectName(_fromUtf8("grbDadosPessoaJuridica"))

        self.txtCnpj = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtCnpj.setEnabled(False)
        self.txtCnpj.setGeometry(QtCore.QRect(142, 38, 182, 25))
        self.txtCnpj.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpj.setText(_fromUtf8("..-"))
        self.txtCnpj.setCursorPosition(0)
        self.txtCnpj.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpj.setObjectName(_fromUtf8("txtCnpj"))

        self.lblNome = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblNome.setGeometry(QtCore.QRect(10, 64, 81, 19))
        self.lblNome.setObjectName(_fromUtf8("lblNome"))

        self.lblCpf = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblCpf.setGeometry(QtCore.QRect(142, 18, 41, 19))
        self.lblCpf.setObjectName(_fromUtf8("lblCpf"))

        self.txtNome = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtNome.setEnabled(False)
        self.txtNome.setGeometry(QtCore.QRect(10, 84, 841, 25))
        self.txtNome.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNome.setMaxLength(70)
        self.txtNome.setObjectName(_fromUtf8("txtNome"))

        self.lblSobrenome = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblSobrenome.setGeometry(QtCore.QRect(8, 108, 101, 19))
        self.lblSobrenome.setObjectName(_fromUtf8("lblSobrenome"))

        self.txtInscricaoEstadua = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtInscricaoEstadua.setEnabled(False)
        self.txtInscricaoEstadua.setGeometry(QtCore.QRect(330, 38, 178, 25))
        self.txtInscricaoEstadua.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadua.setMaxLength(8)
        self.txtInscricaoEstadua.setObjectName(_fromUtf8("txtInscricaoEstadua"))

        self.txtSobrenome = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtSobrenome.setEnabled(False)
        self.txtSobrenome.setGeometry(QtCore.QRect(8, 128, 844, 25))
        self.txtSobrenome.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtSobrenome.setMaxLength(70)
        self.txtSobrenome.setObjectName(_fromUtf8("txtSobrenome"))

        self.lblRg = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblRg.setGeometry(QtCore.QRect(330, 18, 121, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))

        self.lblCodigo = QtGui.QLabel(self.grbDadosPessoaJuridica)
        self.lblCodigo.setGeometry(QtCore.QRect(10, 18, 71, 19))
        self.lblCodigo.setObjectName(_fromUtf8("lblCodigo"))

        self.txtCodigo = QtGui.QLineEdit(self.grbDadosPessoaJuridica)
        self.txtCodigo.setGeometry(QtCore.QRect(10, 38, 121, 25))
        self.txtCodigo.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCodigo.setMaxLength(8)
        self.txtCodigo.setObjectName(_fromUtf8("txtCodigo"))

        self.btnPesquisarPessoaFisica = QtGui.QPushButton(self.grbDadosPessoaJuridica)
        self.btnPesquisarPessoaFisica.setGeometry(QtCore.QRect(123, 50, 16, 16))
        self.btnPesquisarPessoaFisica.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarPessoaFisica.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search_mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarPessoaFisica.setIcon(icon)
        self.btnPesquisarPessoaFisica.setFlat(True)
        self.btnPesquisarPessoaFisica.setObjectName(_fromUtf8("btnPesquisarPessoaFisica"))

        self.tabWiAdicionais = QtGui.QTabWidget(frmCadastroFuncionario)
        self.tabWiAdicionais.setEnabled(False)
        self.tabWiAdicionais.setGeometry(QtCore.QRect(10, 180, 871, 281))
        self.tabWiAdicionais.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWiAdicionais.setDocumentMode(True)
        self.tabWiAdicionais.setObjectName(_fromUtf8("tabWiAdicionais"))

        self.geral = QtGui.QWidget()
        self.geral.setObjectName(_fromUtf8("geral"))

        self.txtObservacao = QtGui.QTextEdit(self.geral)
        self.txtObservacao.setGeometry(QtCore.QRect(10, 110, 851, 71))
        self.txtObservacao.setObjectName(_fromUtf8("txtObservacao"))

        self.lblObservacao = QtGui.QLabel(self.geral)
        self.lblObservacao.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.lblObservacao.setObjectName(_fromUtf8("lblObservacao"))

        self.lblEstadoCivil = QtGui.QLabel(self.geral)
        self.lblEstadoCivil.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.lblEstadoCivil.setObjectName(_fromUtf8("lblEstadoCivil"))

        self.cBoxEstadoCivil = QtGui.QComboBox(self.geral)
        self.cBoxEstadoCivil.setGeometry(QtCore.QRect(10, 40, 171, 25))
        self.cBoxEstadoCivil.setObjectName(_fromUtf8("cBoxEstadoCivil"))

        self.cBoxDeficiencia = QtGui.QComboBox(self.geral)
        self.cBoxDeficiencia.setGeometry(QtCore.QRect(190, 40, 281, 25))
        self.cBoxDeficiencia.setObjectName(_fromUtf8("cBoxDeficiencia"))

        self.lblDeficiencia = QtGui.QLabel(self.geral)
        self.lblDeficiencia.setGeometry(QtCore.QRect(190, 20, 81, 19))
        self.lblDeficiencia.setObjectName(_fromUtf8("lblDeficiencia"))

        self.grbAtivo = QtGui.QGroupBox(self.geral)
        self.grbAtivo.setEnabled(False)
        self.grbAtivo.setGeometry(QtCore.QRect(490, 20, 120, 61))
        self.grbAtivo.setObjectName(_fromUtf8("grbAtivo"))

        self.radBtnAtivo = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnAtivo.setGeometry(QtCore.QRect(20, 20, 61, 17))
        self.radBtnAtivo.setObjectName(_fromUtf8("radBtnAtivo"))

        self.radBtnDesativo = QtGui.QRadioButton(self.grbAtivo)
        self.radBtnDesativo.setGeometry(QtCore.QRect(20, 40, 81, 17))
        self.radBtnDesativo.setObjectName(_fromUtf8("radBtnDesativo"))

        self.tabWiAdicionais.addTab(self.geral, _fromUtf8(""))
        self.contatos = QtGui.QWidget()
        self.contatos.setObjectName(_fromUtf8("contatos"))

        self.tabContatoTelefone = QtGui.QTableWidget(self.contatos)
        self.tabContatoTelefone.setGeometry(QtCore.QRect(13, 84, 361, 141))
        self.tabContatoTelefone.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabContatoTelefone.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabContatoTelefone.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabContatoTelefone.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabContatoTelefone.setObjectName(_fromUtf8("tabContatoTelefone"))
        self.tabContatoTelefone.setColumnCount(2)
        self.tabContatoTelefone.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabContatoTelefone.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabContatoTelefone.setHorizontalHeaderItem(1, item)
        self.tabContatoTelefone.horizontalHeader().setStretchLastSection(True)
        self.tabContatoTelefone.verticalHeader().setVisible(False)

        self.btnRemoverTelefone = QtGui.QPushButton(self.contatos)
        self.btnRemoverTelefone.setGeometry(QtCore.QRect(343, 230, 31, 27))
        self.btnRemoverTelefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverTelefone.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoverTelefone.setIcon(icon1)
        self.btnRemoverTelefone.setObjectName(_fromUtf8("btnRemoverTelefone"))

        self.btnAddEmail = QtGui.QPushButton(self.contatos)
        self.btnAddEmail.setGeometry(QtCore.QRect(823, 39, 31, 27))
        self.btnAddEmail.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddEmail.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddEmail.setIcon(icon2)
        self.btnAddEmail.setObjectName(_fromUtf8("btnAddEmail"))

        self.lblContatoTelefone = QtGui.QLabel(self.contatos)
        self.lblContatoTelefone.setGeometry(QtCore.QRect(13, 27, 53, 13))
        self.lblContatoTelefone.setObjectName(_fromUtf8("lblContatoTelefone"))

        self.lblContatoEmail = QtGui.QLabel(self.contatos)
        self.lblContatoEmail.setGeometry(QtCore.QRect(493, 16, 53, 13))
        self.lblContatoEmail.setObjectName(_fromUtf8("lblContatoEmail"))

        self.btnAddTelefone = QtGui.QPushButton(self.contatos)
        self.btnAddTelefone.setGeometry(QtCore.QRect(343, 50, 31, 27))
        self.btnAddTelefone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddTelefone.setText(_fromUtf8(""))
        self.btnAddTelefone.setIcon(icon2)
        self.btnAddTelefone.setObjectName(_fromUtf8("btnAddTelefone"))

        self.txtNumeroTelefone = QtGui.QLineEdit(self.contatos)
        self.txtNumeroTelefone.setGeometry(QtCore.QRect(73, 51, 261, 25))
        self.txtNumeroTelefone.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtNumeroTelefone.setMaxLength(15)
        self.txtNumeroTelefone.setObjectName(_fromUtf8("txtNumeroTelefone"))

        self.txtEnderecoEmail = QtGui.QLineEdit(self.contatos)
        self.txtEnderecoEmail.setGeometry(QtCore.QRect(553, 40, 261, 25))
        self.txtEnderecoEmail.setMaxLength(50)
        self.txtEnderecoEmail.setObjectName(_fromUtf8("txtEnderecoEmail"))

        self.txtContatoEmail = QtGui.QLineEdit(self.contatos)
        self.txtContatoEmail.setGeometry(QtCore.QRect(553, 10, 261, 25))
        self.txtContatoEmail.setMaxLength(25)
        self.txtContatoEmail.setObjectName(_fromUtf8("txtContatoEmail"))

        self.tabContatoEmail = QtGui.QTableWidget(self.contatos)
        self.tabContatoEmail.setGeometry(QtCore.QRect(493, 73, 361, 151))
        self.tabContatoEmail.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabContatoEmail.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabContatoEmail.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabContatoEmail.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabContatoEmail.setObjectName(_fromUtf8("tabContatoEmail"))
        self.tabContatoEmail.setColumnCount(2)
        self.tabContatoEmail.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabContatoEmail.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabContatoEmail.setHorizontalHeaderItem(1, item)
        self.tabContatoEmail.horizontalHeader().setStretchLastSection(True)
        self.tabContatoEmail.verticalHeader().setVisible(False)

        self.txtContatoTelefone = QtGui.QLineEdit(self.contatos)
        self.txtContatoTelefone.setGeometry(QtCore.QRect(73, 21, 261, 25))
        self.txtContatoTelefone.setMaxLength(25)
        self.txtContatoTelefone.setObjectName(_fromUtf8("txtContatoTelefone"))

        self.lblEmail = QtGui.QLabel(self.contatos)
        self.lblEmail.setGeometry(QtCore.QRect(493, 44, 61, 16))
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))

        self.btnRemoverEmail = QtGui.QPushButton(self.contatos)
        self.btnRemoverEmail.setGeometry(QtCore.QRect(823, 230, 31, 27))
        self.btnRemoverEmail.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoverEmail.setText(_fromUtf8(""))
        self.btnRemoverEmail.setIcon(icon1)
        self.btnRemoverEmail.setObjectName(_fromUtf8("btnRemoverEmail"))

        self.lblTelefone = QtGui.QLabel(self.contatos)
        self.lblTelefone.setGeometry(QtCore.QRect(13, 55, 61, 16))
        self.lblTelefone.setObjectName(_fromUtf8("lblTelefone"))

        self.tabWiAdicionais.addTab(self.contatos, _fromUtf8(""))
        self.cadastroSetores = QtGui.QWidget()
        self.cadastroSetores.setObjectName(_fromUtf8("cadastroSetores"))

        self.lblDataAdmissao = QtGui.QLabel(self.cadastroSetores)
        self.lblDataAdmissao.setGeometry(QtCore.QRect(500, 76, 101, 16))
        self.lblDataAdmissao.setObjectName(_fromUtf8("lblDataAdmissao"))

        self.lblDataDemissao = QtGui.QLabel(self.cadastroSetores)
        self.lblDataDemissao.setGeometry(QtCore.QRect(640, 76, 101, 16))
        self.lblDataDemissao.setObjectName(_fromUtf8("lblDataDemissao"))

        self.lblCargo = QtGui.QLabel(self.cadastroSetores)
        self.lblCargo.setGeometry(QtCore.QRect(250, 76, 66, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))

        self.lblSetor = QtGui.QLabel(self.cadastroSetores)
        self.lblSetor.setGeometry(QtCore.QRect(10, 76, 66, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))

        self.txtDataDemissao = QtGui.QLineEdit(self.cadastroSetores)
        self.txtDataDemissao.setEnabled(False)
        self.txtDataDemissao.setGeometry(QtCore.QRect(640, 96, 121, 25))
        self.txtDataDemissao.setText(_fromUtf8("//"))
        self.txtDataDemissao.setObjectName(_fromUtf8("txtDataDemissao"))

        self.txtDataAdmissao = QtGui.QLineEdit(self.cadastroSetores)
        self.txtDataAdmissao.setGeometry(QtCore.QRect(500, 96, 121, 25))
        self.txtDataAdmissao.setText(_fromUtf8("//"))
        self.txtDataAdmissao.setObjectName(_fromUtf8("txtDataAdmissao"))

        self.cBoxSetor = QtGui.QComboBox(self.cadastroSetores)
        self.cBoxSetor.setGeometry(QtCore.QRect(10, 96, 231, 25))
        self.cBoxSetor.setObjectName(_fromUtf8("cBoxSetor"))

        self.cBoxCargo = QtGui.QComboBox(self.cadastroSetores)
        self.cBoxCargo.setGeometry(QtCore.QRect(250, 96, 231, 25))
        self.cBoxCargo.setObjectName(_fromUtf8("cBoxCargo"))

        self.lblCategoriaTrabalhador = QtGui.QLabel(self.cadastroSetores)
        self.lblCategoriaTrabalhador.setGeometry(QtCore.QRect(10, 26, 151, 19))
        self.lblCategoriaTrabalhador.setObjectName(_fromUtf8("lblCategoriaTrabalhador"))

        self.cBoxCateTrabalhador = QtGui.QComboBox(self.cadastroSetores)
        self.cBoxCateTrabalhador.setGeometry(QtCore.QRect(10, 46, 251, 25))
        self.cBoxCateTrabalhador.setObjectName(_fromUtf8("cBoxCateTrabalhador"))

        self.lblPis = QtGui.QLabel(self.cadastroSetores)
        self.lblPis.setGeometry(QtCore.QRect(610, 160, 75, 13))
        self.lblPis.setObjectName(_fromUtf8("lblPis"))

        self.txtPis = QtGui.QLineEdit(self.cadastroSetores)
        self.txtPis.setGeometry(QtCore.QRect(610, 174, 251, 25))
        self.txtPis.setMaxLength(25)
        self.txtPis.setObjectName(_fromUtf8("txtPis"))

        self.txtNumCarteira = QtGui.QLineEdit(self.cadastroSetores)
        self.txtNumCarteira.setGeometry(QtCore.QRect(10, 174, 231, 25))
        self.txtNumCarteira.setMaxLength(25)
        self.txtNumCarteira.setObjectName(_fromUtf8("txtNumCarteira"))

        self.lblNumCarteira = QtGui.QLabel(self.cadastroSetores)
        self.lblNumCarteira.setGeometry(QtCore.QRect(10, 160, 110, 13))
        self.lblNumCarteira.setObjectName(_fromUtf8("lblNumCarteira"))

        self.lblSerie = QtGui.QLabel(self.cadastroSetores)
        self.lblSerie.setGeometry(QtCore.QRect(250, 160, 40, 13))
        self.lblSerie.setObjectName(_fromUtf8("lblSerie"))

        self.txtSerie = QtGui.QLineEdit(self.cadastroSetores)
        self.txtSerie.setGeometry(QtCore.QRect(250, 174, 162, 25))
        self.txtSerie.setMaxLength(25)
        self.txtSerie.setObjectName(_fromUtf8("txtSerie"))


        self.lblUf = QtGui.QLabel(self.cadastroSetores)
        self.lblUf.setGeometry(QtCore.QRect(420, 160, 40, 13))
        self.lblUf.setObjectName(_fromUtf8("lblUf"))

        self.txtUf = QtGui.QLineEdit(self.cadastroSetores)
        self.txtUf.setGeometry(QtCore.QRect(420, 174, 51, 25))
        self.txtUf.setMaxLength(2)
        self.txtUf.setObjectName(_fromUtf8("txtUf"))

        self.lblDataEmissao = QtGui.QLabel(self.cadastroSetores)
        self.lblDataEmissao.setGeometry(QtCore.QRect(480, 157, 101, 16))
        self.lblDataEmissao.setObjectName(_fromUtf8("lblDataEmissao"))

        self.txtDataEmissao = QtGui.QLineEdit(self.cadastroSetores)
        self.txtDataEmissao.setGeometry(QtCore.QRect(480, 174, 121, 25))
        self.txtDataEmissao.setText(_fromUtf8("//"))
        self.txtDataEmissao.setObjectName(_fromUtf8("txtDataEmissao"))

        self.tabWiAdicionais.addTab(self.cadastroSetores, _fromUtf8(""))
        self.horario = QtGui.QWidget()
        self.horario.setObjectName(_fromUtf8("horario"))

        self.lblTabelaHorario = QtGui.QLabel(self.horario)
        self.lblTabelaHorario.setGeometry(QtCore.QRect(10, 20, 151, 19))
        self.lblTabelaHorario.setObjectName(_fromUtf8("lblTabelaHorario"))

        self.cBoxTabelaHorario = QtGui.QComboBox(self.horario)
        self.cBoxTabelaHorario.setGeometry(QtCore.QRect(10, 40, 301, 25))
        self.cBoxTabelaHorario.setObjectName(_fromUtf8("cBoxTabelaHorario"))

        self.tabHorario = QtGui.QTableWidget(self.horario)
        self.tabHorario.setGeometry(QtCore.QRect(150, 100, 551, 141))
        self.tabHorario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabHorario.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabHorario.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tabHorario.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabHorario.setObjectName(_fromUtf8("tabHorario"))
        self.tabHorario.setColumnCount(5)
        self.tabHorario.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHorario.setItem(6, 0, item)
        self.tabHorario.horizontalHeader().setStretchLastSection(True)
        self.tabHorario.verticalHeader().setVisible(False)
        item = QtGui.QTableWidgetItem()

        self.tabWiAdicionais.addTab(self.horario, _fromUtf8(""))
        self.grbBotoes = QtGui.QGroupBox(frmCadastroFuncionario)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 470, 871, 51))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(360, 12, 88, 27))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon3)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(460, 12, 88, 27))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon4)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(660, 12, 88, 27))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon5)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(760, 10, 88, 27))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/critical.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeletar.setIcon(icon6)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(560, 12, 88, 27))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/Save-as_37111.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon7)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.lblPesquisar = QtGui.QLabel(self.grbBotoes)
        self.lblPesquisar.setGeometry(QtCore.QRect(10, 20, 111, 19))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 116, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblPesquisar.setPalette(palette)
        self.lblPesquisar.setObjectName(_fromUtf8("lblPesquisar"))

        self.lblNome.setBuddy(self.txtNome)
        self.lblCpf.setBuddy(self.txtCnpj)
        self.lblSobrenome.setBuddy(self.txtSobrenome)
        self.lblRg.setBuddy(self.txtInscricaoEstadua)
        self.lblCodigo.setBuddy(self.txtCodigo)
        self.lblObservacao.setBuddy(self.txtObservacao)
        self.lblEstadoCivil.setBuddy(self.cBoxEstadoCivil)
        self.lblDeficiencia.setBuddy(self.cBoxDeficiencia)
        self.lblContatoTelefone.setBuddy(self.txtContatoTelefone)
        self.lblContatoEmail.setBuddy(self.txtContatoEmail)
        self.lblEmail.setBuddy(self.txtEnderecoEmail)
        self.lblTelefone.setBuddy(self.txtNumeroTelefone)
        self.lblDataAdmissao.setBuddy(self.txtDataAdmissao)
        self.lblDataDemissao.setBuddy(self.txtDataDemissao)
        self.lblCargo.setBuddy(self.cBoxCargo)
        self.lblSetor.setBuddy(self.cBoxSetor)
        self.lblCategoriaTrabalhador.setBuddy(self.cBoxCateTrabalhador)
        self.lblPis.setBuddy(self.txtPis)
        self.lblNumCarteira.setBuddy(self.txtNumCarteira)
        self.lblSerie.setBuddy(self.txtSerie)
        self.lblUf.setBuddy(self.txtUf)
        self.lblDataEmissao.setBuddy(self.txtDataEmissao)
        self.lblTabelaHorario.setBuddy(self.cBoxTabelaHorario)

        self.retranslateUi(frmCadastroFuncionario)
        self.tabWiAdicionais.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroFuncionario)
        frmCadastroFuncionario.setTabOrder(self.txtCodigo, self.txtCnpj)
        frmCadastroFuncionario.setTabOrder(self.txtCnpj, self.txtInscricaoEstadua)
        frmCadastroFuncionario.setTabOrder(self.txtInscricaoEstadua, self.txtNome)
        frmCadastroFuncionario.setTabOrder(self.txtNome, self.txtSobrenome)
        frmCadastroFuncionario.setTabOrder(self.txtSobrenome, self.tabWiAdicionais)
        frmCadastroFuncionario.setTabOrder(self.tabWiAdicionais, self.cBoxEstadoCivil)
        frmCadastroFuncionario.setTabOrder(self.cBoxEstadoCivil, self.cBoxDeficiencia)
        frmCadastroFuncionario.setTabOrder(self.cBoxDeficiencia, self.radBtnAtivo)
        frmCadastroFuncionario.setTabOrder(self.radBtnAtivo, self.radBtnDesativo)
        frmCadastroFuncionario.setTabOrder(self.radBtnDesativo, self.txtObservacao)
        frmCadastroFuncionario.setTabOrder(self.txtObservacao, self.txtContatoTelefone)
        frmCadastroFuncionario.setTabOrder(self.txtContatoTelefone, self.txtNumeroTelefone)
        frmCadastroFuncionario.setTabOrder(self.txtNumeroTelefone, self.txtContatoEmail)
        frmCadastroFuncionario.setTabOrder(self.txtContatoEmail, self.txtEnderecoEmail)
        frmCadastroFuncionario.setTabOrder(self.txtEnderecoEmail, self.cBoxCateTrabalhador)
        frmCadastroFuncionario.setTabOrder(self.cBoxCateTrabalhador, self.cBoxSetor)
        frmCadastroFuncionario.setTabOrder(self.cBoxSetor, self.cBoxCargo)
        frmCadastroFuncionario.setTabOrder(self.cBoxCargo, self.txtDataAdmissao)
        frmCadastroFuncionario.setTabOrder(self.txtDataAdmissao, self.txtDataDemissao)
        frmCadastroFuncionario.setTabOrder(self.txtDataDemissao, self.txtNumCarteira)
        frmCadastroFuncionario.setTabOrder(self.txtNumCarteira, self.txtSerie)
        frmCadastroFuncionario.setTabOrder(self.txtSerie, self.txtUf)
        frmCadastroFuncionario.setTabOrder(self.txtUf, self.txtDataEmissao)
        frmCadastroFuncionario.setTabOrder(self.txtDataEmissao, self.txtPis)
        frmCadastroFuncionario.setTabOrder(self.txtPis, self.cBoxTabelaHorario)


    def retranslateUi(self, frmCadastroFuncionario):
        frmCadastroFuncionario.setWindowTitle(_translate("frmCadastroFuncionario", "Cadastro Funcionário", None))
        self.grbDadosPessoaJuridica.setWhatsThis(_translate("frmCadastroFuncionario", "Grupo de Dados para cadastro e edição de empresas", None))
        self.grbDadosPessoaJuridica.setTitle(_translate("frmCadastroFuncionario", "Dados Pessoa Fisíca", None))
        self.txtCnpj.setToolTip(_translate("frmCadastroFuncionario", "CPF", None))
        self.txtCnpj.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do CPF", None))
        self.txtCnpj.setInputMask(_translate("frmCadastroFuncionario", "000.000.000-00; ", None))
        self.lblNome.setText(_translate("frmCadastroFuncionario", "Nome", None))
        self.lblCpf.setText(_translate("frmCadastroFuncionario", "CPF", None))
        self.txtNome.setToolTip(_translate("frmCadastroFuncionario", "Nome", None))
        self.txtNome.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da nome", None))
        self.lblSobrenome.setText(_translate("frmCadastroFuncionario", "Sobrenome", None))
        self.txtInscricaoEstadua.setToolTip(_translate("frmCadastroFuncionario", "RG", None))
        self.txtInscricaoEstadua.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do numero do RG", None))
        self.txtSobrenome.setToolTip(_translate("frmCadastroFuncionario", "Sobrenome", None))
        self.txtSobrenome.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do sobrenome", None))
        self.lblRg.setText(_translate("frmCadastroFuncionario", "RG", None))
        self.lblCodigo.setText(_translate("frmCadastroFuncionario", "Codigo", None))
        self.txtCodigo.setToolTip(_translate("frmCadastroFuncionario", "Codigo", None))
        self.txtCodigo.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do numero de identificação da pessoa fisíca</p></body></html>", None))
        self.btnPesquisarPessoaFisica.setWhatsThis(_translate("frmCadastroFuncionario", "Botão para pesquisar dados de empresa", None))
        self.tabWiAdicionais.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão adicionar um novo cargo a lista</p></body></html>", None))
        self.txtObservacao.setToolTip(_translate("frmCadastroFuncionario", "Observação", None))
        self.txtObservacao.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo de texto de observação sobre o funcionario</p></body></html>", None))
        self.lblObservacao.setText(_translate("frmCadastroFuncionario", "Observação", None))
        self.lblEstadoCivil.setText(_translate("frmCadastroFuncionario", "Estado Civil", None))
        self.cBoxEstadoCivil.setToolTip(_translate("frmCadastroFuncionario", "Estado Civil", None))
        self.cBoxEstadoCivil.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo de escolha doestado civil do funcionário</p></body></html>", None))
        self.cBoxDeficiencia.setToolTip(_translate("frmCadastroFuncionario", "Deficiência", None))
        self.cBoxDeficiencia.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo de escolha se o funcionário possui deficiência </p></body></html>", None))
        self.lblDeficiencia.setText(_translate("frmCadastroFuncionario", "Deficiência", None))
        self.grbAtivo.setTitle(_translate("frmCadastroFuncionario", "Situação", None))
        self.radBtnAtivo.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Item de seleção para funcionario ativa e operante</p></body></html>", None))
        self.radBtnAtivo.setText(_translate("frmCadastroFuncionario", "Ativo", None))
        self.radBtnDesativo.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Item de seleção para funcionario desativado e inoperante</p></body></html>", None))
        self.radBtnDesativo.setText(_translate("frmCadastroFuncionario", "Desativo", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.geral), _translate("frmCadastroFuncionario", "Geral", None))
        self.tabContatoTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Tabela de informações de contato de telefone</p></body></html>", None))
        item = self.tabContatoTelefone.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroFuncionario", "Contato", None))
        item = self.tabContatoTelefone.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroFuncionario", "Telefone", None))
        self.btnRemoverTelefone.setToolTip(_translate("frmCadastroFuncionario", "Remover", None))
        self.btnRemoverTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão remover um contato  de telefone a lista</p></body></html>", None))
        self.btnAddEmail.setToolTip(_translate("frmCadastroFuncionario", "Adicionar", None))
        self.btnAddEmail.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão adicionar um contato de e-mail a lista</p></body></html>", None))
        self.lblContatoTelefone.setText(_translate("frmCadastroFuncionario", "Contato", None))
        self.lblContatoEmail.setText(_translate("frmCadastroFuncionario", "Contato", None))
        self.btnAddTelefone.setToolTip(_translate("frmCadastroFuncionario", "Adicionar", None))
        self.btnAddTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão adicionar um contato de telefone a lista</p></body></html>", None))
        self.txtNumeroTelefone.setToolTip(_translate("frmCadastroFuncionario", "Telefone", None))
        self.txtNumeroTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do numero de telefone do contato</p></body></html>", None))
        self.txtEnderecoEmail.setToolTip(_translate("frmCadastroFuncionario", "E-mail", None))
        self.txtEnderecoEmail.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do endereço de e-mail do contato</p></body></html>", None))
        self.txtContatoEmail.setToolTip(_translate("frmCadastroFuncionario", "Contato", None))
        self.txtContatoEmail.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do nome do contato</p></body></html>", None))
        self.tabContatoEmail.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Tabela de informações de endereço de e-mail</p></body></html>", None))
        item = self.tabContatoEmail.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroFuncionario", "Contato", None))
        item = self.tabContatoEmail.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroFuncionario", "E-mail", None))
        self.txtContatoTelefone.setToolTip(_translate("frmCadastroFuncionario", "Contato", None))
        self.txtContatoTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do nome do contato</p></body></html>", None))
        self.lblEmail.setText(_translate("frmCadastroFuncionario", "E-mail", None))
        self.btnRemoverEmail.setToolTip(_translate("frmCadastroFuncionario", "Remover", None))
        self.btnRemoverEmail.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão remover um contato de e-mail da lista</p></body></html>", None))
        self.lblTelefone.setText(_translate("frmCadastroFuncionario", "Telefone", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.contatos), _translate("frmCadastroFuncionario", "Contato", None))
        self.lblDataAdmissao.setText(_translate("frmCadastroFuncionario", "Data Admissão", None))
        self.lblDataDemissao.setText(_translate("frmCadastroFuncionario", "Data Demissão", None))
        self.lblCargo.setText(_translate("frmCadastroFuncionario", "Cargo", None))
        self.lblSetor.setText(_translate("frmCadastroFuncionario", "Setor", None))
        self.txtDataDemissao.setToolTip(_translate("frmCadastroFuncionario", "Data Demição", None))
        self.txtDataAdmissao.setToolTip(_translate("frmCadastroFuncionario", "Data Admição", None))
        self.cBoxSetor.setToolTip(_translate("frmCadastroFuncionario", "Setor", None))
        self.cBoxSetor.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de escolha do setor de trabalho do funcionario", None))
        self.cBoxCargo.setToolTip(_translate("frmCadastroFuncionario", "Cargo", None))
        self.cBoxCargo.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de escolha do cargo de trabalho do funcionario", None))
        self.lblCategoriaTrabalhador.setText(_translate("frmCadastroFuncionario", "Categoria Trabalhador", None))
        self.cBoxCateTrabalhador.setToolTip(_translate("frmCadastroFuncionario", "Categoria Trabalhador", None))
        self.cBoxCateTrabalhador.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo de escolha da categoria do trabalhador</p></body></html>", None))
        self.lblPis.setText(_translate("frmCadastroFuncionario", "PIS/PASEP", None))
        self.txtPis.setToolTip(_translate("frmCadastroFuncionario", "PIS/PASEP", None))
        self.txtPis.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do número do PIS/PASEP do funcionário</p></body></html>", None))
        self.txtNumCarteira.setToolTip(_translate("frmCadastroFuncionario", "Número Carteira", None))
        self.txtNumCarteira.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do número da carteira de trabalho do funcionário</p></body></html>", None))
        self.lblNumCarteira.setText(_translate("frmCadastroFuncionario", "Numero Carteira", None))
        self.lblSerie.setText(_translate("frmCadastroFuncionario", "Série", None))
        self.txtSerie.setToolTip(_translate("frmCadastroFuncionario", "Série", None))
        self.txtSerie.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do numero de série do funcionário</p></body></html>", None))
        self.lblUf.setText(_translate("frmCadastroFuncionario", "UF", None))
        self.txtUf.setToolTip(_translate("frmCadastroFuncionario", "UF", None))
        self.txtUf.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do estado de emissão da carteira</p></body></html>", None))
        self.lblDataEmissao.setText(_translate("frmCadastroFuncionario", "Data Emissão", None))
        self.txtDataEmissao.setToolTip(_translate("frmCadastroFuncionario", "Data Emissão", None))
        self.txtDataEmissao.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo da data de emissão da carteira</p></body></html>", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.cadastroSetores), _translate("frmCadastroFuncionario", "Trabalhador", None))
        self.lblTabelaHorario.setText(_translate("frmCadastroFuncionario", "Tabela de Horários", None))
        self.cBoxTabelaHorario.setToolTip(_translate("frmCadastroFuncionario", "Tabela de Horários", None))
        self.cBoxTabelaHorario.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo de escolha da tabela dos horários da jornada de trabalho</p></body></html>", None))
        self.tabHorario.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Tabela de informações da jornada de trabalho</p></body></html>", None))
        item = self.tabHorario.horizontalHeaderItem(0)
        item.setText(_translate("frmCadastroFuncionario", "Dia", None))
        item = self.tabHorario.horizontalHeaderItem(1)
        item.setText(_translate("frmCadastroFuncionario", "Entrada", None))
        item = self.tabHorario.horizontalHeaderItem(2)
        item.setText(_translate("frmCadastroFuncionario", "Início Intervalo", None))
        item = self.tabHorario.horizontalHeaderItem(3)
        item.setText(_translate("frmCadastroFuncionario", "Término Intervalo", None))
        item = self.tabHorario.horizontalHeaderItem(4)
        item.setText(_translate("frmCadastroFuncionario", "Saída", None))
        __sortingEnabled = self.tabHorario.isSortingEnabled()
        self.tabHorario.setSortingEnabled(False)
        item = self.tabHorario.item(0, 0)
        item.setText(_translate("frmCadastroFuncionario", "SEGUNDA-FEIRA", None))
        item = self.tabHorario.item(1, 0)
        item.setText(_translate("frmCadastroFuncionario", "TERÇA-FEIRA", None))
        item = self.tabHorario.item(2, 0)
        item.setText(_translate("frmCadastroFuncionario", "QUARTA-FEIRA", None))
        item = self.tabHorario.item(3, 0)
        item.setText(_translate("frmCadastroFuncionario", "QUINTA-FEIRA", None))
        item = self.tabHorario.item(4, 0)
        item.setText(_translate("frmCadastroFuncionario", "SEXTA-FEIRA", None))
        item = self.tabHorario.item(5, 0)
        item.setText(_translate("frmCadastroFuncionario", "SABADO", None))
        item = self.tabHorario.item(6, 0)
        item.setText(_translate("frmCadastroFuncionario", "DOMINGO", None))
        self.tabHorario.setSortingEnabled(__sortingEnabled)
        item.setText(_translate("frmCadastroFuncionario", "DOMINGO", None))
        self.tabWiAdicionais.setTabText(self.tabWiAdicionais.indexOf(self.horario), _translate("frmCadastroFuncionario", "Horário", None))
        self.btnNovo.setToolTip(_translate("frmCadastroFuncionario", "Novo", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão para cadastrar uma novo registro da pessoa jurídica</p></body></html>", None))
        self.btnNovo.setText(_translate("frmCadastroFuncionario", "Novo", None))
        self.btnSalvar.setToolTip(_translate("frmCadastroFuncionario", "Salvar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão para salvar um novo registro da pessoa jurídica</p></body></html>", None))
        self.btnSalvar.setText(_translate("frmCadastroFuncionario", "Salvar", None))
        self.btnCancelar.setToolTip(_translate("frmCadastroFuncionario", "Cancelar", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão para cancelar a operação ", None))
        self.btnCancelar.setText(_translate("frmCadastroFuncionario", "Cancelar", None))
        self.btnDeletar.setToolTip(_translate("frmCadastroFuncionario", "Deletar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão de deletar o registro da pessoa jurídica</p></body></html>", None))
        self.btnDeletar.setText(_translate("frmCadastroFuncionario", "Deletar", None))
        self.btnEditar.setToolTip(_translate("frmCadastroFuncionario", "Editar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Botão para salvar o registo editado da pessoa jurídica</p></body></html>", None))
        self.btnEditar.setText(_translate("frmCadastroFuncionario", "Editar", None))
        self.lblPesquisar.setText(_translate("frmCadastroFuncionario", "[F12] Pesquisar", None))
        self.txtDataDemissao.setInputMask(_translate("frmCadastroFuncionario", "00/00/0000; ", None))
        self.txtDataAdmissao.setInputMask(_translate("frmCadastroFuncionario", "00/00/0000; ", None))
        self.txtDataEmissao.setInputMask(_translate("frmCadastroFuncionario", "00/00/0000; ", None))

