# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroClientes.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroClientes(object):
    def setupUi(self, frmCadastroClientes):
        frmCadastroClientes.setObjectName(_fromUtf8("frmCadastroClientes"))
        frmCadastroClientes.resize(895, 695)
        frmCadastroClientes.setMinimumSize(QtCore.QSize(895, 695))
        frmCadastroClientes.setMaximumSize(QtCore.QSize(895, 695))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroClientes.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/clientes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCadastroClientes.setWindowIcon(icon)
        frmCadastroClientes.setSizeGripEnabled(False)
        frmCadastroClientes.setModal(True)

        self.grbBotoes = QtGui.QGroupBox(frmCadastroClientes)

        self.grbBotoes.setGeometry(QtCore.QRect(7, 612, 881, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(370, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(670, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(770, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(470, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(570, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.grbDadosCliente = QtGui.QGroupBox(frmCadastroClientes)
        self.grbDadosCliente.setEnabled(False)
        self.grbDadosCliente.setGeometry(QtCore.QRect(7, 118, 881, 288))
        self.grbDadosCliente.setObjectName(_fromUtf8("grbDadosCliente"))

        self.lblCepCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblCepCliente.setGeometry(QtCore.QRect(368, 149, 31, 19))
        self.lblCepCliente.setObjectName(_fromUtf8("lblCepCliente"))

        self.txtCidadesCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtCidadesCliente.setEnabled(False)
        self.txtCidadesCliente.setGeometry(QtCore.QRect(532, 169, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadesCliente.setPalette(palette)
        self.txtCidadesCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidadesCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidadesCliente.setMaxLength(70)
        self.txtCidadesCliente.setObjectName(_fromUtf8("txtCidadesCliente"))

        self.lblBairroCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblBairroCliente.setGeometry(QtCore.QRect(8, 149, 41, 19))
        self.lblBairroCliente.setObjectName(_fromUtf8("lblBairroCliente"))

        self.lblComplementoCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblComplementoCliente.setGeometry(QtCore.QRect(602, 105, 101, 16))
        self.lblComplementoCliente.setObjectName(_fromUtf8("lblComplementoCliente"))

        self.txtTelefoneCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtTelefoneCliente.setGeometry(QtCore.QRect(222, 214, 191, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTelefoneCliente.setPalette(palette)
        self.txtTelefoneCliente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtTelefoneCliente.setObjectName(_fromUtf8("txtTelefoneCliente"))

        self.txtCnpjCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtCnpjCliente.setGeometry(QtCore.QRect(188, 37, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjCliente.setPalette(palette)
        self.txtCnpjCliente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjCliente.setText(_fromUtf8("../-"))
        self.txtCnpjCliente.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjCliente.setObjectName(_fromUtf8("txtCnpjCliente"))

        self.lblRazaoSocialCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblRazaoSocialCliente.setGeometry(QtCore.QRect(452, 61, 81, 19))
        self.lblRazaoSocialCliente.setObjectName(_fromUtf8("lblRazaoSocialCliente"))

        self.lblCnpjCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblCnpjCliente.setGeometry(QtCore.QRect(188, 17, 41, 19))
        self.lblCnpjCliente.setObjectName(_fromUtf8("lblCnpjCliente"))

        self.txtRazaoSocialCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtRazaoSocialCliente.setGeometry(QtCore.QRect(452, 81, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialCliente.setPalette(palette)
        self.txtRazaoSocialCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialCliente.setMaxLength(70)
        self.txtRazaoSocialCliente.setObjectName(_fromUtf8("txtRazaoSocialCliente"))

        self.txtCepCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtCepCliente.setGeometry(QtCore.QRect(368, 169, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepCliente.setPalette(palette)
        self.txtCepCliente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCepCliente.setInputMask(_fromUtf8("00000-000; "))

        self.txtCepCliente.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCepCliente.setObjectName(_fromUtf8("txtCepCliente"))

        self.lblEnderecoCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblEnderecoCliente.setGeometry(QtCore.QRect(8, 105, 66, 19))
        self.lblEnderecoCliente.setObjectName(_fromUtf8("lblEnderecoCliente"))

        self.txtComplementoCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtComplementoCliente.setGeometry(QtCore.QRect(602, 125, 271, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoCliente.setPalette(palette)
        self.txtComplementoCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtComplementoCliente.setMaxLength(50)
        self.txtComplementoCliente.setObjectName(_fromUtf8("txtComplementoCliente"))

        self.txtEstadosCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtEstadosCliente.setEnabled(False)
        self.txtEstadosCliente.setGeometry(QtCore.QRect(8, 214, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadosCliente.setPalette(palette)
        self.txtEstadosCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstadosCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstadosCliente.setMaxLength(50)
        self.txtEstadosCliente.setObjectName(_fromUtf8("txtEstadosCliente"))

        self.txtNumeroCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtNumeroCliente.setGeometry(QtCore.QRect(436, 125, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroCliente.setPalette(palette)
        self.txtNumeroCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNumeroCliente.setMaxLength(11)
        self.txtNumeroCliente.setObjectName(_fromUtf8("txtNumeroCliente"))

        self.lblNomeFantasiaCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblNomeFantasiaCliente.setGeometry(QtCore.QRect(8, 61, 101, 19))
        self.lblNomeFantasiaCliente.setObjectName(_fromUtf8("lblNomeFantasiaCliente"))

        self.txtBairroCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtBairroCliente.setGeometry(QtCore.QRect(8, 169, 351, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroCliente.setPalette(palette)
        self.txtBairroCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtBairroCliente.setMaxLength(50)
        self.txtBairroCliente.setObjectName(_fromUtf8("txtBairroCliente"))

        self.txtInscricaoEstadualCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtInscricaoEstadualCliente.setGeometry(QtCore.QRect(398, 37, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstadualCliente.setPalette(palette)
        self.txtInscricaoEstadualCliente.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadualCliente.setMaxLength(8)
        self.txtInscricaoEstadualCliente.setObjectName(_fromUtf8("txtInscricaoEstadualCliente"))

        self.lblTelefoeneCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblTelefoeneCliente.setGeometry(QtCore.QRect(222, 194, 61, 19))
        self.lblTelefoeneCliente.setObjectName(_fromUtf8("lblTelefoeneCliente"))

        self.lblNumeroCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblNumeroCliente.setGeometry(QtCore.QRect(436, 105, 51, 19))
        self.lblNumeroCliente.setObjectName(_fromUtf8("lblNumeroCliente"))

        self.txtEnderecoCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtEnderecoCliente.setGeometry(QtCore.QRect(8, 125, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoCliente.setPalette(palette)
        self.txtEnderecoCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEnderecoCliente.setMaxLength(50)
        self.txtEnderecoCliente.setObjectName(_fromUtf8("txtEnderecoCliente"))

        self.txtFantasiaCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtFantasiaCliente.setGeometry(QtCore.QRect(8, 81, 431, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasiaCliente.setPalette(palette)
        self.txtFantasiaCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasiaCliente.setMaxLength(70)
        self.txtFantasiaCliente.setObjectName(_fromUtf8("txtFantasiaCliente"))

        self.lblCidadesCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblCidadesCliente.setGeometry(QtCore.QRect(532, 149, 51, 19))
        self.lblCidadesCliente.setObjectName(_fromUtf8("lblCidadesCliente"))

        self.lblEstadosCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblEstadosCliente.setGeometry(QtCore.QRect(10, 193, 51, 19))
        self.lblEstadosCliente.setObjectName(_fromUtf8("lblEstadosCliente"))

        self.lblInscricaoEstadualCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblInscricaoEstadualCliente.setGeometry(QtCore.QRect(398, 17, 121, 19))
        self.lblInscricaoEstadualCliente.setObjectName(_fromUtf8("lblInscricaoEstadualCliente"))

        self.txtIdCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtIdCliente.setEnabled(False)
        self.txtIdCliente.setGeometry(QtCore.QRect(6, 37, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdCliente.setPalette(palette)
        self.txtIdCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdCliente.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdCliente.setMaxLength(11)
        self.txtIdCliente.setObjectName(_fromUtf8("txtIdCliente"))

        self.lblCodigoCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblCodigoCliente.setGeometry(QtCore.QRect(6, 17, 51, 19))
        self.lblCodigoCliente.setObjectName(_fromUtf8("lblCodigoCliente"))

        self.txtSiteCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtSiteCliente.setGeometry(QtCore.QRect(420, 214, 454, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSiteCliente.setPalette(palette)
        self.txtSiteCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtSiteCliente.setMaxLength(50)
        self.txtSiteCliente.setObjectName(_fromUtf8("txtSiteCliente"))

        self.lblSiteCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblSiteCliente.setGeometry(QtCore.QRect(420, 194, 31, 19))
        self.lblSiteCliente.setObjectName(_fromUtf8("lblSiteCliente"))

        self.lblEmailCliente = QtGui.QLabel(self.grbDadosCliente)
        self.lblEmailCliente.setGeometry(QtCore.QRect(10, 238, 41, 19))
        self.lblEmailCliente.setObjectName(_fromUtf8("lblEmailCliente"))

        self.txtEmailCliente = QtGui.QLineEdit(self.grbDadosCliente)
        self.txtEmailCliente.setGeometry(QtCore.QRect(10, 258, 454, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEmailCliente.setPalette(palette)
        self.txtEmailCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEmailCliente.setMaxLength(50)
        self.txtEmailCliente.setObjectName(_fromUtf8("txtEmailCliente"))

        self.grbPesquisarEmpresa = QtGui.QGroupBox(frmCadastroClientes)
        self.grbPesquisarEmpresa.setGeometry(QtCore.QRect(8, 0, 880, 119))
        self.grbPesquisarEmpresa.setObjectName(_fromUtf8("grbPesquisarEmpresa"))

        self.txtCnpjEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtCnpjEmpresa.setEnabled(False)
        self.txtCnpjEmpresa.setGeometry(QtCore.QRect(501, 87, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmpresa.setPalette(palette)
        self.txtCnpjEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpjEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCnpjEmpresa.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmpresa.setText(_fromUtf8("../-"))
        self.txtCnpjEmpresa.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmpresa.setObjectName(_fromUtf8("txtCnpjEmpresa"))

        self.lblCodigoEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblCodigoEmpresa.setGeometry(QtCore.QRect(10, 17, 51, 19))
        self.lblCodigoEmpresa.setObjectName(_fromUtf8("lblCodigoEmpresa"))

        self.lblNomeFantasiaEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblNomeFantasiaEmpresa.setGeometry(QtCore.QRect(197, 17, 101, 19))
        self.lblNomeFantasiaEmpresa.setObjectName(_fromUtf8("lblNomeFantasiaEmpresa"))

        self.lblCnpjEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblCnpjEmpresa.setGeometry(QtCore.QRect(501, 67, 41, 19))
        self.lblCnpjEmpresa.setObjectName(_fromUtf8("lblCnpjEmpresa"))

        self.txtFantasiaEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtFantasiaEmpresa.setEnabled(False)
        self.txtFantasiaEmpresa.setGeometry(QtCore.QRect(197, 37, 631, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasiaEmpresa.setPalette(palette)
        self.txtFantasiaEmpresa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasiaEmpresa.setMaxLength(70)
        self.txtFantasiaEmpresa.setObjectName(_fromUtf8("txtFantasiaEmpresa"))

        self.txtRazaoSocialEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtRazaoSocialEmpresa.setEnabled(False)
        self.txtRazaoSocialEmpresa.setGeometry(QtCore.QRect(10, 87, 482, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmpresa.setPalette(palette)
        self.txtRazaoSocialEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocialEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRazaoSocialEmpresa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmpresa.setMaxLength(70)
        self.txtRazaoSocialEmpresa.setObjectName(_fromUtf8("txtRazaoSocialEmpresa"))

        self.lblRazaoSocialEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblRazaoSocialEmpresa.setGeometry(QtCore.QRect(10, 67, 81, 19))
        self.lblRazaoSocialEmpresa.setObjectName(_fromUtf8("lblRazaoSocialEmpresa"))

        self.txtIdEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtIdEmpresa.setEnabled(False)
        self.txtIdEmpresa.setGeometry(QtCore.QRect(10, 37, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresa.setPalette(palette)
        self.txtIdEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdEmpresa.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdEmpresa.setMaxLength(11)
        self.txtIdEmpresa.setObjectName(_fromUtf8("txtIdEmpresa"))

        self.txtInscricaoEstaduaEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtInscricaoEstaduaEmpresa.setEnabled(False)
        self.txtInscricaoEstaduaEmpresa.setGeometry(QtCore.QRect(689, 87, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmpresa.setPalette(palette)
        self.txtInscricaoEstaduaEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstaduaEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtInscricaoEstaduaEmpresa.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmpresa.setMaxLength(8)
        self.txtInscricaoEstaduaEmpresa.setObjectName(_fromUtf8("txtInscricaoEstaduaEmpresa"))

        self.lblInscricaoEstadualEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblInscricaoEstadualEmpresa.setGeometry(QtCore.QRect(689, 67, 121, 19))
        self.lblInscricaoEstadualEmpresa.setObjectName(_fromUtf8("lblInscricaoEstadualEmpresa"))

        self.btnPesquisar = QtGui.QPushButton(self.grbPesquisarEmpresa)
        self.btnPesquisar.setGeometry(QtCore.QRect(837, 37, 31, 27))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.grbPesquisa = QtGui.QGroupBox(frmCadastroClientes)
        self.grbPesquisa.setGeometry(QtCore.QRect(8, 408, 881, 201))
        self.grbPesquisa.setTitle(_fromUtf8(""))
        self.grbPesquisa.setObjectName(_fromUtf8("grbPesquisa"))

        self.txtPesquisa = QtGui.QLineEdit(self.grbPesquisa)
        self.txtPesquisa.setGeometry(QtCore.QRect(470, 14, 351, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisa.setPalette(palette)
        self.txtPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPesquisa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtPesquisa.setMaxLength(50)
        self.txtPesquisa.setObjectName(_fromUtf8("txtPesquisa"))

        self.btnPesquisarFornecedor = QtGui.QPushButton(self.grbPesquisa)
        self.btnPesquisarFornecedor.setGeometry(QtCore.QRect(830, 12, 41, 31))
        self.btnPesquisarFornecedor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarFornecedor.setText(_fromUtf8(""))
        self.btnPesquisarFornecedor.setObjectName(_fromUtf8("btnPesquisarFornecedor"))

        self.tbPesquisa = QtGui.QTableWidget(self.grbPesquisa)
        self.tbPesquisa.setGeometry(QtCore.QRect(10, 50, 861, 141))
        self.tbPesquisa.setColumnCount(20)
        self.tbPesquisa.setHorizontalHeaderLabels(['COD.', 'Fornecedor', 'Razão Social', 'CNPJ', 'Ins. Estadual', 'Endereco', 'Numero', 'Complemento', 'Bairro', 'Telefone', 'Site', 'E-mail', 'Cep', 'Cidade', 'Estado', 'COD', 'Empresa', 'Razão Social', 'CNPJ', 'Ins. Estadua'])
        self.tbPesquisa.setEditTriggers(self.tbPesquisa.NoEditTriggers)
        self.tbPesquisa.setSelectionBehavior(self.tbPesquisa.SelectRows)
        self.tbPesquisa.setSelectionMode(self.tbPesquisa.SingleSelection)
        self.tbPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbPesquisa.setObjectName(_fromUtf8("tbPesquisa"))

        self.grbDadosPesquisa = QtGui.QGroupBox(self.grbPesquisa)
        self.grbDadosPesquisa.setGeometry(QtCore.QRect(3, 0, 451, 44))
        self.grbDadosPesquisa.setObjectName(_fromUtf8("grbDadosPesquisa"))

        self.radBtnCodigo = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCodigo.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radBtnCodigo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCodigo.setObjectName(_fromUtf8("radBtnCodigo"))

        self.radBtnFantasia = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnFantasia.setGeometry(QtCore.QRect(80, 20, 71, 17))
        self.radBtnFantasia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnFantasia.setObjectName(_fromUtf8("radBtnFantasia"))

        self.radBtnRazaoSocial = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnRazaoSocial.setGeometry(QtCore.QRect(160, 20, 101, 17))
        self.radBtnRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnRazaoSocial.setObjectName(_fromUtf8("radBtnRazaoSocial"))

        self.radBtnCnpj = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCnpj.setGeometry(QtCore.QRect(270, 20, 51, 17))
        self.radBtnCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCnpj.setObjectName(_fromUtf8("radBtnCnpj"))

        self.radBtnInsEstadual = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnInsEstadual.setGeometry(QtCore.QRect(330, 20, 91, 17))
        self.radBtnInsEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnInsEstadual.setObjectName(_fromUtf8("radBtnInsEstadual"))

        self.lblCepCliente.setBuddy(self.txtCepCliente)
        self.lblBairroCliente.setBuddy(self.txtBairroCliente)
        self.lblComplementoCliente.setBuddy(self.txtComplementoCliente)
        self.lblRazaoSocialCliente.setBuddy(self.txtRazaoSocialCliente)
        self.lblCnpjCliente.setBuddy(self.txtCnpjCliente)
        self.lblEnderecoCliente.setBuddy(self.txtEnderecoCliente)
        self.lblNomeFantasiaCliente.setBuddy(self.txtFantasiaCliente)
        self.lblTelefoeneCliente.setBuddy(self.txtTelefoneCliente)
        self.lblNumeroCliente.setBuddy(self.txtNumeroCliente)
        self.lblCidadesCliente.setBuddy(self.txtCidadesCliente)
        self.lblEstadosCliente.setBuddy(self.txtEstadosCliente)
        self.lblInscricaoEstadualCliente.setBuddy(self.txtInscricaoEstadualCliente)
        self.lblCodigoCliente.setBuddy(self.txtIdCliente)
        self.lblSiteCliente.setBuddy(self.txtEnderecoCliente)
        self.lblEmailCliente.setBuddy(self.txtEnderecoCliente)
        self.lblCodigoEmpresa.setBuddy(self.txtIdEmpresa)
        self.lblNomeFantasiaEmpresa.setBuddy(self.txtFantasiaEmpresa)
        self.lblCnpjEmpresa.setBuddy(self.txtCnpjEmpresa)
        self.lblRazaoSocialEmpresa.setBuddy(self.txtRazaoSocialEmpresa)
        self.lblInscricaoEstadualEmpresa.setBuddy(self.txtInscricaoEstaduaEmpresa)

        self.retranslateUi(frmCadastroClientes)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroClientes)
        frmCadastroClientes.setTabOrder(self.txtIdCliente, self.txtCnpjCliente)
        frmCadastroClientes.setTabOrder(self.txtCnpjCliente, self.txtInscricaoEstadualCliente)
        frmCadastroClientes.setTabOrder(self.txtInscricaoEstadualCliente, self.txtFantasiaCliente)
        frmCadastroClientes.setTabOrder(self.txtFantasiaCliente, self.txtRazaoSocialCliente)
        frmCadastroClientes.setTabOrder(self.txtRazaoSocialCliente, self.txtEnderecoCliente)
        frmCadastroClientes.setTabOrder(self.txtEnderecoCliente, self.txtNumeroCliente)
        frmCadastroClientes.setTabOrder(self.txtNumeroCliente, self.txtComplementoCliente)
        frmCadastroClientes.setTabOrder(self.txtComplementoCliente, self.txtBairroCliente)
        frmCadastroClientes.setTabOrder(self.txtBairroCliente, self.txtCepCliente)
        frmCadastroClientes.setTabOrder(self.txtCepCliente, self.txtCidadesCliente)
        frmCadastroClientes.setTabOrder(self.txtCidadesCliente, self.txtEstadosCliente)
        frmCadastroClientes.setTabOrder(self.txtEstadosCliente, self.txtTelefoneCliente)
        frmCadastroClientes.setTabOrder(self.txtTelefoneCliente, self.btnNovo)
        frmCadastroClientes.setTabOrder(self.btnNovo, self.btnSalvar)
        frmCadastroClientes.setTabOrder(self.btnSalvar, self.btnEditar)
        frmCadastroClientes.setTabOrder(self.btnEditar, self.btnCancelar)
        frmCadastroClientes.setTabOrder(self.btnCancelar, self.btnDeletar)

    def retranslateUi(self, frmCadastroClientes):
        frmCadastroClientes.setWindowTitle(_translate("frmCadastroClientes", "Cadastro Clientes", None))
        self.grbBotoes.setWhatsThis(_translate("frmCadastroClientes", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroClientes", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmCadastroClientes", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroClientes", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmCadastroClientes", "Cancelar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroClientes", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmCadastroClientes", "Deletar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroClientes", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmCadastroClientes", "Salvar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroClientes", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmCadastroClientes", "Editar", None))
        self.grbDadosCliente.setWhatsThis(_translate("frmCadastroClientes", "Grupo de Dados para cadastro e edição de cliente", None))
        self.grbDadosCliente.setTitle(_translate("frmCadastroClientes", "Dados Cliente", None))
        self.lblCepCliente.setText(_translate("frmCadastroClientes", "CEP", None))
        self.txtCidadesCliente.setToolTip(_translate("frmCadastroClientes", "Cidade Cliente", None))
        self.txtCidadesCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblBairroCliente.setText(_translate("frmCadastroClientes", "Bairro", None))
        self.lblComplementoCliente.setText(_translate("frmCadastroClientes", "Complemento", None))
        self.txtTelefoneCliente.setToolTip(_translate("frmCadastroClientes", "Telefone Cliente", None))
        self.txtTelefoneCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do numero de cantato de telefone da Cliente", None))
        self.txtTelefoneCliente.setInputMask(_translate("frmCadastroClientes", "(00) 00000-0000; ", None))
        self.txtCnpjCliente.setToolTip(_translate("frmCadastroClientes", "CNPJ Cliente", None))
        self.txtCnpjCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do numero do CNPJ da Cliente", None))
        self.txtCnpjCliente.setInputMask(_translate("frmCadastroClientes", "00.000.000/0000-00; ", None))
        self.lblRazaoSocialCliente.setText(_translate("frmCadastroClientes", "Razão Social", None))
        self.lblCnpjCliente.setText(_translate("frmCadastroClientes", "CNPJ", None))
        self.txtRazaoSocialCliente.setToolTip(_translate("frmCadastroClientes", "Razão Social Cliente", None))
        self.txtRazaoSocialCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome da razão social da Cliente", None))
        self.txtCepCliente.setToolTip(_translate("frmCadastroClientes", "CEP Cliente", None))
        self.txtCepCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.lblEnderecoCliente.setText(_translate("frmCadastroClientes", "Endereço", None))
        self.txtComplementoCliente.setToolTip(_translate("frmCadastroClientes", "Complemento Cliente", None))
        self.txtComplementoCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo complementar do endereço", None))
        self.txtEstadosCliente.setToolTip(_translate("frmCadastroClientes", "Estado Cliente", None))
        self.txtEstadosCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome do estado de localização do endereço", None))
        self.txtNumeroCliente.setToolTip(_translate("frmCadastroClientes", "Numero Cliente", None))
        self.txtNumeroCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo de numero referente ao numero do endereço", None))
        self.lblNomeFantasiaCliente.setText(_translate("frmCadastroClientes", "Nome Fantasia", None))
        self.txtBairroCliente.setToolTip(_translate("frmCadastroClientes", "Bairro Cliente", None))
        self.txtBairroCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome do bairro referente ao endereço", None))
        self.txtInscricaoEstadualCliente.setToolTip(_translate("frmCadastroClientes", "Inscrição Estadual Cliente", None))
        self.txtInscricaoEstadualCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do numero do inscrição estadual da Cliente", None))
        self.lblTelefoeneCliente.setText(_translate("frmCadastroClientes", "Telefone", None))
        self.lblNumeroCliente.setText(_translate("frmCadastroClientes", "Numero", None))
        self.txtEnderecoCliente.setToolTip(_translate("frmCadastroClientes", "Endereço Cliente", None))
        self.txtEnderecoCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo de descrição do endereço", None))
        self.txtFantasiaCliente.setToolTip(_translate("frmCadastroClientes", "Nome Fantasia Cliente", None))
        self.txtFantasiaCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome fantasia da Cliente", None))
        self.lblCidadesCliente.setText(_translate("frmCadastroClientes", "Cidade", None))
        self.lblEstadosCliente.setText(_translate("frmCadastroClientes", "Estado", None))
        self.lblInscricaoEstadualCliente.setText(_translate("frmCadastroClientes", "Incrição Estadual", None))
        self.txtIdCliente.setToolTip(_translate("frmCadastroClientes", "Codigo Cliente", None))
        self.txtIdCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo do codigo de identificação da Cliente", None))
        self.lblCodigoCliente.setText(_translate("frmCadastroClientes", "Codigo", None))
        self.txtSiteCliente.setToolTip(_translate("frmCadastroClientes", "Endereço site Cliente", None))
        self.txtSiteCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo de descrição do endereço", None))
        self.lblSiteCliente.setText(_translate("frmCadastroClientes", "Site", None))
        self.lblEmailCliente.setText(_translate("frmCadastroClientes", "E-mail", None))
        self.txtEmailCliente.setToolTip(_translate("frmCadastroClientes", "Endereço site Cliente", None))
        self.txtEmailCliente.setWhatsThis(_translate("frmCadastroClientes", "Campo de descrição do endereço", None))
        self.grbPesquisarEmpresa.setTitle(_translate("frmCadastroClientes", "Pesquisar Empresa", None))
        self.txtCnpjEmpresa.setToolTip(_translate("frmCadastroClientes", "CNPJ Empresa", None))
        self.txtCnpjEmpresa.setWhatsThis(_translate("frmCadastroClientes", "Campo do numero do CNPJ da empresa", None))
        self.txtCnpjEmpresa.setInputMask(_translate("frmCadastroClientes", "00.000.000/0000-00; ", None))
        self.lblCodigoEmpresa.setText(_translate("frmCadastroClientes", "Codigo", None))
        self.lblNomeFantasiaEmpresa.setText(_translate("frmCadastroClientes", "Nome Fantasia", None))
        self.lblCnpjEmpresa.setText(_translate("frmCadastroClientes", "CNPJ", None))
        self.txtFantasiaEmpresa.setToolTip(_translate("frmCadastroClientes", "Nome Fantasia Empresa", None))
        self.txtFantasiaEmpresa.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome fantasia da empresa", None))
        self.txtRazaoSocialEmpresa.setToolTip(_translate("frmCadastroClientes", "Razão Social Empresa", None))
        self.txtRazaoSocialEmpresa.setWhatsThis(_translate("frmCadastroClientes", "Campo do nome da razão social da empresa", None))
        self.lblRazaoSocialEmpresa.setText(_translate("frmCadastroClientes", "Razão Social", None))
        self.txtIdEmpresa.setToolTip(_translate("frmCadastroClientes", "Codigo Empresa", None))
        self.txtIdEmpresa.setWhatsThis(_translate("frmCadastroClientes", "Campo do codigo de identificação da empresa", None))
        self.txtInscricaoEstaduaEmpresa.setToolTip(_translate("frmCadastroClientes", "Inscrição Estadual Empresa", None))
        self.txtInscricaoEstaduaEmpresa.setWhatsThis(_translate("frmCadastroClientes", "Campo do numero do inscrição estadual da empresa", None))
        self.lblInscricaoEstadualEmpresa.setText(_translate("frmCadastroClientes", "Incrição Estadual", None))
        self.txtPesquisa.setToolTip(_translate("frmCadastroClientes", "Pesquisa", None))
        self.txtPesquisa.setWhatsThis(_translate("frmCadastroClientes", "Campo pra inserir dados da pesquisa", None))
        self.tbPesquisa.setToolTip(_translate("frmCadastroClientes", "Tabela de Pesquisa", None))
        self.tbPesquisa.setWhatsThis(_translate("frmCadastroClientes", "Campo com as informações da pesquisa", None))
        self.grbDadosPesquisa.setTitle(_translate("frmCadastroClientes", "Dados Pesquisa", None))
        self.radBtnCodigo.setText(_translate("frmCadastroClientes", "Codigo", None))
        self.radBtnFantasia.setText(_translate("frmCadastroClientes", "Fantasia", None))
        self.radBtnRazaoSocial.setText(_translate("frmCadastroClientes", "Razão Social", None))
        self.radBtnCnpj.setText(_translate("frmCadastroClientes", "CNPJ", None))
        self.radBtnInsEstadual.setText(_translate("frmCadastroClientes", "Ins. Esta.", None))

