# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroSetoresCargos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroSetoresCargos(object):
    def setupUi(self, frmCadastroSetoresCargos):
        frmCadastroSetoresCargos.setObjectName(_fromUtf8("frmCadastroSetoresCargos"))
        frmCadastroSetoresCargos.resize(534, 487)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroSetoresCargos.setFont(font)
        self.tabwiCadastroSetoresCargos = QtGui.QTabWidget(frmCadastroSetoresCargos)
        self.tabwiCadastroSetoresCargos.setGeometry(QtCore.QRect(0, 0, 541, 491))
        self.tabwiCadastroSetoresCargos.setWhatsThis(_fromUtf8(""))
        self.tabwiCadastroSetoresCargos.setObjectName(_fromUtf8("tabwiCadastroSetoresCargos"))
        self.cadastroSetores = QtGui.QWidget()
        self.cadastroSetores.setObjectName(_fromUtf8("cadastroSetores"))
        self.txtCadSetoresNomeFantasia = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresNomeFantasia.setGeometry(QtCore.QRect(147, 50, 341, 25))
        self.txtCadSetoresNomeFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadSetoresNomeFantasia.setMaxLength(70)
        self.txtCadSetoresNomeFantasia.setObjectName(_fromUtf8("txtCadSetoresNomeFantasia"))
        self.txtCadSetoresCodigo = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresCodigo.setGeometry(QtCore.QRect(2, 50, 141, 25))
        self.txtCadSetoresCodigo.setMaxLength(11)
        self.txtCadSetoresCodigo.setObjectName(_fromUtf8("txtCadSetoresCodigo"))
        self.txtCadSetoresTipoEmpresa = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresTipoEmpresa.setEnabled(False)
        self.txtCadSetoresTipoEmpresa.setGeometry(QtCore.QRect(1, 102, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresTipoEmpresa.setPalette(palette)
        self.txtCadSetoresTipoEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresTipoEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCadSetoresTipoEmpresa.setMaxLength(50)
        self.txtCadSetoresTipoEmpresa.setObjectName(_fromUtf8("txtCadSetoresTipoEmpresa"))
        self.txtCadSetoresSetor = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresSetor.setGeometry(QtCore.QRect(2, 185, 421, 25))
        self.txtCadSetoresSetor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadSetoresSetor.setMaxLength(50)
        self.txtCadSetoresSetor.setObjectName(_fromUtf8("txtCadSetoresSetor"))
        self.btnCadSetoresPesquisar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresPesquisar.setGeometry(QtCore.QRect(496, 50, 31, 27))
        self.btnCadSetoresPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresPesquisar.setText(_fromUtf8(""))
        self.btnCadSetoresPesquisar.setObjectName(_fromUtf8("btnCadSetoresPesquisar"))
        self.lblCadSetoresCodigo = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresCodigo.setGeometry(QtCore.QRect(5, 30, 51, 19))
        self.lblCadSetoresCodigo.setObjectName(_fromUtf8("lblCadSetoresCodigo"))
        self.lblCadSetoresNomeFantasia = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresNomeFantasia.setGeometry(QtCore.QRect(147, 30, 111, 19))
        self.lblCadSetoresNomeFantasia.setObjectName(_fromUtf8("lblCadSetoresNomeFantasia"))
        self.lblCadSetoresTipoEmpresa = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresTipoEmpresa.setGeometry(QtCore.QRect(3, 82, 131, 19))
        self.lblCadSetoresTipoEmpresa.setObjectName(_fromUtf8("lblCadSetoresTipoEmpresa"))
        self.lblCadSetoresCnpj = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresCnpj.setGeometry(QtCore.QRect(165, 82, 66, 19))
        self.lblCadSetoresCnpj.setObjectName(_fromUtf8("lblCadSetoresCnpj"))
        self.txtCadSetoresCnpj = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresCnpj.setEnabled(False)
        self.txtCadSetoresCnpj.setGeometry(QtCore.QRect(165, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresCnpj.setPalette(palette)
        self.txtCadSetoresCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCadSetoresCnpj.setObjectName(_fromUtf8("txtCadSetoresCnpj"))
        self.lblCadSetoresIncricaoEstadual = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresIncricaoEstadual.setGeometry(QtCore.QRect(349, 82, 131, 19))
        self.lblCadSetoresIncricaoEstadual.setObjectName(_fromUtf8("lblCadSetoresIncricaoEstadual"))
        self.txtCadSetoresInscricaoEstadual = QtGui.QLineEdit(self.cadastroSetores)
        self.txtCadSetoresInscricaoEstadual.setEnabled(False)
        self.txtCadSetoresInscricaoEstadual.setGeometry(QtCore.QRect(349, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadSetoresInscricaoEstadual.setPalette(palette)
        self.txtCadSetoresInscricaoEstadual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadSetoresInscricaoEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCadSetoresInscricaoEstadual.setMaxLength(8)
        self.txtCadSetoresInscricaoEstadual.setObjectName(_fromUtf8("txtCadSetoresInscricaoEstadual"))
        self.lblCadSetoresSetor = QtGui.QLabel(self.cadastroSetores)
        self.lblCadSetoresSetor.setGeometry(QtCore.QRect(2, 165, 41, 19))
        self.lblCadSetoresSetor.setObjectName(_fromUtf8("lblCadSetoresSetor"))
        self.btnCadSetoresEditar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresEditar.setGeometry(QtCore.QRect(220, 370, 81, 61))
        self.btnCadSetoresEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresEditar.setObjectName(_fromUtf8("btnCadSetoresEditar"))
        self.btnCadSetoresDeletar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresDeletar.setGeometry(QtCore.QRect(420, 370, 81, 61))
        self.btnCadSetoresDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresDeletar.setObjectName(_fromUtf8("btnCadSetoresDeletar"))
        self.btnCadSetoresCancelar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresCancelar.setGeometry(QtCore.QRect(320, 370, 81, 61))
        self.btnCadSetoresCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresCancelar.setObjectName(_fromUtf8("btnCadSetoresCancelar"))
        self.btnCadSetoresSalvar = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresSalvar.setGeometry(QtCore.QRect(120, 370, 81, 61))
        self.btnCadSetoresSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresSalvar.setObjectName(_fromUtf8("btnCadSetoresSalvar"))
        self.btnCadSetoresNovo = QtGui.QPushButton(self.cadastroSetores)
        self.btnCadSetoresNovo.setGeometry(QtCore.QRect(20, 370, 81, 61))
        self.btnCadSetoresNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresNovo.setObjectName(_fromUtf8("btnCadSetoresNovo"))
        self.tabwiCadastroSetoresCargos.addTab(self.cadastroSetores, _fromUtf8(""))
        self.cadastroCargos = QtGui.QWidget()
        self.cadastroCargos.setObjectName(_fromUtf8("cadastroCargos"))
        self.lblCadCargoIncricaoEstadual = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoIncricaoEstadual.setGeometry(QtCore.QRect(349, 82, 131, 19))
        self.lblCadCargoIncricaoEstadual.setObjectName(_fromUtf8("lblCadCargoIncricaoEstadual"))
        self.lblCadCargoCargo = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoCargo.setGeometry(QtCore.QRect(2, 165, 41, 19))
        self.lblCadCargoCargo.setObjectName(_fromUtf8("lblCadCargoCargo"))
        self.btnCadCargoEditar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoEditar.setGeometry(QtCore.QRect(220, 370, 81, 61))
        self.btnCadCargoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoEditar.setObjectName(_fromUtf8("btnCadCargoEditar"))
        self.btnCadCargoDeletar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoDeletar.setGeometry(QtCore.QRect(420, 370, 81, 61))
        self.btnCadCargoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoDeletar.setObjectName(_fromUtf8("btnCadCargoDeletar"))
        self.txtCadCargoTipoEmpresa = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoTipoEmpresa.setEnabled(False)
        self.txtCadCargoTipoEmpresa.setGeometry(QtCore.QRect(1, 102, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoTipoEmpresa.setPalette(palette)
        self.txtCadCargoTipoEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoTipoEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCadCargoTipoEmpresa.setMaxLength(50)
        self.txtCadCargoTipoEmpresa.setObjectName(_fromUtf8("txtCadCargoTipoEmpresa"))
        self.txtCadCargoCodigo = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoCodigo.setGeometry(QtCore.QRect(2, 50, 141, 25))
        self.txtCadCargoCodigo.setMaxLength(11)
        self.txtCadCargoCodigo.setObjectName(_fromUtf8("txtCadCargoCodigo"))
        self.lblCadCargoCodigo = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoCodigo.setGeometry(QtCore.QRect(5, 30, 51, 19))
        self.lblCadCargoCodigo.setObjectName(_fromUtf8("lblCadCargoCodigo"))
        self.lblCadCargoTipoEmpresa = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoTipoEmpresa.setGeometry(QtCore.QRect(3, 82, 131, 19))
        self.lblCadCargoTipoEmpresa.setObjectName(_fromUtf8("lblCadCargoTipoEmpresa"))
        self.txtCadCargoNomeFantasia = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoNomeFantasia.setGeometry(QtCore.QRect(147, 50, 341, 25))
        self.txtCadCargoNomeFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadCargoNomeFantasia.setMaxLength(70)
        self.txtCadCargoNomeFantasia.setObjectName(_fromUtf8("txtCadCargoNomeFantasia"))
        self.lblCadCargoNomeFantasia = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoNomeFantasia.setGeometry(QtCore.QRect(147, 30, 111, 19))
        self.lblCadCargoNomeFantasia.setObjectName(_fromUtf8("lblCadCargoNomeFantasia"))
        self.btnCadCargoSalvar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoSalvar.setGeometry(QtCore.QRect(120, 370, 81, 61))
        self.btnCadCargoSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoSalvar.setObjectName(_fromUtf8("btnCadCargoSalvar"))
        self.btnCadCargoPesquisar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoPesquisar.setGeometry(QtCore.QRect(496, 50, 31, 27))
        self.btnCadCargoPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoPesquisar.setText(_fromUtf8(""))
        self.btnCadCargoPesquisar.setObjectName(_fromUtf8("btnCadCargoPesquisar"))
        self.txtCadCargoInscricaoEstadual = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoInscricaoEstadual.setEnabled(False)
        self.txtCadCargoInscricaoEstadual.setGeometry(QtCore.QRect(349, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoInscricaoEstadual.setPalette(palette)
        self.txtCadCargoInscricaoEstadual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoInscricaoEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCadCargoInscricaoEstadual.setMaxLength(8)
        self.txtCadCargoInscricaoEstadual.setObjectName(_fromUtf8("txtCadCargoInscricaoEstadual"))
        self.txtCadCargoCnpj = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoCnpj.setEnabled(False)
        self.txtCadCargoCnpj.setGeometry(QtCore.QRect(165, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCadCargoCnpj.setPalette(palette)
        self.txtCadCargoCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCadCargoCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCadCargoCnpj.setObjectName(_fromUtf8("txtCadCargoCnpj"))
        self.btnCadCargoNovo = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoNovo.setGeometry(QtCore.QRect(20, 370, 81, 61))
        self.btnCadCargoNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoNovo.setObjectName(_fromUtf8("btnCadCargoNovo"))
        self.btnCadCargoCancelar = QtGui.QPushButton(self.cadastroCargos)
        self.btnCadCargoCancelar.setGeometry(QtCore.QRect(320, 370, 81, 61))
        self.btnCadCargoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadCargoCancelar.setObjectName(_fromUtf8("btnCadCargoCancelar"))
        self.txtCadCargoCargo = QtGui.QLineEdit(self.cadastroCargos)
        self.txtCadCargoCargo.setGeometry(QtCore.QRect(2, 185, 421, 25))
        self.txtCadCargoCargo.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCadCargoCargo.setMaxLength(50)
        self.txtCadCargoCargo.setObjectName(_fromUtf8("txtCadCargoCargo"))
        self.lblCadCargoCnpj = QtGui.QLabel(self.cadastroCargos)
        self.lblCadCargoCnpj.setGeometry(QtCore.QRect(165, 82, 66, 19))
        self.lblCadCargoCnpj.setObjectName(_fromUtf8("lblCadCargoCnpj"))
        self.tabwiCadastroSetoresCargos.addTab(self.cadastroCargos, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lblRelacaoCodigo = QtGui.QLabel(self.tab)
        self.lblRelacaoCodigo.setGeometry(QtCore.QRect(5, 30, 51, 19))
        self.lblRelacaoCodigo.setObjectName(_fromUtf8("lblRelacaoCodigo"))
        self.btnRelacaoCancelar = QtGui.QPushButton(self.tab)
        self.btnRelacaoCancelar.setGeometry(QtCore.QRect(320, 370, 81, 61))
        self.btnRelacaoCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoCancelar.setObjectName(_fromUtf8("btnRelacaoCancelar"))
        self.txtRelacaoCnpj = QtGui.QLineEdit(self.tab)
        self.txtRelacaoCnpj.setEnabled(False)
        self.txtRelacaoCnpj.setGeometry(QtCore.QRect(165, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoCnpj.setPalette(palette)
        self.txtRelacaoCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRelacaoCnpj.setObjectName(_fromUtf8("txtRelacaoCnpj"))
        self.btnRelacaoDeletar = QtGui.QPushButton(self.tab)
        self.btnRelacaoDeletar.setGeometry(QtCore.QRect(420, 370, 81, 61))
        self.btnRelacaoDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoDeletar.setObjectName(_fromUtf8("btnRelacaoDeletar"))
        self.lblRelacaoIncricaoEstadual = QtGui.QLabel(self.tab)
        self.lblRelacaoIncricaoEstadual.setGeometry(QtCore.QRect(349, 82, 131, 19))
        self.lblRelacaoIncricaoEstadual.setObjectName(_fromUtf8("lblRelacaoIncricaoEstadual"))
        self.btnRelacaoPesquisar = QtGui.QPushButton(self.tab)
        self.btnRelacaoPesquisar.setGeometry(QtCore.QRect(496, 50, 31, 27))
        self.btnRelacaoPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoPesquisar.setText(_fromUtf8(""))
        self.btnRelacaoPesquisar.setObjectName(_fromUtf8("btnRelacaoPesquisar"))
        self.btnRelacaoSalvar = QtGui.QPushButton(self.tab)
        self.btnRelacaoSalvar.setGeometry(QtCore.QRect(120, 370, 81, 61))
        self.btnRelacaoSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoSalvar.setObjectName(_fromUtf8("btnRelacaoSalvar"))
        self.txtRelacaoCodigo = QtGui.QLineEdit(self.tab)
        self.txtRelacaoCodigo.setGeometry(QtCore.QRect(2, 50, 141, 25))
        self.txtRelacaoCodigo.setMaxLength(11)
        self.txtRelacaoCodigo.setObjectName(_fromUtf8("txtRelacaoCodigo"))
        self.btnRelacaoNovo = QtGui.QPushButton(self.tab)
        self.btnRelacaoNovo.setGeometry(QtCore.QRect(20, 370, 81, 61))
        self.btnRelacaoNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoNovo.setObjectName(_fromUtf8("btnRelacaoNovo"))
        self.btnRelacaoEditar = QtGui.QPushButton(self.tab)
        self.btnRelacaoEditar.setGeometry(QtCore.QRect(220, 370, 81, 61))
        self.btnRelacaoEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRelacaoEditar.setObjectName(_fromUtf8("btnRelacaoEditar"))
        self.lblRelacaoTipoEmpresa = QtGui.QLabel(self.tab)
        self.lblRelacaoTipoEmpresa.setGeometry(QtCore.QRect(3, 82, 131, 19))
        self.lblRelacaoTipoEmpresa.setObjectName(_fromUtf8("lblRelacaoTipoEmpresa"))
        self.lblRelacaoCnpj = QtGui.QLabel(self.tab)
        self.lblRelacaoCnpj.setGeometry(QtCore.QRect(165, 82, 66, 19))
        self.lblRelacaoCnpj.setObjectName(_fromUtf8("lblRelacaoCnpj"))
        self.txtRelacaoNomeFantasia = QtGui.QLineEdit(self.tab)
        self.txtRelacaoNomeFantasia.setGeometry(QtCore.QRect(147, 50, 341, 25))
        self.txtRelacaoNomeFantasia.setMaxLength(70)
        self.txtRelacaoNomeFantasia.setObjectName(_fromUtf8("txtRelacaoNomeFantasia"))
        self.txtRelacaoTipoEmpresa = QtGui.QLineEdit(self.tab)
        self.txtRelacaoTipoEmpresa.setEnabled(False)
        self.txtRelacaoTipoEmpresa.setGeometry(QtCore.QRect(1, 102, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoTipoEmpresa.setPalette(palette)
        self.txtRelacaoTipoEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoTipoEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRelacaoTipoEmpresa.setMaxLength(50)
        self.txtRelacaoTipoEmpresa.setObjectName(_fromUtf8("txtRelacaoTipoEmpresa"))
        self.txtRelacaoInscricaoEstadual = QtGui.QLineEdit(self.tab)
        self.txtRelacaoInscricaoEstadual.setEnabled(False)
        self.txtRelacaoInscricaoEstadual.setGeometry(QtCore.QRect(349, 102, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRelacaoInscricaoEstadual.setPalette(palette)
        self.txtRelacaoInscricaoEstadual.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRelacaoInscricaoEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRelacaoInscricaoEstadual.setMaxLength(8)
        self.txtRelacaoInscricaoEstadual.setObjectName(_fromUtf8("txtRelacaoInscricaoEstadual"))
        self.lblRelacaoNomeFantasia = QtGui.QLabel(self.tab)
        self.lblRelacaoNomeFantasia.setGeometry(QtCore.QRect(147, 30, 111, 19))
        self.lblRelacaoNomeFantasia.setObjectName(_fromUtf8("lblRelacaoNomeFantasia"))
        self.txtRelacaoSetor = QtGui.QComboBox(self.tab)
        self.txtRelacaoSetor.setGeometry(QtCore.QRect(10, 170, 361, 25))
        self.txtRelacaoSetor.setObjectName(_fromUtf8("txtRelacaoSetor"))
        self.txtRelacaoCargo = QtGui.QComboBox(self.tab)
        self.txtRelacaoCargo.setGeometry(QtCore.QRect(10, 250, 361, 25))
        self.txtRelacaoCargo.setObjectName(_fromUtf8("txtRelacaoCargo"))
        self.lblRelacaoSetor = QtGui.QLabel(self.tab)
        self.lblRelacaoSetor.setGeometry(QtCore.QRect(10, 150, 66, 19))
        self.lblRelacaoSetor.setObjectName(_fromUtf8("lblRelacaoSetor"))
        self.lblRelacaoCargo = QtGui.QLabel(self.tab)
        self.lblRelacaoCargo.setGeometry(QtCore.QRect(10, 230, 66, 19))
        self.lblRelacaoCargo.setObjectName(_fromUtf8("lblRelacaoCargo"))
        self.tabwiCadastroSetoresCargos.addTab(self.tab, _fromUtf8(""))
        self.lblCadSetoresCodigo.setBuddy(self.txtCadSetoresCodigo)
        self.lblCadSetoresNomeFantasia.setBuddy(self.txtCadSetoresNomeFantasia)
        self.lblCadSetoresTipoEmpresa.setBuddy(self.txtCadSetoresTipoEmpresa)
        self.lblCadSetoresCnpj.setBuddy(self.txtCadSetoresCnpj)
        self.lblCadSetoresIncricaoEstadual.setBuddy(self.txtCadSetoresInscricaoEstadual)
        self.lblCadSetoresSetor.setBuddy(self.txtCadSetoresSetor)
        self.lblCadCargoIncricaoEstadual.setBuddy(self.txtCadCargoInscricaoEstadual)
        self.lblCadCargoCargo.setBuddy(self.txtCadCargoCargo)
        self.lblCadCargoCodigo.setBuddy(self.txtCadCargoCodigo)
        self.lblCadCargoTipoEmpresa.setBuddy(self.txtCadCargoTipoEmpresa)
        self.lblCadCargoNomeFantasia.setBuddy(self.txtCadCargoNomeFantasia)
        self.lblCadCargoCnpj.setBuddy(self.txtCadCargoCnpj)
        self.lblRelacaoCodigo.setBuddy(self.txtRelacaoCodigo)
        self.lblRelacaoIncricaoEstadual.setBuddy(self.txtRelacaoInscricaoEstadual)
        self.lblRelacaoTipoEmpresa.setBuddy(self.txtRelacaoTipoEmpresa)
        self.lblRelacaoCnpj.setBuddy(self.txtRelacaoCnpj)
        self.lblRelacaoNomeFantasia.setBuddy(self.txtRelacaoNomeFantasia)
        self.lblRelacaoSetor.setBuddy(self.txtRelacaoSetor)
        self.lblRelacaoCargo.setBuddy(self.txtRelacaoCargo)

        self.retranslateUi(frmCadastroSetoresCargos)
        self.tabwiCadastroSetoresCargos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroSetoresCargos)
        frmCadastroSetoresCargos.setTabOrder(self.tabwiCadastroSetoresCargos, self.txtCadSetoresCodigo)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresCodigo, self.txtCadSetoresNomeFantasia)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresNomeFantasia, self.btnCadSetoresPesquisar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadSetoresPesquisar, self.txtCadSetoresTipoEmpresa)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresTipoEmpresa, self.txtCadSetoresCnpj)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresCnpj, self.txtCadSetoresInscricaoEstadual)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresInscricaoEstadual, self.txtCadSetoresSetor)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadSetoresSetor, self.btnCadSetoresNovo)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadSetoresNovo, self.btnCadSetoresSalvar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadSetoresSalvar, self.btnCadSetoresEditar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadSetoresEditar, self.btnCadSetoresCancelar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadSetoresCancelar, self.btnCadSetoresDeletar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadSetoresDeletar, self.txtCadCargoCodigo)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoCodigo, self.txtCadCargoNomeFantasia)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoNomeFantasia, self.btnCadCargoPesquisar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadCargoPesquisar, self.txtCadCargoTipoEmpresa)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoTipoEmpresa, self.txtCadCargoCnpj)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoCnpj, self.txtCadCargoInscricaoEstadual)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoInscricaoEstadual, self.txtCadCargoCargo)
        frmCadastroSetoresCargos.setTabOrder(self.txtCadCargoCargo, self.btnCadCargoNovo)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadCargoNovo, self.btnCadCargoSalvar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadCargoSalvar, self.btnCadCargoEditar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadCargoEditar, self.btnCadCargoCancelar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadCargoCancelar, self.btnCadCargoDeletar)
        frmCadastroSetoresCargos.setTabOrder(self.btnCadCargoDeletar, self.txtRelacaoCodigo)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoCodigo, self.txtRelacaoNomeFantasia)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoNomeFantasia, self.btnRelacaoPesquisar)
        frmCadastroSetoresCargos.setTabOrder(self.btnRelacaoPesquisar, self.txtRelacaoTipoEmpresa)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoTipoEmpresa, self.txtRelacaoCnpj)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoCnpj, self.txtRelacaoInscricaoEstadual)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoInscricaoEstadual, self.txtRelacaoSetor)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoSetor, self.txtRelacaoCargo)
        frmCadastroSetoresCargos.setTabOrder(self.txtRelacaoCargo, self.btnRelacaoNovo)
        frmCadastroSetoresCargos.setTabOrder(self.btnRelacaoNovo, self.btnRelacaoSalvar)
        frmCadastroSetoresCargos.setTabOrder(self.btnRelacaoSalvar, self.btnRelacaoEditar)
        frmCadastroSetoresCargos.setTabOrder(self.btnRelacaoEditar, self.btnRelacaoCancelar)
        frmCadastroSetoresCargos.setTabOrder(self.btnRelacaoCancelar, self.btnRelacaoDeletar)

    def retranslateUi(self, frmCadastroSetoresCargos):
        frmCadastroSetoresCargos.setWindowTitle(_translate("frmCadastroSetoresCargos", "Cadastro Setores e Cargos", None))
        self.txtCadSetoresNomeFantasia.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtCadSetoresNomeFantasia.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.txtCadSetoresCodigo.setToolTip(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.txtCadSetoresCodigo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do Codigo de identificação da empresa", None))
        self.txtCadSetoresTipoEmpresa.setToolTip(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtCadSetoresTipoEmpresa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do tipo da empresa", None))
        self.txtCadSetoresSetor.setToolTip(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.txtCadSetoresSetor.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome do setor", None))
        self.lblCadSetoresCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.lblCadSetoresNomeFantasia.setText(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.lblCadSetoresTipoEmpresa.setText(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.lblCadSetoresCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCadSetoresCnpj.setToolTip(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCadSetoresCnpj.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo numero do CNPJ da empresa", None))
        self.txtCadSetoresCnpj.setInputMask(_translate("frmCadastroSetoresCargos", "00.000.000/0000-00; ", None))
        self.lblCadSetoresIncricaoEstadual.setText(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.txtCadSetoresInscricaoEstadual.setToolTip(_translate("frmCadastroSetoresCargos", "Incrição Estadual", None))
        self.txtCadSetoresInscricaoEstadual.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do numero da iscrição estadual da empresa", None))
        self.lblCadSetoresSetor.setText(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.btnCadSetoresEditar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar edição de um registro existente", None))
        self.btnCadSetoresEditar.setText(_translate("frmCadastroSetoresCargos", "Editar", None))
        self.btnCadSetoresDeletar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de deleção de um registro existente", None))
        self.btnCadSetoresDeletar.setText(_translate("frmCadastroSetoresCargos", "Deletar", None))
        self.btnCadSetoresCancelar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de cancelar a operação iniciada", None))
        self.btnCadSetoresCancelar.setText(_translate("frmCadastroSetoresCargos", "Cancelar", None))
        self.btnCadSetoresSalvar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar um novo registro", None))
        self.btnCadSetoresSalvar.setText(_translate("frmCadastroSetoresCargos", "Salvar", None))
        self.btnCadSetoresNovo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de Criação de um novo registro", None))
        self.btnCadSetoresNovo.setText(_translate("frmCadastroSetoresCargos", "Novo", None))
        self.tabwiCadastroSetoresCargos.setTabText(self.tabwiCadastroSetoresCargos.indexOf(self.cadastroSetores), _translate("frmCadastroSetoresCargos", "Cadastro Setores", None))
        self.lblCadCargoIncricaoEstadual.setText(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.lblCadCargoCargo.setText(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.btnCadCargoEditar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar edição de um registro existente", None))
        self.btnCadCargoEditar.setText(_translate("frmCadastroSetoresCargos", "Editar", None))
        self.btnCadCargoDeletar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de deleção de um registro existente", None))
        self.btnCadCargoDeletar.setText(_translate("frmCadastroSetoresCargos", "Deletar", None))
        self.txtCadCargoTipoEmpresa.setToolTip(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtCadCargoTipoEmpresa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do tipo da empresa", None))
        self.txtCadCargoCodigo.setToolTip(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.txtCadCargoCodigo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do Codigo de identificação da empresa", None))
        self.lblCadCargoCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.lblCadCargoTipoEmpresa.setText(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtCadCargoNomeFantasia.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtCadCargoNomeFantasia.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.lblCadCargoNomeFantasia.setText(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.btnCadCargoSalvar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar um novo registro", None))
        self.btnCadCargoSalvar.setText(_translate("frmCadastroSetoresCargos", "Salvar", None))
        self.txtCadCargoInscricaoEstadual.setToolTip(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.txtCadCargoInscricaoEstadual.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do numero da iscrição estadual da empresa", None))
        self.txtCadCargoCnpj.setToolTip(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtCadCargoCnpj.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo numero do CNPJ da empresa", None))
        self.txtCadCargoCnpj.setInputMask(_translate("frmCadastroSetoresCargos", "00.000.000/0000-00; ", None))
        self.btnCadCargoNovo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de Criação de um novo registro", None))
        self.btnCadCargoNovo.setText(_translate("frmCadastroSetoresCargos", "Novo", None))
        self.btnCadCargoCancelar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de cancelar a operação iniciada", None))
        self.btnCadCargoCancelar.setText(_translate("frmCadastroSetoresCargos", "Cancelar", None))
        self.txtCadCargoCargo.setToolTip(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.txtCadCargoCargo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome do cargo", None))
        self.lblCadCargoCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.tabwiCadastroSetoresCargos.setTabText(self.tabwiCadastroSetoresCargos.indexOf(self.cadastroCargos), _translate("frmCadastroSetoresCargos", "Cadastro Cargos", None))
        self.lblRelacaoCodigo.setText(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.btnRelacaoCancelar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de cancelar a operação iniciada", None))
        self.btnRelacaoCancelar.setText(_translate("frmCadastroSetoresCargos", "Cancelar", None))
        self.txtRelacaoCnpj.setToolTip(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtRelacaoCnpj.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo numero do CNPJ da empresa", None))
        self.txtRelacaoCnpj.setInputMask(_translate("frmCadastroSetoresCargos", "00.000.000/0000-00; ", None))
        self.btnRelacaoDeletar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de deleção de um registro existente", None))
        self.btnRelacaoDeletar.setText(_translate("frmCadastroSetoresCargos", "Deletar", None))
        self.lblRelacaoIncricaoEstadual.setText(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.btnRelacaoSalvar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar um novo registro", None))
        self.btnRelacaoSalvar.setText(_translate("frmCadastroSetoresCargos", "Salvar", None))
        self.txtRelacaoCodigo.setToolTip(_translate("frmCadastroSetoresCargos", "Codigo", None))
        self.txtRelacaoCodigo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do Codigo de identificação da empresa", None))
        self.btnRelacaoNovo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão de Criação de um novo registro", None))
        self.btnRelacaoNovo.setText(_translate("frmCadastroSetoresCargos", "Novo", None))
        self.btnRelacaoEditar.setWhatsThis(_translate("frmCadastroSetoresCargos", "Botão para salvar edição de um registro existente", None))
        self.btnRelacaoEditar.setText(_translate("frmCadastroSetoresCargos", "Editar", None))
        self.lblRelacaoTipoEmpresa.setText(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.lblRelacaoCnpj.setText(_translate("frmCadastroSetoresCargos", "CNPJ", None))
        self.txtRelacaoNomeFantasia.setToolTip(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtRelacaoNomeFantasia.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do nome fantasia da empresa", None))
        self.txtRelacaoTipoEmpresa.setToolTip(_translate("frmCadastroSetoresCargos", "Tipo de Empresa", None))
        self.txtRelacaoTipoEmpresa.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do tipo da empresa", None))
        self.txtRelacaoInscricaoEstadual.setToolTip(_translate("frmCadastroSetoresCargos", "Inscrição Estadual", None))
        self.txtRelacaoInscricaoEstadual.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo do numero da iscrição estadual da empresa", None))
        self.lblRelacaoNomeFantasia.setText(_translate("frmCadastroSetoresCargos", "Nome Fantasia", None))
        self.txtRelacaoSetor.setToolTip(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.txtRelacaoSetor.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo com o nome do setores", None))
        self.txtRelacaoCargo.setToolTip(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.txtRelacaoCargo.setWhatsThis(_translate("frmCadastroSetoresCargos", "Campo com o tipo de cargos", None))
        self.lblRelacaoSetor.setText(_translate("frmCadastroSetoresCargos", "Setor", None))
        self.lblRelacaoCargo.setText(_translate("frmCadastroSetoresCargos", "Cargo", None))
        self.tabwiCadastroSetoresCargos.setTabText(self.tabwiCadastroSetoresCargos.indexOf(self.tab), _translate("frmCadastroSetoresCargos", "Relação Setores e Cargos", None))

