# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroMotorista.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroMotorista(object):
    def setupUi(self, frmCadastroMotorista):
        frmCadastroMotorista.setObjectName(_fromUtf8("frmCadastroMotorista"))
        frmCadastroMotorista.resize(685, 606)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroMotorista.setFont(font)
        #frmCadastroMotorista.setModal(True)

        self.grbFuncionario = QtGui.QGroupBox(frmCadastroMotorista)
        self.grbFuncionario.setGeometry(QtCore.QRect(5, 10, 675, 361))
        self.grbFuncionario.setObjectName(_fromUtf8("grbFuncionario"))

        self.lblNomeMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(178, 20, 121, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))

        self.txtCnh = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCnh.setGeometry(QtCore.QRect(8, 132, 221, 25))
        self.txtCnh.setMaxLength(9)
        self.txtCnh.setObjectName(_fromUtf8("txtCnh"))
        self.txtExpeditor = QtGui.QLineEdit(self.grbFuncionario)
        self.txtExpeditor.setGeometry(QtCore.QRect(216, 86, 113, 25))
        self.txtExpeditor.setMaxLength(5)
        self.txtExpeditor.setObjectName(_fromUtf8("txtExpeditor"))

        self.txtRg = QtGui.QLineEdit(self.grbFuncionario)
        self.txtRg.setGeometry(QtCore.QRect(6, 86, 201, 25))
        self.txtRg.setObjectName(_fromUtf8("txtRg"))
        self.lblDataNascimento = QtGui.QLabel(self.grbFuncionario)
        self.lblDataNascimento.setGeometry(QtCore.QRect(548, 66, 111, 19))
        self.lblDataNascimento.setObjectName(_fromUtf8("lblDataNascimento"))

        self.txtDataNascimento = QtGui.QDateEdit(self.grbFuncionario)
        self.txtDataNascimento.setGeometry(QtCore.QRect(548, 86, 119, 25))
        self.txtDataNascimento.setObjectName(_fromUtf8("txtDataNascimento"))

        self.lblCepMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblCepMotorista.setGeometry(QtCore.QRect(8, 250, 31, 19))
        self.lblCepMotorista.setObjectName(_fromUtf8("lblCepMotorista"))

        self.txtComplemento = QtGui.QLineEdit(self.grbFuncionario)
        self.txtComplemento.setGeometry(QtCore.QRect(8, 224, 291, 25))
        self.txtComplemento.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtComplemento.setMaxLength(50)
        self.txtComplemento.setObjectName(_fromUtf8("txtComplemento"))

        self.lblPisMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblPisMotorista.setGeometry(QtCore.QRect(445, 112, 31, 19))
        self.lblPisMotorista.setObjectName(_fromUtf8("lblPisMotorista"))

        self.txtCidades = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCidades.setEnabled(False)
        self.txtCidades.setGeometry(QtCore.QRect(168, 270, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidades.setPalette(palette)
        self.txtCidades.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidades.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidades.setMaxLength(70)
        self.txtCidades.setObjectName(_fromUtf8("txtCidades"))

        self.lblCpfMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblCpfMotorista.setGeometry(QtCore.QRect(338, 66, 31, 19))
        self.lblCpfMotorista.setObjectName(_fromUtf8("lblCpfMotorista"))

        self.txtPis = QtGui.QLineEdit(self.grbFuncionario)
        self.txtPis.setGeometry(QtCore.QRect(445, 132, 221, 25))
        self.txtPis.setMaxLength(9)
        self.txtPis.setObjectName(_fromUtf8("txtPis"))

        self.txtEstados = QtGui.QLineEdit(self.grbFuncionario)
        self.txtEstados.setEnabled(False)
        self.txtEstados.setGeometry(QtCore.QRect(516, 270, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstados.setPalette(palette)
        self.txtEstados.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstados.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstados.setMaxLength(50)
        self.txtEstados.setObjectName(_fromUtf8("txtEstados"))

        self.txtEndereco = QtGui.QLineEdit(self.grbFuncionario)
        self.txtEndereco.setGeometry(QtCore.QRect(8, 178, 491, 25))
        self.txtEndereco.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEndereco.setMaxLength(50)
        self.txtEndereco.setObjectName(_fromUtf8("txtEndereco"))

        self.lblExpeditorMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblExpeditorMotorista.setGeometry(QtCore.QRect(216, 66, 66, 19))
        self.lblExpeditorMotorista.setObjectName(_fromUtf8("lblExpeditorMotorista"))

        self.txtNumero = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNumero.setGeometry(QtCore.QRect(508, 178, 161, 25))
        self.txtNumero.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNumero.setObjectName(_fromUtf8("txtNumero"))

        self.lblRg = QtGui.QLabel(self.grbFuncionario)
        self.lblRg.setGeometry(QtCore.QRect(6, 66, 31, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))
        self.lblTelefoeneMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblTelefoeneMotorista.setGeometry(QtCore.QRect(8, 296, 61, 19))
        self.lblTelefoeneMotorista.setObjectName(_fromUtf8("lblTelefoeneMotorista"))

        self.txtBairro = QtGui.QLineEdit(self.grbFuncionario)
        self.txtBairro.setGeometry(QtCore.QRect(308, 224, 361, 25))
        self.txtBairro.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtBairro.setMaxLength(50)
        self.txtBairro.setObjectName(_fromUtf8("txtBairro"))

        self.txtCelular = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCelular.setGeometry(QtCore.QRect(208, 316, 191, 25))
        self.txtCelular.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCelular.setObjectName(_fromUtf8("txtCelular"))

        self.txtNomeMotorista = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(178, 40, 488, 25))
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))

        self.lblComplementoMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblComplementoMotorista.setGeometry(QtCore.QRect(8, 204, 101, 16))
        self.lblComplementoMotorista.setObjectName(_fromUtf8("lblComplementoMotorista"))

        self.lblEstadosMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblEstadosMotorista.setGeometry(QtCore.QRect(518, 250, 51, 19))
        self.lblEstadosMotorista.setObjectName(_fromUtf8("lblEstadosMotorista"))

        self.txtCpf = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCpf.setGeometry(QtCore.QRect(338, 86, 201, 25))
        self.txtCpf.setObjectName(_fromUtf8("txtCpf"))

        self.lblBairroMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblBairroMotorista.setGeometry(QtCore.QRect(308, 204, 41, 19))
        self.lblBairroMotorista.setObjectName(_fromUtf8("lblBairroMotorista"))

        self.lblCerlularMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblCerlularMotorista.setGeometry(QtCore.QRect(208, 296, 61, 19))
        self.lblCerlularMotorista.setObjectName(_fromUtf8("lblCerlularMotorista"))

        self.lblNumeroMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblNumeroMotorista.setGeometry(QtCore.QRect(508, 158, 51, 19))
        self.lblNumeroMotorista.setObjectName(_fromUtf8("lblNumeroMotorista"))

        self.lblCidadesMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblCidadesMotorista.setGeometry(QtCore.QRect(168, 250, 51, 19))
        self.lblCidadesMotorista.setObjectName(_fromUtf8("lblCidadesMotorista"))

        self.txtidMotorista = QtGui.QLineEdit(self.grbFuncionario)
        self.txtidMotorista.setEnabled(False)
        self.txtidMotorista.setGeometry(QtCore.QRect(6, 40, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidMotorista.setPalette(palette)
        self.txtidMotorista.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtidMotorista.setMaxLength(11)
        self.txtidMotorista.setObjectName(_fromUtf8("txtidMotorista"))

        self.lblCodigoMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(6, 20, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))

        self.lblEnderecoMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblEnderecoMotorista.setGeometry(QtCore.QRect(8, 158, 66, 19))
        self.lblEnderecoMotorista.setObjectName(_fromUtf8("lblEnderecoMotorista"))

        self.txtCep = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCep.setGeometry(QtCore.QRect(8, 270, 151, 25))
        self.txtCep.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCep.setInputMask(_fromUtf8("00000-000; "))

        self.txtCep.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCep.setObjectName(_fromUtf8("txtCep"))

        self.lblCnhMotorista = QtGui.QLabel(self.grbFuncionario)
        self.lblCnhMotorista.setGeometry(QtCore.QRect(8, 112, 41, 19))
        self.lblCnhMotorista.setObjectName(_fromUtf8("lblCnhMotorista"))

        self.txtTelefone = QtGui.QLineEdit(self.grbFuncionario)
        self.txtTelefone.setGeometry(QtCore.QRect(8, 316, 191, 25))
        self.txtTelefone.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtTelefone.setObjectName(_fromUtf8("txtTelefone"))

        self.lblCategoriaCnh = QtGui.QLabel(self.grbFuncionario)
        self.lblCategoriaCnh.setGeometry(QtCore.QRect(240, 110, 101, 19))
        self.lblCategoriaCnh.setObjectName(_fromUtf8("lblCategoriaCnh"))

        self.txtCategoriaCnh = QtGui.QComboBox(self.grbFuncionario)
        self.txtCategoriaCnh.setGeometry(QtCore.QRect(240, 132, 195, 25))
        self.txtCategoriaCnh.setObjectName(_fromUtf8("txtCategoriaCnh"))

        self.groupBox = QtGui.QGroupBox(frmCadastroMotorista)
        self.groupBox.setGeometry(QtCore.QRect(4, 520, 677, 81))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))

        self.btnCadSetoresSalvar = QtGui.QPushButton(self.groupBox)
        self.btnCadSetoresSalvar.setGeometry(QtCore.QRect(290, 10, 81, 61))
        self.btnCadSetoresSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresSalvar.setObjectName(_fromUtf8("btnCadSetoresSalvar"))

        self.btnCadSetoresEditar = QtGui.QPushButton(self.groupBox)
        self.btnCadSetoresEditar.setGeometry(QtCore.QRect(390, 10, 81, 61))
        self.btnCadSetoresEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresEditar.setObjectName(_fromUtf8("btnCadSetoresEditar"))

        self.btnCadSetoresDeletar = QtGui.QPushButton(self.groupBox)
        self.btnCadSetoresDeletar.setGeometry(QtCore.QRect(590, 10, 81, 61))
        self.btnCadSetoresDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresDeletar.setObjectName(_fromUtf8("btnCadSetoresDeletar"))

        self.btnCadSetoresCancelar = QtGui.QPushButton(self.groupBox)
        self.btnCadSetoresCancelar.setGeometry(QtCore.QRect(490, 10, 81, 61))
        self.btnCadSetoresCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresCancelar.setObjectName(_fromUtf8("btnCadSetoresCancelar"))

        self.btnCadSetoresNovo = QtGui.QPushButton(self.groupBox)
        self.btnCadSetoresNovo.setGeometry(QtCore.QRect(190, 10, 81, 61))
        self.btnCadSetoresNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresNovo.setObjectName(_fromUtf8("btnCadSetoresNovo"))

        self.cbCminhaoFixo = QtGui.QCheckBox(frmCadastroMotorista)
        self.cbCminhaoFixo.setGeometry(QtCore.QRect(10, 370, 101, 23))
        self.cbCminhaoFixo.setObjectName(_fromUtf8("cbCminhaoFixo"))

        self.grbVeiculo = QtGui.QGroupBox(frmCadastroMotorista)
        self.grbVeiculo.setEnabled(True)
        self.grbVeiculo.setGeometry(QtCore.QRect(5, 390, 675, 125))
        self.grbVeiculo.setObjectName(_fromUtf8("grbVeiculo"))

        self.txtModelo = QtGui.QLineEdit(self.grbVeiculo)
        self.txtModelo.setGeometry(QtCore.QRect(10, 90, 331, 25))
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))

        self.lblTipoVeiculo = QtGui.QLabel(self.grbVeiculo)
        self.lblTipoVeiculo.setGeometry(QtCore.QRect(10, 20, 111, 19))
        self.lblTipoVeiculo.setObjectName(_fromUtf8("lblTipoVeiculo"))

        self.lblModelo = QtGui.QLabel(self.grbVeiculo)
        self.lblModelo.setGeometry(QtCore.QRect(10, 70, 61, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))

        self.txtMarca = QtGui.QLineEdit(self.grbVeiculo)
        self.txtMarca.setGeometry(QtCore.QRect(230, 40, 331, 25))
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))

        self.lblMarca = QtGui.QLabel(self.grbVeiculo)
        self.lblMarca.setGeometry(QtCore.QRect(230, 20, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))

        self.txtTipoVeiculo = QtGui.QComboBox(self.grbVeiculo)
        self.txtTipoVeiculo.setGeometry(QtCore.QRect(10, 40, 211, 25))
        self.txtTipoVeiculo.setObjectName(_fromUtf8("txtTipoVeiculo"))

        self.lblPlaca = QtGui.QLabel(self.grbVeiculo)
        self.lblPlaca.setGeometry(QtCore.QRect(350, 70, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))

        self.txtPlaca = QtGui.QLineEdit(self.grbVeiculo)
        self.txtPlaca.setGeometry(QtCore.QRect(350, 90, 211, 25))
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))

        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblDataNascimento.setBuddy(self.txtDataNascimento)
        self.lblCepMotorista.setBuddy(self.txtCep)
        self.lblPisMotorista.setBuddy(self.txtPis)
        self.lblCpfMotorista.setBuddy(self.txtCpf)
        self.lblExpeditorMotorista.setBuddy(self.txtExpeditor)
        self.lblRg.setBuddy(self.txtRg)
        self.lblTelefoeneMotorista.setBuddy(self.txtTelefone)
        self.lblComplementoMotorista.setBuddy(self.txtComplemento)
        self.lblEstadosMotorista.setBuddy(self.txtEstados)
        self.lblBairroMotorista.setBuddy(self.txtBairro)
        self.lblCerlularMotorista.setBuddy(self.txtCelular)
        self.lblNumeroMotorista.setBuddy(self.txtNumero)
        self.lblCidadesMotorista.setBuddy(self.txtCidades)
        self.lblCodigoMotorista.setBuddy(self.txtidMotorista)
        self.lblEnderecoMotorista.setBuddy(self.txtEndereco)
        self.lblCnhMotorista.setBuddy(self.txtCnh)
        self.lblCategoriaCnh.setBuddy(self.txtPis)
        self.lblTipoVeiculo.setBuddy(self.txtTipoVeiculo)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblPlaca.setBuddy(self.txtPlaca)

        self.retranslateUi(frmCadastroMotorista)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroMotorista)
        frmCadastroMotorista.setTabOrder(self.txtNomeMotorista, self.txtRg)
        frmCadastroMotorista.setTabOrder(self.txtRg, self.txtExpeditor)
        frmCadastroMotorista.setTabOrder(self.txtExpeditor, self.txtCpf)
        frmCadastroMotorista.setTabOrder(self.txtCpf, self.txtDataNascimento)
        frmCadastroMotorista.setTabOrder(self.txtDataNascimento, self.txtCnh)
        frmCadastroMotorista.setTabOrder(self.txtCnh, self.txtPis)
        frmCadastroMotorista.setTabOrder(self.txtPis, self.txtEndereco)
        frmCadastroMotorista.setTabOrder(self.txtEndereco, self.txtNumero)
        frmCadastroMotorista.setTabOrder(self.txtNumero, self.txtComplemento)
        frmCadastroMotorista.setTabOrder(self.txtComplemento, self.txtBairro)
        frmCadastroMotorista.setTabOrder(self.txtBairro, self.txtCep)
        frmCadastroMotorista.setTabOrder(self.txtCep, self.txtCidades)
        frmCadastroMotorista.setTabOrder(self.txtCidades, self.txtEstados)
        frmCadastroMotorista.setTabOrder(self.txtEstados, self.txtTelefone)
        frmCadastroMotorista.setTabOrder(self.txtTelefone, self.txtCelular)
        frmCadastroMotorista.setTabOrder(self.txtCelular, self.cbCminhaoFixo)
        frmCadastroMotorista.setTabOrder(self.cbCminhaoFixo, self.txtTipoVeiculo)
        frmCadastroMotorista.setTabOrder(self.txtTipoVeiculo, self.txtMarca)
        frmCadastroMotorista.setTabOrder(self.txtMarca, self.txtModelo)
        frmCadastroMotorista.setTabOrder(self.txtModelo, self.txtPlaca)
        frmCadastroMotorista.setTabOrder(self.txtPlaca, self.txtCnh)
        frmCadastroMotorista.setTabOrder(self.txtCnh, self.txtExpeditor)
        frmCadastroMotorista.setTabOrder(self.txtExpeditor, self.txtRg)
        frmCadastroMotorista.setTabOrder(self.txtRg, self.txtDataNascimento)
        frmCadastroMotorista.setTabOrder(self.txtDataNascimento, self.txtComplemento)
        frmCadastroMotorista.setTabOrder(self.txtComplemento, self.txtCidades)
        frmCadastroMotorista.setTabOrder(self.txtCidades, self.txtPis)
        frmCadastroMotorista.setTabOrder(self.txtPis, self.txtEstados)
        frmCadastroMotorista.setTabOrder(self.txtEstados, self.txtEndereco)
        frmCadastroMotorista.setTabOrder(self.txtEndereco, self.txtNumero)
        frmCadastroMotorista.setTabOrder(self.txtNumero, self.txtBairro)
        frmCadastroMotorista.setTabOrder(self.txtBairro, self.txtCelular)
        frmCadastroMotorista.setTabOrder(self.txtCelular, self.txtNomeMotorista)
        frmCadastroMotorista.setTabOrder(self.txtNomeMotorista, self.txtCpf)
        frmCadastroMotorista.setTabOrder(self.txtCpf, self.txtCep)
        frmCadastroMotorista.setTabOrder(self.txtCep, self.txtTelefone)

    def retranslateUi(self, frmCadastroMotorista):
        frmCadastroMotorista.setWindowTitle(_translate("frmCadastroMotorista", "Cadastro de Motoristas", None))
        self.grbFuncionario.setTitle(_translate("frmCadastroMotorista", "Dados Motoristas", None))
        self.lblNomeMotorista.setText(_translate("frmCadastroMotorista", "Nome Motorista", None))
        self.txtCnh.setToolTip(_translate("frmCadastroMotorista", "CNH", None))
        self.txtCnh.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero de identificação CNH", None))
        self.txtExpeditor.setToolTip(_translate("frmCadastroMotorista", "Expeditor", None))
        self.txtExpeditor.setWhatsThis(_translate("frmCadastroMotorista", "Campo do orgão expeditor do RG", None))
        self.txtRg.setToolTip(_translate("frmCadastroMotorista", "Rg", None))
        self.txtRg.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero do RG do Motorista", None))
        self.txtRg.setInputMask(_translate("frmCadastroMotorista", "000000-0; ", None))
        self.lblDataNascimento.setText(_translate("frmCadastroMotorista", "Data Nascimento", None))
        self.txtDataNascimento.setToolTip(_translate("frmCadastroMotorista", "Data Nascimento", None))
        self.txtDataNascimento.setWhatsThis(_translate("frmCadastroMotorista", "Campo da data de nacimento do Motorista", None))
        self.lblCepMotorista.setText(_translate("frmCadastroMotorista", "CEP", None))
        self.txtComplemento.setToolTip(_translate("frmCadastroMotorista", "Complemento", None))
        self.txtComplemento.setWhatsThis(_translate("frmCadastroMotorista", "Campo complementar do endereço", None))
        self.lblPisMotorista.setText(_translate("frmCadastroMotorista", "PIS", None))
        self.txtCidades.setToolTip(_translate("frmCadastroMotorista", "Cidade", None))
        self.txtCidades.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblCpfMotorista.setText(_translate("frmCadastroMotorista", "CPF", None))
        self.txtPis.setToolTip(_translate("frmCadastroMotorista", "PIS", None))
        self.txtPis.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero do PIS", None))
        self.txtEstados.setToolTip(_translate("frmCadastroMotorista", "Estado", None))
        self.txtEstados.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome do estado de localização do endereço", None))
        self.txtEndereco.setToolTip(_translate("frmCadastroMotorista", "Endereço", None))
        self.txtEndereco.setWhatsThis(_translate("frmCadastroMotorista", "Campo de descrição do endereço", None))
        self.lblExpeditorMotorista.setText(_translate("frmCadastroMotorista", "Expeditor", None))
        self.txtNumero.setToolTip(_translate("frmCadastroMotorista", "Numero", None))
        self.txtNumero.setWhatsThis(_translate("frmCadastroMotorista", "Campo de numero referente ao numero do endereço", None))
        self.lblRg.setText(_translate("frmCadastroMotorista", "RG", None))
        self.lblTelefoeneMotorista.setText(_translate("frmCadastroMotorista", "Telefone", None))
        self.txtBairro.setToolTip(_translate("frmCadastroMotorista", "Bairro", None))
        self.txtBairro.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome do bairro referente ao endereço", None))
        self.txtCelular.setToolTip(_translate("frmCadastroMotorista", "Celular", None))
        self.txtCelular.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero de cantato de celular do funcionario", None))
        self.txtCelular.setInputMask(_translate("frmCadastroMotorista", "(00) 00000-0000; ", None))
        self.txtNomeMotorista.setToolTip(_translate("frmCadastroMotorista", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome do Motorista", None))
        self.lblComplementoMotorista.setText(_translate("frmCadastroMotorista", "Complemento", None))
        self.lblEstadosMotorista.setText(_translate("frmCadastroMotorista", "Estado", None))
        self.txtCpf.setToolTip(_translate("frmCadastroMotorista", "CPF", None))
        self.txtCpf.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero do CPF do Motorista", None))
        self.txtCpf.setInputMask(_translate("frmCadastroMotorista", "000.000.000-00; ", None))
        self.lblBairroMotorista.setText(_translate("frmCadastroMotorista", "Bairro", None))
        self.lblCerlularMotorista.setText(_translate("frmCadastroMotorista", "Celular", None))
        self.lblNumeroMotorista.setText(_translate("frmCadastroMotorista", "Numero", None))
        self.lblCidadesMotorista.setText(_translate("frmCadastroMotorista", "Cidade", None))
        self.txtidMotorista.setToolTip(_translate("frmCadastroMotorista", "Codigo Motorista", None))
        self.txtidMotorista.setWhatsThis(_translate("frmCadastroMotorista", "Campo do Codigo de identificação do Motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmCadastroMotorista", "Codigo Motorista", None))
        self.lblEnderecoMotorista.setText(_translate("frmCadastroMotorista", "Endereço", None))
        self.txtCep.setToolTip(_translate("frmCadastroMotorista", "CEP", None))
        self.txtCep.setWhatsThis(_translate("frmCadastroMotorista", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.lblCnhMotorista.setText(_translate("frmCadastroMotorista", "CNH", None))
        self.txtTelefone.setToolTip(_translate("frmCadastroMotorista", "Telefone", None))
        self.txtTelefone.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero de cantato de telefone da funcionario", None))
        self.txtTelefone.setInputMask(_translate("frmCadastroMotorista", "(00) 0000-0000; ", None))
        self.lblCategoriaCnh.setText(_translate("frmCadastroMotorista", "Categoria CNH", None))
        self.btnCadSetoresSalvar.setWhatsThis(_translate("frmCadastroMotorista", "Botão para salvar um novo registro", None))
        self.btnCadSetoresSalvar.setText(_translate("frmCadastroMotorista", "Salvar", None))
        self.btnCadSetoresEditar.setWhatsThis(_translate("frmCadastroMotorista", "Botão para salvar edição de um registro existente", None))
        self.btnCadSetoresEditar.setText(_translate("frmCadastroMotorista", "Editar", None))
        self.btnCadSetoresDeletar.setWhatsThis(_translate("frmCadastroMotorista", "Botão de deleção de um registro existente", None))
        self.btnCadSetoresDeletar.setText(_translate("frmCadastroMotorista", "Deletar", None))
        self.btnCadSetoresCancelar.setWhatsThis(_translate("frmCadastroMotorista", "Botão de cancelar a operação iniciada", None))
        self.btnCadSetoresCancelar.setText(_translate("frmCadastroMotorista", "Cancelar", None))
        self.btnCadSetoresNovo.setWhatsThis(_translate("frmCadastroMotorista", "Botão de Criação de um novo registro", None))
        self.btnCadSetoresNovo.setText(_translate("frmCadastroMotorista", "Novo", None))
        self.cbCminhaoFixo.setText(_translate("frmCadastroMotorista", "Veiculo Fixo", None))
        self.grbVeiculo.setTitle(_translate("frmCadastroMotorista", "Veiculo", None))
        self.txtModelo.setToolTip(_translate("frmCadastroMotorista", "Modelo", None))
        self.txtModelo.setWhatsThis(_translate("frmCadastroMotorista", "Campo com o nome do modelo do veiculo", None))
        self.lblTipoVeiculo.setText(_translate("frmCadastroMotorista", "Tipo de Veiculo", None))
        self.lblModelo.setText(_translate("frmCadastroMotorista", "Modelo", None))
        self.txtMarca.setToolTip(_translate("frmCadastroMotorista", "Marca", None))
        self.txtMarca.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome da marca do veiculo", None))
        self.lblMarca.setText(_translate("frmCadastroMotorista", "Marca", None))
        self.txtTipoVeiculo.setToolTip(_translate("frmCadastroMotorista", "Tipo de Veiculo", None))
        self.txtTipoVeiculo.setWhatsThis(_translate("frmCadastroMotorista", "Campo de escolha do tipo de veiculo", None))
        self.lblPlaca.setText(_translate("frmCadastroMotorista", "Placa", None))
        self.txtPlaca.setToolTip(_translate("frmCadastroMotorista", "Placa", None))
        self.txtPlaca.setWhatsThis(_translate("frmCadastroMotorista", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmCadastroMotorista", "nnn-0000; ", None))
        self.txtPlaca.setText(_translate("frmCadastroMotorista", "-", None))

