# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroFornecedor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroFornecedor(object):
    def setupUi(self, frmCadastroFornecedor):
        frmCadastroFornecedor.setObjectName(_fromUtf8("frmCadastroFornecedor"))
        frmCadastroFornecedor.resize(895, 695)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroFornecedor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/supplier.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCadastroFornecedor.setWindowIcon(icon)
        frmCadastroFornecedor.setSizeGripEnabled(False)
        frmCadastroFornecedor.setModal(True)

        self.grbBotoes = QtGui.QGroupBox(frmCadastroFornecedor)
        self.grbBotoes.setGeometry(QtCore.QRect(7, 610, 881, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(370, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(670, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(770, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(470, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(570, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.grbDadosFornecedor = QtGui.QGroupBox(frmCadastroFornecedor)
        self.grbDadosFornecedor.setEnabled(False)
        self.grbDadosFornecedor.setGeometry(QtCore.QRect(7, 112, 881, 291))
        self.grbDadosFornecedor.setObjectName(_fromUtf8("grbDadosFornecedor"))

        self.lblCepFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblCepFornecedor.setGeometry(QtCore.QRect(368, 149, 31, 19))
        self.lblCepFornecedor.setObjectName(_fromUtf8("lblCepFornecedor"))

        self.txtCidadesFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtCidadesFornecedor.setEnabled(False)
        self.txtCidadesFornecedor.setGeometry(QtCore.QRect(532, 169, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadesFornecedor.setPalette(palette)
        self.txtCidadesFornecedor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidadesFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidadesFornecedor.setMaxLength(70)
        self.txtCidadesFornecedor.setObjectName(_fromUtf8("txtCidadesFornecedor"))

        self.lblBairroFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblBairroFornecedor.setGeometry(QtCore.QRect(8, 149, 41, 19))
        self.lblBairroFornecedor.setObjectName(_fromUtf8("lblBairroFornecedor"))

        self.lblComplementoFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblComplementoFornecedor.setGeometry(QtCore.QRect(602, 105, 101, 16))
        self.lblComplementoFornecedor.setObjectName(_fromUtf8("lblComplementoFornecedor"))

        self.txtTelefoneFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtTelefoneFornecedor.setGeometry(QtCore.QRect(222, 213, 191, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTelefoneFornecedor.setPalette(palette)
        self.txtTelefoneFornecedor.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtTelefoneFornecedor.setObjectName(_fromUtf8("txtTelefoneFornecedor"))

        self.txtCnpjFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtCnpjFornecedor.setGeometry(QtCore.QRect(188, 36, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjFornecedor.setPalette(palette)
        self.txtCnpjFornecedor.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjFornecedor.setText(_fromUtf8("../-"))
        self.txtCnpjFornecedor.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjFornecedor.setObjectName(_fromUtf8("txtCnpjFornecedor"))

        self.lblRazaoSocialFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblRazaoSocialFornecedor.setGeometry(QtCore.QRect(452, 60, 81, 19))
        self.lblRazaoSocialFornecedor.setObjectName(_fromUtf8("lblRazaoSocialFornecedor"))

        self.lblCnpjFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblCnpjFornecedor.setGeometry(QtCore.QRect(188, 16, 41, 19))
        self.lblCnpjFornecedor.setObjectName(_fromUtf8("lblCnpjFornecedor"))

        self.txtRazaoSocialFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtRazaoSocialFornecedor.setGeometry(QtCore.QRect(452, 80, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialFornecedor.setPalette(palette)
        self.txtRazaoSocialFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialFornecedor.setMaxLength(70)
        self.txtRazaoSocialFornecedor.setObjectName(_fromUtf8("txtRazaoSocialFornecedor"))
        self.txtCepFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtCepFornecedor.setGeometry(QtCore.QRect(368, 169, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepFornecedor.setPalette(palette)
        self.txtCepFornecedor.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCepFornecedor.setInputMask(_fromUtf8("00000-000; "))

        self.txtCepFornecedor.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCepFornecedor.setObjectName(_fromUtf8("txtCepFornecedor"))

        self.lblEnderecoFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblEnderecoFornecedor.setGeometry(QtCore.QRect(8, 105, 66, 19))
        self.lblEnderecoFornecedor.setObjectName(_fromUtf8("lblEnderecoFornecedor"))

        self.txtComplementoFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtComplementoFornecedor.setGeometry(QtCore.QRect(602, 125, 271, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoFornecedor.setPalette(palette)
        self.txtComplementoFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtComplementoFornecedor.setMaxLength(50)
        self.txtComplementoFornecedor.setObjectName(_fromUtf8("txtComplementoFornecedor"))

        self.txtEstadosFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtEstadosFornecedor.setEnabled(False)
        self.txtEstadosFornecedor.setGeometry(QtCore.QRect(8, 213, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadosFornecedor.setPalette(palette)
        self.txtEstadosFornecedor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstadosFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstadosFornecedor.setMaxLength(50)
        self.txtEstadosFornecedor.setObjectName(_fromUtf8("txtEstadosFornecedor"))

        self.txtNumeroFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtNumeroFornecedor.setGeometry(QtCore.QRect(436, 125, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroFornecedor.setPalette(palette)
        self.txtNumeroFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNumeroFornecedor.setMaxLength(11)
        self.txtNumeroFornecedor.setObjectName(_fromUtf8("txtNumeroFornecedor"))

        self.lblNomeFantasiaFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblNomeFantasiaFornecedor.setGeometry(QtCore.QRect(8, 60, 101, 19))
        self.lblNomeFantasiaFornecedor.setObjectName(_fromUtf8("lblNomeFantasiaFornecedor"))

        self.txtBairroFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtBairroFornecedor.setGeometry(QtCore.QRect(8, 169, 351, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroFornecedor.setPalette(palette)
        self.txtBairroFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtBairroFornecedor.setMaxLength(50)
        self.txtBairroFornecedor.setObjectName(_fromUtf8("txtBairroFornecedor"))

        self.txtInscricaoEstadualFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtInscricaoEstadualFornecedor.setGeometry(QtCore.QRect(398, 36, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstadualFornecedor.setPalette(palette)
        self.txtInscricaoEstadualFornecedor.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadualFornecedor.setMaxLength(8)
        self.txtInscricaoEstadualFornecedor.setObjectName(_fromUtf8("txtInscricaoEstadualFornecedor"))

        self.lblTelefoeneFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblTelefoeneFornecedor.setGeometry(QtCore.QRect(222, 193, 61, 19))
        self.lblTelefoeneFornecedor.setObjectName(_fromUtf8("lblTelefoeneFornecedor"))

        self.lblNumeroFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblNumeroFornecedor.setGeometry(QtCore.QRect(436, 105, 51, 19))
        self.lblNumeroFornecedor.setObjectName(_fromUtf8("lblNumeroFornecedor"))

        self.txtEnderecoFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtEnderecoFornecedor.setGeometry(QtCore.QRect(8, 125, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoFornecedor.setPalette(palette)
        self.txtEnderecoFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEnderecoFornecedor.setMaxLength(50)
        self.txtEnderecoFornecedor.setObjectName(_fromUtf8("txtEnderecoFornecedor"))

        self.txtFantasiaFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtFantasiaFornecedor.setGeometry(QtCore.QRect(8, 80, 431, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasiaFornecedor.setPalette(palette)
        self.txtFantasiaFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasiaFornecedor.setMaxLength(70)
        self.txtFantasiaFornecedor.setObjectName(_fromUtf8("txtFantasiaFornecedor"))

        self.lblCidadesFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblCidadesFornecedor.setGeometry(QtCore.QRect(532, 149, 51, 19))
        self.lblCidadesFornecedor.setObjectName(_fromUtf8("lblCidadesFornecedor"))

        self.lblEstadosFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblEstadosFornecedor.setGeometry(QtCore.QRect(10, 193, 51, 19))
        self.lblEstadosFornecedor.setObjectName(_fromUtf8("lblEstadosFornecedor"))

        self.lblInscricaoEstadualFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblInscricaoEstadualFornecedor.setGeometry(QtCore.QRect(398, 16, 121, 19))
        self.lblInscricaoEstadualFornecedor.setObjectName(_fromUtf8("lblInscricaoEstadualFornecedor"))

        self.txtIdFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtIdFornecedor.setEnabled(False)
        self.txtIdFornecedor.setGeometry(QtCore.QRect(6, 36, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdFornecedor.setPalette(palette)
        self.txtIdFornecedor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdFornecedor.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdFornecedor.setMaxLength(11)
        self.txtIdFornecedor.setObjectName(_fromUtf8("txtIdFornecedor"))

        self.lblCodigoFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblCodigoFornecedor.setGeometry(QtCore.QRect(6, 16, 51, 19))
        self.lblCodigoFornecedor.setObjectName(_fromUtf8("lblCodigoFornecedor"))

        self.txtSiteFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtSiteFornecedor.setGeometry(QtCore.QRect(420, 213, 451, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSiteFornecedor.setPalette(palette)
        self.txtSiteFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtSiteFornecedor.setMaxLength(50)
        self.txtSiteFornecedor.setObjectName(_fromUtf8("txtSiteFornecedor"))

        self.lblSiteFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblSiteFornecedor.setGeometry(QtCore.QRect(420, 193, 31, 19))
        self.lblSiteFornecedor.setObjectName(_fromUtf8("lblSiteFornecedor"))

        self.lblEmailFornecedor = QtGui.QLabel(self.grbDadosFornecedor)
        self.lblEmailFornecedor.setGeometry(QtCore.QRect(10, 240, 41, 19))
        self.lblEmailFornecedor.setObjectName(_fromUtf8("lblEmailFornecedor"))

        self.txtEmailFornecedor = QtGui.QLineEdit(self.grbDadosFornecedor)
        self.txtEmailFornecedor.setGeometry(QtCore.QRect(10, 260, 451, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEmailFornecedor.setPalette(palette)
        self.txtEmailFornecedor.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEmailFornecedor.setMaxLength(50)
        self.txtEmailFornecedor.setObjectName(_fromUtf8("txtEmailFornecedor"))

        self.grbPesquisarEmpresa = QtGui.QGroupBox(frmCadastroFornecedor)
        self.grbPesquisarEmpresa.setGeometry(QtCore.QRect(8, 0, 880, 114))
        self.grbPesquisarEmpresa.setObjectName(_fromUtf8("grbPesquisarEmpresa"))

        self.txtCnpjEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtCnpjEmpresa.setEnabled(False)
        self.txtCnpjEmpresa.setGeometry(QtCore.QRect(501, 82, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmpresa.setPalette(palette)
        self.txtCnpjEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpjEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCnpjEmpresa.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmpresa.setText(_fromUtf8("../-"))
        self.txtCnpjEmpresa.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmpresa.setObjectName(_fromUtf8("txtCnpjEmpresa"))

        self.lblCodigoEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblCodigoEmpresa.setGeometry(QtCore.QRect(10, 17, 51, 19))
        self.lblCodigoEmpresa.setObjectName(_fromUtf8("lblCodigoEmpresa"))

        self.lblNomeFantasiaEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblNomeFantasiaEmpresa.setGeometry(QtCore.QRect(197, 17, 101, 19))
        self.lblNomeFantasiaEmpresa.setObjectName(_fromUtf8("lblNomeFantasiaEmpresa"))

        self.lblCnpjEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblCnpjEmpresa.setGeometry(QtCore.QRect(501, 62, 41, 19))
        self.lblCnpjEmpresa.setObjectName(_fromUtf8("lblCnpjEmpresa"))

        self.txtFantasiaEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtFantasiaEmpresa.setEnabled(False)
        self.txtFantasiaEmpresa.setGeometry(QtCore.QRect(197, 37, 631, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasiaEmpresa.setPalette(palette)
        self.txtFantasiaEmpresa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasiaEmpresa.setMaxLength(70)
        self.txtFantasiaEmpresa.setObjectName(_fromUtf8("txtFantasiaEmpresa"))

        self.txtRazaoSocialEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtRazaoSocialEmpresa.setEnabled(False)
        self.txtRazaoSocialEmpresa.setGeometry(QtCore.QRect(10, 82, 482, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmpresa.setPalette(palette)
        self.txtRazaoSocialEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocialEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRazaoSocialEmpresa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmpresa.setMaxLength(70)
        self.txtRazaoSocialEmpresa.setObjectName(_fromUtf8("txtRazaoSocialEmpresa"))

        self.lblRazaoSocialEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblRazaoSocialEmpresa.setGeometry(QtCore.QRect(10, 62, 81, 19))
        self.lblRazaoSocialEmpresa.setObjectName(_fromUtf8("lblRazaoSocialEmpresa"))

        self.txtIdEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtIdEmpresa.setEnabled(False)
        self.txtIdEmpresa.setGeometry(QtCore.QRect(10, 37, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresa.setPalette(palette)
        self.txtIdEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdEmpresa.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdEmpresa.setMaxLength(11)
        self.txtIdEmpresa.setObjectName(_fromUtf8("txtIdEmpresa"))

        self.txtInscricaoEstaduaEmpresa = QtGui.QLineEdit(self.grbPesquisarEmpresa)
        self.txtInscricaoEstaduaEmpresa.setEnabled(False)
        self.txtInscricaoEstaduaEmpresa.setGeometry(QtCore.QRect(689, 82, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmpresa.setPalette(palette)
        self.txtInscricaoEstaduaEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstaduaEmpresa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtInscricaoEstaduaEmpresa.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmpresa.setMaxLength(8)
        self.txtInscricaoEstaduaEmpresa.setObjectName(_fromUtf8("txtInscricaoEstaduaEmpresa"))

        self.lblInscricaoEstadualEmpresa = QtGui.QLabel(self.grbPesquisarEmpresa)
        self.lblInscricaoEstadualEmpresa.setGeometry(QtCore.QRect(689, 62, 121, 19))
        self.lblInscricaoEstadualEmpresa.setObjectName(_fromUtf8("lblInscricaoEstadualEmpresa"))

        self.btnPesquisar = QtGui.QPushButton(self.grbPesquisarEmpresa)
        self.btnPesquisar.setGeometry(QtCore.QRect(837, 40, 31, 27))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.grbPesquisa = QtGui.QGroupBox(frmCadastroFornecedor)
        self.grbPesquisa.setGeometry(QtCore.QRect(7, 406, 881, 201))
        self.grbPesquisa.setTitle(_fromUtf8(""))
        self.grbPesquisa.setObjectName(_fromUtf8("grbPesquisa"))
        self.txtPesquisa = QtGui.QLineEdit(self.grbPesquisa)
        self.txtPesquisa.setGeometry(QtCore.QRect(470, 14, 351, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisa.setPalette(palette)
        self.txtPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPesquisa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtPesquisa.setMaxLength(50)
        self.txtPesquisa.setObjectName(_fromUtf8("txtPesquisa"))
        self.btnPesquisarFornecedor = QtGui.QPushButton(self.grbPesquisa)
        self.btnPesquisarFornecedor.setGeometry(QtCore.QRect(830, 12, 41, 31))
        self.btnPesquisarFornecedor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarFornecedor.setText(_fromUtf8(""))
        self.btnPesquisarFornecedor.setObjectName(_fromUtf8("btnPesquisarFornecedor"))

        self.tbPesquisa = QtGui.QTableWidget(self.grbPesquisa)
        self.tbPesquisa.setGeometry(QtCore.QRect(10, 50, 861, 141))
        self.tbPesquisa.setColumnCount(20)
        self.tbPesquisa.setHorizontalHeaderLabels(['COD.', 'Fornecedor', 'Razão Social', 'CNPJ', 'Ins. Estadual', 'Endereco', 'Numero', 'Complemento', 'Bairro', 'Telefone', 'Site', 'E-mail', 'Cep', 'Cidade', 'Estado', 'COD', 'Empresa', 'Razão Social', 'CNPJ', 'Ins. Estadua'])
        self.tbPesquisa.setEditTriggers(self.tbPesquisa.NoEditTriggers)
        self.tbPesquisa.setSelectionBehavior(self.tbPesquisa.SelectRows)
        self.tbPesquisa.setSelectionMode(self.tbPesquisa.SingleSelection)
        self.tbPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbPesquisa.setObjectName(_fromUtf8("tbPesquisa"))

        self.grbDadosPesquisa = QtGui.QGroupBox(self.grbPesquisa)
        self.grbDadosPesquisa.setGeometry(QtCore.QRect(3, 0, 451, 44))
        self.grbDadosPesquisa.setObjectName(_fromUtf8("grbDadosPesquisa"))

        self.radBtnCodigo = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCodigo.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radBtnCodigo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCodigo.setObjectName(_fromUtf8("radBtnCodigo"))
        self.radBtnFantasia = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnFantasia.setGeometry(QtCore.QRect(80, 20, 71, 17))
        self.radBtnFantasia.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnFantasia.setObjectName(_fromUtf8("radBtnFantasia"))
        self.radBtnRazaoSocial = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnRazaoSocial.setGeometry(QtCore.QRect(160, 20, 101, 17))
        self.radBtnRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnRazaoSocial.setObjectName(_fromUtf8("radBtnRazaoSocial"))
        self.radBtnCnpj = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCnpj.setGeometry(QtCore.QRect(270, 20, 51, 17))
        self.radBtnCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCnpj.setObjectName(_fromUtf8("radBtnCnpj"))
        self.radBtnInsEstadual = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnInsEstadual.setGeometry(QtCore.QRect(330, 20, 91, 17))
        self.radBtnInsEstadual.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnInsEstadual.setObjectName(_fromUtf8("radBtnInsEstadual"))
        self.lblCepFornecedor.setBuddy(self.txtCepFornecedor)
        self.lblBairroFornecedor.setBuddy(self.txtBairroFornecedor)
        self.lblComplementoFornecedor.setBuddy(self.txtComplementoFornecedor)
        self.lblRazaoSocialFornecedor.setBuddy(self.txtRazaoSocialFornecedor)
        self.lblCnpjFornecedor.setBuddy(self.txtCnpjFornecedor)
        self.lblEnderecoFornecedor.setBuddy(self.txtEnderecoFornecedor)
        self.lblNomeFantasiaFornecedor.setBuddy(self.txtFantasiaFornecedor)
        self.lblTelefoeneFornecedor.setBuddy(self.txtTelefoneFornecedor)
        self.lblNumeroFornecedor.setBuddy(self.txtNumeroFornecedor)
        self.lblCidadesFornecedor.setBuddy(self.txtCidadesFornecedor)
        self.lblEstadosFornecedor.setBuddy(self.txtEstadosFornecedor)
        self.lblInscricaoEstadualFornecedor.setBuddy(self.txtInscricaoEstadualFornecedor)
        self.lblCodigoFornecedor.setBuddy(self.txtIdFornecedor)
        self.lblSiteFornecedor.setBuddy(self.txtSiteFornecedor)
        self.lblEmailFornecedor.setBuddy(self.txtEmailFornecedor)
        self.lblCodigoEmpresa.setBuddy(self.txtIdEmpresa)
        self.lblNomeFantasiaEmpresa.setBuddy(self.txtFantasiaEmpresa)
        self.lblCnpjEmpresa.setBuddy(self.txtCnpjEmpresa)
        self.lblRazaoSocialEmpresa.setBuddy(self.txtRazaoSocialEmpresa)
        self.lblInscricaoEstadualEmpresa.setBuddy(self.txtInscricaoEstaduaEmpresa)

        self.retranslateUi(frmCadastroFornecedor)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtIdEmpresa, self.txtFantasiaEmpresa)
        frmCadastroFornecedor.setTabOrder(self.txtFantasiaEmpresa, self.txtIdFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtIdFornecedor, self.txtCnpjFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtCnpjFornecedor, self.txtInscricaoEstadualFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtInscricaoEstadualFornecedor, self.txtFantasiaFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtFantasiaFornecedor, self.txtRazaoSocialFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtRazaoSocialFornecedor, self.txtEnderecoFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtEnderecoFornecedor, self.txtNumeroFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtNumeroFornecedor, self.txtComplementoFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtComplementoFornecedor, self.txtBairroFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtBairroFornecedor, self.txtCepFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtCepFornecedor, self.txtCidadesFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtCidadesFornecedor, self.txtEstadosFornecedor)
        frmCadastroFornecedor.setTabOrder(self.txtEstadosFornecedor, self.txtTelefoneFornecedor)

    def retranslateUi(self, frmCadastroFornecedor):
        frmCadastroFornecedor.setWindowTitle(_translate("frmCadastroFornecedor", "Cadastro Fornecedor", None))
        self.grbBotoes.setWhatsThis(_translate("frmCadastroFornecedor", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmCadastroFornecedor", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmCadastroFornecedor", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmCadastroFornecedor", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmCadastroFornecedor", "Cancelar", None))
        self.btnDeletar.setWhatsThis(_translate("frmCadastroFornecedor", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmCadastroFornecedor", "Deletar", None))
        self.btnSalvar.setWhatsThis(_translate("frmCadastroFornecedor", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmCadastroFornecedor", "Salvar", None))
        self.btnEditar.setWhatsThis(_translate("frmCadastroFornecedor", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmCadastroFornecedor", "Editar", None))
        self.grbDadosFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Grupo de Dados para cadastro e edição de empresas", None))
        self.grbDadosFornecedor.setTitle(_translate("frmCadastroFornecedor", "Dados Fornecedor", None))
        self.lblCepFornecedor.setText(_translate("frmCadastroFornecedor", "CEP", None))
        self.txtCidadesFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Cidade fornecedor", None))
        self.txtCidadesFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblBairroFornecedor.setText(_translate("frmCadastroFornecedor", "Bairro", None))
        self.lblComplementoFornecedor.setText(_translate("frmCadastroFornecedor", "Complemento", None))
        self.txtTelefoneFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Telefone fornecedor", None))
        self.txtTelefoneFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do numero de cantato de telefone da fornecedor", None))
        self.txtTelefoneFornecedor.setInputMask(_translate("frmCadastroFornecedor", "(00)00000-0000; ", None))
        self.txtCnpjFornecedor.setToolTip(_translate("frmCadastroFornecedor", "CNPJ fornecedor", None))
        self.txtCnpjFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do numero do CNPJ da fornecedor", None))
        self.txtCnpjFornecedor.setInputMask(_translate("frmCadastroFornecedor", "00.000.000/0000-00; ", None))
        self.lblRazaoSocialFornecedor.setText(_translate("frmCadastroFornecedor", "Razão Social", None))
        self.lblCnpjFornecedor.setText(_translate("frmCadastroFornecedor", "CNPJ", None))
        self.txtRazaoSocialFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Razão Social fornecedor", None))
        self.txtRazaoSocialFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome da razão social da fornecedor", None))
        self.txtCepFornecedor.setToolTip(_translate("frmCadastroFornecedor", "CEP fornecedor", None))
        self.txtCepFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.lblEnderecoFornecedor.setText(_translate("frmCadastroFornecedor", "Endereço", None))
        self.txtComplementoFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Complemento fornecedor", None))
        self.txtComplementoFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo complementar do endereço", None))
        self.txtEstadosFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Estado fornecedor", None))
        self.txtEstadosFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome do estado de localização do endereço", None))
        self.txtNumeroFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Numero fornecedor", None))
        self.txtNumeroFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo de numero referente ao numero do endereço", None))
        self.lblNomeFantasiaFornecedor.setText(_translate("frmCadastroFornecedor", "Nome Fantasia", None))
        self.txtBairroFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Bairro fornecedor", None))
        self.txtBairroFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome do bairro referente ao endereço", None))
        self.txtInscricaoEstadualFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Inscrição Estadual fornecedor", None))
        self.txtInscricaoEstadualFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do numero do inscrição estadual da fornecedor", None))
        self.lblTelefoeneFornecedor.setText(_translate("frmCadastroFornecedor", "Telefone", None))
        self.lblNumeroFornecedor.setText(_translate("frmCadastroFornecedor", "Numero", None))
        self.txtEnderecoFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Endereço fornecedor", None))
        self.txtEnderecoFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo de descrição do endereço", None))
        self.txtFantasiaFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Nome Fantasia fornecedor", None))
        self.txtFantasiaFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome fantasia da fornecedor", None))
        self.lblCidadesFornecedor.setText(_translate("frmCadastroFornecedor", "Cidade", None))
        self.lblEstadosFornecedor.setText(_translate("frmCadastroFornecedor", "Estado", None))
        self.lblInscricaoEstadualFornecedor.setText(_translate("frmCadastroFornecedor", "Incrição Estadual", None))
        self.txtIdFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Codigo fornecedor", None))
        self.txtIdFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do codigo de identificação da fornecedor", None))
        self.lblCodigoFornecedor.setText(_translate("frmCadastroFornecedor", "Codigo", None))
        self.txtSiteFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Endereço site fornecedor", None))
        self.txtSiteFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo de descrição do endereço", None))
        self.lblSiteFornecedor.setText(_translate("frmCadastroFornecedor", "Site", None))
        self.lblEmailFornecedor.setText(_translate("frmCadastroFornecedor", "E-Mail", None))
        self.txtEmailFornecedor.setToolTip(_translate("frmCadastroFornecedor", "Endereço e-mail fornecedor", None))
        self.txtEmailFornecedor.setWhatsThis(_translate("frmCadastroFornecedor", "Campo de descrição do endereço", None))
        self.grbPesquisarEmpresa.setTitle(_translate("frmCadastroFornecedor", "Pesquisar Empresa", None))
        self.txtCnpjEmpresa.setToolTip(_translate("frmCadastroFornecedor", "CNPJ Empresa", None))
        self.txtCnpjEmpresa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do numero do CNPJ da empresa", None))
        self.txtCnpjEmpresa.setInputMask(_translate("frmCadastroFornecedor", "00.000.000/0000-00; ", None))
        self.lblCodigoEmpresa.setText(_translate("frmCadastroFornecedor", "Codigo", None))
        self.lblNomeFantasiaEmpresa.setText(_translate("frmCadastroFornecedor", "Nome Fantasia", None))
        self.lblCnpjEmpresa.setText(_translate("frmCadastroFornecedor", "CNPJ", None))
        self.txtFantasiaEmpresa.setToolTip(_translate("frmCadastroFornecedor", "Nome Fantasia Empresa", None))
        self.txtFantasiaEmpresa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome fantasia da empresa", None))
        self.txtRazaoSocialEmpresa.setToolTip(_translate("frmCadastroFornecedor", "Razão Social Empresa", None))
        self.txtRazaoSocialEmpresa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do nome da razão social da empresa", None))
        self.lblRazaoSocialEmpresa.setText(_translate("frmCadastroFornecedor", "Razão Social", None))
        self.txtIdEmpresa.setToolTip(_translate("frmCadastroFornecedor", "Codigo Empresa", None))
        self.txtIdEmpresa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do codigo de identificação da empresa", None))
        self.txtInscricaoEstaduaEmpresa.setToolTip(_translate("frmCadastroFornecedor", "Inscrição Estadual Empresa", None))
        self.txtInscricaoEstaduaEmpresa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo do numero do inscrição estadual da empresa", None))
        self.lblInscricaoEstadualEmpresa.setText(_translate("frmCadastroFornecedor", "Incrição Estadual", None))
        self.txtPesquisa.setToolTip(_translate("frmCadastroFornecedor", "Pesquisa", None))
        self.txtPesquisa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo pra inserir dados da pesquisa", None))
        self.tbPesquisa.setToolTip(_translate("frmCadastroFornecedor", "Tabela de Pesquisa", None))
        self.tbPesquisa.setWhatsThis(_translate("frmCadastroFornecedor", "Campo com as informações da pesquisa", None))
        self.grbDadosPesquisa.setTitle(_translate("frmCadastroFornecedor", "Dados Pesquisa", None))
        self.radBtnCodigo.setText(_translate("frmCadastroFornecedor", "Codigo", None))
        self.radBtnFantasia.setText(_translate("frmCadastroFornecedor", "Fantasia", None))
        self.radBtnRazaoSocial.setText(_translate("frmCadastroFornecedor", "Razão Social", None))
        self.radBtnCnpj.setText(_translate("frmCadastroFornecedor", "CNPJ", None))
        self.radBtnInsEstadual.setText(_translate("frmCadastroFornecedor", "Ins. Esta.", None))

