# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroMotorista.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

import datetime
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroMotorista(object):
    def setupUi(self, frmCadastroMotorista):
        frmCadastroMotorista.setObjectName(_fromUtf8("frmCadastroMotorista"))
        frmCadastroMotorista.resize(828, 690)
        frmCadastroMotorista.setMinimumSize(QtCore.QSize(828, 690))
        frmCadastroMotorista.setMaximumSize(QtCore.QSize(828, 690))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroMotorista.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/motorista.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCadastroMotorista.setWindowIcon(icon)
        frmCadastroMotorista.setSizeGripEnabled(False)
        frmCadastroMotorista.setModal(True)

        self.grbMotorista = QtGui.QGroupBox(frmCadastroMotorista)
        self.grbMotorista.setEnabled(False)
        self.grbMotorista.setGeometry(QtCore.QRect(5, 0, 817, 298))
        self.grbMotorista.setObjectName(_fromUtf8("grbMotorista"))

        self.lblNomeMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(178, 20, 121, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))

        self.txtCnh = QtGui.QLineEdit(self.grbMotorista)
        self.txtCnh.setGeometry(QtCore.QRect(8, 132, 221, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnh.setPalette(palette)
        self.txtCnh.setMaxLength(9)
        self.txtCnh.setObjectName(_fromUtf8("txtCnh"))

        self.txtExpeditor = QtGui.QLineEdit(self.grbMotorista)
        self.txtExpeditor.setGeometry(QtCore.QRect(216, 86, 113, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtExpeditor.setPalette(palette)
        self.txtExpeditor.setMaxLength(5)
        self.txtExpeditor.setObjectName(_fromUtf8("txtExpeditor"))

        self.txtRg = QtGui.QLineEdit(self.grbMotorista)
        self.txtRg.setGeometry(QtCore.QRect(6, 86, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRg.setPalette(palette)
        self.txtRg.setObjectName(_fromUtf8("txtRg"))

        self.lblDataNascimento = QtGui.QLabel(self.grbMotorista)
        self.lblDataNascimento.setGeometry(QtCore.QRect(670, 20, 111, 19))
        self.lblDataNascimento.setObjectName(_fromUtf8("lblDataNascimento"))

        self.txtDataNascimento = QtGui.QDateEdit(self.grbMotorista)
        self.txtDataNascimento.setDate(QDate.currentDate())
        self.txtDataNascimento.setGeometry(QtCore.QRect(670, 40, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtDataNascimento.setPalette(palette)
        self.txtDataNascimento.setCalendarPopup(True)
        self.txtDataNascimento.setObjectName(_fromUtf8("txtDataNascimento"))

        self.lblCepMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblCepMotorista.setGeometry(QtCore.QRect(8, 200, 31, 19))
        self.lblCepMotorista.setObjectName(_fromUtf8("lblCepMotorista"))

        self.txtComplemento = QtGui.QLineEdit(self.grbMotorista)
        self.txtComplemento.setGeometry(QtCore.QRect(178, 176, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplemento.setPalette(palette)
        self.txtComplemento.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtComplemento.setMaxLength(50)
        self.txtComplemento.setObjectName(_fromUtf8("txtComplemento"))

        self.lblPisMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblPisMotorista.setGeometry(QtCore.QRect(547, 66, 31, 19))
        self.lblPisMotorista.setObjectName(_fromUtf8("lblPisMotorista"))

        self.txtCidades = QtGui.QLineEdit(self.grbMotorista)
        self.txtCidades.setGeometry(QtCore.QRect(168, 220, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidades.setPalette(palette)
        self.txtCidades.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidades.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCidades.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidades.setMaxLength(70)
        self.txtCidades.setObjectName(_fromUtf8("txtCidades"))

        self.lblCpfMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblCpfMotorista.setGeometry(QtCore.QRect(338, 66, 31, 19))
        self.lblCpfMotorista.setObjectName(_fromUtf8("lblCpfMotorista"))

        self.txtPis = QtGui.QLineEdit(self.grbMotorista)
        self.txtPis.setGeometry(QtCore.QRect(547, 86, 262, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPis.setPalette(palette)
        self.txtPis.setMaxLength(9)
        self.txtPis.setObjectName(_fromUtf8("txtPis"))

        self.txtEstados = QtGui.QLineEdit(self.grbMotorista)
        self.txtEstados.setGeometry(QtCore.QRect(516, 220, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstados.setPalette(palette)
        self.txtEstados.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstados.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtEstados.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstados.setMaxLength(50)
        self.txtEstados.setObjectName(_fromUtf8("txtEstados"))

        self.txtEndereco = QtGui.QLineEdit(self.grbMotorista)
        self.txtEndereco.setGeometry(QtCore.QRect(352, 133, 455, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEndereco.setPalette(palette)
        self.txtEndereco.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEndereco.setMaxLength(50)
        self.txtEndereco.setObjectName(_fromUtf8("txtEndereco"))

        self.lblExpeditorMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblExpeditorMotorista.setGeometry(QtCore.QRect(216, 66, 66, 19))
        self.lblExpeditorMotorista.setObjectName(_fromUtf8("lblExpeditorMotorista"))

        self.txtNumero = QtGui.QLineEdit(self.grbMotorista)
        self.txtNumero.setGeometry(QtCore.QRect(10, 176, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumero.setPalette(palette)
        self.txtNumero.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNumero.setObjectName(_fromUtf8("txtNumero"))

        self.lblRg = QtGui.QLabel(self.grbMotorista)
        self.lblRg.setGeometry(QtCore.QRect(6, 66, 31, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))

        self.lblTelefoeneMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblTelefoeneMotorista.setGeometry(QtCore.QRect(8, 246, 61, 19))
        self.lblTelefoeneMotorista.setObjectName(_fromUtf8("lblTelefoeneMotorista"))

        self.txtBairro = QtGui.QLineEdit(self.grbMotorista)
        self.txtBairro.setGeometry(QtCore.QRect(477, 176, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairro.setPalette(palette)
        self.txtBairro.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtBairro.setMaxLength(50)
        self.txtBairro.setObjectName(_fromUtf8("txtBairro"))

        self.txtCelular = QtGui.QLineEdit(self.grbMotorista)
        self.txtCelular.setGeometry(QtCore.QRect(208, 266, 191, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCelular.setPalette(palette)
        self.txtCelular.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCelular.setObjectName(_fromUtf8("txtCelular"))

        self.txtNomeMotorista = QtGui.QLineEdit(self.grbMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(178, 40, 488, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMotorista.setPalette(palette)
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))

        self.lblComplementoMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblComplementoMotorista.setGeometry(QtCore.QRect(178, 156, 101, 16))
        self.lblComplementoMotorista.setObjectName(_fromUtf8("lblComplementoMotorista"))

        self.lblEstadosMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblEstadosMotorista.setGeometry(QtCore.QRect(518, 200, 51, 19))
        self.lblEstadosMotorista.setObjectName(_fromUtf8("lblEstadosMotorista"))

        self.txtCpf = QtGui.QLineEdit(self.grbMotorista)
        self.txtCpf.setGeometry(QtCore.QRect(338, 86, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCpf.setPalette(palette)
        self.txtCpf.setObjectName(_fromUtf8("txtCpf"))

        self.lblBairroMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblBairroMotorista.setGeometry(QtCore.QRect(476, 155, 41, 19))
        self.lblBairroMotorista.setObjectName(_fromUtf8("lblBairroMotorista"))

        self.lblCerlularMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblCerlularMotorista.setGeometry(QtCore.QRect(208, 246, 61, 19))
        self.lblCerlularMotorista.setObjectName(_fromUtf8("lblCerlularMotorista"))

        self.lblNumeroMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblNumeroMotorista.setGeometry(QtCore.QRect(10, 156, 51, 19))
        self.lblNumeroMotorista.setObjectName(_fromUtf8("lblNumeroMotorista"))

        self.lblCidadesMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblCidadesMotorista.setGeometry(QtCore.QRect(168, 200, 51, 19))
        self.lblCidadesMotorista.setObjectName(_fromUtf8("lblCidadesMotorista"))

        self.txtidMotorista = QtGui.QLineEdit(self.grbMotorista)
        self.txtidMotorista.setEnabled(False)
        self.txtidMotorista.setGeometry(QtCore.QRect(6, 40, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidMotorista.setPalette(palette)
        self.txtidMotorista.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidMotorista.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtidMotorista.setMaxLength(11)
        self.txtidMotorista.setObjectName(_fromUtf8("txtidMotorista"))

        self.lblCodigoMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(6, 20, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))

        self.lblEnderecoMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblEnderecoMotorista.setGeometry(QtCore.QRect(350, 113, 66, 19))
        self.lblEnderecoMotorista.setObjectName(_fromUtf8("lblEnderecoMotorista"))

        self.txtCep = QtGui.QLineEdit(self.grbMotorista)
        self.txtCep.setGeometry(QtCore.QRect(8, 220, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCep.setPalette(palette)
        self.txtCep.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCep.setInputMask(_fromUtf8("00000-000; "))
        self.txtCep.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCep.setObjectName(_fromUtf8("txtCep"))

        self.lblCnhMotorista = QtGui.QLabel(self.grbMotorista)
        self.lblCnhMotorista.setGeometry(QtCore.QRect(8, 112, 41, 19))
        self.lblCnhMotorista.setObjectName(_fromUtf8("lblCnhMotorista"))

        self.txtTelefone = QtGui.QLineEdit(self.grbMotorista)
        self.txtTelefone.setGeometry(QtCore.QRect(8, 266, 191, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTelefone.setPalette(palette)
        self.txtTelefone.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtTelefone.setObjectName(_fromUtf8("txtTelefone"))

        self.lblCategoriaCnh = QtGui.QLabel(self.grbMotorista)
        self.lblCategoriaCnh.setGeometry(QtCore.QRect(240, 110, 101, 19))
        self.lblCategoriaCnh.setObjectName(_fromUtf8("lblCategoriaCnh"))

        self.txtCategoriaCnh = QtGui.QComboBox(self.grbMotorista)
        self.txtCategoriaCnh.setGeometry(QtCore.QRect(240, 132, 101, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCategoriaCnh.setPalette(palette)
        self.txtCategoriaCnh.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtCategoriaCnh.setObjectName(_fromUtf8("txtCategoriaCnh"))

        self.grbSexo = QtGui.QGroupBox(self.grbMotorista)
        self.grbSexo.setGeometry(QtCore.QRect(630, 244, 176, 45))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.grbSexo.setPalette(palette)
        self.grbSexo.setObjectName(_fromUtf8("grbSexo"))

        self.radBtnMasculino = QtGui.QRadioButton(self.grbSexo)
        self.radBtnMasculino.setGeometry(QtCore.QRect(6, 20, 82, 17))
        self.radBtnMasculino.setObjectName(_fromUtf8("radBtnMasculino"))

        self.radBtnFeminino = QtGui.QRadioButton(self.grbSexo)
        self.radBtnFeminino.setGeometry(QtCore.QRect(96, 20, 82, 17))
        self.radBtnFeminino.setObjectName(_fromUtf8("radBtnFeminino"))

        self.grbBotoes = QtGui.QGroupBox(frmCadastroMotorista)
        self.grbBotoes.setGeometry(QtCore.QRect(4, 606, 817, 81))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnCadSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnCadSalvar.setEnabled(False)
        self.btnCadSalvar.setGeometry(QtCore.QRect(410, 10, 81, 61))
        self.btnCadSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadSalvar.setObjectName(_fromUtf8("btnCadSalvar"))

        self.btnCadEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnCadEditar.setEnabled(False)
        self.btnCadEditar.setGeometry(QtCore.QRect(510, 10, 81, 61))
        self.btnCadEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadEditar.setObjectName(_fromUtf8("btnCadEditar"))

        self.btnCadDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnCadDeletar.setEnabled(False)
        self.btnCadDeletar.setGeometry(QtCore.QRect(710, 10, 81, 61))
        self.btnCadDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadDeletar.setObjectName(_fromUtf8("btnCadDeletar"))

        self.btnCadCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCadCancelar.setEnabled(False)
        self.btnCadCancelar.setGeometry(QtCore.QRect(610, 10, 81, 61))
        self.btnCadCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadCancelar.setObjectName(_fromUtf8("btnCadCancelar"))

        self.btnCadNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnCadNovo.setGeometry(QtCore.QRect(310, 10, 81, 61))
        self.btnCadNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCadNovo.setObjectName(_fromUtf8("btnCadNovo"))

        self.grbVeiculo = QtGui.QGroupBox(frmCadastroMotorista)
        self.grbVeiculo.setEnabled(False)
        self.grbVeiculo.setGeometry(QtCore.QRect(5, 300, 816, 125))
        self.grbVeiculo.setObjectName(_fromUtf8("grbVeiculo"))

        self.txtModelo = QtGui.QLineEdit(self.grbVeiculo)
        self.txtModelo.setGeometry(QtCore.QRect(520, 40, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModelo.setPalette(palette)
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))

        self.lblTipoVeiculo = QtGui.QLabel(self.grbVeiculo)
        self.lblTipoVeiculo.setGeometry(QtCore.QRect(10, 20, 111, 19))
        self.lblTipoVeiculo.setObjectName(_fromUtf8("lblTipoVeiculo"))

        self.lblModelo = QtGui.QLabel(self.grbVeiculo)
        self.lblModelo.setGeometry(QtCore.QRect(520, 20, 61, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))

        self.txtMarca = QtGui.QLineEdit(self.grbVeiculo)
        self.txtMarca.setGeometry(QtCore.QRect(230, 40, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarca.setPalette(palette)
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))

        self.lblMarca = QtGui.QLabel(self.grbVeiculo)
        self.lblMarca.setGeometry(QtCore.QRect(230, 20, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))

        self.txtTipoVeiculo = QtGui.QComboBox(self.grbVeiculo)
        self.txtTipoVeiculo.setGeometry(QtCore.QRect(10, 40, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTipoVeiculo.setPalette(palette)
        self.txtTipoVeiculo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtTipoVeiculo.setObjectName(_fromUtf8("txtTipoVeiculo"))

        self.lblPlaca = QtGui.QLabel(self.grbVeiculo)
        self.lblPlaca.setGeometry(QtCore.QRect(10, 70, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))

        self.txtPlaca = QtGui.QLineEdit(self.grbVeiculo)
        self.txtPlaca.setGeometry(QtCore.QRect(10, 90, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlaca.setPalette(palette)
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))

        self.grbPesquisa = QtGui.QGroupBox(frmCadastroMotorista)
        self.grbPesquisa.setGeometry(QtCore.QRect(5, 430, 815, 171))
        self.grbPesquisa.setTitle(_fromUtf8(""))
        self.grbPesquisa.setObjectName(_fromUtf8("grbPesquisa"))

        self.txtPesquisa = QtGui.QLineEdit(self.grbPesquisa)
        self.txtPesquisa.setGeometry(QtCore.QRect(470, 14, 267, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisa.setPalette(palette)
        self.txtPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPesquisa.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtPesquisa.setMaxLength(50)
        self.txtPesquisa.setObjectName(_fromUtf8("txtPesquisa"))

        self.btnPesquisar = QtGui.QPushButton(self.grbPesquisa)
        self.btnPesquisar.setGeometry(QtCore.QRect(760, 12, 41, 31))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.tbPesquisa = QtGui.QTableWidget(self.grbPesquisa)
        self.tbPesquisa.setGeometry(QtCore.QRect(10, 51, 796, 111))
        self.tbPesquisa.setColumnCount(23)
        self.tbPesquisa.setHorizontalHeaderLabels(['COD.', 'Motorista', 'Nascimento', 'RG', 'Expeditor', 'CPF', 'PIS/PASEP', 'CNH', 'Categoria', 'Sexo', 'Endereco', 'Numero',  'Complemento', 'Bairro', 'Telefone', 'Celular', 'Cep', 'Cidade', 'Estado',  'Tipo Veiculo', 'Marca', 'Modelo', 'Placa'])
        self.tbPesquisa.setEditTriggers(self.tbPesquisa.NoEditTriggers)
        self.tbPesquisa.setSelectionBehavior(self.tbPesquisa.SelectRows)
        self.tbPesquisa.setSelectionMode(self.tbPesquisa.SingleSelection)
        self.tbPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbPesquisa.setObjectName(_fromUtf8("tbPesquisa"))

        self.grbDadosPesquisa = QtGui.QGroupBox(self.grbPesquisa)
        self.grbDadosPesquisa.setGeometry(QtCore.QRect(5, 0, 451, 44))
        self.grbDadosPesquisa.setObjectName(_fromUtf8("grbDadosPesquisa"))

        self.radBtnCodigo = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCodigo.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.radBtnCodigo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCodigo.setObjectName(_fromUtf8("radBtnCodigo"))

        self.radBtnNome = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnNome.setGeometry(QtCore.QRect(90, 20, 71, 17))
        self.radBtnNome.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnNome.setObjectName(_fromUtf8("radBtnNome"))

        self.radBtnCpf = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCpf.setGeometry(QtCore.QRect(160, 20, 51, 17))
        self.radBtnCpf.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCpf.setObjectName(_fromUtf8("radBtnCpf"))

        self.radBtnRg = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnRg.setGeometry(QtCore.QRect(217, 20, 41, 17))
        self.radBtnRg.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnRg.setObjectName(_fromUtf8("radBtnRg"))

        self.radBtnNumCnh = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnNumCnh.setGeometry(QtCore.QRect(275, 20, 71, 17))
        self.radBtnNumCnh.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnNumCnh.setObjectName(_fromUtf8("radBtnNumCnh"))

        self.radBtnPis = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnPis.setGeometry(QtCore.QRect(365, 20, 41, 17))
        self.radBtnPis.setObjectName(_fromUtf8("radBtnPis"))

        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblDataNascimento.setBuddy(self.txtDataNascimento)
        self.lblCepMotorista.setBuddy(self.txtCep)
        self.lblPisMotorista.setBuddy(self.txtPis)
        self.lblCpfMotorista.setBuddy(self.txtCpf)
        self.lblExpeditorMotorista.setBuddy(self.txtExpeditor)
        self.lblRg.setBuddy(self.txtRg)
        self.lblTelefoeneMotorista.setBuddy(self.txtTelefone)
        self.lblComplementoMotorista.setBuddy(self.txtComplemento)
        self.lblEstadosMotorista.setBuddy(self.txtEstados)
        self.lblBairroMotorista.setBuddy(self.txtBairro)
        self.lblCerlularMotorista.setBuddy(self.txtCelular)
        self.lblNumeroMotorista.setBuddy(self.txtNumero)
        self.lblCidadesMotorista.setBuddy(self.txtCidades)
        self.lblCodigoMotorista.setBuddy(self.txtidMotorista)
        self.lblEnderecoMotorista.setBuddy(self.txtEndereco)
        self.lblCnhMotorista.setBuddy(self.txtCnh)
        self.lblCategoriaCnh.setBuddy(self.txtCategoriaCnh)
        self.lblTipoVeiculo.setBuddy(self.txtTipoVeiculo)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblPlaca.setBuddy(self.txtPlaca)

        self.retranslateUi(frmCadastroMotorista)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroMotorista)
        frmCadastroMotorista.setTabOrder(self.txtNomeMotorista, self.txtDataNascimento)
        frmCadastroMotorista.setTabOrder(self.txtDataNascimento, self.txtRg)
        frmCadastroMotorista.setTabOrder(self.txtRg, self.txtExpeditor)
        frmCadastroMotorista.setTabOrder(self.txtExpeditor, self.txtCpf)
        frmCadastroMotorista.setTabOrder(self.txtCpf, self.txtPis)
        frmCadastroMotorista.setTabOrder(self.txtPis, self.txtCnh)
        frmCadastroMotorista.setTabOrder(self.txtCnh, self.txtCategoriaCnh)
        frmCadastroMotorista.setTabOrder(self.txtCategoriaCnh, self.txtEndereco)
        frmCadastroMotorista.setTabOrder(self.txtEndereco, self.txtNumero)
        frmCadastroMotorista.setTabOrder(self.txtNumero, self.txtComplemento)
        frmCadastroMotorista.setTabOrder(self.txtComplemento, self.txtBairro)
        frmCadastroMotorista.setTabOrder(self.txtBairro, self.txtCep)
        frmCadastroMotorista.setTabOrder(self.txtCep, self.txtCidades)
        frmCadastroMotorista.setTabOrder(self.txtCidades, self.txtEstados)
        frmCadastroMotorista.setTabOrder(self.txtEstados, self.txtTelefone)
        frmCadastroMotorista.setTabOrder(self.txtTelefone, self.txtCelular)
        frmCadastroMotorista.setTabOrder(self.txtCelular, self.txtTipoVeiculo)
        frmCadastroMotorista.setTabOrder(self.txtTipoVeiculo, self.txtMarca)
        frmCadastroMotorista.setTabOrder(self.txtMarca, self.txtModelo)
        frmCadastroMotorista.setTabOrder(self.txtModelo, self.txtPlaca)


    def retranslateUi(self, frmCadastroMotorista):
        frmCadastroMotorista.setWindowTitle(_translate("frmCadastroMotorista", "Cadastro de Motoristas", None))
        self.grbMotorista.setTitle(_translate("frmCadastroMotorista", "Dados Motoristas", None))
        self.lblNomeMotorista.setText(_translate("frmCadastroMotorista", "Nome Motorista", None))
        self.txtCnh.setToolTip(_translate("frmCadastroMotorista", "CNH", None))
        self.txtCnh.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero de identificação CNH", None))
        self.txtExpeditor.setToolTip(_translate("frmCadastroMotorista", "Expeditor", None))
        self.txtExpeditor.setWhatsThis(_translate("frmCadastroMotorista", "Campo do orgão expeditor do RG", None))
        self.txtRg.setToolTip(_translate("frmCadastroMotorista", "Rg", None))
        self.txtRg.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero do RG do Motorista", None))
        self.txtRg.setInputMask(_translate("frmCadastroMotorista", "0000000-0; ", None))
        self.lblDataNascimento.setText(_translate("frmCadastroMotorista", "Data Nascimento", None))
        self.txtDataNascimento.setToolTip(_translate("frmCadastroMotorista", "Data Nascimento", None))
        self.txtDataNascimento.setWhatsThis(_translate("frmCadastroMotorista", "Campo da data de nacimento do Motorista", None))
        self.lblCepMotorista.setText(_translate("frmCadastroMotorista", "CEP", None))
        self.txtComplemento.setToolTip(_translate("frmCadastroMotorista", "Complemento", None))
        self.txtComplemento.setWhatsThis(_translate("frmCadastroMotorista", "Campo complementar do endereço", None))
        self.lblPisMotorista.setText(_translate("frmCadastroMotorista", "PIS", None))
        self.txtCidades.setToolTip(_translate("frmCadastroMotorista", "Cidade", None))
        self.txtCidades.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblCpfMotorista.setText(_translate("frmCadastroMotorista", "CPF", None))
        self.txtPis.setToolTip(_translate("frmCadastroMotorista", "PIS", None))
        self.txtPis.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero do PIS", None))
        self.txtEstados.setToolTip(_translate("frmCadastroMotorista", "Estado", None))
        self.txtEstados.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome do estado de localização do endereço", None))
        self.txtEndereco.setToolTip(_translate("frmCadastroMotorista", "Endereço", None))
        self.txtEndereco.setWhatsThis(_translate("frmCadastroMotorista", "Campo de descrição do endereço", None))
        self.lblExpeditorMotorista.setText(_translate("frmCadastroMotorista", "Expeditor", None))
        self.txtNumero.setToolTip(_translate("frmCadastroMotorista", "Numero", None))
        self.txtNumero.setWhatsThis(_translate("frmCadastroMotorista", "Campo de numero referente ao numero do endereço", None))
        self.lblRg.setText(_translate("frmCadastroMotorista", "RG", None))
        self.lblTelefoeneMotorista.setText(_translate("frmCadastroMotorista", "Telefone", None))
        self.txtBairro.setToolTip(_translate("frmCadastroMotorista", "Bairro", None))
        self.txtBairro.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome do bairro referente ao endereço", None))
        self.txtCelular.setToolTip(_translate("frmCadastroMotorista", "Celular", None))
        self.txtCelular.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero de cantato de celular do funcionario", None))
        self.txtCelular.setInputMask(_translate("frmCadastroMotorista", "(00)00000-0000; ", None))
        self.txtNomeMotorista.setToolTip(_translate("frmCadastroMotorista", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome do Motorista", None))
        self.lblComplementoMotorista.setText(_translate("frmCadastroMotorista", "Complemento", None))
        self.lblEstadosMotorista.setText(_translate("frmCadastroMotorista", "Estado", None))
        self.txtCpf.setToolTip(_translate("frmCadastroMotorista", "CPF", None))
        self.txtCpf.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero do CPF do Motorista", None))
        self.txtCpf.setInputMask(_translate("frmCadastroMotorista", "000.000.000-00; ", None))
        self.lblBairroMotorista.setText(_translate("frmCadastroMotorista", "Bairro", None))
        self.lblCerlularMotorista.setText(_translate("frmCadastroMotorista", "Celular", None))
        self.lblNumeroMotorista.setText(_translate("frmCadastroMotorista", "Numero", None))
        self.lblCidadesMotorista.setText(_translate("frmCadastroMotorista", "Cidade", None))
        self.txtidMotorista.setToolTip(_translate("frmCadastroMotorista", "Codigo Motorista", None))
        self.txtidMotorista.setWhatsThis(_translate("frmCadastroMotorista", "Campo do Codigo de identificação do Motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmCadastroMotorista", "Codigo Motorista", None))
        self.lblEnderecoMotorista.setText(_translate("frmCadastroMotorista", "Endereço", None))
        self.txtCep.setToolTip(_translate("frmCadastroMotorista", "CEP", None))
        self.txtCep.setWhatsThis(_translate("frmCadastroMotorista", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.lblCnhMotorista.setText(_translate("frmCadastroMotorista", "CNH", None))
        self.txtTelefone.setToolTip(_translate("frmCadastroMotorista", "Telefone", None))
        self.txtTelefone.setWhatsThis(_translate("frmCadastroMotorista", "Campo do numero de cantato de telefone da funcionario", None))
        self.txtTelefone.setInputMask(_translate("frmCadastroMotorista", "(00)0000-0000; ", None))
        self.lblCategoriaCnh.setText(_translate("frmCadastroMotorista", "Categoria CNH", None))
        self.grbSexo.setTitle(_translate("frmCadastroMotorista", "Sexo", None))
        self.radBtnMasculino.setText(_translate("frmCadastroMotorista", "Masculino", None))
        self.radBtnFeminino.setText(_translate("frmCadastroMotorista", "Feminino", None))
        self.btnCadSalvar.setWhatsThis(_translate("frmCadastroMotorista", "Botão para salvar um novo registro", None))
        self.btnCadSalvar.setText(_translate("frmCadastroMotorista", "Salvar", None))
        self.btnCadEditar.setWhatsThis(_translate("frmCadastroMotorista", "Botão para salvar edição de um registro existente", None))
        self.btnCadEditar.setText(_translate("frmCadastroMotorista", "Editar", None))
        self.btnCadDeletar.setWhatsThis(_translate("frmCadastroMotorista", "Botão de deleção de um registro existente", None))
        self.btnCadDeletar.setText(_translate("frmCadastroMotorista", "Deletar", None))
        self.btnCadCancelar.setWhatsThis(_translate("frmCadastroMotorista", "Botão de cancelar a operação iniciada", None))
        self.btnCadCancelar.setText(_translate("frmCadastroMotorista", "Cancelar", None))
        self.btnCadNovo.setWhatsThis(_translate("frmCadastroMotorista", "Botão de Criação de um novo registro", None))
        self.btnCadNovo.setText(_translate("frmCadastroMotorista", "Novo", None))
        self.grbVeiculo.setTitle(_translate("frmCadastroMotorista", "Veiculo", None))
        self.txtModelo.setToolTip(_translate("frmCadastroMotorista", "Modelo", None))
        self.txtModelo.setWhatsThis(_translate("frmCadastroMotorista", "Campo com o nome do modelo do veiculo", None))
        self.lblTipoVeiculo.setText(_translate("frmCadastroMotorista", "Tipo de Veiculo", None))
        self.lblModelo.setText(_translate("frmCadastroMotorista", "Modelo", None))
        self.txtMarca.setToolTip(_translate("frmCadastroMotorista", "Marca", None))
        self.txtMarca.setWhatsThis(_translate("frmCadastroMotorista", "Campo do nome da marca do veiculo", None))
        self.lblMarca.setText(_translate("frmCadastroMotorista", "Marca", None))
        self.txtTipoVeiculo.setToolTip(_translate("frmCadastroMotorista", "Tipo de Veiculo", None))
        self.txtTipoVeiculo.setWhatsThis(_translate("frmCadastroMotorista", "Campo de escolha do tipo de veiculo", None))
        self.lblPlaca.setText(_translate("frmCadastroMotorista", "Placa", None))
        self.txtPlaca.setToolTip(_translate("frmCadastroMotorista", "Placa", None))
        self.txtPlaca.setWhatsThis(_translate("frmCadastroMotorista", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmCadastroMotorista", "NNN-0000; ", None))
        self.txtPlaca.setText(_translate("frmCadastroMotorista", "-", None))
        #self.txtPesquisa.setToolTip(_translate("frmCadastroMotorista", "Pesquisa", None))
        self.txtPesquisa.setWhatsThis(_translate("frmCadastroMotorista", "Campo pra inserir dados da pesquisa", None))
        self.tbPesquisa.setToolTip(_translate("frmCadastroMotorista", "Tabela de Pesquisa", None))
        self.tbPesquisa.setWhatsThis(_translate("frmCadastroMotorista", "Campo com as informações da pesquisa", None))
        self.grbDadosPesquisa.setTitle(_translate("frmCadastroMotorista", "Dados Pesquisa", None))
        self.radBtnCodigo.setText(_translate("frmCadastroMotorista", "Codigo", None))
        self.radBtnNome.setText(_translate("frmCadastroMotorista", "Nome", None))
        self.radBtnCpf.setText(_translate("frmCadastroMotorista", "CPF", None))
        self.radBtnRg.setText(_translate("frmCadastroMotorista", "RG", None))
        self.radBtnNumCnh.setText(_translate("frmCadastroMotorista", "Nº CNH", None))
        self.radBtnPis.setText(_translate("frmCadastroMotorista", "PIS", None))

