# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaVeiculosCarregamentos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaVeiculosCarregamento(object):
    def setupUi(self, frmEntradaVeiculosCarregamento):
        frmEntradaVeiculosCarregamento.setObjectName(_fromUtf8("frmEntradaVeiculosCarregamento"))
        frmEntradaVeiculosCarregamento.resize(890, 474)
        frmEntradaVeiculosCarregamento.setMinimumSize(QtCore.QSize(890, 474))
        frmEntradaVeiculosCarregamento.setMaximumSize(QtCore.QSize(890, 474))
        font = QtGui.QFont()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/carregamento.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmEntradaVeiculosCarregamento.setWindowIcon(icon)
        frmEntradaVeiculosCarregamento.setSizeGripEnabled(True)
        frmEntradaVeiculosCarregamento.setModal(True)
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)

        frmEntradaVeiculosCarregamento.setFont(font)
        self.grbDadosMotorista = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(10, 50, 871, 114))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))

        self.txtModeloMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModeloMotorista.setEnabled(False)
        self.txtModeloMotorista.setGeometry(QtCore.QRect(10, 80, 291, 25))
        self.txtModeloMotorista.setMaxLength(50)
        self.txtModeloMotorista.setObjectName(_fromUtf8("txtModeloMotorista"))

        self.lblMarcaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarcaMotorista.setGeometry(QtCore.QRect(310, 62, 51, 19))
        self.lblMarcaMotorista.setObjectName(_fromUtf8("lblMarcaMotorista"))

        self.txtMarcaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarcaMotorista.setEnabled(False)
        self.txtMarcaMotorista.setGeometry(QtCore.QRect(310, 82, 331, 25))
        self.txtMarcaMotorista.setMaxLength(50)
        self.txtMarcaMotorista.setObjectName(_fromUtf8("txtMarcaMotorista"))

        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setEnabled(False)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(180, 36, 621, 25))
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))

        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 16, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))

        self.txtPlacaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlacaMotorista.setEnabled(False)
        self.txtPlacaMotorista.setGeometry(QtCore.QRect(650, 82, 211, 25))
        self.txtPlacaMotorista.setObjectName(_fromUtf8("txtPlacaMotorista"))

        self.lblModeloMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModeloMotorista.setGeometry(QtCore.QRect(10, 60, 51, 19))
        self.lblModeloMotorista.setObjectName(_fromUtf8("lblModeloMotorista"))

        self.txtidMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidMotorista.setGeometry(QtCore.QRect(10, 36, 161, 25))
        self.txtidMotorista.setMaxLength(11)
        self.txtidMotorista.setObjectName(_fromUtf8("txtidMotorista"))

        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 16, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))

        self.lblPlacaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlacaMotorista.setGeometry(QtCore.QRect(650, 62, 51, 19))
        self.lblPlacaMotorista.setObjectName(_fromUtf8("lblPlacaMotorista"))

        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(820, 35, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarMotorista.setFont(font)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarMotorista.setIcon(icon)
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))

        self.grbDadosClienteDestinatario = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbDadosClienteDestinatario.setEnabled(False)
        self.grbDadosClienteDestinatario.setGeometry(QtCore.QRect(10, 165, 871, 251))
        self.grbDadosClienteDestinatario.setObjectName(_fromUtf8("grbDadosClienteDestinatario"))

        self.txtIdClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtIdClienteDestinatario.setGeometry(QtCore.QRect(10, 35, 181, 25))
        self.txtIdClienteDestinatario.setMaxLength(11)
        self.txtIdClienteDestinatario.setObjectName(_fromUtf8("txtIdClienteDestinatario"))

        self.txtNomeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNomeClienteDestinatario.setEnabled(False)
        self.txtNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 35, 601, 25))
        self.txtNomeClienteDestinatario.setMaxLength(70)
        self.txtNomeClienteDestinatario.setObjectName(_fromUtf8("txtNomeClienteDestinatario"))

        self.lblCodigoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCodigoClienteDestinatario.setGeometry(QtCore.QRect(10, 15, 171, 21))
        self.lblCodigoClienteDestinatario.setObjectName(_fromUtf8("lblCodigoClienteDestinatario"))

        self.lblNomeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 15, 231, 16))
        self.lblNomeClienteDestinatario.setObjectName(_fromUtf8("lblNomeClienteDestinatario"))

        self.txtInscricaoEstaduaClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtInscricaoEstaduaClienteDestinatario.setEnabled(False)
        self.txtInscricaoEstaduaClienteDestinatario.setGeometry(QtCore.QRect(688, 80, 173, 25))
        self.txtInscricaoEstaduaClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaClienteDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaClienteDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaClienteDestinatario"))

        self.txtRazaoSocialClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtRazaoSocialClienteDestinatario.setEnabled(False)
        self.txtRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 80, 481, 25))
        self.txtRazaoSocialClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialClienteDestinatario.setMaxLength(70)
        self.txtRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("txtRazaoSocialClienteDestinatario"))

        self.lblRazaoSocialClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("lblRazaoSocialClienteDestinatario"))

        self.lblCnpjClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCnpjClienteDestinatario.setGeometry(QtCore.QRect(500, 60, 41, 19))
        self.lblCnpjClienteDestinatario.setObjectName(_fromUtf8("lblCnpjClienteDestinatario"))

        self.lblInscricaoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setGeometry(QtCore.QRect(688, 60, 121, 19))
        self.lblInscricaoClienteDestinatario.setObjectName(_fromUtf8("lblInscricaoClienteDestinatario"))

        self.txtCnpjClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCnpjClienteDestinatario.setEnabled(False)
        self.txtCnpjClienteDestinatario.setGeometry(QtCore.QRect(500, 80, 182, 25))
        self.txtCnpjClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjClienteDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjClienteDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjClienteDestinatario.setObjectName(_fromUtf8("txtCnpjClienteDestinatario"))

        self.btnPesquisarClienteDestinatario = QtGui.QPushButton(self.grbDadosClienteDestinatario)
        self.btnPesquisarClienteDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarClienteDestinatario.setGeometry(QtCore.QRect(820, 34, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarClienteDestinatario.setFont(font)
        self.btnPesquisarClienteDestinatario.setText(_fromUtf8(""))
        self.btnPesquisarClienteDestinatario.setIcon(icon)
        self.btnPesquisarClienteDestinatario.setObjectName(_fromUtf8("btnPesquisarClienteDestinatario"))

        self.lblCep = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCep.setGeometry(QtCore.QRect(200, 197, 31, 19))
        self.lblCep.setObjectName(_fromUtf8("lblCep"))

        self.lblCidade = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCidade.setGeometry(QtCore.QRect(380, 153, 51, 19))
        self.lblCidade.setObjectName(_fromUtf8("lblCidade"))

        self.txtCidade = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCidade.setEnabled(False)
        self.txtCidade.setGeometry(QtCore.QRect(380, 173, 481, 25))
        self.txtCidade.setMaxLength(75)
        self.txtCidade.setObjectName(_fromUtf8("txtCidade"))

        self.txtEndereco = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEndereco.setEnabled(False)
        self.txtEndereco.setGeometry(QtCore.QRect(10, 126, 441, 25))
        self.txtEndereco.setMaxLength(50)
        self.txtEndereco.setObjectName(_fromUtf8("txtEndereco"))

        self.txtEstado = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEstado.setEnabled(False)
        self.txtEstado.setGeometry(QtCore.QRect(10, 217, 181, 25))
        self.txtEstado.setMaxLength(50)
        self.txtEstado.setObjectName(_fromUtf8("txtEstado"))

        self.txtCep = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCep.setEnabled(False)
        self.txtCep.setGeometry(QtCore.QRect(200, 217, 131, 25))
        self.txtCep.setObjectName(_fromUtf8("txtCep"))

        self.txtBairro = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtBairro.setEnabled(False)
        self.txtBairro.setGeometry(QtCore.QRect(10, 170, 361, 25))
        self.txtBairro.setMaxLength(50)
        self.txtBairro.setObjectName(_fromUtf8("txtBairro"))

        self.lblEndereco = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEndereco.setGeometry(QtCore.QRect(10, 106, 66, 19))
        self.lblEndereco.setObjectName(_fromUtf8("lblEndereco"))

        self.txtComplemento = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtComplemento.setEnabled(False)
        self.txtComplemento.setGeometry(QtCore.QRect(610, 127, 251, 24))
        self.txtComplemento.setMaxLength(50)
        self.txtComplemento.setObjectName(_fromUtf8("txtComplemento"))

        self.lblNumero = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNumero.setGeometry(QtCore.QRect(460, 106, 66, 19))
        self.lblNumero.setObjectName(_fromUtf8("lblNumero"))

        self.txtNumero = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNumero.setEnabled(False)
        self.txtNumero.setGeometry(QtCore.QRect(460, 126, 141, 25))
        self.txtNumero.setMaxLength(11)
        self.txtNumero.setObjectName(_fromUtf8("txtNumero"))

        self.lblBairro = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblBairro.setGeometry(QtCore.QRect(10, 150, 51, 19))
        self.lblBairro.setObjectName(_fromUtf8("lblBairro"))

        self.lblEstado = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEstado.setGeometry(QtCore.QRect(10, 197, 51, 19))
        self.lblEstado.setObjectName(_fromUtf8("lblEstado"))

        self.lblComplemento = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblComplemento.setGeometry(QtCore.QRect(610, 107, 101, 16))
        self.lblComplemento.setObjectName(_fromUtf8("lblComplemento"))

        self.lblHoraEntrada = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.lblHoraEntrada.setGeometry(QtCore.QRect(150, 6, 91, 16))
        self.lblHoraEntrada.setObjectName(_fromUtf8("lblHoraEntrada"))

        self.txtData = QtGui.QDateEdit(frmEntradaVeiculosCarregamento)
        self.txtData.setDate(QtCore.QDate.currentDate())
        self.txtData.setEnabled(False)
        self.txtData.setGeometry(QtCore.QRect(20, 26, 110, 25))
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))

        self.txtHora = QtGui.QTimeEdit(frmEntradaVeiculosCarregamento)
        self.txtHora.setTime(QtCore.QTime.currentTime())
        self.txtHora.setEnabled(False)
        self.txtHora.setGeometry(QtCore.QRect(150, 26, 118, 25))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))

        self.lblDataEntrada = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.lblDataEntrada.setGeometry(QtCore.QRect(20, 6, 101, 16))
        self.lblDataEntrada.setObjectName(_fromUtf8("lblDataEntrada"))

        self.txtTipoCarga = QtGui.QComboBox(frmEntradaVeiculosCarregamento)
        self.txtTipoCarga.setEnabled(False)
        self.txtTipoCarga.setGeometry(QtCore.QRect(290, 26, 241, 25))
        self.txtTipoCarga.setObjectName(_fromUtf8("txtTipoCarga"))

        self.lblTipoCarga = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.lblTipoCarga.setGeometry(QtCore.QRect(290, 4, 101, 16))
        self.lblTipoCarga.setObjectName(_fromUtf8("lblTipoCarga"))

        self.txtProduto = QtGui.QComboBox(frmEntradaVeiculosCarregamento)
        self.txtProduto.setEnabled(False)
        self.txtProduto.setGeometry(QtCore.QRect(540, 26, 241, 25))
        self.txtProduto.setObjectName(_fromUtf8("txtProduto"))

        self.lblProduto = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.lblProduto.setGeometry(QtCore.QRect(540, 4, 51, 16))
        self.lblProduto.setObjectName(_fromUtf8("lblProduto"))

        self.grbBotoes = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 420, 871, 51))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(500, 12, 88, 27))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon1)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(600, 12, 88, 27))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon2)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(700, 12, 88, 27))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon3)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))


        self.lblMarcaMotorista.setBuddy(self.txtMarcaMotorista)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblModeloMotorista.setBuddy(self.txtModeloMotorista)
        self.lblCodigoMotorista.setBuddy(self.txtidMotorista)
        self.lblPlacaMotorista.setBuddy(self.txtPlacaMotorista)
        self.lblCodigoClienteDestinatario.setBuddy(self.txtIdClienteDestinatario)
        self.lblNomeClienteDestinatario.setBuddy(self.txtNomeClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setBuddy(self.txtRazaoSocialClienteDestinatario)
        self.lblCnpjClienteDestinatario.setBuddy(self.txtCnpjClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setBuddy(self.txtInscricaoEstaduaClienteDestinatario)
        self.lblCep.setBuddy(self.txtCep)
        self.lblCidade.setBuddy(self.txtCidade)
        self.lblEndereco.setBuddy(self.txtEndereco)
        self.lblNumero.setBuddy(self.txtNumero)
        self.lblBairro.setBuddy(self.txtBairro)
        self.lblEstado.setBuddy(self.txtEstado)
        self.lblComplemento.setBuddy(self.txtComplemento)
        self.lblHoraEntrada.setBuddy(self.txtHora)
        self.lblDataEntrada.setBuddy(self.txtData)
        self.lblTipoCarga.setBuddy(self.txtTipoCarga)
        self.lblProduto.setBuddy(self.txtTipoCarga)

        self.retranslateUi(frmEntradaVeiculosCarregamento)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaVeiculosCarregamento)

    def retranslateUi(self, frmEntradaVeiculosCarregamento):
        frmEntradaVeiculosCarregamento.setWindowTitle(_translate("frmEntradaVeiculosCarregamento", "Entrada de Veiculos Carregamentos", None))
        self.grbDadosMotorista.setTitle(_translate("frmEntradaVeiculosCarregamento", "Motorista", None))
        self.txtModeloMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtModeloMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo de identicação do modelo do veiculo", None))
        self.lblMarcaMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Marca", None))
        self.txtMarcaMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtMarcaMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome da marca do veiculo", None))
        self.txtNomeMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome do Motorista", None))
        self.lblNomeMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Nome Motorista", None))
        self.txtPlacaMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Placa do Veiculo", None))
        self.txtPlacaMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo de identificação da placa do veiculo", None))
        self.txtPlacaMotorista.setInputMask(_translate("frmEntradaVeiculosCarregamento", "nnn-0000; ", None))
        self.txtPlacaMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "-", None))
        self.lblModeloMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Modelo", None))
        self.txtidMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Codigo Motorista", None))
        self.txtidMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do Codigo de identificação do Motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Codigo Motorista", None))
        self.lblPlacaMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Placa", None))
        self.grbDadosClienteDestinatario.setTitle(_translate("frmEntradaVeiculosCarregamento", "Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do codigo de identificação do cliente destinatario", None))
        self.txtNomeClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Nome Cliente Destinatario", None))
        self.txtNomeClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome do cliente destinatario", None))
        self.lblCodigoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.lblNomeClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Nome Fantasia Cliente Destinatario", None))
        self.txtInscricaoEstaduaClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do numero do inscrição estadual do cliente destinatario", None))
        self.txtRazaoSocialClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Razão Social ", None))
        self.txtRazaoSocialClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome da razão social do cliente destinatario", None))
        self.lblRazaoSocialClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Razão Social", None))
        self.lblCnpjClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "CNPJ", None))
        self.lblInscricaoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Incrição Estadual", None))
        self.txtCnpjClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "CNPJ ", None))
        self.txtCnpjClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do numero do CNPJ docliente destinatario", None))
        self.txtCnpjClienteDestinatario.setInputMask(_translate("frmEntradaVeiculosCarregamento", "00.000.000/0000-00; ", None))
        self.lblCep.setText(_translate("frmEntradaVeiculosCarregamento", "CEP", None))
        self.lblCidade.setText(_translate("frmEntradaVeiculosCarregamento", "Cidade", None))
        self.txtCidade.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Cidade", None))
        self.txtCidade.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do nome da cidade onde fica localizado o cliente destinatario</p></body></html>", None))
        self.txtEndereco.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Endereço", None))
        self.txtEndereco.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do endereço do cliente destinatario</p></body></html>", None))
        self.txtEstado.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Estado", None))
        self.txtEstado.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do nome do estado onde fica localizado a cidade o cliente destinatario</p></body></html>", None))
        self.txtCep.setToolTip(_translate("frmEntradaVeiculosCarregamento", "CEP", None))
        self.txtCep.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do número do CEP da cidade onde fica localizada o cliente destinatario</p></body></html>", None))
        self.txtCep.setInputMask(_translate("frmEntradaVeiculosCarregamento", "00000-000; ", None))
        self.txtBairro.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Bairro", None))
        self.txtBairro.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do nome do bairro do endereço do cliente destinatario</p></body></html>", None))
        self.lblEndereco.setText(_translate("frmEntradaVeiculosCarregamento", "Endereço", None))
        self.txtComplemento.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Complemento", None))
        self.txtComplemento.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do complemento do endereço do cliente destinatario</p></body></html>", None))
        self.lblNumero.setText(_translate("frmEntradaVeiculosCarregamento", "Numero", None))
        self.txtNumero.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Número", None))
        self.txtNumero.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Campo do número do endereço do cliente destinatario</p></body></html>", None))
        self.lblBairro.setText(_translate("frmEntradaVeiculosCarregamento", "Bairro", None))
        self.lblEstado.setText(_translate("frmEntradaVeiculosCarregamento", "Estado", None))
        self.lblComplemento.setText(_translate("frmEntradaVeiculosCarregamento", "Complemento", None))
        self.lblHoraEntrada.setText(_translate("frmEntradaVeiculosCarregamento", "Hora Entrada", None))
        self.txtData.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Data Entrada", None))
        self.txtHora.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Hora Entrada", None))
        self.lblDataEntrada.setText(_translate("frmEntradaVeiculosCarregamento", "Data Entrada", None))
        self.txtTipoCarga.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Tipo de Carga", None))
        self.lblTipoCarga.setText(_translate("frmEntradaVeiculosCarregamento", "Tipo de Carga", None))
        self.txtProduto.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Tipo de Carga", None))
        self.lblProduto.setText(_translate("frmEntradaVeiculosCarregamento", "Produto", None))
        self.btnNovo.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Novo", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Botão para cadastrar uma novo registro da pessoa jurídica</p></body></html>", None))
        self.btnNovo.setText(_translate("frmEntradaVeiculosCarregamento", "Novo", None))
        self.btnSalvar.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Salvar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "<html><head/><body><p>Botão para salvar um novo registro da pessoa jurídica</p></body></html>", None))
        self.btnSalvar.setText(_translate("frmEntradaVeiculosCarregamento", "Salvar", None))
        self.btnCancelar.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Cancelar", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Botão para cancelar a operação ", None))
        self.btnCancelar.setText(_translate("frmEntradaVeiculosCarregamento", "Cancelar", None))

