# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaNotas.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

import datetime
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaNotaRomaneios(object):
    def setupUi(self, frmEntradaNotaRomaneios):
        frmEntradaNotaRomaneios.setObjectName(_fromUtf8("frmEntradaNotaRomaneios"))
        frmEntradaNotaRomaneios.resize(1003, 689)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmEntradaNotaRomaneios.setFont(font)
        frmEntradaNotaRomaneios.setSizeGripEnabled(False)
        frmEntradaNotaRomaneios.setModal(True)

        self.grbDadosEmitente = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbDadosEmitente.setEnabled(False)
        self.grbDadosEmitente.setGeometry(QtCore.QRect(6, -1, 991, 106))
        self.grbDadosEmitente.setObjectName(_fromUtf8("grbDadosEmitente"))

        self.txtIdEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtIdEmitente.setEnabled(False)
        self.txtIdEmitente.setGeometry(QtCore.QRect(14, 33, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmitente.setPalette(palette)
        self.txtIdEmitente.setMaxLength(11)
        self.txtIdEmitente.setObjectName(_fromUtf8("txtIdEmitente"))

        self.txtNomeEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtNomeEmitente.setGeometry(QtCore.QRect(207, 33, 551, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmitente.setPalette(palette)
        self.txtNomeEmitente.setMaxLength(70)
        self.txtNomeEmitente.setObjectName(_fromUtf8("txtNomeEmitente"))

        self.btnPesquisarEmitente = QtGui.QPushButton(self.grbDadosEmitente)
        self.btnPesquisarEmitente.setGeometry(QtCore.QRect(770, 33, 31, 25))
        self.btnPesquisarEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarEmitente.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarEmitente.setIcon(icon)
        self.btnPesquisarEmitente.setObjectName(_fromUtf8("btnPesquisarEmitente"))

        self.lblCodigoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCodigoEmitente.setGeometry(QtCore.QRect(14, 13, 131, 21))
        self.lblCodigoEmitente.setObjectName(_fromUtf8("lblCodigoEmitente"))

        self.lblNomeEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblNomeEmitente.setGeometry(QtCore.QRect(207, 13, 161, 16))
        self.lblNomeEmitente.setObjectName(_fromUtf8("lblNomeEmitente"))

        self.txtInscricaoEstaduaEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtInscricaoEstaduaEmitente.setEnabled(False)
        self.txtInscricaoEstaduaEmitente.setGeometry(QtCore.QRect(710, 76, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmitente.setPalette(palette)
        self.txtInscricaoEstaduaEmitente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstaduaEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtInscricaoEstaduaEmitente.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmitente.setMaxLength(8)
        self.txtInscricaoEstaduaEmitente.setObjectName(_fromUtf8("txtInscricaoEstaduaEmitente"))

        self.txtRazaoSocialEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtRazaoSocialEmitente.setEnabled(False)
        self.txtRazaoSocialEmitente.setGeometry(QtCore.QRect(13, 76, 501, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmitente.setPalette(palette)
        self.txtRazaoSocialEmitente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocialEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRazaoSocialEmitente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmitente.setMaxLength(70)
        self.txtRazaoSocialEmitente.setObjectName(_fromUtf8("txtRazaoSocialEmitente"))

        self.lblRazaoSocialEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblRazaoSocialEmitente.setGeometry(QtCore.QRect(13, 56, 81, 19))
        self.lblRazaoSocialEmitente.setObjectName(_fromUtf8("lblRazaoSocialEmitente"))

        self.lblCnpjEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCnpjEmitente.setGeometry(QtCore.QRect(522, 56, 41, 19))
        self.lblCnpjEmitente.setObjectName(_fromUtf8("lblCnpjEmitente"))
        self.lblInscricaoEstadualEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblInscricaoEstadualEmitente.setGeometry(QtCore.QRect(710, 56, 121, 19))
        self.lblInscricaoEstadualEmitente.setObjectName(_fromUtf8("lblInscricaoEstadualEmitente"))

        self.txtCnpjEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCnpjEmitente.setEnabled(False)
        self.txtCnpjEmitente.setGeometry(QtCore.QRect(522, 76, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmitente.setPalette(palette)
        self.txtCnpjEmitente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpjEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCnpjEmitente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmitente.setText(_fromUtf8("../-"))
        self.txtCnpjEmitente.setCursorPosition(0)
        self.txtCnpjEmitente.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmitente.setObjectName(_fromUtf8("txtCnpjEmitente"))

        self.grbDadosDestinatario = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbDadosDestinatario.setEnabled(False)
        self.grbDadosDestinatario.setGeometry(QtCore.QRect(6, 102, 991, 111))
        self.grbDadosDestinatario.setObjectName(_fromUtf8("grbDadosDestinatario"))

        self.txtCnpjDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCnpjDestinatario.setEnabled(False)
        self.txtCnpjDestinatario.setGeometry(QtCore.QRect(530, 79, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjDestinatario.setPalette(palette)
        self.txtCnpjDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpjDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCnpjDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjDestinatario.setCursorPosition(0)
        self.txtCnpjDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjDestinatario.setObjectName(_fromUtf8("txtCnpjDestinatario"))

        self.lblCodigoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCodigoDestinatario.setGeometry(QtCore.QRect(13, 15, 151, 19))
        self.lblCodigoDestinatario.setObjectName(_fromUtf8("lblCodigoDestinatario"))

        self.lblNomeFantasiaDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblNomeFantasiaDestinatario.setGeometry(QtCore.QRect(210, 15, 181, 19))
        self.lblNomeFantasiaDestinatario.setObjectName(_fromUtf8("lblNomeFantasiaDestinatario"))

        self.lblCnpjDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCnpjDestinatario.setGeometry(QtCore.QRect(530, 59, 41, 19))
        self.lblCnpjDestinatario.setObjectName(_fromUtf8("lblCnpjDestinatario"))

        self.txtFantasiaDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtFantasiaDestinatario.setGeometry(QtCore.QRect(210, 35, 551, 25))
        self.txtFantasiaDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasiaDestinatario.setPalette(palette)
        self.txtFantasiaDestinatario.setMaxLength(70)
        self.txtFantasiaDestinatario.setObjectName(_fromUtf8("txtFantasiaDestinatario"))

        self.txtRazaoSocialDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtRazaoSocialDestinatario.setEnabled(False)
        self.txtRazaoSocialDestinatario.setGeometry(QtCore.QRect(13, 79, 511, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialDestinatario.setPalette(palette)
        self.txtRazaoSocialDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocialDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRazaoSocialDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialDestinatario.setMaxLength(70)
        self.txtRazaoSocialDestinatario.setObjectName(_fromUtf8("txtRazaoSocialDestinatario"))

        self.lblRazaoSocialDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblRazaoSocialDestinatario.setGeometry(QtCore.QRect(13, 59, 81, 19))
        self.lblRazaoSocialDestinatario.setObjectName(_fromUtf8("lblRazaoSocialDestinatario"))

        self.txtIdDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtIdDestinatario.setEnabled(False)
        self.txtIdDestinatario.setGeometry(QtCore.QRect(13, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdDestinatario.setPalette(palette)
        self.txtIdDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdDestinatario.setMaxLength(11)
        self.txtIdDestinatario.setObjectName(_fromUtf8("txtIdDestinatario"))

        self.txtInscricaoEstaduaDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtInscricaoEstaduaDestinatario.setEnabled(False)
        self.txtInscricaoEstaduaDestinatario.setGeometry(QtCore.QRect(718, 79, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaDestinatario.setPalette(palette)
        self.txtInscricaoEstaduaDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstaduaDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtInscricaoEstaduaDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaDestinatario"))

        self.lblInscricaoEstadualDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblInscricaoEstadualDestinatario.setGeometry(QtCore.QRect(718, 59, 121, 19))
        self.lblInscricaoEstadualDestinatario.setObjectName(_fromUtf8("lblInscricaoEstadualDestinatario"))

        self.btnPesquisarDestinatario = QtGui.QPushButton(self.grbDadosDestinatario)
        self.btnPesquisarDestinatario.setGeometry(QtCore.QRect(774, 34, 31, 27))
        self.btnPesquisarDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarDestinatario.setText(_fromUtf8(""))
        self.btnPesquisarDestinatario.setIcon(icon)
        self.btnPesquisarDestinatario.setObjectName(_fromUtf8("btnPesquisarDestinatario"))

        self.grbBotoes = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbBotoes.setGeometry(QtCore.QRect(5, 614, 993, 72))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(470, 5, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(770, 5, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(574, 5, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(674, 5, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.lblF12 = QtGui.QLabel(self.grbBotoes)
        self.lblF12.setGeometry(QtCore.QRect(5, 49, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(17, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblF12.setPalette(palette)
        self.lblF12.setObjectName(_fromUtf8("lblF12"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(870, 5, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.grbDadosNotaFiscal = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbDadosNotaFiscal.setEnabled(False)
        self.grbDadosNotaFiscal.setGeometry(QtCore.QRect(6, 330, 531, 71))
        self.grbDadosNotaFiscal.setObjectName(_fromUtf8("grbDadosNotaFiscal"))

        self.lblNumeroNotaFiscal = QtGui.QLabel(self.grbDadosNotaFiscal)
        self.lblNumeroNotaFiscal.setGeometry(QtCore.QRect(10, 17, 131, 16))
        self.lblNumeroNotaFiscal.setObjectName(_fromUtf8("lblNumeroNotaFiscal"))

        self.txtNumeroNotaFiscal = QtGui.QLineEdit(self.grbDadosNotaFiscal)
        self.txtNumeroNotaFiscal.setGeometry(QtCore.QRect(10, 37, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroNotaFiscal.setPalette(palette)
        self.txtNumeroNotaFiscal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtNumeroNotaFiscal.setMaxLength(11)
        self.txtNumeroNotaFiscal.setObjectName(_fromUtf8("txtNumeroNotaFiscal"))

        self.lblDataEmissao = QtGui.QLabel(self.grbDadosNotaFiscal)
        self.lblDataEmissao.setGeometry(QtCore.QRect(196, 19, 91, 16))
        self.lblDataEmissao.setObjectName(_fromUtf8("lblDataEmissao"))

        self.txtValorTotal = QtGui.QLineEdit(self.grbDadosNotaFiscal)
        self.txtValorTotal.setGeometry(QtCore.QRect(340, 40, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtValorTotal.setPalette(palette)
        self.txtValorTotal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtValorTotal.setMaxLength(17)
        self.txtValorTotal.setCursorPosition(17)
        self.txtValorTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorTotal.setObjectName(_fromUtf8("txtValorTotal"))

        self.lblValorTotal = QtGui.QLabel(self.grbDadosNotaFiscal)
        self.lblValorTotal.setGeometry(QtCore.QRect(340, 20, 151, 16))
        self.lblValorTotal.setObjectName(_fromUtf8("lblValorTotal"))

        self.txtDataEmissao = QtGui.QDateEdit(self.grbDadosNotaFiscal)
        self.txtDataEmissao.setDate(QDate.currentDate())
        self.txtDataEmissao.setGeometry(QtCore.QRect(194, 37, 141, 25))
        self.txtDataEmissao.setCalendarPopup(True)
        self.txtDataEmissao.setObjectName(_fromUtf8("txtDataEmissao"))

        self.grbDadosMotorista = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(6, 210, 992, 121))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))

        self.txtidMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidMotorista.setEnabled(False)
        self.txtidMotorista.setGeometry(QtCore.QRect(10, 40, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidMotorista.setPalette(palette)
        self.txtidMotorista.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidMotorista.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtidMotorista.setMaxLength(11)
        self.txtidMotorista.setObjectName(_fromUtf8("txtidMotorista"))

        self.txtCpf = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtCpf.setEnabled(False)
        self.txtCpf.setGeometry(QtCore.QRect(200, 86, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCpf.setPalette(palette)
        self.txtCpf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCpf.setMaxLength(14)
        self.txtCpf.setObjectName(_fromUtf8("txtCpf"))

        self.txtRg = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtRg.setEnabled(False)
        self.txtRg.setGeometry(QtCore.QRect(10, 86, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRg.setPalette(palette)
        self.txtRg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRg.setObjectName(_fromUtf8("txtRg"))

        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(210, 20, 181, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))

        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(210, 40, 488, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMotorista.setPalette(palette)
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))

        self.lblRg = QtGui.QLabel(self.grbDadosMotorista)
        self.lblRg.setGeometry(QtCore.QRect(10, 66, 91, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))

        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))

        self.lblCpfMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCpfMotorista.setGeometry(QtCore.QRect(200, 66, 81, 19))
        self.lblCpfMotorista.setObjectName(_fromUtf8("lblCpfMotorista"))

        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(710, 39, 31, 27))
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        self.btnPesquisarMotorista.setIcon(icon)
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))

        self.lblMarca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarca.setGeometry(QtCore.QRect(390, 67, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))

        self.txtMarca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarca.setEnabled(False)
        self.txtMarca.setGeometry(QtCore.QRect(390, 87, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarca.setPalette(palette)
        self.txtMarca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtMarca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))

        self.lblModelo = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModelo.setGeometry(QtCore.QRect(600, 66, 51, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))

        self.txtModelo = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModelo.setEnabled(False)
        self.txtModelo.setGeometry(QtCore.QRect(600, 86, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModelo.setPalette(palette)
        self.txtModelo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtModelo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))

        self.lblPlaca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlaca.setGeometry(QtCore.QRect(810, 66, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))

        self.txtPlaca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlaca.setEnabled(False)
        self.txtPlaca.setGeometry(QtCore.QRect(811, 86, 168, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlaca.setPalette(palette)
        self.txtPlaca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtPlaca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))

        self.grbDadosRomaneio = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbDadosRomaneio.setEnabled(False)
        self.grbDadosRomaneio.setGeometry(QtCore.QRect(540, 330, 458, 71))
        self.grbDadosRomaneio.setObjectName(_fromUtf8("grbDadosRomaneio"))

        self.txtNumeroRomaneio = QtGui.QLineEdit(self.grbDadosRomaneio)
        self.txtNumeroRomaneio.setGeometry(QtCore.QRect(10, 40, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroRomaneio.setPalette(palette)
        self.txtNumeroRomaneio.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtNumeroRomaneio.setMaxLength(11)
        self.txtNumeroRomaneio.setObjectName(_fromUtf8("txtNumeroRomaneio"))

        self.lblNumeroRomaneio = QtGui.QLabel(self.grbDadosRomaneio)
        self.lblNumeroRomaneio.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.lblNumeroRomaneio.setObjectName(_fromUtf8("lblNumeroRomaneio"))

        self.txtMetragemMadeira = QtGui.QComboBox(self.grbDadosRomaneio)
        self.txtMetragemMadeira.setGeometry(QtCore.QRect(220, 40, 207, 25))
        self.txtMetragemMadeira.setObjectName(_fromUtf8("txtMetragemMadeira"))

        self.lblMetragemMadeira = QtGui.QLabel(self.grbDadosRomaneio)
        self.lblMetragemMadeira.setGeometry(QtCore.QRect(220, 20, 131, 16))
        self.lblMetragemMadeira.setObjectName(_fromUtf8("lblMetragemMadeira"))

        self.txtCertificada = QtGui.QCheckBox(self.grbDadosRomaneio)
        self.txtCertificada.setGeometry(QtCore.QRect(363, 14, 91, 17))
        self.txtCertificada.setToolTip(_fromUtf8(""))
        self.txtCertificada.setObjectName(_fromUtf8("txtCertificada"))

        self.grbDadosProduto = QtGui.QGroupBox(frmEntradaNotaRomaneios)
        self.grbDadosProduto.setEnabled(False)
        self.grbDadosProduto.setGeometry(QtCore.QRect(5, 400, 993, 211))
        self.grbDadosProduto.setToolTip(_fromUtf8(""))
        self.grbDadosProduto.setWhatsThis(_fromUtf8(""))
        self.grbDadosProduto.setObjectName(_fromUtf8("grbDadosProduto"))

        self.lblTipoCargaServco = QtGui.QLabel(self.grbDadosProduto)
        self.lblTipoCargaServco.setGeometry(QtCore.QRect(6, 16, 161, 16))
        self.lblTipoCargaServco.setObjectName(_fromUtf8("lblTipoCargaServco"))

        self.txtQuantidade = QtGui.QLineEdit(self.grbDadosProduto)
        self.txtQuantidade.setGeometry(QtCore.QRect(582, 36, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtQuantidade.setPalette(palette)
        self.txtQuantidade.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtQuantidade.setMaxLength(11)
        self.txtQuantidade.setAlignment(QtCore.Qt.AlignCenter)
        self.txtQuantidade.setObjectName(_fromUtf8("txtQuantidade"))

        self.txtValorUnitario = QtGui.QLineEdit(self.grbDadosProduto)
        self.txtValorUnitario.setGeometry(QtCore.QRect(769, 36, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtValorUnitario.setPalette(palette)
        self.txtValorUnitario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtValorUnitario.setMaxLength(17)
        self.txtValorUnitario.setCursorPosition(17)
        self.txtValorUnitario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorUnitario.setObjectName(_fromUtf8("txtValorUnitario"))

        self.lblQuantidade = QtGui.QLabel(self.grbDadosProduto)
        self.lblQuantidade.setGeometry(QtCore.QRect(582, 16, 81, 16))
        self.lblQuantidade.setObjectName(_fromUtf8("lblQuantidade"))

        self.lblValorUnitario = QtGui.QLabel(self.grbDadosProduto)
        self.lblValorUnitario.setGeometry(QtCore.QRect(769, 16, 91, 16))
        self.lblValorUnitario.setObjectName(_fromUtf8("lblValorUnitario"))

        self.txtTipoProdutoServico = QtGui.QComboBox(self.grbDadosProduto)
        self.txtTipoProdutoServico.setGeometry(QtCore.QRect(256, 36, 261, 25))
        self.txtTipoProdutoServico.setObjectName(_fromUtf8("txtTipoProdutoServico"))

        self.lblTipoProdutoServico = QtGui.QLabel(self.grbDadosProduto)
        self.lblTipoProdutoServico.setGeometry(QtCore.QRect(256, 16, 181, 16))
        self.lblTipoProdutoServico.setObjectName(_fromUtf8("lblTipoProdutoServico"))

        self.tbProduto = QtGui.QTableWidget(self.grbDadosProduto)
        self.tbProduto.setGeometry(QtCore.QRect(6, 66, 981, 111))
        self.tbProduto.setColumnCount(5)
        self.tbProduto.setHorizontalHeaderLabels(['Tipo Carga', 'Tipo Produto', 'UN', 'QTD', 'Valor Unitario'])
        self.tbProduto.setEditTriggers(self.tbProduto.NoEditTriggers)
        self.tbProduto.setSelectionBehavior(self.tbProduto.SelectRows)
        #self.tbProduto.setSelectionMode(self.tbProduto.SingleSelection)
        self.tbProduto.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbProduto.setObjectName(_fromUtf8("tbProduto"))

        self.txtTipoCargaServico = QtGui.QComboBox(self.grbDadosProduto)
        self.txtTipoCargaServico.setGeometry(QtCore.QRect(6, 36, 241, 25))
        self.txtTipoCargaServico.setObjectName(_fromUtf8("txtTipoCargaServico"))

        self.btnExcluir = QtGui.QPushButton(self.grbDadosProduto)
        self.btnExcluir.setGeometry(QtCore.QRect(956, 178, 31, 27))
        self.btnExcluir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnExcluir.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExcluir.setIcon(icon1)
        self.btnExcluir.setObjectName(_fromUtf8("btnExcluir"))

        self.btnAdicionar = QtGui.QPushButton(self.grbDadosProduto)
        self.btnAdicionar.setGeometry(QtCore.QRect(956, 34, 31, 27))
        self.btnAdicionar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAdicionar.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdicionar.setIcon(icon2)
        self.btnAdicionar.setObjectName(_fromUtf8("btnAdicionar"))

        self.txtUn = QtGui.QComboBox(self.grbDadosProduto)
        self.txtUn.setGeometry(QtCore.QRect(520, 36, 60, 25))
        self.txtUn.setObjectName(_fromUtf8("txtUn"))
        self.lblUn = QtGui.QLabel(self.grbDadosProduto)
        self.lblUn.setGeometry(QtCore.QRect(533, 16, 31, 16))
        self.lblUn.setObjectName(_fromUtf8("lblUn"))

        self.lblCodigoEmitente.setBuddy(self.txtIdEmitente)
        self.lblNomeEmitente.setBuddy(self.txtNomeEmitente)
        self.lblRazaoSocialEmitente.setBuddy(self.txtRazaoSocialEmitente)
        self.lblCnpjEmitente.setBuddy(self.txtCnpjEmitente)
        self.lblInscricaoEstadualEmitente.setBuddy(self.txtInscricaoEstaduaEmitente)
        self.lblCodigoDestinatario.setBuddy(self.txtIdDestinatario)
        self.lblNomeFantasiaDestinatario.setBuddy(self.txtFantasiaDestinatario)
        self.lblCnpjDestinatario.setBuddy(self.txtCnpjDestinatario)
        self.lblRazaoSocialDestinatario.setBuddy(self.txtRazaoSocialDestinatario)
        self.lblInscricaoEstadualDestinatario.setBuddy(self.txtInscricaoEstaduaDestinatario)
        self.lblNumeroNotaFiscal.setBuddy(self.txtNumeroNotaFiscal)
        self.lblDataEmissao.setBuddy(self.txtDataEmissao)
        self.lblValorTotal.setBuddy(self.txtValorTotal)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblRg.setBuddy(self.txtRg)
        self.lblCodigoMotorista.setBuddy(self.txtidMotorista)
        self.lblCpfMotorista.setBuddy(self.txtCpf)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblPlaca.setBuddy(self.txtPlaca)
        self.lblNumeroRomaneio.setBuddy(self.txtNumeroRomaneio)
        self.lblMetragemMadeira.setBuddy(self.txtMetragemMadeira)
        self.lblTipoCargaServco.setBuddy(self.txtTipoProdutoServico)
        self.lblQuantidade.setBuddy(self.txtQuantidade)
        self.lblValorUnitario.setBuddy(self.txtValorUnitario)
        self.lblTipoProdutoServico.setBuddy(self.txtTipoProdutoServico)
        self.lblUn.setBuddy(self.txtUn)

        self.retranslateUi(frmEntradaNotaRomaneios)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaNotaRomaneios)
        frmEntradaNotaRomaneios.setTabOrder(self.txtIdEmitente, self.txtNomeEmitente)
        frmEntradaNotaRomaneios.setTabOrder(self.txtNomeEmitente, self.txtIdDestinatario)
        frmEntradaNotaRomaneios.setTabOrder(self.txtIdDestinatario, self.txtFantasiaDestinatario)
        frmEntradaNotaRomaneios.setTabOrder(self.txtFantasiaDestinatario, self.txtidMotorista)
        frmEntradaNotaRomaneios.setTabOrder(self.txtidMotorista, self.txtNomeMotorista)
        frmEntradaNotaRomaneios.setTabOrder(self.txtNomeMotorista, self.txtNumeroNotaFiscal)
        frmEntradaNotaRomaneios.setTabOrder(self.txtNumeroNotaFiscal, self.txtDataEmissao)
        frmEntradaNotaRomaneios.setTabOrder(self.txtDataEmissao, self.txtValorTotal)
        frmEntradaNotaRomaneios.setTabOrder(self.txtValorTotal, self.txtNumeroRomaneio)
        frmEntradaNotaRomaneios.setTabOrder(self.txtNumeroRomaneio, self.txtMetragemMadeira)
        frmEntradaNotaRomaneios.setTabOrder(self.txtMetragemMadeira, self.txtCertificada)
        frmEntradaNotaRomaneios.setTabOrder(self.txtCertificada, self.txtTipoCargaServico)
        frmEntradaNotaRomaneios.setTabOrder(self.txtTipoCargaServico, self.txtTipoProdutoServico)
        frmEntradaNotaRomaneios.setTabOrder(self.txtTipoProdutoServico, self.txtUn)
        frmEntradaNotaRomaneios.setTabOrder(self.txtUn, self.txtQuantidade)
        frmEntradaNotaRomaneios.setTabOrder(self.txtQuantidade, self.txtValorUnitario)

    def retranslateUi(self, frmEntradaNotaRomaneios):
        frmEntradaNotaRomaneios.setWindowTitle(_translate("frmEntradaNotaRomaneios", "Entrada de Notas Fiscais e Romaneios", None))
        self.grbDadosEmitente.setTitle(_translate("frmEntradaNotaRomaneios", "Dados do Emitente", None))
        self.txtIdEmitente.setToolTip(_translate("frmEntradaNotaRomaneios", "Codigo Emitente", None))
        self.txtIdEmitente.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do codigo de identificação do emitente", None))
        self.txtNomeEmitente.setToolTip(_translate("frmEntradaNotaRomaneios", "Nome Fantasia Emitente", None))
        self.txtNomeEmitente.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome fantasia  do emitente", None))
        self.lblCodigoEmitente.setText(_translate("frmEntradaNotaRomaneios", "Codigo Emitente", None))
        self.lblNomeEmitente.setText(_translate("frmEntradaNotaRomaneios", "Nome Fantasia Emitente", None))
        self.txtInscricaoEstaduaEmitente.setToolTip(_translate("frmEntradaNotaRomaneios", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmitente.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do numero do inscrição estadual do emitente", None))
        self.txtRazaoSocialEmitente.setToolTip(_translate("frmEntradaNotaRomaneios", "Razão Social ", None))
        self.txtRazaoSocialEmitente.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome da razão social do emitente", None))
        self.lblRazaoSocialEmitente.setText(_translate("frmEntradaNotaRomaneios", "Razão Social", None))
        self.lblCnpjEmitente.setText(_translate("frmEntradaNotaRomaneios", "CNPJ", None))
        self.lblInscricaoEstadualEmitente.setText(_translate("frmEntradaNotaRomaneios", "Incrição Estadual", None))
        self.txtCnpjEmitente.setToolTip(_translate("frmEntradaNotaRomaneios", "CNPJ ", None))
        self.txtCnpjEmitente.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do numero do CNPJ do emitente", None))
        self.txtCnpjEmitente.setInputMask(_translate("frmEntradaNotaRomaneios", "00.000.000/0000-00; ", None))
        self.grbDadosDestinatario.setTitle(_translate("frmEntradaNotaRomaneios", "Dados Destinatario", None))
        self.txtCnpjDestinatario.setToolTip(_translate("frmEntradaNotaRomaneios", "CNPJ ", None))
        self.txtCnpjDestinatario.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do numero do CNPJ do destinatario", None))
        self.txtCnpjDestinatario.setInputMask(_translate("frmEntradaNotaRomaneios", "00.000.000/0000-00; ", None))
        self.lblCodigoDestinatario.setText(_translate("frmEntradaNotaRomaneios", "Codigo do Destinatario", None))
        self.lblNomeFantasiaDestinatario.setText(_translate("frmEntradaNotaRomaneios", "Nome Fantasia Destinatario", None))
        self.lblCnpjDestinatario.setText(_translate("frmEntradaNotaRomaneios", "CNPJ", None))
        self.txtFantasiaDestinatario.setToolTip(_translate("frmEntradaNotaRomaneios", "Nome Fantasia Destinatario", None))
        self.txtFantasiaDestinatario.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome fantasia do destinatario", None))
        self.txtRazaoSocialDestinatario.setToolTip(_translate("frmEntradaNotaRomaneios", "Razão Social ", None))
        self.txtRazaoSocialDestinatario.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome da razão social do destinatario", None))
        self.lblRazaoSocialDestinatario.setText(_translate("frmEntradaNotaRomaneios", "Razão Social", None))
        self.txtIdDestinatario.setToolTip(_translate("frmEntradaNotaRomaneios", "Codigo Destinatario", None))
        self.txtIdDestinatario.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do codigo de identificação do destinatario", None))
        self.txtInscricaoEstaduaDestinatario.setToolTip(_translate("frmEntradaNotaRomaneios", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaDestinatario.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do numero do inscrição estadual do destinatario", None))
        self.lblInscricaoEstadualDestinatario.setText(_translate("frmEntradaNotaRomaneios", "Incrição Estadual", None))
        self.grbBotoes.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmEntradaNotaRomaneios", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmEntradaNotaRomaneios", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmEntradaNotaRomaneios", "Salvar", None))
        self.btnEditar.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Botão de Criação de um novo registro", None))
        self.btnEditar.setText(_translate("frmEntradaNotaRomaneios", "Editar", None))
        self.lblF12.setText(_translate("frmEntradaNotaRomaneios", "F12 - [PESQUISAR]", None))
        self.btnDeletar.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Botão de cancelar a operação iniciada", None))
        self.btnDeletar.setText(_translate("frmEntradaNotaRomaneios", "Deletar", None))
        self.grbDadosNotaFiscal.setTitle(_translate("frmEntradaNotaRomaneios", "Dados Nota Fiscal", None))
        self.lblNumeroNotaFiscal.setText(_translate("frmEntradaNotaRomaneios", "Numero Nota Fiscal", None))
        self.txtNumeroNotaFiscal.setToolTip(_translate("frmEntradaNotaRomaneios", "Numero Nota Fical", None))
        self.txtNumeroNotaFiscal.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Codigo de identificação do numero da Nota Fiscal", None))
        self.lblDataEmissao.setText(_translate("frmEntradaNotaRomaneios", "Data Emissão", None))
        self.txtValorTotal.setToolTip(_translate("frmEntradaNotaRomaneios", "Valor Total Nota Fiscal", None))
        self.txtValorTotal.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do valor total da Nota Fiscal", None))
        self.txtValorTotal.setInputMask(_translate("frmEntradaNotaRomaneios", "R$ 00000000000,00; ", None))
        self.lblValorTotal.setText(_translate("frmEntradaNotaRomaneios", "Valor Total Nota Fiscal", None))
        self.txtDataEmissao.setToolTip(_translate("frmEntradaNotaRomaneios", "Data Emissão", None))
        self.txtDataEmissao.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo de data da emissão da Nota Fiscal", None))
        self.grbDadosMotorista.setTitle(_translate("frmEntradaNotaRomaneios", "Dados Transportadora / Motorista", None))
        self.txtidMotorista.setToolTip(_translate("frmEntradaNotaRomaneios", "Codigo Motorista", None))
        self.txtidMotorista.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do Codigo de identificação do Motorista", None))
        self.txtCpf.setToolTip(_translate("frmEntradaNotaRomaneios", "CPF", None))
        self.txtCpf.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do numero do CPF do Motorista", None))
        self.txtCpf.setInputMask(_translate("frmEntradaNotaRomaneios", "000.000.000-00; ", None))
        self.txtRg.setToolTip(_translate("frmEntradaNotaRomaneios", "Rg", None))
        self.txtRg.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do numero do RG do Motorista", None))
        self.txtRg.setInputMask(_translate("frmEntradaNotaRomaneios", "000000-0; ", None))
        self.lblNomeMotorista.setText(_translate("frmEntradaNotaRomaneios", "Nome Fantasia / Motorista", None))
        self.txtNomeMotorista.setToolTip(_translate("frmEntradaNotaRomaneios", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome do Motorista", None))
        self.lblRg.setText(_translate("frmEntradaNotaRomaneios", "RG / Ins.Est.", None))
        self.lblCodigoMotorista.setText(_translate("frmEntradaNotaRomaneios", "Codigo Motorista", None))
        self.lblCpfMotorista.setText(_translate("frmEntradaNotaRomaneios", "CPF / Cnpj", None))
        self.lblMarca.setText(_translate("frmEntradaNotaRomaneios", "Marca", None))
        self.txtMarca.setToolTip(_translate("frmEntradaNotaRomaneios", "Marca", None))
        self.txtMarca.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome da marca do veiculo", None))
        self.lblModelo.setText(_translate("frmEntradaNotaRomaneios", "Modelo", None))
        self.txtModelo.setToolTip(_translate("frmEntradaNotaRomaneios", "Modelo", None))
        self.txtModelo.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo do nome do modelo do veiculo", None))
        self.lblPlaca.setText(_translate("frmEntradaNotaRomaneios", "Placa", None))
        self.txtPlaca.setToolTip(_translate("frmEntradaNotaRomaneios", "Placa", None))
        self.txtPlaca.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmEntradaNotaRomaneios", "nnn-0000; ", None))
        self.grbDadosRomaneio.setTitle(_translate("frmEntradaNotaRomaneios", "Dados Romaneio", None))
        self.txtNumeroRomaneio.setToolTip(_translate("frmEntradaNotaRomaneios", "Numero Romaneio", None))
        self.txtNumeroRomaneio.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Codigo de identificação do numero do romaneio", None))
        self.lblNumeroRomaneio.setText(_translate("frmEntradaNotaRomaneios", "Numero Romaneio", None))
        self.txtMetragemMadeira.setToolTip(_translate("frmEntradaNotaRomaneios", "Metragem Madeira", None))
        self.txtMetragemMadeira.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo de escolha do tipo de metragem madeira", None))
        self.lblMetragemMadeira.setText(_translate("frmEntradaNotaRomaneios", "Metragem Madeira", None))
        self.txtCertificada.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Campo de identificação se o produto é certificado", None))
        self.txtCertificada.setText(_translate("frmEntradaNotaRomaneios", "Certificada", None))
        self.grbDadosProduto.setTitle(_translate("frmEntradaNotaRomaneios", "Dados dos Produtos / Serviços", None))
        self.lblTipoCargaServco.setText(_translate("frmEntradaNotaRomaneios", "Tipo de Carga / Serviço", None))
        self.txtQuantidade.setToolTip(_translate("frmEntradaNotaRomaneios", "Quantidade", None))
        self.txtQuantidade.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Codigo de quantidade", None))
        self.txtValorUnitario.setToolTip(_translate("frmEntradaNotaRomaneios", "Valor Unitario", None))
        self.txtValorUnitario.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Codigo do valor unitario do produto", None))
        self.txtValorUnitario.setInputMask(_translate("frmEntradaNotaRomaneios", "R$ 00000000000,00; ", None))
        self.txtValorUnitario.setText(_translate("frmEntradaNotaRomaneios", "R$ ,", None))
        self.lblQuantidade.setText(_translate("frmEntradaNotaRomaneios", "Quantidade", None))
        self.lblValorUnitario.setText(_translate("frmEntradaNotaRomaneios", "Valor Unitario", None))
        self.txtTipoProdutoServico.setToolTip(_translate("frmEntradaNotaRomaneios", "Tipo do Produto / Serviços", None))
        self.txtTipoProdutoServico.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Tipo de produto ou serviço", None))
        self.lblTipoProdutoServico.setText(_translate("frmEntradaNotaRomaneios", "Tipo de Produto / Serviços", None))
        self.txtTipoCargaServico.setToolTip(_translate("frmEntradaNotaRomaneios", "Tipo do Produto", None))
        self.txtTipoCargaServico.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Tipo de carga ou serviço", None))
        self.txtUn.setToolTip(_translate("frmEntradaNotaRomaneios", "Unidade de Medida", None))
        self.txtUn.setWhatsThis(_translate("frmEntradaNotaRomaneios", "Tipo de unidade de medida", None))
        self.lblUn.setText(_translate("frmEntradaNotaRomaneios", "UN.", None))

