# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaVeiculosDescarregamento.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaVeiculosDescarregamento(object):
    def setupUi(self, frmEntradaVeiculosDescarregamento):
        frmEntradaVeiculosDescarregamento.setObjectName(_fromUtf8("frmEntradaVeiculosDescarregamento"))
        frmEntradaVeiculosDescarregamento.resize(1012, 687)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmEntradaVeiculosDescarregamento.setFont(font)
        self.grbTipoOperacao = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbTipoOperacao.setEnabled(False)
        self.grbTipoOperacao.setGeometry(QtCore.QRect(5, 0, 631, 41))
        self.grbTipoOperacao.setObjectName(_fromUtf8("grbTipoOperacao"))
        self.radbtnDescarregamentoComNotaFiscal = QtGui.QRadioButton(self.grbTipoOperacao)
        self.radbtnDescarregamentoComNotaFiscal.setGeometry(QtCore.QRect(4, 20, 291, 17))
        self.radbtnDescarregamentoComNotaFiscal.setObjectName(_fromUtf8("radbtnDescarregamentoComNotaFiscal"))
        self.radbtnDescarregamentoSemNotaFiscal = QtGui.QRadioButton(self.grbTipoOperacao)
        self.radbtnDescarregamentoSemNotaFiscal.setGeometry(QtCore.QRect(320, 20, 291, 17))
        self.radbtnDescarregamentoSemNotaFiscal.setObjectName(_fromUtf8("radbtnDescarregamentoSemNotaFiscal"))
        self.txtData = QtGui.QDateEdit(frmEntradaVeiculosDescarregamento)
        self.txtData.setEnabled(False)
        self.txtData.setGeometry(QtCore.QRect(15, 105, 110, 22))
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.txtHora = QtGui.QTimeEdit(frmEntradaVeiculosDescarregamento)
        self.txtHora.setEnabled(False)
        self.txtHora.setGeometry(QtCore.QRect(139, 105, 118, 22))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.lblDataEntrada = QtGui.QLabel(frmEntradaVeiculosDescarregamento)
        self.lblDataEntrada.setGeometry(QtCore.QRect(15, 85, 101, 16))
        self.lblDataEntrada.setObjectName(_fromUtf8("lblDataEntrada"))
        self.lblHoraEntrada = QtGui.QLabel(frmEntradaVeiculosDescarregamento)
        self.lblHoraEntrada.setGeometry(QtCore.QRect(139, 85, 91, 16))
        self.lblHoraEntrada.setObjectName(_fromUtf8("lblHoraEntrada"))
        self.grbDadosDestinatario = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbDadosDestinatario.setEnabled(False)
        self.grbDadosDestinatario.setGeometry(QtCore.QRect(5, 337, 1001, 156))
        self.grbDadosDestinatario.setObjectName(_fromUtf8("grbDadosDestinatario"))
        self.txtCnpjDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCnpjDestinatario.setGeometry(QtCore.QRect(4, 78, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjDestinatario.setPalette(palette)
        self.txtCnpjDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjDestinatario.setObjectName(_fromUtf8("txtCnpjDestinatario"))
        self.lblCodigoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCodigoDestinatario.setGeometry(QtCore.QRect(4, 14, 151, 19))
        self.lblCodigoDestinatario.setObjectName(_fromUtf8("lblCodigoDestinatario"))
        self.lblNomeFantasiaDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblNomeFantasiaDestinatario.setGeometry(QtCore.QRect(198, 14, 181, 19))
        self.lblNomeFantasiaDestinatario.setObjectName(_fromUtf8("lblNomeFantasiaDestinatario"))
        self.lblCnpjDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCnpjDestinatario.setGeometry(QtCore.QRect(4, 58, 41, 19))
        self.lblCnpjDestinatario.setObjectName(_fromUtf8("lblCnpjDestinatario"))
        self.txtFantasiaDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtFantasiaDestinatario.setGeometry(QtCore.QRect(198, 34, 401, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtFantasiaDestinatario.setPalette(palette)
        self.txtFantasiaDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasiaDestinatario.setMaxLength(70)
        self.txtFantasiaDestinatario.setObjectName(_fromUtf8("txtFantasiaDestinatario"))
        self.txtRazaoSocialDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtRazaoSocialDestinatario.setGeometry(QtCore.QRect(610, 34, 381, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialDestinatario.setPalette(palette)
        self.txtRazaoSocialDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialDestinatario.setMaxLength(70)
        self.txtRazaoSocialDestinatario.setObjectName(_fromUtf8("txtRazaoSocialDestinatario"))
        self.lblRazaoSocialDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblRazaoSocialDestinatario.setGeometry(QtCore.QRect(610, 14, 81, 19))
        self.lblRazaoSocialDestinatario.setObjectName(_fromUtf8("lblRazaoSocialDestinatario"))
        self.txtIdDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtIdDestinatario.setGeometry(QtCore.QRect(4, 34, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdDestinatario.setPalette(palette)
        self.txtIdDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdDestinatario.setMaxLength(11)
        self.txtIdDestinatario.setObjectName(_fromUtf8("txtIdDestinatario"))
        self.txtInscricaoEstaduaDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtInscricaoEstaduaDestinatario.setGeometry(QtCore.QRect(184, 78, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaDestinatario.setPalette(palette)
        self.txtInscricaoEstaduaDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaDestinatario"))
        self.lblInscricaoEstadualDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblInscricaoEstadualDestinatario.setGeometry(QtCore.QRect(184, 58, 121, 19))
        self.lblInscricaoEstadualDestinatario.setObjectName(_fromUtf8("lblInscricaoEstadualDestinatario"))
        self.lblCepDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCepDestinatario.setGeometry(QtCore.QRect(794, 104, 61, 16))
        self.lblCepDestinatario.setObjectName(_fromUtf8("lblCepDestinatario"))
        self.lblComplementoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblComplementoDestinatario.setGeometry(QtCore.QRect(790, 60, 91, 16))
        self.lblComplementoDestinatario.setObjectName(_fromUtf8("lblComplementoDestinatario"))
        self.txtComplementoDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtComplementoDestinatario.setGeometry(QtCore.QRect(790, 80, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoDestinatario.setPalette(palette)
        self.txtComplementoDestinatario.setMaxLength(50)
        self.txtComplementoDestinatario.setObjectName(_fromUtf8("txtComplementoDestinatario"))
        self.lblCidadeDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCidadeDestinatario.setGeometry(QtCore.QRect(284, 105, 61, 16))
        self.lblCidadeDestinatario.setObjectName(_fromUtf8("lblCidadeDestinatario"))
        self.txtEnderecoDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtEnderecoDestinatario.setGeometry(QtCore.QRect(360, 78, 271, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoDestinatario.setPalette(palette)
        self.txtEnderecoDestinatario.setMaxLength(50)
        self.txtEnderecoDestinatario.setObjectName(_fromUtf8("txtEnderecoDestinatario"))
        self.txtNumeroDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtNumeroDestinatario.setGeometry(QtCore.QRect(640, 80, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroDestinatario.setPalette(palette)
        self.txtNumeroDestinatario.setMaxLength(11)
        self.txtNumeroDestinatario.setObjectName(_fromUtf8("txtNumeroDestinatario"))
        self.lblEnderecoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblEnderecoDestinatario.setGeometry(QtCore.QRect(360, 58, 61, 16))
        self.lblEnderecoDestinatario.setObjectName(_fromUtf8("lblEnderecoDestinatario"))
        self.txtBairroDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtBairroDestinatario.setGeometry(QtCore.QRect(4, 125, 271, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroDestinatario.setPalette(palette)
        self.txtBairroDestinatario.setMaxLength(50)
        self.txtBairroDestinatario.setObjectName(_fromUtf8("txtBairroDestinatario"))
        self.txtCidadeDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCidadeDestinatario.setGeometry(QtCore.QRect(284, 125, 299, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadeDestinatario.setPalette(palette)
        self.txtCidadeDestinatario.setMaxLength(70)
        self.txtCidadeDestinatario.setObjectName(_fromUtf8("txtCidadeDestinatario"))
        self.lblNumeroDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblNumeroDestinatario.setGeometry(QtCore.QRect(640, 60, 61, 16))
        self.lblNumeroDestinatario.setObjectName(_fromUtf8("lblNumeroDestinatario"))
        self.txtEstadoDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtEstadoDestinatario.setGeometry(QtCore.QRect(588, 124, 195, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadoDestinatario.setPalette(palette)
        self.txtEstadoDestinatario.setMaxLength(50)
        self.txtEstadoDestinatario.setObjectName(_fromUtf8("txtEstadoDestinatario"))
        self.txtCepDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCepDestinatario.setGeometry(QtCore.QRect(794, 124, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepDestinatario.setPalette(palette)
        self.txtCepDestinatario.setObjectName(_fromUtf8("txtCepDestinatario"))
        self.lblBairroDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblBairroDestinatario.setGeometry(QtCore.QRect(4, 105, 61, 16))
        self.lblBairroDestinatario.setObjectName(_fromUtf8("lblBairroDestinatario"))
        self.lblEstadoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblEstadoDestinatario.setGeometry(QtCore.QRect(588, 104, 61, 16))
        self.lblEstadoDestinatario.setObjectName(_fromUtf8("lblEstadoDestinatario"))
        self.btnPesquisarDestinatario = QtGui.QPushButton(self.grbDadosDestinatario)
        self.btnPesquisarDestinatario.setGeometry(QtCore.QRect(960, 122, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarDestinatario.setFont(font)
        self.btnPesquisarDestinatario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarDestinatario.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/JEFFERSON/Faculdade/Estagio I/Sistema Contorle Movimentos Portaria/imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarDestinatario.setIcon(icon)
        self.btnPesquisarDestinatario.setObjectName(_fromUtf8("btnPesquisarDestinatario"))
        self.grbDadosEmitente = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbDadosEmitente.setEnabled(False)
        self.grbDadosEmitente.setGeometry(QtCore.QRect(5, 189, 1001, 151))
        self.grbDadosEmitente.setObjectName(_fromUtf8("grbDadosEmitente"))
        self.txtIdEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtIdEmitente.setGeometry(QtCore.QRect(4, 32, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmitente.setPalette(palette)
        self.txtIdEmitente.setMaxLength(11)
        self.txtIdEmitente.setObjectName(_fromUtf8("txtIdEmitente"))
        self.txtNomeEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtNomeEmitente.setGeometry(QtCore.QRect(195, 32, 411, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmitente.setPalette(palette)
        self.txtNomeEmitente.setMaxLength(70)
        self.txtNomeEmitente.setObjectName(_fromUtf8("txtNomeEmitente"))
        self.lblCodigoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCodigoEmitente.setGeometry(QtCore.QRect(4, 12, 131, 21))
        self.lblCodigoEmitente.setObjectName(_fromUtf8("lblCodigoEmitente"))
        self.lblNomeEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblNomeEmitente.setGeometry(QtCore.QRect(195, 12, 151, 16))
        self.lblNomeEmitente.setObjectName(_fromUtf8("lblNomeEmitente"))
        self.txtEnderecoEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtEnderecoEmitente.setGeometry(QtCore.QRect(354, 75, 271, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoEmitente.setPalette(palette)
        self.txtEnderecoEmitente.setMaxLength(50)
        self.txtEnderecoEmitente.setObjectName(_fromUtf8("txtEnderecoEmitente"))
        self.txtNumeroEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtNumeroEmitente.setGeometry(QtCore.QRect(630, 75, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroEmitente.setPalette(palette)
        self.txtNumeroEmitente.setMaxLength(11)
        self.txtNumeroEmitente.setObjectName(_fromUtf8("txtNumeroEmitente"))
        self.txtComplementoEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtComplementoEmitente.setGeometry(QtCore.QRect(780, 75, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoEmitente.setPalette(palette)
        self.txtComplementoEmitente.setMaxLength(50)
        self.txtComplementoEmitente.setObjectName(_fromUtf8("txtComplementoEmitente"))
        self.txtCidadeEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCidadeEmitente.setGeometry(QtCore.QRect(286, 119, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadeEmitente.setPalette(palette)
        self.txtCidadeEmitente.setMaxLength(70)
        self.txtCidadeEmitente.setObjectName(_fromUtf8("txtCidadeEmitente"))
        self.txtEstadoEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtEstadoEmitente.setGeometry(QtCore.QRect(584, 119, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadoEmitente.setPalette(palette)
        self.txtEstadoEmitente.setMaxLength(50)
        self.txtEstadoEmitente.setObjectName(_fromUtf8("txtEstadoEmitente"))
        self.txtCepEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCepEmitente.setGeometry(QtCore.QRect(794, 119, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepEmitente.setPalette(palette)
        self.txtCepEmitente.setObjectName(_fromUtf8("txtCepEmitente"))
        self.txtBairroEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtBairroEmitente.setGeometry(QtCore.QRect(4, 119, 271, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroEmitente.setPalette(palette)
        self.txtBairroEmitente.setMaxLength(50)
        self.txtBairroEmitente.setObjectName(_fromUtf8("txtBairroEmitente"))
        self.lblEnderecoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblEnderecoEmitente.setGeometry(QtCore.QRect(354, 55, 61, 16))
        self.lblEnderecoEmitente.setObjectName(_fromUtf8("lblEnderecoEmitente"))
        self.lblNumeroEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblNumeroEmitente.setGeometry(QtCore.QRect(630, 55, 61, 16))
        self.lblNumeroEmitente.setObjectName(_fromUtf8("lblNumeroEmitente"))
        self.lblComplementoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblComplementoEmitente.setGeometry(QtCore.QRect(780, 55, 91, 16))
        self.lblComplementoEmitente.setObjectName(_fromUtf8("lblComplementoEmitente"))
        self.lblBairroEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblBairroEmitente.setGeometry(QtCore.QRect(6, 99, 61, 16))
        self.lblBairroEmitente.setObjectName(_fromUtf8("lblBairroEmitente"))
        self.lblCidadeEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCidadeEmitente.setGeometry(QtCore.QRect(284, 99, 61, 16))
        self.lblCidadeEmitente.setObjectName(_fromUtf8("lblCidadeEmitente"))
        self.lblEstadoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblEstadoEmitente.setGeometry(QtCore.QRect(584, 99, 61, 16))
        self.lblEstadoEmitente.setObjectName(_fromUtf8("lblEstadoEmitente"))
        self.lblCepEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCepEmitente.setGeometry(QtCore.QRect(794, 99, 61, 16))
        self.lblCepEmitente.setObjectName(_fromUtf8("lblCepEmitente"))
        self.txtInscricaoEstaduaEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtInscricaoEstaduaEmitente.setGeometry(QtCore.QRect(184, 75, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmitente.setPalette(palette)
        self.txtInscricaoEstaduaEmitente.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmitente.setMaxLength(8)
        self.txtInscricaoEstaduaEmitente.setObjectName(_fromUtf8("txtInscricaoEstaduaEmitente"))
        self.txtRazaoSocialEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtRazaoSocialEmitente.setGeometry(QtCore.QRect(610, 32, 381, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmitente.setPalette(palette)
        self.txtRazaoSocialEmitente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmitente.setMaxLength(70)
        self.txtRazaoSocialEmitente.setObjectName(_fromUtf8("txtRazaoSocialEmitente"))
        self.lblRazaoSocialEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblRazaoSocialEmitente.setGeometry(QtCore.QRect(610, 12, 81, 19))
        self.lblRazaoSocialEmitente.setObjectName(_fromUtf8("lblRazaoSocialEmitente"))
        self.lblCnpjEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCnpjEmitente.setGeometry(QtCore.QRect(5, 55, 41, 19))
        self.lblCnpjEmitente.setObjectName(_fromUtf8("lblCnpjEmitente"))
        self.lblInscricaoEstadualEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblInscricaoEstadualEmitente.setGeometry(QtCore.QRect(184, 55, 121, 19))
        self.lblInscricaoEstadualEmitente.setObjectName(_fromUtf8("lblInscricaoEstadualEmitente"))
        self.txtCnpjEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCnpjEmitente.setGeometry(QtCore.QRect(5, 75, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmitente.setPalette(palette)
        self.txtCnpjEmitente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmitente.setText(_fromUtf8("../-"))
        self.txtCnpjEmitente.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmitente.setObjectName(_fromUtf8("txtCnpjEmitente"))
        self.btnPesquisarEmitente = QtGui.QPushButton(self.grbDadosEmitente)
        self.btnPesquisarEmitente.setGeometry(QtCore.QRect(960, 117, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarEmitente.setFont(font)
        self.btnPesquisarEmitente.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarEmitente.setText(_fromUtf8(""))
        self.btnPesquisarEmitente.setIcon(icon)
        self.btnPesquisarEmitente.setObjectName(_fromUtf8("btnPesquisarEmitente"))
        self.btnPesquisarNotaFiscal = QtGui.QPushButton(frmEntradaVeiculosDescarregamento)
        self.btnPesquisarNotaFiscal.setEnabled(False)
        self.btnPesquisarNotaFiscal.setGeometry(QtCore.QRect(970, 19, 31, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarNotaFiscal.setFont(font)
        self.btnPesquisarNotaFiscal.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarNotaFiscal.setText(_fromUtf8(""))
        self.btnPesquisarNotaFiscal.setIcon(icon)
        self.btnPesquisarNotaFiscal.setObjectName(_fromUtf8("btnPesquisarNotaFiscal"))
        self.lblPesquisa = QtGui.QLabel(frmEntradaVeiculosDescarregamento)
        self.lblPesquisa.setGeometry(QtCore.QRect(640, 0, 141, 16))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))
        self.grbNotaFiscal = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbNotaFiscal.setEnabled(False)
        self.grbNotaFiscal.setGeometry(QtCore.QRect(5, 128, 1001, 63))
        self.grbNotaFiscal.setObjectName(_fromUtf8("grbNotaFiscal"))
        self.lblNumeroRomaneio = QtGui.QLabel(self.grbNotaFiscal)
        self.lblNumeroRomaneio.setGeometry(QtCore.QRect(580, 13, 131, 16))
        self.lblNumeroRomaneio.setObjectName(_fromUtf8("lblNumeroRomaneio"))
        self.txtMetragemMadeira = QtGui.QLineEdit(self.grbNotaFiscal)
        self.txtMetragemMadeira.setGeometry(QtCore.QRect(810, 33, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMetragemMadeira.setPalette(palette)
        self.txtMetragemMadeira.setMaxLength(50)
        self.txtMetragemMadeira.setObjectName(_fromUtf8("txtMetragemMadeira"))
        self.txtNumeroRomaneio = QtGui.QLineEdit(self.grbNotaFiscal)
        self.txtNumeroRomaneio.setGeometry(QtCore.QRect(580, 33, 221, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroRomaneio.setPalette(palette)
        self.txtNumeroRomaneio.setMaxLength(11)
        self.txtNumeroRomaneio.setObjectName(_fromUtf8("txtNumeroRomaneio"))
        self.lblMetragemMadeira = QtGui.QLabel(self.grbNotaFiscal)
        self.lblMetragemMadeira.setGeometry(QtCore.QRect(810, 13, 131, 16))
        self.lblMetragemMadeira.setObjectName(_fromUtf8("lblMetragemMadeira"))
        self.txtNumeroNotaFiscal = QtGui.QLineEdit(self.grbNotaFiscal)
        self.txtNumeroNotaFiscal.setGeometry(QtCore.QRect(4, 33, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroNotaFiscal.setPalette(palette)
        self.txtNumeroNotaFiscal.setMaxLength(11)
        self.txtNumeroNotaFiscal.setObjectName(_fromUtf8("txtNumeroNotaFiscal"))
        self.lblTipoProduto = QtGui.QLabel(self.grbNotaFiscal)
        self.lblTipoProduto.setGeometry(QtCore.QRect(194, 13, 111, 16))
        self.lblTipoProduto.setObjectName(_fromUtf8("lblTipoProduto"))
        self.txtTipoProduto = QtGui.QLineEdit(self.grbNotaFiscal)
        self.txtTipoProduto.setGeometry(QtCore.QRect(194, 33, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTipoProduto.setPalette(palette)
        self.txtTipoProduto.setMaxLength(50)
        self.txtTipoProduto.setObjectName(_fromUtf8("txtTipoProduto"))
        self.txtCertificada = QtGui.QLineEdit(self.grbNotaFiscal)
        self.txtCertificada.setGeometry(QtCore.QRect(400, 33, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCertificada.setPalette(palette)
        self.txtCertificada.setMaxLength(25)
        self.txtCertificada.setObjectName(_fromUtf8("txtCertificada"))
        self.lblNumeroNotaFiscal = QtGui.QLabel(self.grbNotaFiscal)
        self.lblNumeroNotaFiscal.setGeometry(QtCore.QRect(4, 13, 131, 16))
        self.lblNumeroNotaFiscal.setObjectName(_fromUtf8("lblNumeroNotaFiscal"))
        self.lblCertificada = QtGui.QLabel(self.grbNotaFiscal)
        self.lblCertificada.setGeometry(QtCore.QRect(400, 13, 81, 16))
        self.lblCertificada.setObjectName(_fromUtf8("lblCertificada"))
        self.grbDadosMotorista = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(5, 491, 1001, 109))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))
        self.txtModelo = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModelo.setGeometry(QtCore.QRect(710, 34, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModelo.setPalette(palette)
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))
        self.lblMarca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarca.setGeometry(QtCore.QRect(4, 58, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))
        self.txtMarca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarca.setGeometry(QtCore.QRect(4, 78, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarca.setPalette(palette)
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(174, 34, 521, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeFuncionario.setPalette(palette)
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(174, 14, 171, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtPlaca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlaca.setGeometry(QtCore.QRect(344, 78, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlaca.setPalette(palette)
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))
        self.lblModelo = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModelo.setGeometry(QtCore.QRect(710, 14, 51, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setGeometry(QtCore.QRect(5, 34, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(4, 14, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblPlaca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlaca.setGeometry(QtCore.QRect(344, 58, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))
        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(582, 76, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarMotorista.setFont(font)
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        self.btnPesquisarMotorista.setIcon(icon)
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        self.grbBotoes = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbBotoes.setGeometry(QtCore.QRect(5, 603, 1001, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(600, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(500, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(700, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(800, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(900, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        self.grbTipoPesquisa = QtGui.QGroupBox(frmEntradaVeiculosDescarregamento)
        self.grbTipoPesquisa.setEnabled(False)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(5, 40, 631, 39))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))
        self.radbtnNumeroNota = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnNumeroNota.setGeometry(QtCore.QRect(4, 19, 151, 17))
        self.radbtnNumeroNota.setObjectName(_fromUtf8("radbtnNumeroNota"))
        self.radbtnNumeroRomaneio = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnNumeroRomaneio.setGeometry(QtCore.QRect(170, 19, 141, 17))
        self.radbtnNumeroRomaneio.setObjectName(_fromUtf8("radbtnNumeroRomaneio"))
        self.radbtnEmitente = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnEmitente.setGeometry(QtCore.QRect(326, 19, 81, 17))
        self.radbtnEmitente.setObjectName(_fromUtf8("radbtnEmitente"))
        self.radbtnDstinatario = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnDstinatario.setGeometry(QtCore.QRect(416, 19, 101, 17))
        self.radbtnDstinatario.setObjectName(_fromUtf8("radbtnDstinatario"))
        self.radbtnMotorista = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnMotorista.setGeometry(QtCore.QRect(536, 19, 81, 17))
        self.radbtnMotorista.setObjectName(_fromUtf8("radbtnMotorista"))
        self.txtPesquisar = QtGui.QLineEdit(frmEntradaVeiculosDescarregamento)
        self.txtPesquisar.setEnabled(False)
        self.txtPesquisar.setGeometry(QtCore.QRect(640, 20, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisar.setPalette(palette)
        self.txtPesquisar.setMaxLength(70)
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))
        self.tabPesquisar = QtGui.QTableWidget(frmEntradaVeiculosDescarregamento)
        self.tabPesquisar.setEnabled(False)
        self.tabPesquisar.setGeometry(QtCore.QRect(640, 50, 361, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tabPesquisar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tabPesquisar.setFont(font)
        self.tabPesquisar.setObjectName(_fromUtf8("tabPesquisar"))
        self.tabPesquisar.setColumnCount(0)
        self.tabPesquisar.setRowCount(0)
        self.lblDataEntrada.setBuddy(self.txtData)
        self.lblHoraEntrada.setBuddy(self.txtHora)
        self.lblCodigoDestinatario.setBuddy(self.txtIdDestinatario)
        self.lblNomeFantasiaDestinatario.setBuddy(self.txtFantasiaDestinatario)
        self.lblCnpjDestinatario.setBuddy(self.txtCnpjDestinatario)
        self.lblRazaoSocialDestinatario.setBuddy(self.txtRazaoSocialDestinatario)
        self.lblInscricaoEstadualDestinatario.setBuddy(self.txtInscricaoEstaduaDestinatario)
        self.lblCepDestinatario.setBuddy(self.txtCepDestinatario)
        self.lblComplementoDestinatario.setBuddy(self.txtComplementoDestinatario)
        self.lblCidadeDestinatario.setBuddy(self.txtCidadeDestinatario)
        self.lblEnderecoDestinatario.setBuddy(self.txtEnderecoDestinatario)
        self.lblNumeroDestinatario.setBuddy(self.txtNumeroDestinatario)
        self.lblBairroDestinatario.setBuddy(self.txtBairroDestinatario)
        self.lblEstadoDestinatario.setBuddy(self.txtEstadoDestinatario)
        self.lblCodigoEmitente.setBuddy(self.txtIdEmitente)
        self.lblNomeEmitente.setBuddy(self.txtNomeEmitente)
        self.lblEnderecoEmitente.setBuddy(self.txtEnderecoEmitente)
        self.lblNumeroEmitente.setBuddy(self.txtNumeroEmitente)
        self.lblComplementoEmitente.setBuddy(self.txtComplementoEmitente)
        self.lblBairroEmitente.setBuddy(self.txtBairroEmitente)
        self.lblCidadeEmitente.setBuddy(self.txtCidadeEmitente)
        self.lblEstadoEmitente.setBuddy(self.txtEstadoEmitente)
        self.lblCepEmitente.setBuddy(self.txtCepEmitente)
        self.lblRazaoSocialEmitente.setBuddy(self.txtRazaoSocialEmitente)
        self.lblCnpjEmitente.setBuddy(self.txtCnpjEmitente)
        self.lblInscricaoEstadualEmitente.setBuddy(self.txtInscricaoEstaduaEmitente)
        self.lblPesquisa.setBuddy(self.txtPesquisar)
        self.lblNumeroRomaneio.setBuddy(self.txtNumeroRomaneio)
        self.lblMetragemMadeira.setBuddy(self.txtMetragemMadeira)
        self.lblTipoProduto.setBuddy(self.txtTipoProduto)
        self.lblNumeroNotaFiscal.setBuddy(self.txtNumeroNotaFiscal)
        self.lblCertificada.setBuddy(self.txtCertificada)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblNomeMotorista.setBuddy(self.txtNomeFuncionario)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlaca.setBuddy(self.txtPlaca)

        self.retranslateUi(frmEntradaVeiculosDescarregamento)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaVeiculosDescarregamento)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnDescarregamentoComNotaFiscal, self.radbtnDescarregamentoSemNotaFiscal)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnDescarregamentoSemNotaFiscal, self.radbtnNumeroNota)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnNumeroNota, self.radbtnNumeroRomaneio)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnNumeroRomaneio, self.radbtnEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnEmitente, self.radbtnDstinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnDstinatario, self.radbtnMotorista)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.radbtnMotorista, self.txtPesquisar)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtPesquisar, self.txtData)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtData, self.txtHora)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtHora, self.txtNumeroNotaFiscal)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtNumeroNotaFiscal, self.txtTipoProduto)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtTipoProduto, self.txtCertificada)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCertificada, self.txtNumeroRomaneio)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtNumeroRomaneio, self.txtMetragemMadeira)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtMetragemMadeira, self.txtIdEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtIdEmitente, self.txtNomeEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtNomeEmitente, self.txtRazaoSocialEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtRazaoSocialEmitente, self.txtCnpjEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCnpjEmitente, self.txtInscricaoEstaduaEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtInscricaoEstaduaEmitente, self.txtEnderecoEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtEnderecoEmitente, self.txtNumeroEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtNumeroEmitente, self.txtComplementoEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtComplementoEmitente, self.txtBairroEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtBairroEmitente, self.txtCidadeEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCidadeEmitente, self.txtEstadoEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtEstadoEmitente, self.txtCepEmitente)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCepEmitente, self.txtIdDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtIdDestinatario, self.txtFantasiaDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtFantasiaDestinatario, self.txtRazaoSocialDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtRazaoSocialDestinatario, self.txtCnpjDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCnpjDestinatario, self.txtInscricaoEstaduaDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtInscricaoEstaduaDestinatario, self.txtEnderecoDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtEnderecoDestinatario, self.txtNumeroDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtNumeroDestinatario, self.txtComplementoDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtComplementoDestinatario, self.txtBairroDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtBairroDestinatario, self.txtCidadeDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCidadeDestinatario, self.txtEstadoDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtEstadoDestinatario, self.txtCepDestinatario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtCepDestinatario, self.txtidFuncionario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtidFuncionario, self.txtNomeFuncionario)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtNomeFuncionario, self.txtModelo)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtModelo, self.txtMarca)
        frmEntradaVeiculosDescarregamento.setTabOrder(self.txtMarca, self.txtPlaca)

    def retranslateUi(self, frmEntradaVeiculosDescarregamento):
        frmEntradaVeiculosDescarregamento.setWindowTitle(_translate("frmEntradaVeiculosDescarregamento", "Entrada de Veiculos Descarregamento", None))
        self.grbTipoOperacao.setTitle(_translate("frmEntradaVeiculosDescarregamento", "Tipo de Operação", None))
        self.radbtnDescarregamentoComNotaFiscal.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo de escolha se a operação consiste em descarregar com nota fiscal e/ou romaneio", None))
        self.radbtnDescarregamentoComNotaFiscal.setText(_translate("frmEntradaVeiculosDescarregamento", "Descarreg. com Nota Fiscal ou Romaneio", None))
        self.radbtnDescarregamentoSemNotaFiscal.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo de escolha se a operação consiste em descarregar sem nota fiscal e/ou romaneio", None))
        self.radbtnDescarregamentoSemNotaFiscal.setText(_translate("frmEntradaVeiculosDescarregamento", "Descarreg. sem Nota Fiscal ou Romaneio", None))
        self.txtData.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Data Entrada", None))
        self.txtHora.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Hora Entrada", None))
        self.lblDataEntrada.setText(_translate("frmEntradaVeiculosDescarregamento", "Data Entrada", None))
        self.lblHoraEntrada.setText(_translate("frmEntradaVeiculosDescarregamento", "Hora Entrada", None))
        self.grbDadosDestinatario.setTitle(_translate("frmEntradaVeiculosDescarregamento", "Destinatario", None))
        self.txtCnpjDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "CNPJ ", None))
        self.txtCnpjDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do numero do CNPJ do destinatario", None))
        self.txtCnpjDestinatario.setInputMask(_translate("frmEntradaVeiculosDescarregamento", "00.000.000/0000-00; ", None))
        self.lblCodigoDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Codigo do Destinatario", None))
        self.lblNomeFantasiaDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Nome Fantasia Destinatario", None))
        self.lblCnpjDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "CNPJ", None))
        self.txtFantasiaDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Nome Fantasia Destinatario", None))
        self.txtFantasiaDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome fantasia do destinatario", None))
        self.txtRazaoSocialDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Razão Social ", None))
        self.txtRazaoSocialDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome da razão social do destinatario", None))
        self.lblRazaoSocialDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Razão Social", None))
        self.txtIdDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Codigo Destinatario", None))
        self.txtIdDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do codigo de identificação do destinatario", None))
        self.txtInscricaoEstaduaDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do numero do inscrição estadual do destinatario", None))
        self.lblInscricaoEstadualDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Incrição Estadual", None))
        self.lblCepDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "CEP", None))
        self.lblComplementoDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Complemento", None))
        self.txtComplementoDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Complemento", None))
        self.txtComplementoDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Complemento do endereço do destinatario", None))
        self.lblCidadeDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Cidade", None))
        self.txtEnderecoDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Endereço", None))
        self.txtEnderecoDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Endereço do destinatario", None))
        self.txtNumeroDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Numero", None))
        self.txtNumeroDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Numero referente ao endereço do destinatario", None))
        self.lblEnderecoDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Endereço", None))
        self.txtBairroDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Bairro", None))
        self.txtBairroDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Nome do bairro localizado o endereço do destinatario", None))
        self.txtCidadeDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Cidade", None))
        self.txtCidadeDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Nome da cidade onde destinatario reside", None))
        self.lblNumeroDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Numero", None))
        self.txtEstadoDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Estado", None))
        self.txtEstadoDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Nome do estado onde fica localizado a cidade do destinatario", None))
        self.txtCepDestinatario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Cep", None))
        self.txtCepDestinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Codigo do CEP referente a cidade do destinatario", None))
        self.txtCepDestinatario.setInputMask(_translate("frmEntradaVeiculosDescarregamento", "00000-000; ", None))
        self.lblBairroDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Bairro", None))
        self.lblEstadoDestinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Estado", None))
        self.grbDadosEmitente.setTitle(_translate("frmEntradaVeiculosDescarregamento", "Emitente", None))
        self.txtIdEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Codigo Emitente", None))
        self.txtIdEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do codigo de identificação do emitente", None))
        self.txtNomeEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Nome Fantasia Emitente", None))
        self.txtNomeEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome fantasia do emitente", None))
        self.lblCodigoEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Codigo Emitente", None))
        self.lblNomeEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Nome Fatasia Emitente", None))
        self.txtEnderecoEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Endereço ", None))
        self.txtEnderecoEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Endereço do emitente", None))
        self.txtNumeroEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Numero ", None))
        self.txtNumeroEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Numero referente ao endereço do emitente", None))
        self.txtComplementoEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Complemento", None))
        self.txtComplementoEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Complemento do endereço do emitente", None))
        self.txtCidadeEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Cidade", None))
        self.txtCidadeEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Nome da cidade onde o emitente reside", None))
        self.txtEstadoEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Estado", None))
        self.txtEstadoEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Nome do estado onde fica localizado a cidade do emitente", None))
        self.txtCepEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "CEP ", None))
        self.txtCepEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Codigo do CEP referente a cidade do emitente", None))
        self.txtCepEmitente.setInputMask(_translate("frmEntradaVeiculosDescarregamento", "00000-000; ", None))
        self.txtBairroEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Bairro", None))
        self.txtBairroEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Nome do bairro localizado o endereço do emitente", None))
        self.lblEnderecoEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Endereço", None))
        self.lblNumeroEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Numero", None))
        self.lblComplementoEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Complemento", None))
        self.lblBairroEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Bairro", None))
        self.lblCidadeEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Cidade", None))
        self.lblEstadoEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Estado", None))
        self.lblCepEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "CEP", None))
        self.txtInscricaoEstaduaEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do numero do inscrição estadual do emitente", None))
        self.txtRazaoSocialEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Razão Social ", None))
        self.txtRazaoSocialEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome da razão social do emitente", None))
        self.lblRazaoSocialEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Razão Social", None))
        self.lblCnpjEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "CNPJ", None))
        self.lblInscricaoEstadualEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Incrição Estadual", None))
        self.txtCnpjEmitente.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "CNPJ ", None))
        self.txtCnpjEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do numero do CNPJ do emitente", None))
        self.txtCnpjEmitente.setInputMask(_translate("frmEntradaVeiculosDescarregamento", "00.000.000/0000-00; ", None))
        self.lblPesquisa.setText(_translate("frmEntradaVeiculosDescarregamento", "Pesquisa Nota Fiscal", None))
        self.grbNotaFiscal.setTitle(_translate("frmEntradaVeiculosDescarregamento", "Nota Fiscal", None))
        self.lblNumeroRomaneio.setText(_translate("frmEntradaVeiculosDescarregamento", "Numero Romaneio", None))
        self.txtMetragemMadeira.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Metragem Madeira", None))
        self.txtMetragemMadeira.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo de metragem madeira", None))
        self.txtNumeroRomaneio.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Numero Romaneio", None))
        self.txtNumeroRomaneio.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do numero do romaneio", None))
        self.lblMetragemMadeira.setText(_translate("frmEntradaVeiculosDescarregamento", "Metragem Madeira", None))
        self.txtNumeroNotaFiscal.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Numero Nota Fiscal", None))
        self.txtNumeroNotaFiscal.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do numero da nota fiscal", None))
        self.lblTipoProduto.setText(_translate("frmEntradaVeiculosDescarregamento", "Tipo de Produto", None))
        self.txtTipoProduto.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Tipo de Produto", None))
        self.txtTipoProduto.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo de descrição do tipo de produto", None))
        self.txtCertificada.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Certificada", None))
        self.txtCertificada.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo de identicação se o produto é certificado", None))
        self.lblNumeroNotaFiscal.setText(_translate("frmEntradaVeiculosDescarregamento", "Numero Nota Fiscal", None))
        self.lblCertificada.setText(_translate("frmEntradaVeiculosDescarregamento", "Certificada", None))
        self.grbDadosMotorista.setTitle(_translate("frmEntradaVeiculosDescarregamento", "Motorista", None))
        self.txtModelo.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Marca do Veiculo", None))
        self.txtModelo.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome do modelo do veiculo", None))
        self.lblMarca.setText(_translate("frmEntradaVeiculosDescarregamento", "Marca", None))
        self.txtMarca.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Marca do Veiculo", None))
        self.txtMarca.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome da marca do veiculo", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Nome Fantasia Motorista", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do nome fantasia do motorista", None))
        self.lblNomeMotorista.setText(_translate("frmEntradaVeiculosDescarregamento", "Nome Fantasia Motorista", None))
        self.txtPlaca.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Placa do Veiculo", None))
        self.txtPlaca.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmEntradaVeiculosDescarregamento", "nnn-0000; ", None))
        self.txtPlaca.setText(_translate("frmEntradaVeiculosDescarregamento", "-", None))
        self.lblModelo.setText(_translate("frmEntradaVeiculosDescarregamento", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Codigo Motorista", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do Codigo de identificação do motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmEntradaVeiculosDescarregamento", "Codigo Motorista", None))
        self.lblPlaca.setText(_translate("frmEntradaVeiculosDescarregamento", "Placa", None))
        self.grbBotoes.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Grupo de botões referente as suas funções", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmEntradaVeiculosDescarregamento", "Salvar", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmEntradaVeiculosDescarregamento", "Novo", None))
        self.btnEditar.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmEntradaVeiculosDescarregamento", "Editar", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmEntradaVeiculosDescarregamento", "Cancelar", None))
        self.btnDeletar.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmEntradaVeiculosDescarregamento", "Deletar", None))
        self.grbTipoPesquisa.setTitle(_translate("frmEntradaVeiculosDescarregamento", "Tipo de pesquisa", None))
        self.radbtnNumeroNota.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "campo de escolha para pesquisar por numero nota fical", None))
        self.radbtnNumeroNota.setText(_translate("frmEntradaVeiculosDescarregamento", "Numero Nota Fiscal", None))
        self.radbtnNumeroRomaneio.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "campo de escolha para pesquisar por numero romaneio", None))
        self.radbtnNumeroRomaneio.setText(_translate("frmEntradaVeiculosDescarregamento", "Numero Romaneio", None))
        self.radbtnEmitente.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "campo de escolha para pesquisar por emitente", None))
        self.radbtnEmitente.setText(_translate("frmEntradaVeiculosDescarregamento", "Emitente", None))
        self.radbtnDstinatario.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "campo de escolha para pesquisar por destinatario", None))
        self.radbtnDstinatario.setText(_translate("frmEntradaVeiculosDescarregamento", "Destinatario", None))
        self.radbtnMotorista.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "campo de escolha para pesquisar por motorista", None))
        self.radbtnMotorista.setText(_translate("frmEntradaVeiculosDescarregamento", "Motorista", None))
        self.txtPesquisar.setToolTip(_translate("frmEntradaVeiculosDescarregamento", "Pesquisa", None))
        self.txtPesquisar.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Campo do pesquisa", None))
        self.tabPesquisar.setWhatsThis(_translate("frmEntradaVeiculosDescarregamento", "Tabela de resultados de pesquisa", None))

