# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaVeiculosTerceiros.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaVeiculosEmpresaTerceiros(object):
    def setupUi(self, frmEntradaVeiculosEmpresaTerceiros):
        frmEntradaVeiculosEmpresaTerceiros.setObjectName(_fromUtf8("frmEntradaVeiculosEmpresaTerceiros"))
        frmEntradaVeiculosEmpresaTerceiros.resize(891, 686)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmEntradaVeiculosEmpresaTerceiros.setFont(font)
        
        self.lblObservacao = QtGui.QLabel(frmEntradaVeiculosEmpresaTerceiros)
        self.lblObservacao.setGeometry(QtCore.QRect(20, 485, 91, 16))
        self.lblObservacao.setObjectName(_fromUtf8("lblObservacao"))
        
        self.txtObservacao = QtGui.QTextEdit(frmEntradaVeiculosEmpresaTerceiros)
        self.txtObservacao.setEnabled(False)
        self.txtObservacao.setGeometry(QtCore.QRect(20, 505, 851, 91))
        self.txtObservacao.setObjectName(_fromUtf8("txtObservacao"))
        
        self.grbDadosEmpresaDestino = QtGui.QGroupBox(frmEntradaVeiculosEmpresaTerceiros)
        self.grbDadosEmpresaDestino.setEnabled(False)
        self.grbDadosEmpresaDestino.setGeometry(QtCore.QRect(10, 320, 871, 161))
        self.grbDadosEmpresaDestino.setObjectName(_fromUtf8("grbDadosEmpresaDestino"))
        
        self.txtIdEmpresaDestino = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtIdEmpresaDestino.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresaDestino.setPalette(palette)
        self.txtIdEmpresaDestino.setMaxLength(11)
        self.txtIdEmpresaDestino.setObjectName(_fromUtf8("txtIdEmpresaDestino"))
        
        self.txtNomeEmpresaDestino = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtNomeEmpresaDestino.setGeometry(QtCore.QRect(201, 35, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmpresaDestino.setPalette(palette)
        self.txtNomeEmpresaDestino.setMaxLength(70)
        self.txtNomeEmpresaDestino.setObjectName(_fromUtf8("txtNomeEmpresaDestino"))
        
        self.lblCodigoEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblCodigoEmpresaOrigem.setGeometry(QtCore.QRect(10, 15, 161, 21))
        self.lblCodigoEmpresaOrigem.setObjectName(_fromUtf8("lblCodigoEmpresaOrigem"))
        
        self.lblNomeEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 15, 221, 16))
        self.lblNomeEmpresaOrigem.setObjectName(_fromUtf8("lblNomeEmpresaOrigem"))
        
        self.txtInscricaoEstaduaEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtInscricaoEstaduaEmpresaOrigem.setEnabled(False)
        self.txtInscricaoEstaduaEmpresaOrigem.setGeometry(QtCore.QRect(688, 80, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmpresaOrigem.setPalette(palette)
        self.txtInscricaoEstaduaEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmpresaOrigem.setMaxLength(8)
        self.txtInscricaoEstaduaEmpresaOrigem.setObjectName(_fromUtf8("txtInscricaoEstaduaEmpresaOrigem"))
        
        self.txtRazaoSocialEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtRazaoSocialEmpresaOrigem.setEnabled(False)
        self.txtRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 80, 481, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmpresaOrigem.setPalette(palette)
        self.txtRazaoSocialEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmpresaOrigem.setMaxLength(70)
        self.txtRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("txtRazaoSocialEmpresaOrigem"))
        
        self.lblRazaoSocialEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("lblRazaoSocialEmpresaOrigem"))
        
        self.lblCnpjEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblCnpjEmpresaOrigem.setGeometry(QtCore.QRect(500, 60, 41, 19))
        self.lblCnpjEmpresaOrigem.setObjectName(_fromUtf8("lblCnpjEmpresaOrigem"))
        
        self.lblInscricaoEstadualEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblInscricaoEstadualEmpresaOrigem.setGeometry(QtCore.QRect(688, 60, 121, 19))
        self.lblInscricaoEstadualEmpresaOrigem.setObjectName(_fromUtf8("lblInscricaoEstadualEmpresaOrigem"))
        
        self.txtCnpjEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtCnpjEmpresaOrigem.setEnabled(False)
        self.txtCnpjEmpresaOrigem.setGeometry(QtCore.QRect(500, 80, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmpresaOrigem.setPalette(palette)
        self.txtCnpjEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmpresaOrigem.setText(_fromUtf8("../-"))
        self.txtCnpjEmpresaOrigem.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmpresaOrigem.setObjectName(_fromUtf8("txtCnpjEmpresaOrigem"))
        
        self.btnPesquisarEmpresaOrigem = QtGui.QPushButton(self.grbDadosEmpresaDestino)
        self.btnPesquisarEmpresaOrigem.setGeometry(QtCore.QRect(820, 34, 31, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarEmpresaOrigem.setFont(font)
        self.btnPesquisarEmpresaOrigem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarEmpresaOrigem.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarEmpresaOrigem.setIcon(icon)
        self.btnPesquisarEmpresaOrigem.setObjectName(_fromUtf8("btnPesquisarEmpresaOrigem"))
        
        self.lblSetor = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblSetor.setGeometry(QtCore.QRect(10, 107, 41, 16))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        
        self.txtSetor = QtGui.QComboBox(self.grbDadosEmpresaDestino)
        self.txtSetor.setGeometry(QtCore.QRect(10, 127, 241, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetor.setPalette(palette)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        
        self.grbLugarOrigem = QtGui.QGroupBox(frmEntradaVeiculosEmpresaTerceiros)
        self.grbLugarOrigem.setEnabled(False)
        self.grbLugarOrigem.setGeometry(QtCore.QRect(10, 200, 871, 121))
        self.grbLugarOrigem.setObjectName(_fromUtf8("grbLugarOrigem"))
        
        self.lblCep = QtGui.QLabel(self.grbLugarOrigem)
        self.lblCep.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.lblCep.setObjectName(_fromUtf8("lblCep"))
        
        self.txtEstado = QtGui.QLineEdit(self.grbLugarOrigem)
        self.txtEstado.setEnabled(False)
        self.txtEstado.setGeometry(QtCore.QRect(10, 90, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstado.setPalette(palette)
        self.txtEstado.setMaxLength(50)
        self.txtEstado.setObjectName(_fromUtf8("txtEstado"))
        
        self.tctCep = QtGui.QLineEdit(self.grbLugarOrigem)
        self.tctCep.setGeometry(QtCore.QRect(10, 40, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tctCep.setPalette(palette)
        self.tctCep.setObjectName(_fromUtf8("tctCep"))
        
        self.txtCidade = QtGui.QLineEdit(self.grbLugarOrigem)
        self.txtCidade.setEnabled(False)
        self.txtCidade.setGeometry(QtCore.QRect(200, 40, 661, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidade.setPalette(palette)
        self.txtCidade.setMaxLength(70)
        self.txtCidade.setObjectName(_fromUtf8("txtCidade"))
        
        self.lblCidade = QtGui.QLabel(self.grbLugarOrigem)
        self.lblCidade.setGeometry(QtCore.QRect(200, 20, 51, 16))
        self.lblCidade.setObjectName(_fromUtf8("lblCidade"))
        
        self.lblEstado = QtGui.QLabel(self.grbLugarOrigem)
        self.lblEstado.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.lblEstado.setObjectName(_fromUtf8("lblEstado"))
        
        self.btnPesquisarLugarOrigem = QtGui.QPushButton(self.grbLugarOrigem)
        self.btnPesquisarLugarOrigem.setGeometry(QtCore.QRect(320, 89, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarLugarOrigem.setFont(font)
        self.btnPesquisarLugarOrigem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarLugarOrigem.setText(_fromUtf8(""))
        self.btnPesquisarLugarOrigem.setIcon(icon)
        self.btnPesquisarLugarOrigem.setObjectName(_fromUtf8("btnPesquisarLugarOrigem"))
        
        self.grbDadosCondutor = QtGui.QGroupBox(frmEntradaVeiculosEmpresaTerceiros)
        self.grbDadosCondutor.setEnabled(False)
        self.grbDadosCondutor.setGeometry(QtCore.QRect(10, 80, 871, 121))
        self.grbDadosCondutor.setObjectName(_fromUtf8("grbDadosCondutor"))
        
        self.lblPlacaVeiculo = QtGui.QLabel(self.grbDadosCondutor)
        self.lblPlacaVeiculo.setGeometry(QtCore.QRect(660, 70, 111, 16))
        self.lblPlacaVeiculo.setObjectName(_fromUtf8("lblPlacaVeiculo"))
        
        self.lblMarcaVeiculo = QtGui.QLabel(self.grbDadosCondutor)
        self.lblMarcaVeiculo.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.lblMarcaVeiculo.setObjectName(_fromUtf8("lblMarcaVeiculo"))
        
        self.lblModeloVeiculo = QtGui.QLabel(self.grbDadosCondutor)
        self.lblModeloVeiculo.setGeometry(QtCore.QRect(340, 70, 111, 16))
        self.lblModeloVeiculo.setObjectName(_fromUtf8("lblModeloVeiculo"))
        
        self.txtMarcaVeiculo = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtMarcaVeiculo.setGeometry(QtCore.QRect(10, 90, 321, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarcaVeiculo.setPalette(palette)
        self.txtMarcaVeiculo.setMaxLength(50)
        self.txtMarcaVeiculo.setObjectName(_fromUtf8("txtMarcaVeiculo"))
        
        self.txtNomeCondutor = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtNomeCondutor.setGeometry(QtCore.QRect(10, 40, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeCondutor.setPalette(palette)
        self.txtNomeCondutor.setMaxLength(70)
        self.txtNomeCondutor.setObjectName(_fromUtf8("txtNomeCondutor"))
        
        self.txtPlacaVeiculo = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtPlacaVeiculo.setGeometry(QtCore.QRect(660, 90, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlacaVeiculo.setPalette(palette)
        self.txtPlacaVeiculo.setObjectName(_fromUtf8("txtPlacaVeiculo"))
        
        self.txtModeloVeiculo = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtModeloVeiculo.setGeometry(QtCore.QRect(340, 90, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModeloVeiculo.setPalette(palette)
        self.txtModeloVeiculo.setMaxLength(50)
        self.txtModeloVeiculo.setObjectName(_fromUtf8("txtModeloVeiculo"))
        
        self.lblNomeCondutor = QtGui.QLabel(self.grbDadosCondutor)
        self.lblNomeCondutor.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.lblNomeCondutor.setObjectName(_fromUtf8("lblNomeCondutor"))
        
        self.grbDadosEntrada = QtGui.QGroupBox(frmEntradaVeiculosEmpresaTerceiros)
        self.grbDadosEntrada.setEnabled(False)
        self.grbDadosEntrada.setGeometry(QtCore.QRect(10, 10, 871, 71))
        self.grbDadosEntrada.setObjectName(_fromUtf8("grbDadosEntrada"))
        
        self.txtHora = QtGui.QTimeEdit(self.grbDadosEntrada)
        self.txtHora.setGeometry(QtCore.QRect(150, 40, 118, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtHora.setPalette(palette)
        self.txtHora.setCalendarPopup(False)
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        
        self.lblHoraEntrada = QtGui.QLabel(self.grbDadosEntrada)
        self.lblHoraEntrada.setGeometry(QtCore.QRect(150, 20, 91, 16))
        self.lblHoraEntrada.setObjectName(_fromUtf8("lblHoraEntrada"))
        
        self.lblTipoAfazer = QtGui.QLabel(self.grbDadosEntrada)
        self.lblTipoAfazer.setGeometry(QtCore.QRect(290, 20, 101, 16))
        self.lblTipoAfazer.setObjectName(_fromUtf8("lblTipoAfazer"))
        
        self.txtTipoAfzer = QtGui.QComboBox(self.grbDadosEntrada)
        self.txtTipoAfzer.setGeometry(QtCore.QRect(290, 40, 321, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTipoAfzer.setPalette(palette)
        self.txtTipoAfzer.setObjectName(_fromUtf8("txtTipoAfzer"))
        
        self.txtData = QtGui.QDateEdit(self.grbDadosEntrada)
        self.txtData.setGeometry(QtCore.QRect(20, 40, 110, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtData.setPalette(palette)
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))
        
        self.lblDataEntrada = QtGui.QLabel(self.grbDadosEntrada)
        self.lblDataEntrada.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.lblDataEntrada.setObjectName(_fromUtf8("lblDataEntrada"))
        
        self.txtEspecie = QtGui.QComboBox(self.grbDadosEntrada)
        self.txtEspecie.setGeometry(QtCore.QRect(620, 40, 241, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEspecie.setPalette(palette)
        self.txtEspecie.setObjectName(_fromUtf8("txtEspecie"))
        
        self.lblEspecie = QtGui.QLabel(self.grbDadosEntrada)
        self.lblEspecie.setGeometry(QtCore.QRect(620, 20, 101, 16))
        self.lblEspecie.setObjectName(_fromUtf8("lblEspecie"))
        
        self.grbBotoes = QtGui.QGroupBox(frmEntradaVeiculosEmpresaTerceiros)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 600, 871, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(760, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(660, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(460, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(360, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(560, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        
        self.lblObservacao.setBuddy(self.txtObservacao)
        self.lblCodigoEmpresaOrigem.setBuddy(self.txtIdEmpresaDestino)
        self.lblNomeEmpresaOrigem.setBuddy(self.txtNomeEmpresaDestino)
        self.lblRazaoSocialEmpresaOrigem.setBuddy(self.txtRazaoSocialEmpresaOrigem)
        self.lblCnpjEmpresaOrigem.setBuddy(self.txtCnpjEmpresaOrigem)
        self.lblInscricaoEstadualEmpresaOrigem.setBuddy(self.txtInscricaoEstaduaEmpresaOrigem)
        self.lblSetor.setBuddy(self.txtTipoAfzer)
        self.lblCep.setBuddy(self.tctCep)
        self.lblCidade.setBuddy(self.txtCidade)
        self.lblEstado.setBuddy(self.txtEstado)
        self.lblPlacaVeiculo.setBuddy(self.txtPlacaVeiculo)
        self.lblMarcaVeiculo.setBuddy(self.txtMarcaVeiculo)
        self.lblModeloVeiculo.setBuddy(self.txtModeloVeiculo)
        self.lblNomeCondutor.setBuddy(self.txtNomeCondutor)
        self.lblHoraEntrada.setBuddy(self.txtHora)
        self.lblTipoAfazer.setBuddy(self.txtTipoAfzer)
        self.lblDataEntrada.setBuddy(self.txtData)
        self.lblEspecie.setBuddy(self.txtTipoAfzer)

        self.retranslateUi(frmEntradaVeiculosEmpresaTerceiros)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaVeiculosEmpresaTerceiros)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtData, self.txtHora)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtHora, self.txtTipoAfzer)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtTipoAfzer, self.txtNomeCondutor)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtNomeCondutor, self.txtMarcaVeiculo)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtMarcaVeiculo, self.txtModeloVeiculo)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtModeloVeiculo, self.txtPlacaVeiculo)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtPlacaVeiculo, self.tctCep)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.tctCep, self.txtCidade)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtCidade, self.txtEstado)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtEstado, self.txtIdEmpresaDestino)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtIdEmpresaDestino, self.txtNomeEmpresaDestino)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtNomeEmpresaDestino, self.txtRazaoSocialEmpresaOrigem)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtRazaoSocialEmpresaOrigem, self.txtCnpjEmpresaOrigem)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtCnpjEmpresaOrigem, self.txtInscricaoEstaduaEmpresaOrigem)
        frmEntradaVeiculosEmpresaTerceiros.setTabOrder(self.txtInscricaoEstaduaEmpresaOrigem, self.txtObservacao)

    def retranslateUi(self, frmEntradaVeiculosEmpresaTerceiros):
        frmEntradaVeiculosEmpresaTerceiros.setWindowTitle(_translate("frmEntradaVeiculosEmpresaTerceiros", "Entrada Veiculos Empresa e Terceiros", None))
        self.lblObservacao.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Observações", None))
        self.txtObservacao.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Observação", None))
        self.txtObservacao.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo de observações", None))
        self.grbDadosEmpresaDestino.setTitle(_translate("frmEntradaVeiculosEmpresaTerceiros", "Empresa Destino", None))
        self.txtIdEmpresaDestino.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Codigo Empresa Origem", None))
        self.txtIdEmpresaDestino.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do codigo de identificação da empresa origem", None))
        self.txtNomeEmpresaDestino.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Nome Fantasia Empresa Origem", None))
        self.txtNomeEmpresaDestino.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do nome fantasia da empresa de origem", None))
        self.lblCodigoEmpresaOrigem.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Codigo Empresa Destino", None))
        self.lblNomeEmpresaOrigem.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Nome Fantasia Empresa Destino", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do numero do inscrição estadual da empresa de origem", None))
        self.txtRazaoSocialEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Razão Social ", None))
        self.txtRazaoSocialEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do nome da razão social da empresa de origem", None))
        self.lblRazaoSocialEmpresaOrigem.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Razão Social", None))
        self.lblCnpjEmpresaOrigem.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "CNPJ", None))
        self.lblInscricaoEstadualEmpresaOrigem.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Incrição Estadual", None))
        self.txtCnpjEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "CNPJ ", None))
        self.txtCnpjEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do numero do CNPJ da empresa de origem", None))
        self.txtCnpjEmpresaOrigem.setInputMask(_translate("frmEntradaVeiculosEmpresaTerceiros", "00.000.000/0000-00; ", None))
        self.lblSetor.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Setor", None))
        self.txtSetor.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Setor", None))
        self.txtSetor.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo de descrição do setor", None))
        self.grbLugarOrigem.setTitle(_translate("frmEntradaVeiculosEmpresaTerceiros", "Lugar Origem", None))
        self.lblCep.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "CEP", None))
        self.txtEstado.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Estado", None))
        self.txtEstado.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do nome do estado", None))
        self.tctCep.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Cep", None))
        self.tctCep.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do numero do CEP da cidade", None))
        self.tctCep.setInputMask(_translate("frmEntradaVeiculosEmpresaTerceiros", "00000-000; ", None))
        self.txtCidade.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Cidade", None))
        self.txtCidade.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do nome da cidade", None))
        self.lblCidade.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Cidade", None))
        self.lblEstado.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Estado", None))
        self.grbDadosCondutor.setTitle(_translate("frmEntradaVeiculosEmpresaTerceiros", "Dados Condutor", None))
        self.lblPlacaVeiculo.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Placa Veiculo", None))
        self.lblMarcaVeiculo.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Marca Veiculo", None))
        self.lblModeloVeiculo.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Modelo Veiculo", None))
        self.txtMarcaVeiculo.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Marca Veiculo", None))
        self.txtNomeCondutor.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Nome Condutor", None))
        self.txtNomeCondutor.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do nome do condutor", None))
        self.txtPlacaVeiculo.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Placa Veiculo", None))
        self.txtPlacaVeiculo.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo de identificação da placa do Veiculo", None))
        self.txtPlacaVeiculo.setInputMask(_translate("frmEntradaVeiculosEmpresaTerceiros", "nnn-0000; ", None))
        self.txtModeloVeiculo.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Modelo Veiculo", None))
        self.txtModeloVeiculo.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo do nome do modelo do veiculo", None))
        self.lblNomeCondutor.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Nome Condutor", None))
        self.grbDadosEntrada.setTitle(_translate("frmEntradaVeiculosEmpresaTerceiros", "Dados Entrada", None))
        self.txtHora.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Hora Entrada", None))
        self.txtHora.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo da hora de entrada", None))
        self.lblHoraEntrada.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Hora Entrada", None))
        self.lblTipoAfazer.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Tipo de Afazer", None))
        self.txtTipoAfzer.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Tipo de Afazer", None))
        self.txtData.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Data Entrada", None))
        self.txtData.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Campo da data de entrda", None))
        self.lblDataEntrada.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Data Entrada", None))
        self.txtEspecie.setToolTip(_translate("frmEntradaVeiculosEmpresaTerceiros", "Especie do condutor do veículo", None))
        self.lblEspecie.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Especie", None))
        self.grbBotoes.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Grupo de botões referente as suas funções", None))
        self.btnDeletar.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Deletar", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Salvar", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Novo", None))
        self.btnEditar.setWhatsThis(_translate("frmEntradaVeiculosEmpresaTerceiros", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmEntradaVeiculosEmpresaTerceiros", "Editar", None))

