# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaNF.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

import datetime
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4 import QtGui, QtCore
from PyQt4.QtCore import *
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaNF(object):
    def setupUi(self, frmEntradaNF):
        frmEntradaNF.setObjectName(_fromUtf8("frmEntradaNF"))
        frmEntradaNF.resize(882, 590)
        frmEntradaNF.setMinimumSize(QtCore.QSize(882, 590))
        frmEntradaNF.setMaximumSize(QtCore.QSize(882, 590))
        font = QtGui.QFont()
        font.setPointSize(10)
        frmEntradaNF.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/NF.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmEntradaNF.setWindowIcon(icon)
        frmEntradaNF.setSizeGripEnabled(True)
        frmEntradaNF.setModal(True)
        
        self.grbFornecedor = QtGui.QGroupBox(frmEntradaNF)
        self.grbFornecedor.setEnabled(False)
        self.grbFornecedor.setGeometry(QtCore.QRect(4, 4, 491, 51))
        self.grbFornecedor.setTitle(_fromUtf8(""))
        self.grbFornecedor.setObjectName(_fromUtf8("grbFornecedor"))
        
        self.txtCodig = QtGui.QLineEdit(self.grbFornecedor)
        self.txtCodig.setGeometry(QtCore.QRect(10, 20, 113, 25))
        self.txtCodig.setObjectName(_fromUtf8("txtCodig"))
        
        self.lblCodigo = QtGui.QLabel(self.grbFornecedor)
        self.lblCodigo.setGeometry(QtCore.QRect(10, 0, 31, 19))
        self.lblCodigo.setObjectName(_fromUtf8("lblCodigo"))
        
        self.lblFornecedor = QtGui.QLabel(self.grbFornecedor)
        self.lblFornecedor.setGeometry(QtCore.QRect(130, 0, 81, 19))
        self.lblFornecedor.setObjectName(_fromUtf8("lblFornecedor"))
        
        self.txtFornecedor = QtGui.QLineEdit(self.grbFornecedor)
        self.txtFornecedor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtFornecedor.setEnabled(False)
        self.txtFornecedor.setGeometry(QtCore.QRect(130, 20, 351, 25))
        self.txtFornecedor.setObjectName(_fromUtf8("txtFornecedor"))
        
        self.btnPesquisarFornecedor = QtGui.QPushButton(self.grbFornecedor)
        self.btnPesquisarFornecedor.setGeometry(QtCore.QRect(117, 35, 16, 16))
        self.btnPesquisarFornecedor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarFornecedor.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search_mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarFornecedor.setIcon(icon)
        self.btnPesquisarFornecedor.setDefault(False)
        self.btnPesquisarFornecedor.setFlat(True)
        self.btnPesquisarFornecedor.setObjectName(_fromUtf8("btnPesquisarFornecedor"))
        
        self.grbDadosNF = QtGui.QGroupBox(frmEntradaNF)
        self.grbDadosNF.setEnabled(False)
        self.grbDadosNF.setGeometry(QtCore.QRect(496, 108, 381, 51))
        self.grbDadosNF.setTitle(_fromUtf8(""))
        self.grbDadosNF.setObjectName(_fromUtf8("grbDadosNF"))
        
        self.txtNumNF = QtGui.QLineEdit(self.grbDadosNF)
        self.txtNumNF.setGeometry(QtCore.QRect(260, 20, 113, 25))
        self.txtNumNF.setObjectName(_fromUtf8("txtNumNF"))
        
        self.lblNumNF = QtGui.QLabel(self.grbDadosNF)
        self.lblNumNF.setGeometry(QtCore.QRect(260, 0, 66, 19))
        self.lblNumNF.setObjectName(_fromUtf8("lblNumNF"))
        
        self.lblSerie = QtGui.QLabel(self.grbDadosNF)
        self.lblSerie.setGeometry(QtCore.QRect(120, 0, 66, 19))
        self.lblSerie.setObjectName(_fromUtf8("lblSerie"))
        
        self.txtSerie = QtGui.QLineEdit(self.grbDadosNF)
        self.txtSerie.setGeometry(QtCore.QRect(120, 20, 61, 25))
        self.txtSerie.setObjectName(_fromUtf8("txtSerie"))
        
        self.cboxTipos = QtGui.QComboBox(self.grbDadosNF)
        self.cboxTipos.setGeometry(QtCore.QRect(10, 20, 101, 25))
        self.cboxTipos.setObjectName(_fromUtf8("cboxTipos"))
        
        self.lblTipo = QtGui.QLabel(self.grbDadosNF)
        self.lblTipo.setGeometry(QtCore.QRect(10, 0, 66, 19))
        self.lblTipo.setObjectName(_fromUtf8("lblTipo"))
        
        self.txtModelo = QtGui.QLineEdit(self.grbDadosNF)
        self.txtModelo.setGeometry(QtCore.QRect(190, 20, 61, 25))
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))
        
        self.lblModelo = QtGui.QLabel(self.grbDadosNF)
        self.lblModelo.setGeometry(QtCore.QRect(190, 0, 66, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))
        
        self.grbData = QtGui.QGroupBox(frmEntradaNF)
        self.grbData.setEnabled(False)
        self.grbData.setGeometry(QtCore.QRect(496, 56, 261, 51))
        self.grbData.setTitle(_fromUtf8(""))
        self.grbData.setObjectName(_fromUtf8("grbData"))
        
        self.lblEntrada = QtGui.QLabel(self.grbData)
        self.lblEntrada.setGeometry(QtCore.QRect(136, 0, 66, 19))
        self.lblEntrada.setObjectName(_fromUtf8("lblEntrada"))
        
        self.dateDataEntrada = QtGui.QDateEdit(self.grbData)
        self.dateDataEntrada.setDate(QDate.currentDate())
        self.dateDataEntrada.setGeometry(QtCore.QRect(136, 20, 115, 25))
        self.dateDataEntrada.setCalendarPopup(True)
        self.dateDataEntrada.setObjectName(_fromUtf8("dateDataEntrada"))
        
        self.dateDataEmissao = QtGui.QDateEdit(self.grbData)
        self.dateDataEmissao.setDate(QDate.currentDate())
        self.dateDataEmissao.setGeometry(QtCore.QRect(10, 20, 116, 25))
        self.dateDataEmissao.setCalendarPopup(True)
        self.dateDataEmissao.setObjectName(_fromUtf8("dateDataEmissao"))
        
        self.lblEmissao = QtGui.QLabel(self.grbData)
        self.lblEmissao.setGeometry(QtCore.QRect(10, 0, 66, 19))
        self.lblEmissao.setObjectName(_fromUtf8("lblEmissao"))
        
        self.grbCalculoImposto = QtGui.QGroupBox(frmEntradaNF)
        self.grbCalculoImposto.setEnabled(False)
        self.grbCalculoImposto.setGeometry(QtCore.QRect(4, 160, 873, 101))
        self.grbCalculoImposto.setTitle(_fromUtf8(""))
        self.grbCalculoImposto.setObjectName(_fromUtf8("grbCalculoImposto"))
        
        self.txtBaseICMS = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtBaseICMS.setGeometry(QtCore.QRect(10, 20, 113, 25))
        self.txtBaseICMS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBaseICMS.setObjectName(_fromUtf8("txtBaseICMS"))
        
        self.lblBaseICMS = QtGui.QLabel(self.grbCalculoImposto)
        self.lblBaseICMS.setGeometry(QtCore.QRect(10, 0, 81, 19))
        self.lblBaseICMS.setObjectName(_fromUtf8("lblBaseICMS"))
        
        self.txtValorICMS = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorICMS.setGeometry(QtCore.QRect(130, 20, 113, 25))
        self.txtValorICMS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorICMS.setObjectName(_fromUtf8("txtValorICMS"))
        
        self.lblValorICMS = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorICMS.setGeometry(QtCore.QRect(130, 0, 81, 19))
        self.lblValorICMS.setObjectName(_fromUtf8("lblValorICMS"))
        
        self.txtBaseICMSST = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtBaseICMSST.setGeometry(QtCore.QRect(250, 20, 113, 25))
        self.txtBaseICMSST.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBaseICMSST.setObjectName(_fromUtf8("txtBaseICMSST"))
        
        self.lblBaseICMSST = QtGui.QLabel(self.grbCalculoImposto)
        self.lblBaseICMSST.setGeometry(QtCore.QRect(250, 0, 101, 19))
        self.lblBaseICMSST.setObjectName(_fromUtf8("lblBaseICMSST"))
        
        self.txtValorICMSSub = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorICMSSub.setGeometry(QtCore.QRect(370, 20, 113, 25))
        self.txtValorICMSSub.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorICMSSub.setObjectName(_fromUtf8("txtValorICMSSub"))
        
        self.lblValorICMSSub = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorICMSSub.setGeometry(QtCore.QRect(370, 0, 121, 19))
        self.lblValorICMSSub.setObjectName(_fromUtf8("lblValorICMSSub"))
        
        self.txtValorPIS = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorPIS.setGeometry(QtCore.QRect(490, 20, 113, 25))
        self.txtValorPIS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorPIS.setObjectName(_fromUtf8("txtValorPIS"))
        
        self.lblValorPis = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorPis.setGeometry(QtCore.QRect(490, 0, 66, 19))
        self.lblValorPis.setObjectName(_fromUtf8("lblValorPis"))
        
        self.txtValorConfins = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorConfins.setGeometry(QtCore.QRect(610, 20, 113, 25))
        self.txtValorConfins.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorConfins.setObjectName(_fromUtf8("txtValorConfins"))
        
        self.lblValorConfins = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorConfins.setGeometry(QtCore.QRect(610, 0, 101, 19))
        self.lblValorConfins.setObjectName(_fromUtf8("lblValorConfins"))
        
        self.txtValorFrete = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorFrete.setGeometry(QtCore.QRect(10, 70, 113, 25))
        self.txtValorFrete.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorFrete.setObjectName(_fromUtf8("txtValorFrete"))
        
        self.lblValorFrete = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorFrete.setGeometry(QtCore.QRect(10, 50, 81, 19))
        self.lblValorFrete.setObjectName(_fromUtf8("lblValorFrete"))
        
        self.txtValorSeguro = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorSeguro.setGeometry(QtCore.QRect(130, 70, 113, 25))
        self.txtValorSeguro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorSeguro.setObjectName(_fromUtf8("txtValorSeguro"))
        
        self.lblValorSeguro = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorSeguro.setGeometry(QtCore.QRect(130, 50, 101, 19))
        self.lblValorSeguro.setObjectName(_fromUtf8("lblValorSeguro"))
        
        self.txtValorDesconto = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorDesconto.setGeometry(QtCore.QRect(250, 70, 113, 25))
        self.txtValorDesconto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorDesconto.setObjectName(_fromUtf8("txtValorDesconto"))
        
        self.lblValorDesconto = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorDesconto.setGeometry(QtCore.QRect(250, 50, 111, 19))
        self.lblValorDesconto.setObjectName(_fromUtf8("lblValorDesconto"))
        
        self.txtOutrasDespesas = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtOutrasDespesas.setGeometry(QtCore.QRect(370, 70, 113, 25))
        self.txtOutrasDespesas.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtOutrasDespesas.setObjectName(_fromUtf8("txtOutrasDespesas"))
        
        self.lblOutrasDespesas = QtGui.QLabel(self.grbCalculoImposto)
        self.lblOutrasDespesas.setGeometry(QtCore.QRect(370, 50, 111, 19))
        self.lblOutrasDespesas.setObjectName(_fromUtf8("lblOutrasDespesas"))
        
        self.txtValorIPI = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtValorIPI.setGeometry(QtCore.QRect(490, 70, 113, 25))
        self.txtValorIPI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorIPI.setObjectName(_fromUtf8("txtValorIPI"))
        
        self.lblValorIPI = QtGui.QLabel(self.grbCalculoImposto)
        self.lblValorIPI.setGeometry(QtCore.QRect(490, 50, 66, 19))
        self.lblValorIPI.setObjectName(_fromUtf8("lblValorIPI"))

        self.txtAlicotaICMS = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtAlicotaICMS.setGeometry(QtCore.QRect(612, 70, 113, 25))
        self.txtAlicotaICMS.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txtAlicotaICMS.setObjectName(_fromUtf8("txtAlicotaICMS"))

        self.lblAlicotaICMS = QtGui.QLabel(self.grbCalculoImposto)
        self.lblAlicotaICMS.setGeometry(QtCore.QRect(612, 50, 86, 19))
        self.lblAlicotaICMS.setObjectName(_fromUtf8("lblAlicotaICMS"))

        self.txtAlicotaIPI = QtGui.QLineEdit(self.grbCalculoImposto)
        self.txtAlicotaIPI.setGeometry(QtCore.QRect(733, 70, 113, 25))
        self.txtAlicotaIPI.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.txtAlicotaIPI.setObjectName(_fromUtf8("txtAlicotaIPI"))

        self.lblAlicotaIPI = QtGui.QLabel(self.grbCalculoImposto)
        self.lblAlicotaIPI.setGeometry(QtCore.QRect(733, 50, 66, 19))
        self.lblAlicotaIPI.setObjectName(_fromUtf8("lblAlicotaIPI"))

        self.grbDescricaoProduto = QtGui.QGroupBox(frmEntradaNF)
        self.grbDescricaoProduto.setEnabled(False)
        self.grbDescricaoProduto.setGeometry(QtCore.QRect(4, 262, 873, 231))
        self.grbDescricaoProduto.setTitle(_fromUtf8(""))
        self.grbDescricaoProduto.setObjectName(_fromUtf8("grbDescricaoProduto"))
        
        self.cBoxProduto = QtGui.QComboBox(self.grbDescricaoProduto)
        self.cBoxProduto.setGeometry(QtCore.QRect(10, 20, 321, 25))
        self.cBoxProduto.setObjectName(_fromUtf8("cBoxProduto"))
        
        self.lblUn = QtGui.QLabel(self.grbDescricaoProduto)
        self.lblUn.setGeometry(QtCore.QRect(340, 0, 31, 19))
        self.lblUn.setObjectName(_fromUtf8("lblUn"))
        
        self.lblQtd = QtGui.QLabel(self.grbDescricaoProduto)
        self.lblQtd.setGeometry(QtCore.QRect(460, 0, 41, 19))
        self.lblQtd.setObjectName(_fromUtf8("lblQtd"))
        
        self.lblValorUnitario = QtGui.QLabel(self.grbDescricaoProduto)
        self.lblValorUnitario.setGeometry(QtCore.QRect(540, 0, 101, 19))
        self.lblValorUnitario.setObjectName(_fromUtf8("lblValorUnitario"))
        
        self.lblProduto = QtGui.QLabel(self.grbDescricaoProduto)
        self.lblProduto.setGeometry(QtCore.QRect(10, 0, 66, 19))
        self.lblProduto.setObjectName(_fromUtf8("lblProduto"))
        
        self.cBoxUn = QtGui.QComboBox(self.grbDescricaoProduto)
        self.cBoxUn.setGeometry(QtCore.QRect(340, 20, 61, 22))
        self.cBoxUn.setFrame(True)
        self.cBoxUn.setObjectName(_fromUtf8("cBoxUn"))
        
        self.txtValorUnotario = QtGui.QLineEdit(self.grbDescricaoProduto)
        self.txtValorUnotario.setGeometry(QtCore.QRect(540, 20, 121, 25))
        self.txtValorUnotario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorUnotario.setObjectName(_fromUtf8("txtValorUnotario"))
        
        self.tabDescricaoProduto = QtGui.QTableWidget(self.grbDescricaoProduto)
        self.tabDescricaoProduto.setGeometry(QtCore.QRect(10, 50, 854, 141))
        self.tabDescricaoProduto.setToolTip(_fromUtf8(""))
        self.tabDescricaoProduto.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabDescricaoProduto.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabDescricaoProduto.setObjectName(_fromUtf8("tabDescricaoProduto"))
        self.tabDescricaoProduto.setColumnCount(14)
        self.tabDescricaoProduto.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tabDescricaoProduto.setHorizontalHeaderItem(13, item)
        self.tabDescricaoProduto.horizontalHeader().setStretchLastSection(True)
        self.tabDescricaoProduto.verticalHeader().setVisible(False)
        
        self.txtQtd = QtGui.QLineEdit(self.grbDescricaoProduto)
        self.txtQtd.setGeometry(QtCore.QRect(410, 20, 121, 25))
        self.txtQtd.setAlignment(QtCore.Qt.AlignCenter)
        self.txtQtd.setObjectName(_fromUtf8("txtQtd"))
        
        self.lblValorTotal = QtGui.QLabel(self.grbDescricaoProduto)
        self.lblValorTotal.setGeometry(QtCore.QRect(670, 0, 81, 19))
        self.lblValorTotal.setObjectName(_fromUtf8("lblValorTotal"))
        
        self.txtValorTotal = QtGui.QLineEdit(self.grbDescricaoProduto)
        self.txtValorTotal.setGeometry(QtCore.QRect(670, 20, 111, 25))
        self.txtValorTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorTotal.setObjectName(_fromUtf8("txtValorTotal"))
        
        self.btnAdd = QtGui.QPushButton(self.grbDescricaoProduto)
        self.btnAdd.setGeometry(QtCore.QRect(834, 20, 31, 27))
        self.btnAdd.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnAdd.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        
        self.btnRemove = QtGui.QPushButton(self.grbDescricaoProduto)
        self.btnRemove.setGeometry(QtCore.QRect(834, 194, 31, 27))
        self.btnRemove.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnRemove.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon2)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        
        self.SomatoriaTotalValor = QtGui.QLabel(self.grbDescricaoProduto)
        self.SomatoriaTotalValor.setGeometry(QtCore.QRect(10, 200, 124, 19))
        self.SomatoriaTotalValor.setObjectName(_fromUtf8("SomatoriaTotalValor"))
        
        self.txtSomatoriaTotalValor = QtGui.QLineEdit(self.grbDescricaoProduto)
        self.txtSomatoriaTotalValor.setGeometry(QtCore.QRect(135, 197, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSomatoriaTotalValor.setPalette(palette)
        self.txtSomatoriaTotalValor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtSomatoriaTotalValor.setAcceptDrops(False)
        self.txtSomatoriaTotalValor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtSomatoriaTotalValor.setObjectName(_fromUtf8("txtSomatoriaTotalValor"))
        
        self.grbIssqn = QtGui.QGroupBox(frmEntradaNF)
        self.grbIssqn.setEnabled(False)
        self.grbIssqn.setGeometry(QtCore.QRect(4, 494, 551, 51))
        self.grbIssqn.setTitle(_fromUtf8(""))
        self.grbIssqn.setObjectName(_fromUtf8("grbIssqn"))
        
        self.txtBaseIssqn = QtGui.QLineEdit(self.grbIssqn)
        self.txtBaseIssqn.setGeometry(QtCore.QRect(310, 20, 113, 25))
        self.txtBaseIssqn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBaseIssqn.setObjectName(_fromUtf8("txtBaseIssqn"))
        
        self.lblValorIssqn = QtGui.QLabel(self.grbIssqn)
        self.lblValorIssqn.setGeometry(QtCore.QRect(430, 0, 91, 19))
        self.lblValorIssqn.setObjectName(_fromUtf8("lblValorIssqn"))
        
        self.txtInsMunicipal = QtGui.QLineEdit(self.grbIssqn)
        self.txtInsMunicipal.setGeometry(QtCore.QRect(10, 20, 131, 25))
        self.txtInsMunicipal.setObjectName(_fromUtf8("txtInsMunicipal"))
        
        self.lblInsMunicipal = QtGui.QLabel(self.grbIssqn)
        self.lblInsMunicipal.setGeometry(QtCore.QRect(10, 0, 101, 19))
        self.lblInsMunicipal.setObjectName(_fromUtf8("lblInsMunicipal"))
        
        self.txtValorTotalServico = QtGui.QLineEdit(self.grbIssqn)
        self.txtValorTotalServico.setGeometry(QtCore.QRect(150, 20, 151, 25))
        self.txtValorTotalServico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorTotalServico.setObjectName(_fromUtf8("txtValorTotalServico"))
        
        self.txtValorIssqn = QtGui.QLineEdit(self.grbIssqn)
        self.txtValorIssqn.setGeometry(QtCore.QRect(430, 20, 113, 25))
        self.txtValorIssqn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtValorIssqn.setObjectName(_fromUtf8("txtValorIssqn"))
        
        self.lblBaseIssqn = QtGui.QLabel(self.grbIssqn)
        self.lblBaseIssqn.setGeometry(QtCore.QRect(310, 0, 91, 19))
        self.lblBaseIssqn.setObjectName(_fromUtf8("lblBaseIssqn"))
        
        self.lblValorTotalServico = QtGui.QLabel(self.grbIssqn)
        self.lblValorTotalServico.setGeometry(QtCore.QRect(150, 0, 111, 19))
        self.lblValorTotalServico.setObjectName(_fromUtf8("lblValorTotalServico"))
        
        self.grbImpostos = QtGui.QGroupBox(frmEntradaNF)
        self.grbImpostos.setEnabled(False)
        self.grbImpostos.setGeometry(QtCore.QRect(4, 108, 491, 51))
        self.grbImpostos.setTitle(_fromUtf8(""))
        self.grbImpostos.setObjectName(_fromUtf8("grbImpostos"))
        
        self.lblCst = QtGui.QLabel(self.grbImpostos)
        self.lblCst.setGeometry(QtCore.QRect(370, 0, 31, 19))
        self.lblCst.setObjectName(_fromUtf8("lblCst"))
        
        self.lblCfop = QtGui.QLabel(self.grbImpostos)
        self.lblCfop.setGeometry(QtCore.QRect(130, 0, 41, 19))
        self.lblCfop.setObjectName(_fromUtf8("lblCfop"))
        
        self.cBoxNcm = QtGui.QComboBox(self.grbImpostos)
        self.cBoxNcm.setGeometry(QtCore.QRect(10, 20, 111, 25))
        self.cBoxNcm.setObjectName(_fromUtf8("cBoxNcm"))
        
        self.lblNcm = QtGui.QLabel(self.grbImpostos)
        self.lblNcm.setGeometry(QtCore.QRect(10, 0, 41, 19))
        self.lblNcm.setObjectName(_fromUtf8("lblNcm"))
        
        self.cBoxCst = QtGui.QComboBox(self.grbImpostos)
        self.cBoxCst.setGeometry(QtCore.QRect(370, 20, 112, 25))
        self.cBoxCst.setObjectName(_fromUtf8("cBoxCst"))

        self.cBoxCfop = QtGui.QComboBox(self.grbImpostos)
        self.cBoxCfop.setGeometry(QtCore.QRect(130, 20, 111, 25))
        self.cBoxCfop.setObjectName(_fromUtf8("cBoxCst"))
        
        self.cBoxCsosn = QtGui.QComboBox(self.grbImpostos)
        self.cBoxCsosn.setGeometry(QtCore.QRect(250, 20, 111, 25))
        self.cBoxCsosn.setObjectName(_fromUtf8("cBoxCsosn"))
        
        self.lblCsosn = QtGui.QLabel(self.grbImpostos)
        self.lblCsosn.setGeometry(QtCore.QRect(250, 0, 51, 19))
        self.lblCsosn.setObjectName(_fromUtf8("lblCsosn"))

        self.grbTransportadoraMotorista = QtGui.QGroupBox(frmEntradaNF)
        self.grbTransportadoraMotorista.setEnabled(False)
        self.grbTransportadoraMotorista.setGeometry(QtCore.QRect(4, 56, 491, 51))
        self.grbTransportadoraMotorista.setTitle(_fromUtf8(""))
        self.grbTransportadoraMotorista.setObjectName(_fromUtf8("grbTransportadoraMotorista"))

        self.txtCodigoMotorista = QtGui.QLineEdit(self.grbTransportadoraMotorista)
        self.txtCodigoMotorista.setGeometry(QtCore.QRect(10, 20, 113, 25))
        self.txtCodigoMotorista.setObjectName(_fromUtf8("txtCodigoMotorista"))

        self.lblCodigoMotorista = QtGui.QLabel(self.grbTransportadoraMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 0, 31, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        
        self.lblMotorista = QtGui.QLabel(self.grbTransportadoraMotorista)
        self.lblMotorista.setGeometry(QtCore.QRect(130, 0, 161, 19))
        self.lblMotorista.setObjectName(_fromUtf8("lblMotorista"))
        
        self.txtMotorista = QtGui.QLineEdit(self.grbTransportadoraMotorista)
        self.txtMotorista.setEnabled(False)
        self.txtMotorista.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtMotorista.setGeometry(QtCore.QRect(130, 20, 351, 25))
        self.txtMotorista.setObjectName(_fromUtf8("txtMotorista"))
        
        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbTransportadoraMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(117, 35, 16, 16))
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/search_mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarMotorista.setIcon(icon3)
        self.btnPesquisarMotorista.setDefault(False)
        self.btnPesquisarMotorista.setFlat(True)
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        
        self.grbBotoes = QtGui.QGroupBox(frmEntradaNF)
        self.grbBotoes.setGeometry(QtCore.QRect(4, 546, 873, 41))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(770, 7, 71, 27))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/critical.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeletar.setIcon(icon6)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(697, 7, 71, 27))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon5)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(551, 7, 71, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon4)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(478, 7, 71, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon3)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(624, 7, 71, 27))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/Save-as_37111.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon7)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))


        self.retranslateUi(frmEntradaNF)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaNF)
        frmEntradaNF.setTabOrder(self.txtCodig, self.btnPesquisarFornecedor)
        frmEntradaNF.setTabOrder(self.btnPesquisarFornecedor, self.txtCodigoMotorista)
        frmEntradaNF.setTabOrder(self.txtCodigoMotorista, self.btnPesquisarMotorista)
        frmEntradaNF.setTabOrder(self.btnPesquisarMotorista, self.dateDataEmissao)
        frmEntradaNF.setTabOrder(self.dateDataEmissao, self.dateDataEntrada)
        frmEntradaNF.setTabOrder(self.dateDataEntrada, self.cboxTipos)
        frmEntradaNF.setTabOrder(self.cboxTipos, self.txtSerie)
        frmEntradaNF.setTabOrder(self.txtSerie, self.txtModelo)
        frmEntradaNF.setTabOrder(self.txtModelo, self.txtNumNF)
        frmEntradaNF.setTabOrder(self.txtNumNF, self.cBoxNcm)
        frmEntradaNF.setTabOrder(self.cBoxNcm,  self.cBoxCfop)
        frmEntradaNF.setTabOrder(self.cBoxCfop, self.cBoxCsosn)
        frmEntradaNF.setTabOrder(self.cBoxCsosn,  self.cBoxCst)
        frmEntradaNF.setTabOrder( self.cBoxCst, self.txtBaseICMS)
        frmEntradaNF.setTabOrder(self.txtBaseICMS, self.txtValorICMS)
        frmEntradaNF.setTabOrder(self.txtValorICMS, self.txtBaseICMSST)
        frmEntradaNF.setTabOrder(self.txtBaseICMSST, self.txtValorICMSSub)
        frmEntradaNF.setTabOrder(self.txtValorICMSSub, self.txtValorPIS)
        frmEntradaNF.setTabOrder(self.txtValorPIS, self.txtValorConfins)
        frmEntradaNF.setTabOrder(self.txtValorConfins, self.txtValorFrete)
        frmEntradaNF.setTabOrder(self.txtValorFrete, self.txtValorSeguro)
        frmEntradaNF.setTabOrder(self.txtValorSeguro, self.txtValorDesconto)
        frmEntradaNF.setTabOrder(self.txtValorDesconto, self.txtOutrasDespesas)
        frmEntradaNF.setTabOrder(self.txtOutrasDespesas, self.txtValorIPI)
        frmEntradaNF.setTabOrder(self.txtValorIPI, self.txtAlicotaICMS)
        frmEntradaNF.setTabOrder(self.txtAlicotaICMS, self.txtAlicotaIPI)
        frmEntradaNF.setTabOrder(self.txtAlicotaIPI, self.cBoxProduto)
        frmEntradaNF.setTabOrder(self.cBoxProduto, self.cBoxUn)
        frmEntradaNF.setTabOrder(self.cBoxUn, self.txtQtd)
        frmEntradaNF.setTabOrder(self.txtQtd, self.txtValorUnotario)
        frmEntradaNF.setTabOrder(self.txtValorUnotario, self.txtValorTotal)
        frmEntradaNF.setTabOrder(self.txtValorTotal, self.btnAdd)
        frmEntradaNF.setTabOrder(self.btnAdd, self.tabDescricaoProduto)
        frmEntradaNF.setTabOrder(self.tabDescricaoProduto, self.txtSomatoriaTotalValor)
        frmEntradaNF.setTabOrder(self.txtSomatoriaTotalValor, self.btnRemove)
        frmEntradaNF.setTabOrder(self.btnRemove, self.txtInsMunicipal)
        frmEntradaNF.setTabOrder(self.txtInsMunicipal, self.txtValorTotalServico)
        frmEntradaNF.setTabOrder(self.txtValorTotalServico, self.txtBaseIssqn)
        frmEntradaNF.setTabOrder(self.txtBaseIssqn, self.txtValorIssqn)
        frmEntradaNF.setTabOrder(self.txtValorIssqn, self.btnDeletar)
        frmEntradaNF.setTabOrder(self.btnDeletar, self.btnCancelar)
        frmEntradaNF.setTabOrder(self.btnCancelar, self.btnSalvar)
        frmEntradaNF.setTabOrder(self.btnSalvar, self.btnNovo)
        frmEntradaNF.setTabOrder(self.btnNovo, self.btnEditar)

    def retranslateUi(self, frmEntradaNF):
        frmEntradaNF.setWindowTitle(_translate("frmEntradaNF", "Entrada de Nota Fiscal", None))
        self.txtCodig.setToolTip(_translate("frmEntradaNF", "Codigo", None))
        self.txtCodig.setWhatsThis(_translate("frmEntradaNF", "Campo do codigo de identificação do fornecedor", None))
        self.lblCodigo.setText(_translate("frmEntradaNF", "Cod.", None))
        self.lblFornecedor.setText(_translate("frmEntradaNF", "Fornecedor", None))
        self.txtFornecedor.setToolTip(_translate("frmEntradaNF", "Fornecedor", None))
        self.txtFornecedor.setWhatsThis(_translate("frmEntradaNF", "Campo do nome do fornecedor", None))
        self.txtNumNF.setToolTip(_translate("frmEntradaNF", "Numero NF", None))
        self.txtNumNF.setWhatsThis(_translate("frmEntradaNF", "Campo do numero da NF", None))
        self.lblNumNF.setText(_translate("frmEntradaNF", "Num. NF", None))
        self.lblSerie.setText(_translate("frmEntradaNF", "Serie", None))
        self.txtSerie.setToolTip(_translate("frmEntradaNF", "Série", None))
        self.txtSerie.setWhatsThis(_translate("frmEntradaNF", "Campo do numero de serie da NF", None))
        self.cboxTipos.setToolTip(_translate("frmEntradaNF", "Tipo", None))
        self.cboxTipos.setWhatsThis(_translate("frmEntradaNF", "Campo do tipo de NF", None))
        self.lblTipo.setText(_translate("frmEntradaNF", "Tipos", None))
        self.txtModelo.setToolTip(_translate("frmEntradaNF", "Modelo", None))
        self.txtModelo.setWhatsThis(_translate("frmEntradaNF", "Campo do numero do modelo da NF", None))
        self.lblModelo.setText(_translate("frmEntradaNF", "Modelo", None))
        self.lblEntrada.setText(_translate("frmEntradaNF", "Entrada", None))
        self.dateDataEntrada.setToolTip(_translate("frmEntradaNF", "Entrada", None))
        self.dateDataEntrada.setWhatsThis(_translate("frmEntradaNF", "Campo da data de entrada na NF no sistema", None))
        self.dateDataEmissao.setToolTip(_translate("frmEntradaNF", "Emissão", None))
        self.dateDataEmissao.setWhatsThis(_translate("frmEntradaNF", "Campo da data de emissão da NF", None))
        self.lblEmissao.setText(_translate("frmEntradaNF", "Emissão", None))
        self.txtBaseICMS.setToolTip(_translate("frmEntradaNF", "Base ICMS", None))
        self.txtBaseICMS.setWhatsThis(_translate("frmEntradaNF", "Campo da base de porcentagem do imposto ICMS do produto", None))
        self.txtBaseICMS.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblBaseICMS.setText(_translate("frmEntradaNF", "Base ICMS", None))
        self.txtValorICMS.setToolTip(_translate("frmEntradaNF", "Valor do ICMS", None))
        self.txtValorICMS.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do ICMS", None))
        self.txtValorICMS.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorICMS.setText(_translate("frmEntradaNF", "Valor ICMS", None))
        self.txtBaseICMSST.setToolTip(_translate("frmEntradaNF", "Base ICMS ST", None))
        self.txtBaseICMSST.setWhatsThis(_translate("frmEntradaNF", "Campo da base do ICMS ST", None))
        self.txtBaseICMSST.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblBaseICMSST.setText(_translate("frmEntradaNF", "Base ICMS ST", None))
        self.txtValorICMSSub.setToolTip(_translate("frmEntradaNF", "Valor ICMS Substituto", None))
        self.txtValorICMSSub.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do ICMS substituto", None))
        self.txtValorICMSSub.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorICMSSub.setText(_translate("frmEntradaNF", "Valor ICMS Sub.", None))
        self.txtValorPIS.setToolTip(_translate("frmEntradaNF", "Valor PIS", None))
        self.txtValorPIS.setWhatsThis(_translate("frmEntradaNF", "Campo do Valor do PIS", None))
        self.txtValorPIS.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorPis.setText(_translate("frmEntradaNF", "Valor PIS", None))
        self.txtValorConfins.setToolTip(_translate("frmEntradaNF", "Valor Confins", None))
        self.txtValorConfins.setWhatsThis(_translate("frmEntradaNF", "Campo do valor o Confins", None))
        self.txtValorConfins.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorConfins.setText(_translate("frmEntradaNF", "Valor Confins", None))
        self.txtValorFrete.setToolTip(_translate("frmEntradaNF", "Valor Frete", None))
        self.txtValorFrete.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do Frete", None))
        self.txtValorFrete.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorFrete.setText(_translate("frmEntradaNF", "Valor Frete", None))
        self.txtValorSeguro.setToolTip(_translate("frmEntradaNF", "Valor do Seguro", None))
        self.txtValorSeguro.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do seguro", None))
        self.txtValorSeguro.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorSeguro.setText(_translate("frmEntradaNF", "Valor Seguro", None))
        self.txtValorDesconto.setToolTip(_translate("frmEntradaNF", "Valor Desconto", None))
        self.txtValorDesconto.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do desconto", None))
        self.txtValorDesconto.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorDesconto.setText(_translate("frmEntradaNF", "Valor Desconto", None))
        self.txtOutrasDespesas.setToolTip(_translate("frmEntradaNF", "Outras Despesas", None))
        self.txtOutrasDespesas.setWhatsThis(_translate("frmEntradaNF", "Campo do valor de outras despesas", None))
        self.txtOutrasDespesas.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblOutrasDespesas.setText(_translate("frmEntradaNF", "Outr. Despesas", None))
        self.txtValorIPI.setToolTip(_translate("frmEntradaNF", "Valor IPI", None))
        self.txtValorIPI.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do IPI", None))
        self.txtValorIPI.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorIPI.setText(_translate("frmEntradaNF", "Valor IPI", None))

        self.txtAlicotaICMS.setToolTip(_translate("frmEntradaNF", "Alicota ICMS", None))
        self.txtAlicotaICMS.setWhatsThis(_translate("frmEntradaNF", "Campo da alicota do ICMS", None))
        self.txtAlicotaICMS.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblAlicotaICMS.setText(_translate("frmEntradaNF", "Alicota ICMS", None))

        self.txtAlicotaIPI.setToolTip(_translate("frmEntradaNF", "Alicota IPI", None))
        self.txtAlicotaIPI.setWhatsThis(_translate("frmEntradaNF", "Campo da alicota do IPI", None))
        self.txtAlicotaIPI.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblAlicotaIPI.setText(_translate("frmEntradaNF", "Alicota IPI", None))

        self.cBoxProduto.setToolTip(_translate("frmEntradaNF", "Produto", None))
        self.cBoxProduto.setWhatsThis(_translate("frmEntradaNF", "Campo do escolha do produto", None))
        self.lblUn.setText(_translate("frmEntradaNF", "UN", None))
        self.lblQtd.setText(_translate("frmEntradaNF", "QTD", None))
        self.lblValorUnitario.setText(_translate("frmEntradaNF", "Valor Unitario", None))
        self.lblProduto.setText(_translate("frmEntradaNF", "Produto", None))
        self.cBoxUn.setToolTip(_translate("frmEntradaNF", "UN", None))
        self.cBoxUn.setWhatsThis(_translate("frmEntradaNF", "Campo de escolha da unidade de medida do produto", None))
        self.txtValorUnotario.setToolTip(_translate("frmEntradaNF", "Valor Unitario", None))
        self.txtValorUnotario.setWhatsThis(_translate("frmEntradaNF", "Campo do valor unitario do produto", None))
        self.txtValorUnotario.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.tabDescricaoProduto.setWhatsThis(_translate("frmEntradaNF", "Campo de descrição de produtos da NF", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(0)
        item.setText(_translate("frmEntradaNF", "Cod.", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(1)
        item.setText(_translate("frmEntradaNF", "Descrição", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(2)
        item.setText(_translate("frmEntradaNF", "NCM/SH", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(3)
        item.setText(_translate("frmEntradaNF", "CST", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(4)
        item.setText(_translate("frmEntradaNF", "CFOP", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(5)
        item.setText(_translate("frmEntradaNF", "CSOSN", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(6)
        item.setText(_translate("frmEntradaNF", "UN", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(7)
        item.setText(_translate("frmEntradaNF", "QTD", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(8)
        item.setText(_translate("frmEntradaNF", "Valor Unitario", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(9)
        item.setText(_translate("frmEntradaNF", "Valor Total", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(10)
        item.setText(_translate("frmEntradaNF", "Valor ICMS", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(11)
        item.setText(_translate("frmEntradaNF", "Valor IPI", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(12)
        item.setText(_translate("frmEntradaNF", "Alicota ICMS", None))
        item = self.tabDescricaoProduto.horizontalHeaderItem(13)
        item.setText(_translate("frmEntradaNF", "Alicota IPI", None))
        self.txtQtd.setToolTip(_translate("frmEntradaNF", "Quantidade", None))
        self.txtQtd.setWhatsThis(_translate("frmEntradaNF", "Campo de quantidade do produto", None))
        self.txtQtd.setPlaceholderText(_translate("frmEntradaNF", "0", None))
        self.lblValorTotal.setText(_translate("frmEntradaNF", "Valor Total", None))
        self.txtValorTotal.setToolTip(_translate("frmEntradaNF", "Valor Total", None))
        self.txtValorTotal.setWhatsThis(_translate("frmEntradaNF", "Campo do valor total do produto", None))
        self.txtValorTotal.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.SomatoriaTotalValor.setText(_translate("frmEntradaNF", "Somatoria Total Valor", None))
        self.txtSomatoriaTotalValor.setToolTip(_translate("frmEntradaNF", "Somatoria Total Valor", None))
        self.txtSomatoriaTotalValor.setWhatsThis(_translate("frmEntradaNF", "Campo do resultado do valor total produtos", None))
        self.txtSomatoriaTotalValor.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.txtBaseIssqn.setToolTip(_translate("frmEntradaNF", "Base ISSQN", None))
        self.txtBaseIssqn.setWhatsThis(_translate("frmEntradaNF", "Campo da base do ISSQN", None))
        self.txtBaseIssqn.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblValorIssqn.setText(_translate("frmEntradaNF", "Valor ISSQN", None))
        self.txtInsMunicipal.setToolTip(_translate("frmEntradaNF", "Inscrição Municipal", None))
        self.txtInsMunicipal.setWhatsThis(_translate("frmEntradaNF", "Campo do número da Inscrição Estadual", None))
        self.lblInsMunicipal.setText(_translate("frmEntradaNF", "Ins. Municipal", None))
        self.txtValorTotalServico.setToolTip(_translate("frmEntradaNF", "Valor Total Serviço", None))
        self.txtValorTotalServico.setWhatsThis(_translate("frmEntradaNF", "Campo do valor total do serviço", None))
        self.txtValorTotalServico.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.txtValorIssqn.setToolTip(_translate("frmEntradaNF", "Valor ISSQN", None))
        self.txtValorIssqn.setWhatsThis(_translate("frmEntradaNF", "Campo do valor do ISSQN", None))
        self.txtValorIssqn.setPlaceholderText(_translate("frmEntradaNF", "0,00", None))
        self.lblBaseIssqn.setText(_translate("frmEntradaNF", "Base ISSQN", None))
        self.lblValorTotalServico.setText(_translate("frmEntradaNF", "Valor Total Ser.", None))
        self.lblCst.setText(_translate("frmEntradaNF", "CST", None))
        self.lblCfop.setText(_translate("frmEntradaNF", "CFOP", None))
        self.cBoxNcm.setToolTip(_translate("frmEntradaNF", "NCM", None))
        self.cBoxNcm.setWhatsThis(_translate("frmEntradaNF", "Campo de escolha do codigo do imposto NCM", None))
        self.lblNcm.setText(_translate("frmEntradaNF", "NCM", None))
        self.cBoxCfop.setToolTip(_translate("frmEntradaNF", "CFOP", None))
        self.cBoxCfop.setWhatsThis(_translate("frmEntradaNF", "Campo de escolha do codigo do imposto CFOP", None))
        self.cBoxCst.setToolTip(_translate("frmEntradaNF", "CFOP", None))
        self.cBoxCst.setWhatsThis(_translate("frmEntradaNF", "Campo de escolha do codigo do imposto CST", None))
        self.cBoxCsosn.setToolTip(_translate("frmEntradaNF", "CSOSN", None))
        self.cBoxCsosn.setWhatsThis(_translate("frmEntradaNF", "Campo de escolha do codigo do imposto CSOSN", None))
        self.lblCsosn.setText(_translate("frmEntradaNF", "CSOSN", None))
        self.txtCodigoMotorista.setToolTip(_translate("frmEntradaNF", "Codigo", None))
        self.txtCodigoMotorista.setWhatsThis(_translate("frmEntradaNF", "Campo do codigo de identificação do motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmEntradaNF", "Cod.", None))
        self.lblMotorista.setText(_translate("frmEntradaNF", "Transportadora / Motorista", None))
        self.txtMotorista.setToolTip(_translate("frmEntradaNF", "Motorista", None))
        self.txtMotorista.setWhatsThis(_translate("frmEntradaNF", "Campo do nomedo motorista", None))
        self.btnDeletar.setWhatsThis(_translate("frmEntradaNF", "Botão para deletar a NF cadastrada", None))
        self.btnDeletar.setText(_translate("frmEntradaNF", "Deletar", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaNF", "Botão de cancelar a entrada ou edição de NF", None))
        self.btnCancelar.setText(_translate("frmEntradaNF", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaNF", "botão para salvar a entrada da NF", None))
        self.btnSalvar.setText(_translate("frmEntradaNF", "Salvar", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaNF", "Botão para nova entrada de NF", None))
        self.btnNovo.setText(_translate("frmEntradaNF", "Novo", None))
        self.btnEditar.setWhatsThis(_translate("frmEntradaNF", "botão para salvar edição de NF", None))
        self.btnEditar.setText(_translate("frmEntradaNF", "Editar", None))