# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaVeiculosEmpresa.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaVeiculosEmpresa(object):
    def setupUi(self, frmEntradaVeiculosEmpresa):
        frmEntradaVeiculosEmpresa.setObjectName(_fromUtf8("frmEntradaVeiculosEmpresa"))
        frmEntradaVeiculosEmpresa.resize(570, 607)
        frmEntradaVeiculosEmpresa.setMinimumSize(QtCore.QSize(570, 607))
        frmEntradaVeiculosEmpresa.setMaximumSize(QtCore.QSize(570, 607))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/carro.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmEntradaVeiculosEmpresa.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        frmEntradaVeiculosEmpresa.setFont(font)

        self.txtPesquisar = QtGui.QLineEdit(frmEntradaVeiculosEmpresa)
        self.txtPesquisar.setGeometry(QtCore.QRect(170, 40, 341, 25))
        self.txtPesquisar.setMaxLength(70)
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))
        self.btnPesquisar = QtGui.QPushButton(frmEntradaVeiculosEmpresa)
        self.btnPesquisar.setGeometry(QtCore.QRect(520, 40, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisar.setFont(font)
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))
        self.grbTipoCosulta = QtGui.QGroupBox(frmEntradaVeiculosEmpresa)
        self.grbTipoCosulta.setGeometry(QtCore.QRect(10, 10, 151, 81))
        self.grbTipoCosulta.setObjectName(_fromUtf8("grbTipoCosulta"))
        self.radbtnVeiculo = QtGui.QRadioButton(self.grbTipoCosulta)
        self.radbtnVeiculo.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radbtnVeiculo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radbtnVeiculo.setObjectName(_fromUtf8("radbtnVeiculo"))
        self.radbtnNomeContudor = QtGui.QRadioButton(self.grbTipoCosulta)
        self.radbtnNomeContudor.setGeometry(QtCore.QRect(10, 20, 131, 17))
        self.radbtnNomeContudor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radbtnNomeContudor.setObjectName(_fromUtf8("radbtnNomeContudor"))
        self.radbtnPlacaVeiculo = QtGui.QRadioButton(self.grbTipoCosulta)
        self.radbtnPlacaVeiculo.setGeometry(QtCore.QRect(10, 60, 111, 17))
        self.radbtnPlacaVeiculo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radbtnPlacaVeiculo.setObjectName(_fromUtf8("radbtnPlacaVeiculo"))
        self.lblPesquisa = QtGui.QLabel(frmEntradaVeiculosEmpresa)
        self.lblPesquisa.setGeometry(QtCore.QRect(170, 20, 61, 16))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))
        self.tabPesquisa = QtGui.QTableWidget(frmEntradaVeiculosEmpresa)
        self.tabPesquisa.setGeometry(QtCore.QRect(10, 100, 551, 151))
        self.tabPesquisa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabPesquisa.setObjectName(_fromUtf8("tabPesquisa"))
        self.tabPesquisa.setColumnCount(0)
        self.tabPesquisa.setRowCount(0)
        self.grbBotoes = QtGui.QGroupBox(frmEntradaVeiculosEmpresa)
        self.grbBotoes.setGeometry(QtCore.QRect(4, 522, 562, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(270, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setGeometry(QtCore.QRect(470, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setGeometry(QtCore.QRect(370, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.groupBox = QtGui.QGroupBox(frmEntradaVeiculosEmpresa)
        self.groupBox.setGeometry(QtCore.QRect(4, 258, 563, 261))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.txtData = QtGui.QDateEdit(self.groupBox)
        self.txtData.setGeometry(QtCore.QRect(10, 230, 110, 25))
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.lblHoraEntrada = QtGui.QLabel(self.groupBox)
        self.lblHoraEntrada.setGeometry(QtCore.QRect(150, 210, 111, 19))
        self.lblHoraEntrada.setObjectName(_fromUtf8("lblHoraEntrada"))
        self.txtModelo = QtGui.QLineEdit(self.groupBox)
        self.txtModelo.setEnabled(False)
        self.txtModelo.setGeometry(QtCore.QRect(230, 124, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModelo.setPalette(palette)
        self.txtModelo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))
        self.lblTipoVeiculo = QtGui.QLabel(self.groupBox)
        self.lblTipoVeiculo.setGeometry(QtCore.QRect(10, 104, 111, 19))
        self.lblTipoVeiculo.setObjectName(_fromUtf8("lblTipoVeiculo"))
        self.lblMarca = QtGui.QLabel(self.groupBox)
        self.lblMarca.setGeometry(QtCore.QRect(10, 152, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))
        self.lblDataEntrada = QtGui.QLabel(self.groupBox)
        self.lblDataEntrada.setGeometry(QtCore.QRect(10, 210, 111, 19))
        self.lblDataEntrada.setObjectName(_fromUtf8("lblDataEntrada"))
        self.txtMarca = QtGui.QLineEdit(self.groupBox)
        self.txtMarca.setEnabled(False)
        self.txtMarca.setGeometry(QtCore.QRect(10, 172, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarca.setPalette(palette)
        self.txtMarca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtMarca.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.groupBox)
        self.txtNomeFuncionario.setEnabled(False)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(180, 24, 381, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeFuncionario.setPalette(palette)
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.txtHora = QtGui.QTimeEdit(self.groupBox)
        self.txtHora.setGeometry(QtCore.QRect(150, 230, 118, 25))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.txtSetor = QtGui.QLineEdit(self.groupBox)
        self.txtSetor.setEnabled(False)
        self.txtSetor.setGeometry(QtCore.QRect(10, 71, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetor.setPalette(palette)
        self.txtSetor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtSetor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtSetor.setMaxLength(50)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        self.lblNomeFuncionario = QtGui.QLabel(self.groupBox)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(180, 4, 151, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))
        self.lblCargo = QtGui.QLabel(self.groupBox)
        self.lblCargo.setGeometry(QtCore.QRect(230, 51, 66, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))
        self.txtPlaca = QtGui.QLineEdit(self.groupBox)
        self.txtPlaca.setEnabled(False)
        self.txtPlaca.setGeometry(QtCore.QRect(350, 174, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlaca.setPalette(palette)
        self.txtPlaca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtPlaca.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))
        self.lblSetor = QtGui.QLabel(self.groupBox)
        self.lblSetor.setGeometry(QtCore.QRect(10, 51, 66, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        self.lblModelo = QtGui.QLabel(self.groupBox)
        self.lblModelo.setGeometry(QtCore.QRect(230, 104, 51, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))
        self.txtidFuncionario = QtGui.QLineEdit(self.groupBox)
        self.txtidFuncionario.setEnabled(False)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 24, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoFuncionario = QtGui.QLabel(self.groupBox)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(10, 4, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))
        self.txtCargos = QtGui.QLineEdit(self.groupBox)
        self.txtCargos.setEnabled(False)
        self.txtCargos.setGeometry(QtCore.QRect(230, 71, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCargos.setPalette(palette)
        self.txtCargos.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCargos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCargos.setMaxLength(50)
        self.txtCargos.setObjectName(_fromUtf8("txtCargos"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(10, 124, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit.setPalette(palette)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setMaxLength(40)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lblPlaca = QtGui.QLabel(self.groupBox)
        self.lblPlaca.setGeometry(QtCore.QRect(350, 154, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))
        self.lblHoraEntrada.setBuddy(self.txtHora)
        self.lblTipoVeiculo.setBuddy(self.lineEdit)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblDataEntrada.setBuddy(self.txtData)
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblCargo.setBuddy(self.txtCargos)
        self.lblSetor.setBuddy(self.txtSetor)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)
        self.lblPlaca.setBuddy(self.txtPlaca)

        self.retranslateUi(frmEntradaVeiculosEmpresa)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaVeiculosEmpresa)
        frmEntradaVeiculosEmpresa.setTabOrder(self.radbtnNomeContudor, self.radbtnVeiculo)
        frmEntradaVeiculosEmpresa.setTabOrder(self.radbtnVeiculo, self.radbtnPlacaVeiculo)
        frmEntradaVeiculosEmpresa.setTabOrder(self.radbtnPlacaVeiculo, self.txtPesquisar)
        frmEntradaVeiculosEmpresa.setTabOrder(self.txtPesquisar, self.btnPesquisar)
        frmEntradaVeiculosEmpresa.setTabOrder(self.btnPesquisar, self.tabPesquisa)

    def retranslateUi(self, frmEntradaVeiculosEmpresa):
        frmEntradaVeiculosEmpresa.setWindowTitle(_translate("frmEntradaVeiculosEmpresa", "Entrada de Veiculos Empresa", None))
        self.txtPesquisar.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Pesquisa", None))
        self.txtPesquisar.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo de pesquisa", None))
        self.grbTipoCosulta.setTitle(_translate("frmEntradaVeiculosEmpresa", "Tipo de Consulta", None))
        self.radbtnVeiculo.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo de escolha do tipo de consulta por veiculo", None))
        self.radbtnVeiculo.setText(_translate("frmEntradaVeiculosEmpresa", "Veiculo", None))
        self.radbtnNomeContudor.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo de escolha do tipo de consulta por nome condutor", None))
        self.radbtnNomeContudor.setText(_translate("frmEntradaVeiculosEmpresa", "Nome Condutor", None))
        self.radbtnPlacaVeiculo.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo de escolha do tipo de consulta por plca veiculo", None))
        self.radbtnPlacaVeiculo.setText(_translate("frmEntradaVeiculosEmpresa", "Placa Veiculo", None))
        self.lblPesquisa.setText(_translate("frmEntradaVeiculosEmpresa", "Pesquisa", None))
        self.tabPesquisa.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Tabela de resultados da pesquisa", None))
        self.grbBotoes.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmEntradaVeiculosEmpresa", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmEntradaVeiculosEmpresa", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmEntradaVeiculosEmpresa", "Salvar", None))
        self.txtData.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Data Entrada", None))
        self.txtData.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo da data de entrada", None))
        self.lblHoraEntrada.setText(_translate("frmEntradaVeiculosEmpresa", "Hora Entrada", None))
        self.txtModelo.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Marca do Veiculo", None))
        self.txtModelo.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo do nome do modelo do veiculo", None))
        self.lblTipoVeiculo.setText(_translate("frmEntradaVeiculosEmpresa", "Tipo de Veiculos", None))
        self.lblMarca.setText(_translate("frmEntradaVeiculosEmpresa", "Marca", None))
        self.lblDataEntrada.setText(_translate("frmEntradaVeiculosEmpresa", "Data Entrada", None))
        self.txtMarca.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Marca do Veiculo", None))
        self.txtMarca.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo do nome da marca do veiculo", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo do nome do funcionario", None))
        self.txtHora.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Hora Entrada", None))
        self.txtHora.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo da hora de entrada", None))
        self.txtSetor.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Setor do Funcionario", None))
        self.txtSetor.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo do setor de trabalho do funcionario", None))
        self.lblNomeFuncionario.setText(_translate("frmEntradaVeiculosEmpresa", "Nome Funcionario", None))
        self.lblCargo.setText(_translate("frmEntradaVeiculosEmpresa", "Cargo", None))
        self.txtPlaca.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Placa do Veiculo", None))
        self.txtPlaca.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmEntradaVeiculosEmpresa", "nnn-0000; ", None))
        self.txtPlaca.setText(_translate("frmEntradaVeiculosEmpresa", "-", None))
        self.lblSetor.setText(_translate("frmEntradaVeiculosEmpresa", "Setor", None))
        self.lblModelo.setText(_translate("frmEntradaVeiculosEmpresa", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo do codigo de identificação do funcionario", None))
        self.lblCodigoFuncionario.setText(_translate("frmEntradaVeiculosEmpresa", "Codigo Funcionario", None))
        self.txtCargos.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Cargo do Funcionario", None))
        self.txtCargos.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo do cargo de trabalho do funcionario", None))
        self.lineEdit.setToolTip(_translate("frmEntradaVeiculosEmpresa", "Tipo do Veiculo", None))
        self.lineEdit.setWhatsThis(_translate("frmEntradaVeiculosEmpresa", "Campo de descrição do tipo de veiculo", None))
        self.lblPlaca.setText(_translate("frmEntradaVeiculosEmpresa", "Placa", None))

