# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPesquisarFornecedor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmPesquisarFornecedor(object):
    def setupUi(self, frmPesquisarFornecedor):
        frmPesquisarFornecedor.setObjectName(_fromUtf8("frmPesquisarFornecedor"))
        frmPesquisarFornecedor.resize(794, 504)
        frmPesquisarFornecedor.setMinimumSize(QtCore.QSize(794, 504))
        frmPesquisarFornecedor.setMaximumSize(QtCore.QSize(794, 504))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmPesquisarFornecedor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/folder_saved_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmPesquisarFornecedor.setWindowIcon(icon)
        frmPesquisarFornecedor.setSizeGripEnabled(True)
        frmPesquisarFornecedor.setModal(True)

        self.grbTipoPesquisa = QtGui.QGroupBox(frmPesquisarFornecedor)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(10, 10, 331, 91))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))

        self.radBtnRazaoSocial = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnRazaoSocial.setGeometry(QtCore.QRect(10, 40, 161, 23))
        self.radBtnRazaoSocial.setObjectName(_fromUtf8("radBtnRazaoSocial"))

        self.radBtnFantasia = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnFantasia.setGeometry(QtCore.QRect(10, 60, 171, 23))
        self.radBtnFantasia.setObjectName(_fromUtf8("radBtnFantasia"))

        self.radBtnCnpj = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnCnpj.setGeometry(QtCore.QRect(180, 20, 91, 23))
        self.radBtnCnpj.setObjectName(_fromUtf8("radBtnCnpj"))

        self.radBtnInsEstadual = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnInsEstadual.setGeometry(QtCore.QRect(180, 40, 141, 23))
        self.radBtnInsEstadual.setObjectName(_fromUtf8("radBtnInsEstadual"))

        self.radBtnCodigo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnCodigo.setGeometry(QtCore.QRect(10, 20, 63, 23))
        self.radBtnCodigo.setObjectName(_fromUtf8("radBtnCodigo"))

        self.txtPesquisar = QtGui.QLineEdit(frmPesquisarFornecedor)
        self.txtPesquisar.setGeometry(QtCore.QRect(350, 70, 391, 25))
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))

        self.btnPesquisar = QtGui.QPushButton(frmPesquisarFornecedor)
        self.btnPesquisar.setGeometry(QtCore.QRect(750, 70, 31, 27))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisar.setIcon(icon)
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.tabPesquisar = QtGui.QTableWidget(frmPesquisarFornecedor)
        self.tabPesquisar.setGeometry(QtCore.QRect(10, 110, 771, 381))
        self.tabPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabPesquisar.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabPesquisar.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabPesquisar.setObjectName(_fromUtf8("tabPesquisar"))
        self.tabPesquisar.setColumnCount(19)
        self.tabPesquisar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(18, item)
        self.tabPesquisar.verticalHeader().setVisible(False)
        self.tabPesquisar.verticalHeader().setCascadingSectionResizes(True)

        self.retranslateUi(frmPesquisarFornecedor)
        QtCore.QMetaObject.connectSlotsByName(frmPesquisarFornecedor)
        frmPesquisarFornecedor.setTabOrder(self.radBtnRazaoSocial, self.radBtnFantasia)
        frmPesquisarFornecedor.setTabOrder(self.radBtnFantasia, self.radBtnCnpj)
        frmPesquisarFornecedor.setTabOrder(self.radBtnCnpj, self.radBtnInsEstadual)
        frmPesquisarFornecedor.setTabOrder(self.radBtnInsEstadual, self.txtPesquisar)
        frmPesquisarFornecedor.setTabOrder(self.txtPesquisar, self.btnPesquisar)
        frmPesquisarFornecedor.setTabOrder(self.btnPesquisar, self.tabPesquisar)

    def retranslateUi(self, frmPesquisarFornecedor):
        frmPesquisarFornecedor.setWindowTitle(_translate("frmPesquisarFornecedor", "Pesquisar Fornecedor", None))
        self.grbTipoPesquisa.setTitle(_translate("frmPesquisarFornecedor", "Tipo Pesquisa", None))
        self.radBtnRazaoSocial.setToolTip(_translate("frmPesquisarFornecedor", "Razão Social / Nome", None))
        self.radBtnRazaoSocial.setWhatsThis(_translate("frmPesquisarFornecedor", "Item de seleção para a pesquisa por razão social ou nome", None))
        self.radBtnRazaoSocial.setText(_translate("frmPesquisarFornecedor", "Razão Social / Nome", None))
        self.radBtnFantasia.setToolTip(_translate("frmPesquisarFornecedor", "Fantasia / Sobrenome", None))
        self.radBtnFantasia.setWhatsThis(_translate("frmPesquisarFornecedor", "Item de seleção para a pesquisa por nome fantasia ou sobrenome", None))
        self.radBtnFantasia.setText(_translate("frmPesquisarFornecedor", "Fantasia / Sobrenome", None))
        self.radBtnCnpj.setToolTip(_translate("frmPesquisarFornecedor", "CNPJ / CPF", None))
        self.radBtnCnpj.setWhatsThis(_translate("frmPesquisarFornecedor", "Item de seleção para a pesquisa por CNPJ OU CPF", None))
        self.radBtnCnpj.setText(_translate("frmPesquisarFornecedor", "CNPJ / CPF", None))
        self.radBtnInsEstadual.setToolTip(_translate("frmPesquisarFornecedor", "Inscrição Estadual / RG", None))
        self.radBtnInsEstadual.setWhatsThis(_translate("frmPesquisarFornecedor", "Item de seleção para a pesquisa por inscrição estadual ou RG", None))
        self.radBtnInsEstadual.setText(_translate("frmPesquisarFornecedor", "Ins. Estadual / RG", None))
        self.radBtnCodigo.setToolTip(_translate("frmPesquisarFornecedor", "Codigo", None))
        self.radBtnCodigo.setWhatsThis(_translate("frmPesquisarFornecedor", "Item de seleção para a pesquisa por codigo", None))
        self.radBtnCodigo.setText(_translate("frmPesquisarFornecedor", "Codigo", None))
        self.txtPesquisar.setToolTip(_translate("frmPesquisarFornecedor", "Pesquisar", None))
        self.txtPesquisar.setWhatsThis(_translate("frmPesquisarFornecedor", "Campo de inserir os dados para pesquisar", None))
        self.txtPesquisar.setPlaceholderText(_translate("frmPesquisarFornecedor", "Pesquisa", None))
        self.btnPesquisar.setWhatsThis(_translate("frmPesquisarFornecedor", "Botão para pesquisar as informações", None))
        self.tabPesquisar.setWhatsThis(_translate("frmPesquisarFornecedor", "Tabela dos dados pesquisados", None))
        item = self.tabPesquisar.horizontalHeaderItem(0)
        item.setText(_translate("frmPesquisarFornecedor", "Cod.", None))
        item = self.tabPesquisar.horizontalHeaderItem(1)
        item.setText(_translate("frmPesquisarFornecedor", "Tipo", None))
        item = self.tabPesquisar.horizontalHeaderItem(2)
        item.setText(_translate("frmPesquisarFornecedor", "R. Social / Nome", None))
        item = self.tabPesquisar.horizontalHeaderItem(3)
        item.setText(_translate("frmPesquisarFornecedor", "Fantasia / Sobrenome", None))
        item = self.tabPesquisar.horizontalHeaderItem(4)
        item.setText(_translate("frmPesquisarFornecedor", "CNPJ / CPF", None))
        item = self.tabPesquisar.horizontalHeaderItem(5)
        item.setText(_translate("frmPesquisarFornecedor", "Ins. Estadual / RG", None))
        item = self.tabPesquisar.horizontalHeaderItem(6)
        item.setText(_translate("frmPesquisarFornecedor", "Expeditor", None))
        item = self.tabPesquisar.horizontalHeaderItem(7)
        item.setText(_translate("frmPesquisarFornecedor", "UF", None))
        item = self.tabPesquisar.horizontalHeaderItem(8)
        item.setText(_translate("frmPesquisarFornecedor", "Aniversario", None))
        item = self.tabPesquisar.horizontalHeaderItem(9)
        item.setText(_translate("frmPesquisarFornecedor", "Endereço", None))
        item = self.tabPesquisar.horizontalHeaderItem(10)
        item.setText(_translate("frmPesquisarFornecedor", "Número", None))
        item = self.tabPesquisar.horizontalHeaderItem(11)
        item.setText(_translate("frmPesquisarFornecedor", "Complemento", None))
        item = self.tabPesquisar.horizontalHeaderItem(12)
        item.setText(_translate("frmPesquisarFornecedor", "Bairro", None))
        item = self.tabPesquisar.horizontalHeaderItem(13)
        item.setText(_translate("frmPesquisarFornecedor", "Cidade", None))
        item = self.tabPesquisar.horizontalHeaderItem(14)
        item.setText(_translate("frmPesquisarFornecedor", "Estado", None))
        item = self.tabPesquisar.horizontalHeaderItem(15)
        item.setText(_translate("frmPesquisarFornecedor", "CEP", None))
        item = self.tabPesquisar.horizontalHeaderItem(16)
        item.setText(_translate("frmPesquisarFornecedor", "Site", None))
        item = self.tabPesquisar.horizontalHeaderItem(17)
        item.setText(_translate("frmPesquisarFornecedor", "Obs", None))
        item = self.tabPesquisar.horizontalHeaderItem(18)
        item.setText(_translate("frmPesquisarFornecedor", "Situação", None))

