# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPesquisarMotorista.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmConsultarMotoristas(object):
    def setupUi(self, frmConsultarMotoristas):
        frmConsultarMotoristas.setObjectName(_fromUtf8("frmConsultarMotoristas"))
        frmConsultarMotoristas.resize(793, 502)
        frmConsultarMotoristas.setMinimumSize(QtCore.QSize(793, 502))
        frmConsultarMotoristas.setMaximumSize(QtCore.QSize(793, 502))
        font = QtGui.QFont()
        font.setPointSize(11)
        frmConsultarMotoristas.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/folder_saved_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmConsultarMotoristas.setWindowIcon(icon)
        frmConsultarMotoristas.setSizeGripEnabled(True)
        frmConsultarMotoristas.setModal(True)

        self.grbTipoPesquisa = QtGui.QGroupBox(frmConsultarMotoristas)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))

        self.radBtnNome = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnNome.setGeometry(QtCore.QRect(20, 33, 81, 23))
        self.radBtnNome.setObjectName(_fromUtf8("radBtnNome"))

        self.radBtnCpf = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnCpf.setGeometry(QtCore.QRect(20, 53, 51, 23))
        self.radBtnCpf.setObjectName(_fromUtf8("radBtnCpf"))

        self.radBtnRg = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnRg.setGeometry(QtCore.QRect(110, 13, 41, 23))
        self.radBtnRg.setObjectName(_fromUtf8("radBtnRg"))

        self.radBtnNumCarteira = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnNumCarteira.setGeometry(QtCore.QRect(110, 33, 161, 23))
        self.radBtnNumCarteira.setObjectName(_fromUtf8("radBtnNumCarteira"))

        self.radBtnPis = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnPis.setGeometry(QtCore.QRect(110, 53, 161, 23))
        self.radBtnPis.setObjectName(_fromUtf8("radBtnPis"))

        self.radBtnCodigo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnCodigo.setGeometry(QtCore.QRect(20, 14, 71, 23))
        self.radBtnCodigo.setObjectName(_fromUtf8("radBtnCodigo"))

        self.txtPesquisar = QtGui.QLineEdit(frmConsultarMotoristas)
        self.txtPesquisar.setGeometry(QtCore.QRect(300, 60, 441, 25))
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))

        self.btnPesquisar = QtGui.QPushButton(frmConsultarMotoristas)
        self.btnPesquisar.setGeometry(QtCore.QRect(750, 60, 31, 27))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisar.setIcon(icon)
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.tabPesquisar = QtGui.QTableWidget(frmConsultarMotoristas)
        self.tabPesquisar.setGeometry(QtCore.QRect(10, 100, 771, 381))
        self.tabPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabPesquisar.setObjectName(_fromUtf8("tabPesquisar"))
        self.tabPesquisar.setColumnCount(26)
        self.tabPesquisar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisar.setHorizontalHeaderItem(25, item)

        self.retranslateUi(frmConsultarMotoristas)
        QtCore.QMetaObject.connectSlotsByName(frmConsultarMotoristas)
        frmConsultarMotoristas.setTabOrder(self.radBtnNome, self.radBtnCpf)
        frmConsultarMotoristas.setTabOrder(self.radBtnCpf, self.radBtnRg)
        frmConsultarMotoristas.setTabOrder(self.radBtnRg, self.txtPesquisar)
        frmConsultarMotoristas.setTabOrder(self.txtPesquisar, self.btnPesquisar)
        frmConsultarMotoristas.setTabOrder(self.btnPesquisar, self.tabPesquisar)

    def retranslateUi(self, frmConsultarMotoristas):
        frmConsultarMotoristas.setWindowTitle(_translate("frmConsultarMotoristas", "Pesquisa Motoristas", None))
        self.grbTipoPesquisa.setTitle(_translate("frmConsultarMotoristas", "Tipo Pesquisa", None))
        self.radBtnNome.setToolTip(_translate("frmConsultarMotoristas", "Nome", None))
        self.radBtnNome.setText(_translate("frmConsultarMotoristas", "Nome", None))
        self.radBtnCpf.setToolTip(_translate("frmConsultarMotoristas", "CPF", None))
        self.radBtnCpf.setText(_translate("frmConsultarMotoristas", "CPF", None))
        self.radBtnRg.setToolTip(_translate("frmConsultarMotoristas", "RG", None))
        self.radBtnRg.setText(_translate("frmConsultarMotoristas", "RG", None))
        self.radBtnNumCarteira.setToolTip(_translate("frmConsultarMotoristas", "Nº Carteira", None))
        self.radBtnNumCarteira.setText(_translate("frmConsultarMotoristas", "Nº Carteira Motorista", None))
        self.radBtnPis.setToolTip(_translate("frmConsultarMotoristas", "Nº Carteira", None))
        self.radBtnPis.setText(_translate("frmConsultarMotoristas", "PIS/PASEP", None))
        self.radBtnCodigo.setToolTip(_translate("frmConsultarMotoristas", "Nº Carteira", None))
        self.radBtnCodigo.setText(_translate("frmConsultarMotoristas", "Codigo", None))
        self.txtPesquisar.setToolTip(_translate("frmConsultarMotoristas", "Pesquisar", None))
        self.txtPesquisar.setWhatsThis(_translate("frmConsultarMotoristas", "Campo de inserir os dados para pesquisar", None))
        self.txtPesquisar.setPlaceholderText(_translate("frmConsultarMotoristas", "Pesquisar", None))
        item = self.tabPesquisar.horizontalHeaderItem(0)
        item.setText(_translate("frmConsultarMotoristas", "Cod.", None))
        item = self.tabPesquisar.horizontalHeaderItem(1)
        item.setText(_translate("frmConsultarMotoristas", "Nome", None))
        item = self.tabPesquisar.horizontalHeaderItem(2)
        item.setText(_translate("frmConsultarMotoristas", "Sobrenome", None))
        item = self.tabPesquisar.horizontalHeaderItem(3)
        item.setText(_translate("frmConsultarMotoristas", "CNH", None))
        item = self.tabPesquisar.horizontalHeaderItem(4)
        item.setText(_translate("frmConsultarMotoristas", "CPF", None))
        item = self.tabPesquisar.horizontalHeaderItem(5)
        item.setText(_translate("frmConsultarMotoristas", "RG", None))
        item = self.tabPesquisar.horizontalHeaderItem(6)
        item.setText(_translate("frmConsultarMotoristas", "Expeditor", None))
        item = self.tabPesquisar.horizontalHeaderItem(7)
        item.setText(_translate("frmConsultarMotoristas", "UF", None))
        item = self.tabPesquisar.horizontalHeaderItem(8)
        item.setText(_translate("frmConsultarMotoristas", "PIS/PASEP", None))
        item = self.tabPesquisar.horizontalHeaderItem(9)
        item.setText(_translate("frmConsultarMotoristas", "Data", None))
        item = self.tabPesquisar.horizontalHeaderItem(10)
        item.setText(_translate("frmConsultarMotoristas", "Gênero", None))
        item = self.tabPesquisar.horizontalHeaderItem(11)
        item.setText(_translate("frmConsultarMotoristas", "Mãe", None))
        item = self.tabPesquisar.horizontalHeaderItem(12)
        item.setText(_translate("frmConsultarMotoristas", "Pai", None))
        item = self.tabPesquisar.horizontalHeaderItem(13)
        item.setText(_translate("frmConsultarMotoristas", "Endereco", None))
        item = self.tabPesquisar.horizontalHeaderItem(14)
        item.setText(_translate("frmConsultarMotoristas", "Numero", None))
        item = self.tabPesquisar.horizontalHeaderItem(15)
        item.setText(_translate("frmConsultarMotoristas", "Complemento", None))
        item = self.tabPesquisar.horizontalHeaderItem(16)
        item.setText(_translate("frmConsultarMotoristas", "Bairro", None))
        item = self.tabPesquisar.horizontalHeaderItem(17)
        item.setText(_translate("frmConsultarMotoristas", "Cidade", None))
        item = self.tabPesquisar.horizontalHeaderItem(18)
        item.setText(_translate("frmConsultarMotoristas", "Estado", None))
        item = self.tabPesquisar.horizontalHeaderItem(19)
        item.setText(_translate("frmConsultarMotoristas", "CEP", None))
        item = self.tabPesquisar.horizontalHeaderItem(20)
        item.setText(_translate("frmConsultarMotoristas", "Categoria CNH", None))
        item = self.tabPesquisar.horizontalHeaderItem(21)
        item.setText(_translate("frmConsultarMotoristas", "Marca Vei.", None))
        item = self.tabPesquisar.horizontalHeaderItem(22)
        item.setText(_translate("frmConsultarMotoristas", "Modelo Veic.", None))
        item = self.tabPesquisar.horizontalHeaderItem(23)
        item.setText(_translate("frmConsultarMotoristas", "Placa Veic.", None))
        item = self.tabPesquisar.horizontalHeaderItem(24)
        item.setText(_translate("frmConsultarMotoristas", "Observação", None))
        item = self.tabPesquisar.horizontalHeaderItem(25)
        item.setText(_translate("frmConsultarMotoristas", "Situação", None))

