# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaVeiculosCarregamentos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaVeiculosCarregamento(object):
    def setupUi(self, frmSaidaVeiculosCarregamento):
        frmSaidaVeiculosCarregamento.setObjectName(_fromUtf8("frmSaidaVeiculosCarregamento"))
        frmSaidaVeiculosCarregamento.resize(887, 628)
        frmSaidaVeiculosCarregamento.setMinimumSize(QtCore.QSize(887, 628))
        frmSaidaVeiculosCarregamento.setMaximumSize(QtCore.QSize(887, 628))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/carregamento.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmSaidaVeiculosCarregamento.setWindowIcon(icon)
        frmSaidaVeiculosCarregamento.setSizeGripEnabled(True)
        frmSaidaVeiculosCarregamento.setModal(True)

        frmSaidaVeiculosCarregamento.setFont(font)
        self.grbDadosMotorista = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(6, 211, 871, 107))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))

        self.txtModeloMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModeloMotorista.setGeometry(QtCore.QRect(10, 76, 251, 25))
        self.txtModeloMotorista.setMaxLength(50)
        self.txtModeloMotorista.setObjectName(_fromUtf8("txtModeloMotorista"))

        self.lblMarcaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarcaMotorista.setGeometry(QtCore.QRect(270, 58, 51, 19))
        self.lblMarcaMotorista.setObjectName(_fromUtf8("lblMarcaMotorista"))

        self.txtMarcaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarcaMotorista.setGeometry(QtCore.QRect(270, 78, 311, 25))
        self.txtMarcaMotorista.setMaxLength(50)
        self.txtMarcaMotorista.setObjectName(_fromUtf8("txtMarcaMotorista"))

        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(180, 33, 361, 25))
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))

        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 13, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))

        self.txtPlacaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlacaMotorista.setGeometry(QtCore.QRect(590, 78, 171, 25))
        self.txtPlacaMotorista.setObjectName(_fromUtf8("txtPlacaMotorista"))

        self.lblModeloMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModeloMotorista.setGeometry(QtCore.QRect(10, 57, 51, 19))
        self.lblModeloMotorista.setObjectName(_fromUtf8("lblModeloMotorista"))

        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 33, 161, 25))
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))

        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 13, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))

        self.lblPlacaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlacaMotorista.setGeometry(QtCore.QRect(590, 58, 51, 19))
        self.lblPlacaMotorista.setObjectName(_fromUtf8("lblPlacaMotorista"))

        self.lblHoraSaida = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblHoraSaida.setGeometry(QtCore.QRect(146, 167, 91, 16))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))

        self.txtData = QtGui.QDateEdit(frmSaidaVeiculosCarregamento)
        self.txtData.setDate(QtCore.QDate.currentDate())
        self.txtData.setEnabled(False)
        self.txtData.setGeometry(QtCore.QRect(16, 187, 110, 23))
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))

        self.txtHora = QtGui.QTimeEdit(frmSaidaVeiculosCarregamento)
        self.txtHora.setTime(QtCore.QTime.currentTime())
        self.txtHora.setEnabled(False)
        self.txtHora.setGeometry(QtCore.QRect(146, 187, 118, 24))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))

        self.lblDataSaida = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblDataSaida.setGeometry(QtCore.QRect(16, 167, 101, 16))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))

        self.tabPesquisa = QtGui.QTableWidget(frmSaidaVeiculosCarregamento)
        self.tabPesquisa.setEnabled(False)
        self.tabPesquisa.setGeometry(QtCore.QRect(5, 10, 871, 141))
        self.tabPesquisa.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabPesquisa.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabPesquisa.setObjectName(_fromUtf8("tabPesquisa"))
        self.tabPesquisa.setColumnCount(20)
        self.tabPesquisa.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tabPesquisa.setHorizontalHeaderItem(19, item)
        self.tabPesquisa.horizontalHeader().setStretchLastSection(True)
        self.tabPesquisa.verticalHeader().setVisible(False)

        self.lblProduto = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblProduto.setGeometry(QtCore.QRect(530, 169, 51, 16))
        self.lblProduto.setObjectName(_fromUtf8("lblProduto"))

        self.lblTipoCarga = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblTipoCarga.setGeometry(QtCore.QRect(280, 169, 101, 16))
        self.lblTipoCarga.setObjectName(_fromUtf8("lblTipoCarga"))

        self.grbDadosClienteDestinatario = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbDadosClienteDestinatario.setEnabled(False)
        self.grbDadosClienteDestinatario.setGeometry(QtCore.QRect(6, 317, 871, 251))
        self.grbDadosClienteDestinatario.setObjectName(_fromUtf8("grbDadosClienteDestinatario"))

        self.txtIdClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtIdClienteDestinatario.setGeometry(QtCore.QRect(10, 35, 181, 25))
        self.txtIdClienteDestinatario.setMaxLength(11)
        self.txtIdClienteDestinatario.setObjectName(_fromUtf8("txtIdClienteDestinatario"))

        self.txtNomeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNomeClienteDestinatario.setEnabled(False)
        self.txtNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 35, 601, 25))
        self.txtNomeClienteDestinatario.setMaxLength(70)
        self.txtNomeClienteDestinatario.setObjectName(_fromUtf8("txtNomeClienteDestinatario"))

        self.lblCodigoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCodigoClienteDestinatario.setGeometry(QtCore.QRect(10, 15, 171, 21))
        self.lblCodigoClienteDestinatario.setObjectName(_fromUtf8("lblCodigoClienteDestinatario"))

        self.lblNomeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 15, 231, 16))
        self.lblNomeClienteDestinatario.setObjectName(_fromUtf8("lblNomeClienteDestinatario"))

        self.txtInscricaoEstaduaClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtInscricaoEstaduaClienteDestinatario.setEnabled(False)
        self.txtInscricaoEstaduaClienteDestinatario.setGeometry(QtCore.QRect(688, 80, 173, 25))
        self.txtInscricaoEstaduaClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaClienteDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaClienteDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaClienteDestinatario"))

        self.txtRazaoSocialClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtRazaoSocialClienteDestinatario.setEnabled(False)
        self.txtRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 80, 481, 25))
        self.txtRazaoSocialClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialClienteDestinatario.setMaxLength(70)
        self.txtRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("txtRazaoSocialClienteDestinatario"))

        self.lblRazaoSocialClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("lblRazaoSocialClienteDestinatario"))

        self.lblCnpjClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCnpjClienteDestinatario.setGeometry(QtCore.QRect(500, 60, 41, 19))
        self.lblCnpjClienteDestinatario.setObjectName(_fromUtf8("lblCnpjClienteDestinatario"))

        self.lblInscricaoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setGeometry(QtCore.QRect(688, 60, 121, 19))
        self.lblInscricaoClienteDestinatario.setObjectName(_fromUtf8("lblInscricaoClienteDestinatario"))

        self.txtCnpjClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCnpjClienteDestinatario.setEnabled(False)
        self.txtCnpjClienteDestinatario.setGeometry(QtCore.QRect(500, 80, 182, 25))
        self.txtCnpjClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjClienteDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjClienteDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjClienteDestinatario.setObjectName(_fromUtf8("txtCnpjClienteDestinatario"))

        self.lblCep = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCep.setGeometry(QtCore.QRect(200, 197, 31, 19))
        self.lblCep.setObjectName(_fromUtf8("lblCep"))

        self.lblCidade = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCidade.setGeometry(QtCore.QRect(380, 153, 51, 19))
        self.lblCidade.setObjectName(_fromUtf8("lblCidade"))

        self.txtCidade = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCidade.setEnabled(False)
        self.txtCidade.setGeometry(QtCore.QRect(380, 173, 481, 25))
        self.txtCidade.setMaxLength(75)
        self.txtCidade.setObjectName(_fromUtf8("txtCidade"))

        self.txtEndereco = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEndereco.setEnabled(False)
        self.txtEndereco.setGeometry(QtCore.QRect(10, 126, 441, 25))
        self.txtEndereco.setMaxLength(50)
        self.txtEndereco.setObjectName(_fromUtf8("txtEndereco"))

        self.txtEstado = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEstado.setEnabled(False)
        self.txtEstado.setGeometry(QtCore.QRect(10, 217, 181, 25))
        self.txtEstado.setMaxLength(50)
        self.txtEstado.setObjectName(_fromUtf8("txtEstado"))

        self.txtCep = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCep.setEnabled(False)
        self.txtCep.setGeometry(QtCore.QRect(200, 217, 131, 25))
        self.txtCep.setObjectName(_fromUtf8("txtCep"))

        self.txtBairro = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtBairro.setEnabled(False)
        self.txtBairro.setGeometry(QtCore.QRect(10, 170, 361, 25))
        self.txtBairro.setMaxLength(50)
        self.txtBairro.setObjectName(_fromUtf8("txtBairro"))

        self.lblEndereco = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEndereco.setGeometry(QtCore.QRect(10, 106, 66, 19))
        self.lblEndereco.setObjectName(_fromUtf8("lblEndereco"))

        self.txtComplemento = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtComplemento.setEnabled(False)
        self.txtComplemento.setGeometry(QtCore.QRect(610, 127, 251, 24))
        self.txtComplemento.setMaxLength(50)
        self.txtComplemento.setObjectName(_fromUtf8("txtComplemento"))

        self.lblNumero = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNumero.setGeometry(QtCore.QRect(460, 106, 66, 19))
        self.lblNumero.setObjectName(_fromUtf8("lblNumero"))

        self.txtNumero = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNumero.setEnabled(False)
        self.txtNumero.setGeometry(QtCore.QRect(460, 126, 141, 25))
        self.txtNumero.setMaxLength(11)
        self.txtNumero.setObjectName(_fromUtf8("txtNumero"))

        self.lblBairro = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblBairro.setGeometry(QtCore.QRect(10, 150, 51, 19))
        self.lblBairro.setObjectName(_fromUtf8("lblBairro"))

        self.lblEstado = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEstado.setGeometry(QtCore.QRect(10, 197, 51, 19))
        self.lblEstado.setObjectName(_fromUtf8("lblEstado"))

        self.lblComplemento = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblComplemento.setGeometry(QtCore.QRect(610, 107, 101, 16))
        self.lblComplemento.setObjectName(_fromUtf8("lblComplemento"))

        self.grbBotoes = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbBotoes.setGeometry(QtCore.QRect(6, 570, 871, 51))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(530, 12, 88, 27))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNovo.setIcon(icon)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(630, 12, 88, 27))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon1)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(730, 12, 88, 27))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon2)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.txtTipoCarga = QtGui.QLineEdit(frmSaidaVeiculosCarregamento)
        self.txtTipoCarga.setEnabled(False)
        self.txtTipoCarga.setGeometry(QtCore.QRect(280, 187, 241, 20))
        self.txtTipoCarga.setObjectName(_fromUtf8("txtTipoCarga"))

        self.txtProduto = QtGui.QLineEdit(frmSaidaVeiculosCarregamento)
        self.txtProduto.setEnabled(False)
        self.txtProduto.setGeometry(QtCore.QRect(530, 187, 241, 20))
        self.txtProduto.setObjectName(_fromUtf8("txtProduto"))

        self.lblMarcaMotorista.setBuddy(self.txtMarcaMotorista)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblModeloMotorista.setBuddy(self.txtModeloMotorista)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlacaMotorista.setBuddy(self.txtPlacaMotorista)
        self.lblHoraSaida.setBuddy(self.txtHora)
        self.lblDataSaida.setBuddy(self.txtData)
        self.lblCodigoClienteDestinatario.setBuddy(self.txtIdClienteDestinatario)
        self.lblNomeClienteDestinatario.setBuddy(self.txtNomeClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setBuddy(self.txtRazaoSocialClienteDestinatario)
        self.lblCnpjClienteDestinatario.setBuddy(self.txtCnpjClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setBuddy(self.txtInscricaoEstaduaClienteDestinatario)
        self.lblCep.setBuddy(self.txtCep)
        self.lblCidade.setBuddy(self.txtCidade)
        self.lblEndereco.setBuddy(self.txtEndereco)
        self.lblNumero.setBuddy(self.txtNumero)
        self.lblBairro.setBuddy(self.txtBairro)
        self.lblEstado.setBuddy(self.txtEstado)
        self.lblComplemento.setBuddy(self.txtComplemento)

        self.retranslateUi(frmSaidaVeiculosCarregamento)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaVeiculosCarregamento)
        frmSaidaVeiculosCarregamento.setTabOrder(self.tabPesquisa, self.txtData)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtData, self.txtHora)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtHora, self.txtidFuncionario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtidFuncionario, self.txtNomeMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtNomeMotorista, self.txtModeloMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtModeloMotorista, self.txtMarcaMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtMarcaMotorista, self.txtPlacaMotorista)

    def retranslateUi(self, frmSaidaVeiculosCarregamento):
        frmSaidaVeiculosCarregamento.setWindowTitle(_translate("frmSaidaVeiculosCarregamento", "Saida de Veiculos Carregamento", None))
        self.grbDadosMotorista.setTitle(_translate("frmSaidaVeiculosCarregamento", "Motorista", None))
        self.txtModeloMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtModeloMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome do modelo do veiculo", None))
        self.lblMarcaMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Marca", None))
        self.txtMarcaMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtMarcaMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome da marca do veiculo", None))
        self.txtNomeMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome do motorista", None))
        self.lblNomeMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Nome Motorista", None))
        self.txtPlacaMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Placa do Veiculo", None))
        self.txtPlacaMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de identificação da placa do veiculo", None))
        self.txtPlacaMotorista.setInputMask(_translate("frmSaidaVeiculosCarregamento", "nnn-0000; ", None))
        self.txtPlacaMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "-", None))
        self.lblModeloMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Codigo Motorista", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do Codigo de identificação do motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Codigo Motorista", None))
        self.lblPlacaMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Placa", None))
        self.lblHoraSaida.setText(_translate("frmSaidaVeiculosCarregamento", "Hora Saida", None))
        self.txtData.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Data Saida", None))
        self.txtData.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo da data de saida", None))
        self.txtHora.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Hora Saida", None))
        self.txtHora.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo da hora de saida", None))
        self.lblDataSaida.setText(_translate("frmSaidaVeiculosCarregamento", "Data Saida", None))
        self.tabPesquisa.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Tabela de resultados da pesquisa", None))
        item = self.tabPesquisa.horizontalHeaderItem(0)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "ID", None))
        item = self.tabPesquisa.horizontalHeaderItem(1)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Data", None))
        item = self.tabPesquisa.horizontalHeaderItem(2)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Hora", None))
        item = self.tabPesquisa.horizontalHeaderItem(3)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Carga", None))
        item = self.tabPesquisa.horizontalHeaderItem(4)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Produto", None))
        item = self.tabPesquisa.horizontalHeaderItem(5)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Motorista", None))
        item = self.tabPesquisa.horizontalHeaderItem(6)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Marca", None))
        item = self.tabPesquisa.horizontalHeaderItem(7)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Modelo", None))
        item = self.tabPesquisa.horizontalHeaderItem(8)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Placa", None))
        item = self.tabPesquisa.horizontalHeaderItem(9)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Cliente", None))
        item = self.tabPesquisa.horizontalHeaderItem(10)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Fantasia Cliente", None))
        item = self.tabPesquisa.horizontalHeaderItem(11)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "CNPJ", None))
        item = self.tabPesquisa.horizontalHeaderItem(12)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Inscr. Estadual", None))
        item = self.tabPesquisa.horizontalHeaderItem(13)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Endereço", None))
        item = self.tabPesquisa.horizontalHeaderItem(14)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Numero", None))
        item = self.tabPesquisa.horizontalHeaderItem(15)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Complemento", None))
        item = self.tabPesquisa.horizontalHeaderItem(16)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Bairro", None))
        item = self.tabPesquisa.horizontalHeaderItem(17)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Cidade", None))
        item = self.tabPesquisa.horizontalHeaderItem(18)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "Estado", None))
        item = self.tabPesquisa.horizontalHeaderItem(19)
        item.setText(_translate("frmSaidaVeiculosCarregamento", "CEP", None))
        self.lblProduto.setText(_translate("frmSaidaVeiculosCarregamento", "Produto", None))
        self.lblTipoCarga.setText(_translate("frmSaidaVeiculosCarregamento", "Tipo de Carga", None))
        self.grbDadosClienteDestinatario.setTitle(_translate("frmSaidaVeiculosCarregamento", "Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do codigo de identificação do cliente destinatario", None))
        self.txtNomeClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Nome Cliente Destinatario", None))
        self.txtNomeClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome do cliente destinatario", None))
        self.lblCodigoClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.lblNomeClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Nome Fantasia Cliente Destinatario", None))
        self.txtInscricaoEstaduaClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do numero do inscrição estadual do cliente destinatario", None))
        self.txtRazaoSocialClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Razão Social ", None))
        self.txtRazaoSocialClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome da razão social do cliente destinatario", None))
        self.lblRazaoSocialClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Razão Social", None))
        self.lblCnpjClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "CNPJ", None))
        self.lblInscricaoClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Incrição Estadual", None))
        self.txtCnpjClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "CNPJ ", None))
        self.txtCnpjClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do numero do CNPJ docliente destinatario", None))
        self.txtCnpjClienteDestinatario.setInputMask(_translate("frmSaidaVeiculosCarregamento", "00.000.000/0000-00; ", None))
        self.lblCep.setText(_translate("frmSaidaVeiculosCarregamento", "CEP", None))
        self.lblCidade.setText(_translate("frmSaidaVeiculosCarregamento", "Cidade", None))
        self.txtCidade.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Cidade", None))
        self.txtCidade.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do nome da cidade onde fica localizado o cliente destinatario</p></body></html>", None))
        self.txtEndereco.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Endereço", None))
        self.txtEndereco.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do endereço do cliente destinatario</p></body></html>", None))
        self.txtEstado.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Estado", None))
        self.txtEstado.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do nome do estado onde fica localizado a cidade o cliente destinatario</p></body></html>", None))
        self.txtCep.setToolTip(_translate("frmSaidaVeiculosCarregamento", "CEP", None))
        self.txtCep.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do número do CEP da cidade onde fica localizada o cliente destinatario</p></body></html>", None))
        self.txtCep.setInputMask(_translate("frmSaidaVeiculosCarregamento", "00000-000; ", None))
        self.txtBairro.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Bairro", None))
        self.txtBairro.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do nome do bairro do endereço do cliente destinatario</p></body></html>", None))
        self.lblEndereco.setText(_translate("frmSaidaVeiculosCarregamento", "Endereço", None))
        self.txtComplemento.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Complemento", None))
        self.txtComplemento.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do complemento do endereço do cliente destinatario</p></body></html>", None))
        self.lblNumero.setText(_translate("frmSaidaVeiculosCarregamento", "Numero", None))
        self.txtNumero.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Número", None))
        self.txtNumero.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Campo do número do endereço do cliente destinatario</p></body></html>", None))
        self.lblBairro.setText(_translate("frmSaidaVeiculosCarregamento", "Bairro", None))
        self.lblEstado.setText(_translate("frmSaidaVeiculosCarregamento", "Estado", None))
        self.lblComplemento.setText(_translate("frmSaidaVeiculosCarregamento", "Complemento", None))
        self.btnNovo.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Novo", None))
        self.btnNovo.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Botão para cadastrar uma novo registro da pessoa jurídica</p></body></html>", None))
        self.btnNovo.setText(_translate("frmSaidaVeiculosCarregamento", "Novo", None))
        self.btnSalvar.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Salvar", None))
        self.btnSalvar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "<html><head/><body><p>Botão para salvar um novo registro da pessoa jurídica</p></body></html>", None))
        self.btnSalvar.setText(_translate("frmSaidaVeiculosCarregamento", "Salvar", None))
        self.btnCancelar.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Cancelar", None))
        self.btnCancelar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Botão para cancelar a operação ", None))
        self.btnCancelar.setText(_translate("frmSaidaVeiculosCarregamento", "Cancelar", None))

