# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaFuncionario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaFuncionario(object):
    def setupUi(self, frmSaidaFuncionario):
        frmSaidaFuncionario.setObjectName(_fromUtf8("frmSaidaFuncionario"))
        frmSaidaFuncionario.resize(662, 313)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmSaidaFuncionario.setFont(font)
        self.grbBotoes = QtGui.QGroupBox(frmSaidaFuncionario)
        self.grbBotoes.setGeometry(QtCore.QRect(5, 225, 651, 81))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnCadSetoresSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnCadSetoresSalvar.setGeometry(QtCore.QRect(460, 10, 81, 61))
        self.btnCadSetoresSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresSalvar.setObjectName(_fromUtf8("btnCadSetoresSalvar"))
        self.btnCadSetoresCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCadSetoresCancelar.setGeometry(QtCore.QRect(560, 10, 81, 61))
        self.btnCadSetoresCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresCancelar.setObjectName(_fromUtf8("btnCadSetoresCancelar"))
        self.btnCadSetoresNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnCadSetoresNovo.setGeometry(QtCore.QRect(360, 10, 81, 61))
        self.btnCadSetoresNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresNovo.setObjectName(_fromUtf8("btnCadSetoresNovo"))
        self.grbDadosSaidaFuncionario = QtGui.QGroupBox(frmSaidaFuncionario)
        self.grbDadosSaidaFuncionario.setGeometry(QtCore.QRect(5, 10, 651, 211))
        self.grbDadosSaidaFuncionario.setTitle(_fromUtf8(""))
        self.grbDadosSaidaFuncionario.setObjectName(_fromUtf8("grbDadosSaidaFuncionario"))
        self.lblDataSaida = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblDataSaida.setGeometry(QtCore.QRect(6, 136, 81, 19))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))
        self.lblCargo = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblCargo.setGeometry(QtCore.QRect(226, 66, 66, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))
        self.lblNomeFuncionario = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(178, 10, 151, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))
        self.lblCodigoFuncionario = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(6, 10, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtidFuncionario.setEnabled(True)
        self.txtidFuncionario.setGeometry(QtCore.QRect(6, 30, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(178, 30, 421, 25))
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.lblSetor = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblSetor.setGeometry(QtCore.QRect(6, 66, 66, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        self.txtCargos = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtCargos.setEnabled(False)
        self.txtCargos.setGeometry(QtCore.QRect(226, 86, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCargos.setPalette(palette)
        self.txtCargos.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCargos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCargos.setMaxLength(50)
        self.txtCargos.setObjectName(_fromUtf8("txtCargos"))
        self.btnPesquisar = QtGui.QPushButton(self.grbDadosSaidaFuncionario)
        self.btnPesquisar.setGeometry(QtCore.QRect(616, 28, 31, 28))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))
        self.lblHoraSaida = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblHoraSaida.setGeometry(QtCore.QRect(146, 136, 81, 19))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))
        self.txtHoraSaida = QtGui.QTimeEdit(self.grbDadosSaidaFuncionario)
        self.txtHoraSaida.setGeometry(QtCore.QRect(146, 156, 118, 25))
        self.txtHoraSaida.setObjectName(_fromUtf8("txtHoraSaida"))
        self.txtDataSaida = QtGui.QDateEdit(self.grbDadosSaidaFuncionario)
        self.txtDataSaida.setGeometry(QtCore.QRect(6, 156, 110, 25))
        self.txtDataSaida.setObjectName(_fromUtf8("txtDataSaida"))
        self.txtSetor = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtSetor.setEnabled(False)
        self.txtSetor.setGeometry(QtCore.QRect(6, 86, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetor.setPalette(palette)
        self.txtSetor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtSetor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtSetor.setMaxLength(50)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)

        self.retranslateUi(frmSaidaFuncionario)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaFuncionario)
        frmSaidaFuncionario.setTabOrder(self.txtidFuncionario, self.txtNomeFuncionario)
        frmSaidaFuncionario.setTabOrder(self.txtNomeFuncionario, self.btnPesquisar)
        frmSaidaFuncionario.setTabOrder(self.btnPesquisar, self.txtDataSaida)
        frmSaidaFuncionario.setTabOrder(self.txtDataSaida, self.txtHoraSaida)

    def retranslateUi(self, frmSaidaFuncionario):
        frmSaidaFuncionario.setWindowTitle(_translate("frmSaidaFuncionario", "Saida de Funcionarios em Horario de Serviço", None))
        self.btnCadSetoresSalvar.setWhatsThis(_translate("frmSaidaFuncionario", "Botão para salvar um novo registro", None))
        self.btnCadSetoresSalvar.setText(_translate("frmSaidaFuncionario", "Salvar", None))
        self.btnCadSetoresCancelar.setWhatsThis(_translate("frmSaidaFuncionario", "Botão de cancelar a operação iniciada", None))
        self.btnCadSetoresCancelar.setText(_translate("frmSaidaFuncionario", "Cancelar", None))
        self.btnCadSetoresNovo.setWhatsThis(_translate("frmSaidaFuncionario", "Botão de Criação de um novo registro", None))
        self.btnCadSetoresNovo.setText(_translate("frmSaidaFuncionario", "Novo", None))
        self.lblDataSaida.setText(_translate("frmSaidaFuncionario", "Data Saida", None))
        self.lblCargo.setText(_translate("frmSaidaFuncionario", "Cargo", None))
        self.lblNomeFuncionario.setText(_translate("frmSaidaFuncionario", "Nome Funcionario", None))
        self.lblCodigoFuncionario.setText(_translate("frmSaidaFuncionario", "Codigo Funcionario", None))
        self.txtidFuncionario.setToolTip(_translate("frmSaidaFuncionario", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmSaidaFuncionario", "Campo do Codigo de identificação do Funcionario", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmSaidaFuncionario", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmSaidaFuncionario", "Campo do nome do funcionario", None))
        self.lblSetor.setText(_translate("frmSaidaFuncionario", "Setor", None))
        self.txtCargos.setToolTip(_translate("frmSaidaFuncionario", "Cargo", None))
        self.txtCargos.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de descrição do cargo de trabalho do funcionario", None))
        self.lblHoraSaida.setText(_translate("frmSaidaFuncionario", "Hora Saida", None))
        self.txtHoraSaida.setToolTip(_translate("frmSaidaFuncionario", "Hora Saida", None))
        self.txtHoraSaida.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de hora de saida", None))
        self.txtDataSaida.setToolTip(_translate("frmSaidaFuncionario", "Data Saida", None))
        self.txtDataSaida.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de data da saida", None))
        self.txtSetor.setToolTip(_translate("frmSaidaFuncionario", "Setor", None))
        self.txtSetor.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de descrição do setor de trabalho do funcionario", None))

