# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaVeiculosCarregamentos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaVeiculosCarregamento(object):
    def setupUi(self, frmSaidaVeiculosCarregamento):
        frmSaidaVeiculosCarregamento.setObjectName(_fromUtf8("frmSaidaVeiculosCarregamento"))
        frmSaidaVeiculosCarregamento.resize(1004, 658)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmSaidaVeiculosCarregamento.setFont(font)
        self.grbBotoes = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbBotoes.setGeometry(QtCore.QRect(6, 573, 991, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(500, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(800, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(600, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(700, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(900, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        self.grbDadosMotorista = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(6, 244, 991, 107))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))
        self.txtModeloMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModeloMotorista.setGeometry(QtCore.QRect(10, 76, 251, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModeloMotorista.setPalette(palette)
        self.txtModeloMotorista.setMaxLength(50)
        self.txtModeloMotorista.setObjectName(_fromUtf8("txtModeloMotorista"))
        self.lblMarcaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarcaMotorista.setGeometry(QtCore.QRect(270, 58, 51, 19))
        self.lblMarcaMotorista.setObjectName(_fromUtf8("lblMarcaMotorista"))
        self.txtMarcaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarcaMotorista.setGeometry(QtCore.QRect(270, 78, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarcaMotorista.setPalette(palette)
        self.txtMarcaMotorista.setMaxLength(50)
        self.txtMarcaMotorista.setObjectName(_fromUtf8("txtMarcaMotorista"))
        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(180, 33, 361, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMotorista.setPalette(palette)
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))
        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 13, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtPlacaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlacaMotorista.setGeometry(QtCore.QRect(590, 78, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlacaMotorista.setPalette(palette)
        self.txtPlacaMotorista.setObjectName(_fromUtf8("txtPlacaMotorista"))
        self.lblModeloMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModeloMotorista.setGeometry(QtCore.QRect(10, 57, 51, 19))
        self.lblModeloMotorista.setObjectName(_fromUtf8("lblModeloMotorista"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 33, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 13, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblPlacaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlacaMotorista.setGeometry(QtCore.QRect(590, 58, 51, 19))
        self.lblPlacaMotorista.setObjectName(_fromUtf8("lblPlacaMotorista"))
        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(550, 32, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarMotorista.setFont(font)
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/JEFFERSON/Faculdade/Estagio I/Sistema Contorle Movimentos Portaria/imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarMotorista.setIcon(icon)
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        self.grbDadosClienteDestinatario = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbDadosClienteDestinatario.setEnabled(False)
        self.grbDadosClienteDestinatario.setGeometry(QtCore.QRect(6, 351, 991, 111))
        self.grbDadosClienteDestinatario.setObjectName(_fromUtf8("grbDadosClienteDestinatario"))
        self.txtIdClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtIdClienteDestinatario.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdClienteDestinatario.setPalette(palette)
        self.txtIdClienteDestinatario.setMaxLength(11)
        self.txtIdClienteDestinatario.setObjectName(_fromUtf8("txtIdClienteDestinatario"))
        self.txtNomeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 35, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeClienteDestinatario.setPalette(palette)
        self.txtNomeClienteDestinatario.setMaxLength(70)
        self.txtNomeClienteDestinatario.setObjectName(_fromUtf8("txtNomeClienteDestinatario"))
        self.lblCodigoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCodigoClienteDestinatario.setGeometry(QtCore.QRect(10, 15, 171, 21))
        self.lblCodigoClienteDestinatario.setObjectName(_fromUtf8("lblCodigoClienteDestinatario"))
        self.lblNomeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 15, 231, 16))
        self.lblNomeClienteDestinatario.setObjectName(_fromUtf8("lblNomeClienteDestinatario"))
        self.txtInscricaoEstaduaClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtInscricaoEstaduaClienteDestinatario.setGeometry(QtCore.QRect(810, 79, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaClienteDestinatario.setPalette(palette)
        self.txtInscricaoEstaduaClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaClienteDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaClienteDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaClienteDestinatario"))
        self.txtRazaoSocialClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 79, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialClienteDestinatario.setPalette(palette)
        self.txtRazaoSocialClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialClienteDestinatario.setMaxLength(70)
        self.txtRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("txtRazaoSocialClienteDestinatario"))
        self.lblRazaoSocialClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 59, 81, 19))
        self.lblRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("lblRazaoSocialClienteDestinatario"))
        self.lblCnpjClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCnpjClienteDestinatario.setGeometry(QtCore.QRect(622, 59, 41, 19))
        self.lblCnpjClienteDestinatario.setObjectName(_fromUtf8("lblCnpjClienteDestinatario"))
        self.lblInscricaoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setGeometry(QtCore.QRect(810, 59, 121, 19))
        self.lblInscricaoClienteDestinatario.setObjectName(_fromUtf8("lblInscricaoClienteDestinatario"))
        self.txtCnpjClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCnpjClienteDestinatario.setGeometry(QtCore.QRect(622, 79, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjClienteDestinatario.setPalette(palette)
        self.txtCnpjClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjClienteDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjClienteDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjClienteDestinatario.setObjectName(_fromUtf8("txtCnpjClienteDestinatario"))
        self.btnPesquisarClienteDestinatario = QtGui.QPushButton(self.grbDadosClienteDestinatario)
        self.btnPesquisarClienteDestinatario.setGeometry(QtCore.QRect(820, 34, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarClienteDestinatario.setFont(font)
        self.btnPesquisarClienteDestinatario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarClienteDestinatario.setText(_fromUtf8(""))
        self.btnPesquisarClienteDestinatario.setIcon(icon)
        self.btnPesquisarClienteDestinatario.setObjectName(_fromUtf8("btnPesquisarClienteDestinatario"))
        self.grbTipoOperacao = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbTipoOperacao.setEnabled(False)
        self.grbTipoOperacao.setGeometry(QtCore.QRect(4, 0, 261, 41))
        self.grbTipoOperacao.setObjectName(_fromUtf8("grbTipoOperacao"))
        self.radbtnEntrouVazio = QtGui.QRadioButton(self.grbTipoOperacao)
        self.radbtnEntrouVazio.setGeometry(QtCore.QRect(4, 16, 101, 17))
        self.radbtnEntrouVazio.setObjectName(_fromUtf8("radbtnEntrouVazio"))
        self.radbtnEntrouCarregado = QtGui.QRadioButton(self.grbTipoOperacao)
        self.radbtnEntrouCarregado.setGeometry(QtCore.QRect(114, 16, 141, 17))
        self.radbtnEntrouCarregado.setObjectName(_fromUtf8("radbtnEntrouCarregado"))
        self.lblHoraSaida = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblHoraSaida.setGeometry(QtCore.QRect(146, 204, 91, 16))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))
        self.txtData = QtGui.QDateEdit(frmSaidaVeiculosCarregamento)
        self.txtData.setEnabled(False)
        self.txtData.setGeometry(QtCore.QRect(16, 224, 110, 22))
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.btnPesquisarNotaFiscal = QtGui.QPushButton(frmSaidaVeiculosCarregamento)
        self.btnPesquisarNotaFiscal.setEnabled(False)
        self.btnPesquisarNotaFiscal.setGeometry(QtCore.QRect(964, 18, 31, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarNotaFiscal.setFont(font)
        self.btnPesquisarNotaFiscal.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarNotaFiscal.setText(_fromUtf8(""))
        self.btnPesquisarNotaFiscal.setIcon(icon)
        self.btnPesquisarNotaFiscal.setObjectName(_fromUtf8("btnPesquisarNotaFiscal"))
        self.lblPesquisa = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblPesquisa.setGeometry(QtCore.QRect(706, 0, 61, 16))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))
        self.txtHora = QtGui.QTimeEdit(frmSaidaVeiculosCarregamento)
        self.txtHora.setEnabled(False)
        self.txtHora.setGeometry(QtCore.QRect(146, 224, 118, 22))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.lblDataSaida = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblDataSaida.setGeometry(QtCore.QRect(16, 204, 101, 16))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))
        self.txtPesquisar = QtGui.QLineEdit(frmSaidaVeiculosCarregamento)
        self.txtPesquisar.setEnabled(False)
        self.txtPesquisar.setGeometry(QtCore.QRect(706, 20, 251, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisar.setPalette(palette)
        self.txtPesquisar.setMaxLength(70)
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))
        self.grbTipoPesquisa = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbTipoPesquisa.setEnabled(False)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(270, 0, 431, 41))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))
        self.radbtnModeloVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnModeloVeiculo.setGeometry(QtCore.QRect(90, 16, 121, 17))
        self.radbtnModeloVeiculo.setObjectName(_fromUtf8("radbtnModeloVeiculo"))
        self.radbtnMotorista = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnMotorista.setGeometry(QtCore.QRect(5, 16, 81, 17))
        self.radbtnMotorista.setObjectName(_fromUtf8("radbtnMotorista"))
        self.radbtnMarcaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnMarcaVeiculo.setGeometry(QtCore.QRect(210, 17, 121, 17))
        self.radbtnMarcaVeiculo.setObjectName(_fromUtf8("radbtnMarcaVeiculo"))
        self.radbtnPlacaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnPlacaVeiculo.setGeometry(QtCore.QRect(322, 17, 111, 17))
        self.radbtnPlacaVeiculo.setObjectName(_fromUtf8("radbtnPlacaVeiculo"))
        self.tabPesquisa = QtGui.QTableWidget(frmSaidaVeiculosCarregamento)
        self.tabPesquisa.setGeometry(QtCore.QRect(5, 50, 991, 141))
        self.tabPesquisa.setObjectName(_fromUtf8("tabPesquisa"))
        self.tabPesquisa.setColumnCount(0)
        self.tabPesquisa.setRowCount(0)
        self.grbDadosEmpresaOrigem = QtGui.QGroupBox(frmSaidaVeiculosCarregamento)
        self.grbDadosEmpresaOrigem.setEnabled(False)
        self.grbDadosEmpresaOrigem.setGeometry(QtCore.QRect(6, 458, 991, 111))
        self.grbDadosEmpresaOrigem.setObjectName(_fromUtf8("grbDadosEmpresaOrigem"))
        self.txtIdEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtIdEmpresaOrigem.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresaOrigem.setPalette(palette)
        self.txtIdEmpresaOrigem.setMaxLength(11)
        self.txtIdEmpresaOrigem.setObjectName(_fromUtf8("txtIdEmpresaOrigem"))
        self.txtNomeEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 35, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmpresaOrigem.setPalette(palette)
        self.txtNomeEmpresaOrigem.setMaxLength(70)
        self.txtNomeEmpresaOrigem.setObjectName(_fromUtf8("txtNomeEmpresaOrigem"))
        self.lblCodigoEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblCodigoEmpresaOrigem.setGeometry(QtCore.QRect(10, 15, 161, 21))
        self.lblCodigoEmpresaOrigem.setObjectName(_fromUtf8("lblCodigoEmpresaOrigem"))
        self.lblNomeEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 15, 221, 16))
        self.lblNomeEmpresaOrigem.setObjectName(_fromUtf8("lblNomeEmpresaOrigem"))
        self.txtInscricaoEstaduaEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtInscricaoEstaduaEmpresaOrigem.setGeometry(QtCore.QRect(808, 80, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmpresaOrigem.setPalette(palette)
        self.txtInscricaoEstaduaEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmpresaOrigem.setMaxLength(8)
        self.txtInscricaoEstaduaEmpresaOrigem.setObjectName(_fromUtf8("txtInscricaoEstaduaEmpresaOrigem"))
        self.txtRazaoSocialEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 80, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmpresaOrigem.setPalette(palette)
        self.txtRazaoSocialEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmpresaOrigem.setMaxLength(70)
        self.txtRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("txtRazaoSocialEmpresaOrigem"))
        self.lblRazaoSocialEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("lblRazaoSocialEmpresaOrigem"))
        self.lblCnpjEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblCnpjEmpresaOrigem.setGeometry(QtCore.QRect(620, 60, 41, 19))
        self.lblCnpjEmpresaOrigem.setObjectName(_fromUtf8("lblCnpjEmpresaOrigem"))
        self.lblInscricaoEstadualEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblInscricaoEstadualEmpresaOrigem.setGeometry(QtCore.QRect(808, 60, 121, 19))
        self.lblInscricaoEstadualEmpresaOrigem.setObjectName(_fromUtf8("lblInscricaoEstadualEmpresaOrigem"))
        self.txtCnpjEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtCnpjEmpresaOrigem.setGeometry(QtCore.QRect(620, 80, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmpresaOrigem.setPalette(palette)
        self.txtCnpjEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmpresaOrigem.setText(_fromUtf8("../-"))
        self.txtCnpjEmpresaOrigem.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmpresaOrigem.setObjectName(_fromUtf8("txtCnpjEmpresaOrigem"))
        self.btnPesquisarEmpresaOrigem = QtGui.QPushButton(self.grbDadosEmpresaOrigem)
        self.btnPesquisarEmpresaOrigem.setGeometry(QtCore.QRect(820, 35, 31, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarEmpresaOrigem.setFont(font)
        self.btnPesquisarEmpresaOrigem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarEmpresaOrigem.setText(_fromUtf8(""))
        self.btnPesquisarEmpresaOrigem.setIcon(icon)
        self.btnPesquisarEmpresaOrigem.setObjectName(_fromUtf8("btnPesquisarEmpresaOrigem"))
        self.lblProduto = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblProduto.setGeometry(QtCore.QRect(530, 202, 51, 16))
        self.lblProduto.setObjectName(_fromUtf8("lblProduto"))
        self.txtTipoCarga_2 = QtGui.QComboBox(frmSaidaVeiculosCarregamento)
        self.txtTipoCarga_2.setEnabled(False)
        self.txtTipoCarga_2.setGeometry(QtCore.QRect(280, 220, 241, 25))
        self.txtTipoCarga_2.setObjectName(_fromUtf8("txtTipoCarga_2"))
        self.lblTipoCarga = QtGui.QLabel(frmSaidaVeiculosCarregamento)
        self.lblTipoCarga.setGeometry(QtCore.QRect(280, 202, 101, 16))
        self.lblTipoCarga.setObjectName(_fromUtf8("lblTipoCarga"))
        self.txtProduto = QtGui.QComboBox(frmSaidaVeiculosCarregamento)
        self.txtProduto.setEnabled(False)
        self.txtProduto.setGeometry(QtCore.QRect(530, 220, 241, 25))
        self.txtProduto.setObjectName(_fromUtf8("txtProduto"))
        self.lblMarcaMotorista.setBuddy(self.txtMarcaMotorista)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblModeloMotorista.setBuddy(self.txtModeloMotorista)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlacaMotorista.setBuddy(self.txtPlacaMotorista)
        self.lblCodigoClienteDestinatario.setBuddy(self.txtIdClienteDestinatario)
        self.lblNomeClienteDestinatario.setBuddy(self.txtNomeClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setBuddy(self.txtRazaoSocialClienteDestinatario)
        self.lblCnpjClienteDestinatario.setBuddy(self.txtCnpjClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setBuddy(self.txtInscricaoEstaduaClienteDestinatario)
        self.lblHoraSaida.setBuddy(self.txtHora)
        self.lblPesquisa.setBuddy(self.txtPesquisar)
        self.lblDataSaida.setBuddy(self.txtData)
        self.lblCodigoEmpresaOrigem.setBuddy(self.txtIdEmpresaOrigem)
        self.lblNomeEmpresaOrigem.setBuddy(self.txtNomeEmpresaOrigem)
        self.lblRazaoSocialEmpresaOrigem.setBuddy(self.txtRazaoSocialEmpresaOrigem)
        self.lblCnpjEmpresaOrigem.setBuddy(self.txtCnpjEmpresaOrigem)
        self.lblInscricaoEstadualEmpresaOrigem.setBuddy(self.txtInscricaoEstaduaEmpresaOrigem)

        self.retranslateUi(frmSaidaVeiculosCarregamento)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaVeiculosCarregamento)
        frmSaidaVeiculosCarregamento.setTabOrder(self.radbtnEntrouVazio, self.radbtnEntrouCarregado)
        frmSaidaVeiculosCarregamento.setTabOrder(self.radbtnEntrouCarregado, self.radbtnMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.radbtnMotorista, self.radbtnModeloVeiculo)
        frmSaidaVeiculosCarregamento.setTabOrder(self.radbtnModeloVeiculo, self.radbtnMarcaVeiculo)
        frmSaidaVeiculosCarregamento.setTabOrder(self.radbtnMarcaVeiculo, self.radbtnPlacaVeiculo)
        frmSaidaVeiculosCarregamento.setTabOrder(self.radbtnPlacaVeiculo, self.txtPesquisar)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtPesquisar, self.tabPesquisa)
        frmSaidaVeiculosCarregamento.setTabOrder(self.tabPesquisa, self.txtData)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtData, self.txtHora)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtHora, self.txtTipoCarga_2)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtTipoCarga_2, self.txtProduto)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtProduto, self.txtidFuncionario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtidFuncionario, self.txtNomeMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtNomeMotorista, self.txtModeloMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtModeloMotorista, self.txtMarcaMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtMarcaMotorista, self.txtPlacaMotorista)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtPlacaMotorista, self.txtIdClienteDestinatario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtIdClienteDestinatario, self.txtNomeClienteDestinatario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtNomeClienteDestinatario, self.txtRazaoSocialClienteDestinatario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtRazaoSocialClienteDestinatario, self.txtCnpjClienteDestinatario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtCnpjClienteDestinatario, self.txtInscricaoEstaduaClienteDestinatario)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtInscricaoEstaduaClienteDestinatario, self.txtIdEmpresaOrigem)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtIdEmpresaOrigem, self.txtNomeEmpresaOrigem)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtNomeEmpresaOrigem, self.txtRazaoSocialEmpresaOrigem)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtRazaoSocialEmpresaOrigem, self.txtCnpjEmpresaOrigem)
        frmSaidaVeiculosCarregamento.setTabOrder(self.txtCnpjEmpresaOrigem, self.txtInscricaoEstaduaEmpresaOrigem)

    def retranslateUi(self, frmSaidaVeiculosCarregamento):
        frmSaidaVeiculosCarregamento.setWindowTitle(_translate("frmSaidaVeiculosCarregamento", "Saida de Veiculos Carregamento", None))
        self.grbBotoes.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmSaidaVeiculosCarregamento", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmSaidaVeiculosCarregamento", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmSaidaVeiculosCarregamento", "Salvar", None))
        self.btnEditar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Botão para salvar um novo registro", None))
        self.btnEditar.setText(_translate("frmSaidaVeiculosCarregamento", "Editar", None))
        self.btnDeletar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Botão de cancelar a operação iniciada", None))
        self.btnDeletar.setText(_translate("frmSaidaVeiculosCarregamento", "Deletar", None))
        self.grbDadosMotorista.setTitle(_translate("frmSaidaVeiculosCarregamento", "Motorista", None))
        self.txtModeloMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtModeloMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome do modelo do veiculo", None))
        self.lblMarcaMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Marca", None))
        self.txtMarcaMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtMarcaMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome da marca do veiculo", None))
        self.txtNomeMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome do motorista", None))
        self.lblNomeMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Nome Motorista", None))
        self.txtPlacaMotorista.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Placa do Veiculo", None))
        self.txtPlacaMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de identificação da placa do veiculo", None))
        self.txtPlacaMotorista.setInputMask(_translate("frmSaidaVeiculosCarregamento", "nnn-0000; ", None))
        self.txtPlacaMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "-", None))
        self.lblModeloMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Codigo Motorista", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do Codigo de identificação do motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Codigo Motorista", None))
        self.lblPlacaMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Placa", None))
        self.grbDadosClienteDestinatario.setTitle(_translate("frmSaidaVeiculosCarregamento", "Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Codigo Emitente", None))
        self.txtIdClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do codigo de identificação do cliente destinatario", None))
        self.txtNomeClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Nome Fantasia Cliente Destinatario", None))
        self.txtNomeClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome fantasia do cliente destinatario", None))
        self.lblCodigoClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.lblNomeClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Nome Fantasia Cliente Destinatario", None))
        self.txtInscricaoEstaduaClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do numero do inscrição estadual do cliente destinatario", None))
        self.txtRazaoSocialClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Razão Social ", None))
        self.txtRazaoSocialClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome da razão social do cliente destinatario", None))
        self.lblRazaoSocialClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Razão Social", None))
        self.lblCnpjClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "CNPJ", None))
        self.lblInscricaoClienteDestinatario.setText(_translate("frmSaidaVeiculosCarregamento", "Incrição Estadual", None))
        self.txtCnpjClienteDestinatario.setToolTip(_translate("frmSaidaVeiculosCarregamento", "CNPJ ", None))
        self.txtCnpjClienteDestinatario.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do numero do CNPJ do cliente destinatario", None))
        self.txtCnpjClienteDestinatario.setInputMask(_translate("frmSaidaVeiculosCarregamento", "00.000.000/0000-00; ", None))
        self.grbTipoOperacao.setTitle(_translate("frmSaidaVeiculosCarregamento", "Tipo de Operação", None))
        self.radbtnEntrouVazio.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de escolha do tipo de operação que sera por entrou vazio ", None))
        self.radbtnEntrouVazio.setText(_translate("frmSaidaVeiculosCarregamento", "Entrou Vazio", None))
        self.radbtnEntrouCarregado.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de escolha do tipo de operação que sera por entrou carregado", None))
        self.radbtnEntrouCarregado.setText(_translate("frmSaidaVeiculosCarregamento", "Entrou Carregado", None))
        self.lblHoraSaida.setText(_translate("frmSaidaVeiculosCarregamento", "Hora Saida", None))
        self.txtData.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Data Saida", None))
        self.txtData.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo da data de saida", None))
        self.lblPesquisa.setText(_translate("frmSaidaVeiculosCarregamento", "Pesquisa", None))
        self.txtHora.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Hora Saida", None))
        self.txtHora.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo da hora de saida", None))
        self.lblDataSaida.setText(_translate("frmSaidaVeiculosCarregamento", "Data Saida", None))
        self.txtPesquisar.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Pesquisa", None))
        self.txtPesquisar.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de pesquisa", None))
        self.grbTipoPesquisa.setTitle(_translate("frmSaidaVeiculosCarregamento", "Tipo de pesquisa", None))
        self.radbtnModeloVeiculo.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de escolha do tipo de pesquisa por modelo veiculo", None))
        self.radbtnModeloVeiculo.setText(_translate("frmSaidaVeiculosCarregamento", "Modelo Veiculo", None))
        self.radbtnMotorista.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de escolha do tipo de pesquisa por motorista", None))
        self.radbtnMotorista.setText(_translate("frmSaidaVeiculosCarregamento", "Motorista", None))
        self.radbtnMarcaVeiculo.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de escolha do tipo de pesquisa por marca veiculo", None))
        self.radbtnMarcaVeiculo.setText(_translate("frmSaidaVeiculosCarregamento", "Marca Veiculo", None))
        self.radbtnPlacaVeiculo.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo de escolha do tipo de pesquisa por placa veiculo", None))
        self.radbtnPlacaVeiculo.setText(_translate("frmSaidaVeiculosCarregamento", "Placa Veiculo", None))
        self.tabPesquisa.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Tabela de resultados da pesquisa", None))
        self.grbDadosEmpresaOrigem.setTitle(_translate("frmSaidaVeiculosCarregamento", "Empresa Origem", None))
        self.txtIdEmpresaOrigem.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Codigo Empresa Origem", None))
        self.txtIdEmpresaOrigem.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do codigo de identificação da empresa origem", None))
        self.txtNomeEmpresaOrigem.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Nome Fantasia Empresa Origem", None))
        self.txtNomeEmpresaOrigem.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome fantasia da empresa origem", None))
        self.lblCodigoEmpresaOrigem.setText(_translate("frmSaidaVeiculosCarregamento", "Codigo Empresa Origem", None))
        self.lblNomeEmpresaOrigem.setText(_translate("frmSaidaVeiculosCarregamento", "Nome Fantasia Empresa Origem", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do numero do inscrição estadual do empresa origem", None))
        self.txtRazaoSocialEmpresaOrigem.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Razão Social ", None))
        self.txtRazaoSocialEmpresaOrigem.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do nome da razão social do empresa origem", None))
        self.lblRazaoSocialEmpresaOrigem.setText(_translate("frmSaidaVeiculosCarregamento", "Razão Social", None))
        self.lblCnpjEmpresaOrigem.setText(_translate("frmSaidaVeiculosCarregamento", "CNPJ", None))
        self.lblInscricaoEstadualEmpresaOrigem.setText(_translate("frmSaidaVeiculosCarregamento", "Incrição Estadual", None))
        self.txtCnpjEmpresaOrigem.setToolTip(_translate("frmSaidaVeiculosCarregamento", "CNPJ ", None))
        self.txtCnpjEmpresaOrigem.setWhatsThis(_translate("frmSaidaVeiculosCarregamento", "Campo do numero do CNPJ do empresa origem", None))
        self.txtCnpjEmpresaOrigem.setInputMask(_translate("frmSaidaVeiculosCarregamento", "00.000.000/0000-00; ", None))
        self.lblProduto.setText(_translate("frmSaidaVeiculosCarregamento", "Produto", None))
        self.txtTipoCarga_2.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Tipo de Carga", None))
        self.lblTipoCarga.setText(_translate("frmSaidaVeiculosCarregamento", "Tipo de Carga", None))
        self.txtProduto.setToolTip(_translate("frmSaidaVeiculosCarregamento", "Tipo de Carga", None))

