# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaFuncionario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtCore import *
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaFuncionario(object):
    def setupUi(self, frmSaidaFuncionario):
        frmSaidaFuncionario.setObjectName(_fromUtf8("frmSaidaFuncionario"))
        frmSaidaFuncionario.resize(661, 510)
        frmSaidaFuncionario.setMinimumSize(QtCore.QSize(661, 510))
        frmSaidaFuncionario.setMaximumSize(QtCore.QSize(661, 510))
        frmSaidaFuncionario.setSizeGripEnabled(False)
        frmSaidaFuncionario.setModal(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/funcionario-saida.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmSaidaFuncionario.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmSaidaFuncionario.setFont(font)

        self.grbBotoes = QtGui.QGroupBox(frmSaidaFuncionario)
        self.grbBotoes.setGeometry(QtCore.QRect(5, 420, 651, 81))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(250, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(450, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(150, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(550, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(350, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.grbDadosSaidaFuncionario = QtGui.QGroupBox(frmSaidaFuncionario)
        self.grbDadosSaidaFuncionario.setEnabled(False)
        self.grbDadosSaidaFuncionario.setGeometry(QtCore.QRect(5, 10, 651, 211))
        self.grbDadosSaidaFuncionario.setTitle(_fromUtf8(""))
        self.grbDadosSaidaFuncionario.setObjectName(_fromUtf8("grbDadosSaidaFuncionario"))

        self.lblDataSaida = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblDataSaida.setGeometry(QtCore.QRect(6, 136, 81, 19))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))

        self.lblCargo = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblCargo.setGeometry(QtCore.QRect(226, 66, 66, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))

        self.lblNomeFuncionario = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(178, 10, 151, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))

        self.lblCodigoFuncionario = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(6, 10, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))

        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtidFuncionario.setEnabled(False)
        self.txtidFuncionario.setGeometry(QtCore.QRect(6, 30, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))

        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(178, 30, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeFuncionario.setPalette(palette)
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))

        self.lblSetor = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblSetor.setGeometry(QtCore.QRect(6, 66, 66, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))

        self.txtCargos = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtCargos.setEnabled(False)
        self.txtCargos.setGeometry(QtCore.QRect(226, 86, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCargos.setPalette(palette)
        self.txtCargos.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCargos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCargos.setMaxLength(50)
        self.txtCargos.setObjectName(_fromUtf8("txtCargos"))

        self.btnPesquisar = QtGui.QPushButton(self.grbDadosSaidaFuncionario)
        self.btnPesquisar.setGeometry(QtCore.QRect(612, 28, 31, 28))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisar.setIcon(icon)
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))

        self.lblHoraSaida = QtGui.QLabel(self.grbDadosSaidaFuncionario)
        self.lblHoraSaida.setGeometry(QtCore.QRect(146, 136, 81, 19))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))

        self.txtHoraSaida = QtGui.QTimeEdit(self.grbDadosSaidaFuncionario)
        self.txtHoraSaida.setTime(QTime.currentTime())
        self.txtHoraSaida.setGeometry(QtCore.QRect(146, 156, 118, 25))
        self.txtHoraSaida.setObjectName(_fromUtf8("txtHoraSaida"))

        self.txtDataSaida = QtGui.QDateEdit(self.grbDadosSaidaFuncionario)
        self.txtDataSaida.setDate(QDate.currentDate())
        self.txtDataSaida.setGeometry(QtCore.QRect(6, 156, 110, 25))
        self.txtDataSaida.setCalendarPopup(True)
        self.txtDataSaida.setObjectName(_fromUtf8("txtDataSaida"))

        self.txtSetor = QtGui.QLineEdit(self.grbDadosSaidaFuncionario)
        self.txtSetor.setEnabled(False)
        self.txtSetor.setGeometry(QtCore.QRect(6, 86, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetor.setPalette(palette)
        self.txtSetor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtSetor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtSetor.setMaxLength(50)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))

        self.grbPesquisa = QtGui.QGroupBox(frmSaidaFuncionario)
        self.grbPesquisa.setGeometry(QtCore.QRect(5, 223, 651, 191))
        self.grbPesquisa.setTitle(_fromUtf8(""))
        self.grbPesquisa.setObjectName(_fromUtf8("grbPesquisa"))

        self.tbPesquisaFuncionario = QtGui.QTableWidget(self.grbPesquisa)
        self.tbPesquisaFuncionario.setGeometry(QtCore.QRect(5, 80, 641, 111))
        self.tbPesquisaFuncionario.setEditTriggers(self.tbPesquisaFuncionario.NoEditTriggers)
        self.tbPesquisaFuncionario.setSelectionBehavior(self.tbPesquisaFuncionario.SelectRows)
        self.tbPesquisaFuncionario.setSelectionMode(self.tbPesquisaFuncionario.SingleSelection)
        self.tbPesquisaFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbPesquisaFuncionario.setObjectName(_fromUtf8("tbPesquisaFuncionario"))
        self.tbPesquisaFuncionario.setColumnCount(6)
        self.tbPesquisaFuncionario.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tbPesquisaFuncionario.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbPesquisaFuncionario.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbPesquisaFuncionario.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbPesquisaFuncionario.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbPesquisaFuncionario.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbPesquisaFuncionario.setHorizontalHeaderItem(5, item)

        self.txtPesquisaFuncionario = QtGui.QLineEdit(self.grbPesquisa)
        self.txtPesquisaFuncionario.setGeometry(QtCore.QRect(10, 50, 451, 25))
        self.txtPesquisaFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPesquisaFuncionario.setObjectName(_fromUtf8("txtPesquisaFuncionario"))

        self.btnPesquisarFuncionario = QtGui.QPushButton(self.grbPesquisa)
        self.btnPesquisarFuncionario.setGeometry(QtCore.QRect(470, 50, 31, 27))
        self.btnPesquisarFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarFuncionario.setText(_fromUtf8(""))
        self.btnPesquisarFuncionario.setIcon(icon)
        self.btnPesquisarFuncionario.setObjectName(_fromUtf8("btnPesquisarFuncionario"))

        self.grbDadosPesquisa = QtGui.QGroupBox(self.grbPesquisa)
        self.grbDadosPesquisa.setGeometry(QtCore.QRect(10, 10, 291, 36))
        self.grbDadosPesquisa.setObjectName(_fromUtf8("grbDadosPesquisa"))

        self.radBtnNomeFuncionario = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnNomeFuncionario.setGeometry(QtCore.QRect(97, 17, 91, 17))
        self.radBtnNomeFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnNomeFuncionario.setObjectName(_fromUtf8("radBtnNomeFuncionario"))

        self.radBtnRg = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnRg.setGeometry(QtCore.QRect(194, 17, 41, 17))
        self.radBtnRg.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnRg.setObjectName(_fromUtf8("radBtnRg"))

        self.radBtnCpf = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCpf.setGeometry(QtCore.QRect(238, 17, 51, 17))
        self.radBtnCpf.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCpf.setObjectName(_fromUtf8("radBtnCpf"))

        self.radBtnCodigoFuncionario = QtGui.QRadioButton(self.grbDadosPesquisa)
        self.radBtnCodigoFuncionario.setGeometry(QtCore.QRect(8, 17, 82, 17))
        self.radBtnCodigoFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radBtnCodigoFuncionario.setObjectName(_fromUtf8("radBtnCodigoFuncionario"))

        self.lblDataSaida.setBuddy(self.txtDataSaida)
        self.lblCargo.setBuddy(self.txtCargos)
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)
        self.lblSetor.setBuddy(self.txtSetor)
        self.lblHoraSaida.setBuddy(self.txtHoraSaida)

        self.retranslateUi(frmSaidaFuncionario)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaFuncionario)
        frmSaidaFuncionario.setTabOrder(self.txtidFuncionario, self.txtNomeFuncionario)
        frmSaidaFuncionario.setTabOrder(self.txtNomeFuncionario, self.btnPesquisar)
        frmSaidaFuncionario.setTabOrder(self.btnPesquisar, self.txtDataSaida)
        frmSaidaFuncionario.setTabOrder(self.txtDataSaida, self.txtHoraSaida)

    def retranslateUi(self, frmSaidaFuncionario):
        frmSaidaFuncionario.setWindowTitle(_translate("frmSaidaFuncionario", "Saida de Funcionarios em Horario de Serviço", None))
        self.btnSalvar.setWhatsThis(_translate("frmSaidaFuncionario", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmSaidaFuncionario", "Salvar", None))
        self.btnCancelar.setWhatsThis(_translate("frmSaidaFuncionario", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmSaidaFuncionario", "Cancelar", None))
        self.btnNovo.setWhatsThis(_translate("frmSaidaFuncionario", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmSaidaFuncionario", "Novo", None))
        self.btnDeletar.setWhatsThis(_translate("frmSaidaFuncionario", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmSaidaFuncionario", "Deletar", None))
        self.btnEditar.setWhatsThis(_translate("frmSaidaFuncionario", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmSaidaFuncionario", "Editar", None))
        self.lblDataSaida.setText(_translate("frmSaidaFuncionario", "Data Saida", None))
        self.lblCargo.setText(_translate("frmSaidaFuncionario", "Cargo", None))
        self.lblNomeFuncionario.setText(_translate("frmSaidaFuncionario", "Nome Funcionario", None))
        self.lblCodigoFuncionario.setText(_translate("frmSaidaFuncionario", "Codigo Funcionario", None))
        self.txtidFuncionario.setToolTip(_translate("frmSaidaFuncionario", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmSaidaFuncionario", "Campo do Codigo de identificação do Funcionario", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmSaidaFuncionario", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmSaidaFuncionario", "Campo do nome do funcionario", None))
        self.lblSetor.setText(_translate("frmSaidaFuncionario", "Setor", None))
        self.txtCargos.setToolTip(_translate("frmSaidaFuncionario", "Cargo", None))
        self.txtCargos.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de descrição do cargo de trabalho do funcionario", None))
        self.lblHoraSaida.setText(_translate("frmSaidaFuncionario", "Hora Saida", None))
        self.txtHoraSaida.setToolTip(_translate("frmSaidaFuncionario", "Hora Saida", None))
        self.txtHoraSaida.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de hora de saida", None))
        self.txtDataSaida.setToolTip(_translate("frmSaidaFuncionario", "Data Saida", None))
        self.txtDataSaida.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de data da saida", None))
        self.txtSetor.setToolTip(_translate("frmSaidaFuncionario", "Setor", None))
        self.txtSetor.setWhatsThis(_translate("frmSaidaFuncionario", "Campo de descrição do setor de trabalho do funcionario", None))
        item = self.tbPesquisaFuncionario.horizontalHeaderItem(0)
        item.setText(_translate("frmSaidaFuncionario", "COD", None))
        item = self.tbPesquisaFuncionario.horizontalHeaderItem(1)
        item.setText(_translate("frmSaidaFuncionario", "NOME", None))
        item = self.tbPesquisaFuncionario.horizontalHeaderItem(2)
        item.setText(_translate("frmSaidaFuncionario", "DATA SAÍ.", None))
        item = self.tbPesquisaFuncionario.horizontalHeaderItem(3)
        item.setText(_translate("frmSaidaFuncionario", "HORA SAÍ.", None))
        item = self.tbPesquisaFuncionario.horizontalHeaderItem(4)
        item.setText(_translate("frmSaidaFuncionario", "SETOR", None))
        item = self.tbPesquisaFuncionario.horizontalHeaderItem(5)
        item.setText(_translate("frmSaidaFuncionario", "CARGO", None))
        self.grbDadosPesquisa.setTitle(_translate("frmSaidaFuncionario", "Dados Pesquisa", None))
        self.radBtnNomeFuncionario.setText(_translate("frmSaidaFuncionario", "Nome Fun.", None))
        self.radBtnRg.setText(_translate("frmSaidaFuncionario", "RG", None))
        self.radBtnCpf.setText(_translate("frmSaidaFuncionario", "CPF", None))
        self.radBtnCodigoFuncionario.setText(_translate("frmSaidaFuncionario", "Cod. Fun.", None))

