# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaVeiculoDescarregamento.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaVeiculoDescarregamento(object):
    def setupUi(self, frmSaidaVeiculoDescarregamento):
        frmSaidaVeiculoDescarregamento.setObjectName(_fromUtf8("frmSaidaVeiculoDescarregamento"))
        frmSaidaVeiculoDescarregamento.resize(917, 525)
        frmSaidaVeiculoDescarregamento.setMinimumSize(QtCore.QSize(917, 525))
        frmSaidaVeiculoDescarregamento.setMaximumSize(QtCore.QSize(917, 525))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/descarregamento.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmSaidaVeiculoDescarregamento.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmSaidaVeiculoDescarregamento.setFont(font)

        self.grbTipoPesquisa = QtGui.QGroupBox(frmSaidaVeiculoDescarregamento)
        self.grbTipoPesquisa.setEnabled(False)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(10, 10, 351, 81))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))
        self.radbtnNumeroNota = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnNumeroNota.setGeometry(QtCore.QRect(10, 22, 151, 17))
        self.radbtnNumeroNota.setObjectName(_fromUtf8("radbtnNumeroNota"))
        self.radbtnNumeroRomaneio = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnNumeroRomaneio.setGeometry(QtCore.QRect(190, 22, 141, 17))
        self.radbtnNumeroRomaneio.setObjectName(_fromUtf8("radbtnNumeroRomaneio"))
        self.radbtnEmitente = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnEmitente.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.radbtnEmitente.setObjectName(_fromUtf8("radbtnEmitente"))
        self.radbtnDestinatario = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnDestinatario.setGeometry(QtCore.QRect(190, 40, 101, 17))
        self.radbtnDestinatario.setObjectName(_fromUtf8("radbtnDestinatario"))
        self.radbtnMotorista = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnMotorista.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.radbtnMotorista.setObjectName(_fromUtf8("radbtnMotorista"))
        self.radbtnPlacaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnPlacaVeiculo.setGeometry(QtCore.QRect(190, 60, 101, 17))
        self.radbtnPlacaVeiculo.setObjectName(_fromUtf8("radbtnPlacaVeiculo"))
        self.lblPesquisa = QtGui.QLabel(frmSaidaVeiculoDescarregamento)
        self.lblPesquisa.setGeometry(QtCore.QRect(370, 32, 61, 16))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))
        self.btnPesquisarNotaFiscal = QtGui.QPushButton(frmSaidaVeiculoDescarregamento)
        self.btnPesquisarNotaFiscal.setGeometry(QtCore.QRect(720, 48, 31, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarNotaFiscal.setFont(font)
        self.btnPesquisarNotaFiscal.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarNotaFiscal.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/JEFFERSON/Faculdade/Estagio I/Sistema Contorle Movimentos Portaria/imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarNotaFiscal.setIcon(icon)
        self.btnPesquisarNotaFiscal.setObjectName(_fromUtf8("btnPesquisarNotaFiscal"))
        self.tabPesquisa = QtGui.QTableWidget(frmSaidaVeiculoDescarregamento)
        self.tabPesquisa.setEnabled(False)
        self.tabPesquisa.setGeometry(QtCore.QRect(7, 100, 901, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tabPesquisa.setPalette(palette)
        self.tabPesquisa.setObjectName(_fromUtf8("tabPesquisa"))
        self.tabPesquisa.setColumnCount(0)
        self.tabPesquisa.setRowCount(0)
        self.grbBotoes = QtGui.QGroupBox(frmSaidaVeiculoDescarregamento)
        self.grbBotoes.setGeometry(QtCore.QRect(7, 440, 901, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(500, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(400, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(600, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(700, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(800, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        self.grbDadosMotorista = QtGui.QGroupBox(frmSaidaVeiculoDescarregamento)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(7, 320, 901, 114))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))
        self.txtModelo = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModelo.setEnabled(False)
        self.txtModelo.setGeometry(QtCore.QRect(610, 36, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModelo.setPalette(palette)
        self.txtModelo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))
        self.lblMarca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarca.setGeometry(QtCore.QRect(10, 62, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))
        self.txtMarca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarca.setEnabled(False)
        self.txtMarca.setGeometry(QtCore.QRect(10, 82, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarca.setPalette(palette)
        self.txtMarca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeFuncionario.setEnabled(False)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(180, 36, 421, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeFuncionario.setPalette(palette)
        self.txtNomeFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 16, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtPlaca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlaca.setEnabled(False)
        self.txtPlaca.setGeometry(QtCore.QRect(350, 82, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlaca.setPalette(palette)
        self.txtPlaca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))
        self.lblModelo = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModelo.setGeometry(QtCore.QRect(610, 16, 51, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setEnabled(False)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 36, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 16, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblPlaca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlaca.setGeometry(QtCore.QRect(350, 62, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))
        self.lblHoraSaida = QtGui.QLabel(frmSaidaVeiculoDescarregamento)
        self.lblHoraSaida.setGeometry(QtCore.QRect(147, 280, 91, 16))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))
        self.txtData = QtGui.QDateEdit(frmSaidaVeiculoDescarregamento)
        self.txtData.setEnabled(False)
        self.txtData.setGeometry(QtCore.QRect(17, 300, 110, 22))
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.lblDataSaida = QtGui.QLabel(frmSaidaVeiculoDescarregamento)
        self.lblDataSaida.setGeometry(QtCore.QRect(17, 280, 101, 16))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))
        self.txtHora = QtGui.QTimeEdit(frmSaidaVeiculoDescarregamento)
        self.txtHora.setEnabled(False)
        self.txtHora.setGeometry(QtCore.QRect(147, 300, 118, 22))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.txtPesquisar = QtGui.QLineEdit(frmSaidaVeiculoDescarregamento)
        self.txtPesquisar.setEnabled(False)
        self.txtPesquisar.setGeometry(QtCore.QRect(370, 50, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisar.setPalette(palette)
        self.txtPesquisar.setMaxLength(70)
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))
        self.lblPesquisa.setBuddy(self.txtPesquisar)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblNomeMotorista.setBuddy(self.txtNomeFuncionario)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlaca.setBuddy(self.txtPlaca)
        self.lblHoraSaida.setBuddy(self.txtHora)
        self.lblDataSaida.setBuddy(self.txtData)

        self.retranslateUi(frmSaidaVeiculoDescarregamento)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaVeiculoDescarregamento)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.radbtnNumeroNota, self.radbtnNumeroRomaneio)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.radbtnNumeroRomaneio, self.radbtnEmitente)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.radbtnEmitente, self.radbtnDestinatario)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.radbtnDestinatario, self.radbtnMotorista)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.radbtnMotorista, self.txtPesquisar)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtPesquisar, self.tabPesquisa)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.tabPesquisa, self.txtData)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtData, self.txtHora)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtHora, self.txtidFuncionario)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtidFuncionario, self.txtNomeFuncionario)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtNomeFuncionario, self.txtModelo)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtModelo, self.txtMarca)
        frmSaidaVeiculoDescarregamento.setTabOrder(self.txtMarca, self.txtPlaca)

    def retranslateUi(self, frmSaidaVeiculoDescarregamento):
        frmSaidaVeiculoDescarregamento.setWindowTitle(_translate("frmSaidaVeiculoDescarregamento", "Saida de Veiculo Descarregamento", None))
        self.grbTipoPesquisa.setTitle(_translate("frmSaidaVeiculoDescarregamento", "Tipo de pesquisa", None))
        self.radbtnNumeroNota.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de escolha do tipo de pesquisa por numero da nota fiscal", None))
        self.radbtnNumeroNota.setText(_translate("frmSaidaVeiculoDescarregamento", "Numero Nota Fiscal", None))
        self.radbtnNumeroRomaneio.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de escolha do tipo de pesquisa por numero romaneio", None))
        self.radbtnNumeroRomaneio.setText(_translate("frmSaidaVeiculoDescarregamento", "Numero Romaneio", None))
        self.radbtnEmitente.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de escolha do tipo de pesquisa por emitente", None))
        self.radbtnEmitente.setText(_translate("frmSaidaVeiculoDescarregamento", "Emitente", None))
        self.radbtnDestinatario.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de escolha do tipo de pesquisa por destinatario", None))
        self.radbtnDestinatario.setText(_translate("frmSaidaVeiculoDescarregamento", "Destinatario", None))
        self.radbtnMotorista.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de escolha do tipo de pesquisa por motorista", None))
        self.radbtnMotorista.setText(_translate("frmSaidaVeiculoDescarregamento", "Motorista", None))
        self.radbtnPlacaVeiculo.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de escolha do tipo de pesquisa por destinatario", None))
        self.radbtnPlacaVeiculo.setText(_translate("frmSaidaVeiculoDescarregamento", "PlacaVeiculo", None))
        self.lblPesquisa.setText(_translate("frmSaidaVeiculoDescarregamento", "Pesquisa", None))
        self.tabPesquisa.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Tabela de Resultados da pesquisa", None))
        self.grbBotoes.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Grupo de botões referente as suas funções", None))
        self.btnSalvar.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmSaidaVeiculoDescarregamento", "Salvar", None))
        self.btnNovo.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmSaidaVeiculoDescarregamento", "Novo", None))
        self.btnEditar.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmSaidaVeiculoDescarregamento", "Editar", None))
        self.btnCancelar.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmSaidaVeiculoDescarregamento", "Cancelar", None))
        self.btnDeletar.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmSaidaVeiculoDescarregamento", "Deletar", None))
        self.grbDadosMotorista.setTitle(_translate("frmSaidaVeiculoDescarregamento", "Motorista", None))
        self.txtModelo.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Marca do Veiculo", None))
        self.txtModelo.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo do nome do modelo do veiculo", None))
        self.lblMarca.setText(_translate("frmSaidaVeiculoDescarregamento", "Marca", None))
        self.txtMarca.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Marca do Veiculo", None))
        self.txtMarca.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo do nome da marca do veiculo", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo do nome do funcionario", None))
        self.lblNomeMotorista.setText(_translate("frmSaidaVeiculoDescarregamento", "Nome Motorista", None))
        self.txtPlaca.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Placa do Veiculo", None))
        self.txtPlaca.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmSaidaVeiculoDescarregamento", "nnn-0000; ", None))
        self.txtPlaca.setText(_translate("frmSaidaVeiculoDescarregamento", "-", None))
        self.lblModelo.setText(_translate("frmSaidaVeiculoDescarregamento", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo do Codigo de identificação do Funcionario", None))
        self.lblCodigoMotorista.setText(_translate("frmSaidaVeiculoDescarregamento", "Codigo Motorista", None))
        self.lblPlaca.setText(_translate("frmSaidaVeiculoDescarregamento", "Placa", None))
        self.lblHoraSaida.setText(_translate("frmSaidaVeiculoDescarregamento", "Hora Saida", None))
        self.txtData.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Data Saida", None))
        self.txtData.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo da data de saida", None))
        self.lblDataSaida.setText(_translate("frmSaidaVeiculoDescarregamento", "Data Saida", None))
        self.txtHora.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Hora Saida", None))
        self.txtHora.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo da hora de saida", None))
        self.txtPesquisar.setToolTip(_translate("frmSaidaVeiculoDescarregamento", "Pesquisa", None))
        self.txtPesquisar.setWhatsThis(_translate("frmSaidaVeiculoDescarregamento", "Campo de pesquisa", None))

