# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaVeiculosCarregamentos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1004, 697)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        Dialog.setFont(font)
        self.grbBotoes = QtGui.QGroupBox(Dialog)
        self.grbBotoes.setGeometry(QtCore.QRect(6, 610, 991, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(690, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setGeometry(QtCore.QRect(890, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setGeometry(QtCore.QRect(790, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.grbDadosMotorista = QtGui.QGroupBox(Dialog)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(6, 186, 991, 107))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))
        self.txtModeloMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModeloMotorista.setGeometry(QtCore.QRect(10, 76, 251, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModeloMotorista.setPalette(palette)
        self.txtModeloMotorista.setMaxLength(50)
        self.txtModeloMotorista.setObjectName(_fromUtf8("txtModeloMotorista"))
        self.lblMarcaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarcaMotorista.setGeometry(QtCore.QRect(270, 58, 51, 19))
        self.lblMarcaMotorista.setObjectName(_fromUtf8("lblMarcaMotorista"))
        self.txtMarcaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarcaMotorista.setGeometry(QtCore.QRect(270, 78, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarcaMotorista.setPalette(palette)
        self.txtMarcaMotorista.setMaxLength(50)
        self.txtMarcaMotorista.setObjectName(_fromUtf8("txtMarcaMotorista"))
        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(180, 33, 361, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMotorista.setPalette(palette)
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))
        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 13, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtPlacaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlacaMotorista.setGeometry(QtCore.QRect(590, 78, 171, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlacaMotorista.setPalette(palette)
        self.txtPlacaMotorista.setObjectName(_fromUtf8("txtPlacaMotorista"))
        self.lblModeloMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModeloMotorista.setGeometry(QtCore.QRect(10, 57, 51, 19))
        self.lblModeloMotorista.setObjectName(_fromUtf8("lblModeloMotorista"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 33, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 13, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblPlacaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlacaMotorista.setGeometry(QtCore.QRect(590, 58, 51, 19))
        self.lblPlacaMotorista.setObjectName(_fromUtf8("lblPlacaMotorista"))
        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(550, 37, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarMotorista.setFont(font)
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        self.txtTipoCarga = QtGui.QComboBox(self.grbDadosMotorista)
        self.txtTipoCarga.setGeometry(QtCore.QRect(770, 78, 211, 25))
        self.txtTipoCarga.setObjectName(_fromUtf8("txtTipoCarga"))
        self.label = QtGui.QLabel(self.grbDadosMotorista)
        self.label.setGeometry(QtCore.QRect(770, 56, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.grbDadosClienteDestinatario = QtGui.QGroupBox(Dialog)
        self.grbDadosClienteDestinatario.setGeometry(QtCore.QRect(6, 293, 991, 201))
        self.grbDadosClienteDestinatario.setObjectName(_fromUtf8("grbDadosClienteDestinatario"))
        self.txtIdClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtIdClienteDestinatario.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdClienteDestinatario.setPalette(palette)
        self.txtIdClienteDestinatario.setMaxLength(11)
        self.txtIdClienteDestinatario.setObjectName(_fromUtf8("txtIdClienteDestinatario"))
        self.txtNomeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 35, 371, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeClienteDestinatario.setPalette(palette)
        self.txtNomeClienteDestinatario.setMaxLength(70)
        self.txtNomeClienteDestinatario.setObjectName(_fromUtf8("txtNomeClienteDestinatario"))
        self.lblCodigoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCodigoClienteDestinatario.setGeometry(QtCore.QRect(10, 15, 171, 21))
        self.lblCodigoClienteDestinatario.setObjectName(_fromUtf8("lblCodigoClienteDestinatario"))
        self.lblNomeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 15, 231, 16))
        self.lblNomeClienteDestinatario.setObjectName(_fromUtf8("lblNomeClienteDestinatario"))
        self.txtEnderecoClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEnderecoClienteDestinatario.setGeometry(QtCore.QRect(756, 79, 225, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoClienteDestinatario.setPalette(palette)
        self.txtEnderecoClienteDestinatario.setMaxLength(50)
        self.txtEnderecoClienteDestinatario.setObjectName(_fromUtf8("txtEnderecoClienteDestinatario"))
        self.txtNumeroClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNumeroClienteDestinatario.setGeometry(QtCore.QRect(10, 124, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroClienteDestinatario.setPalette(palette)
        self.txtNumeroClienteDestinatario.setMaxLength(11)
        self.txtNumeroClienteDestinatario.setObjectName(_fromUtf8("txtNumeroClienteDestinatario"))
        self.txtComplementoClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtComplementoClienteDestinatario.setGeometry(QtCore.QRect(160, 124, 261, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoClienteDestinatario.setPalette(palette)
        self.txtComplementoClienteDestinatario.setMaxLength(50)
        self.txtComplementoClienteDestinatario.setObjectName(_fromUtf8("txtComplementoClienteDestinatario"))
        self.txtCidadeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCidadeClienteDestinatario.setGeometry(QtCore.QRect(666, 123, 314, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadeClienteDestinatario.setPalette(palette)
        self.txtCidadeClienteDestinatario.setMaxLength(70)
        self.txtCidadeClienteDestinatario.setObjectName(_fromUtf8("txtCidadeClienteDestinatario"))
        self.txtEstadoClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEstadoClienteDestinatario.setGeometry(QtCore.QRect(10, 170, 214, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadoClienteDestinatario.setPalette(palette)
        self.txtEstadoClienteDestinatario.setMaxLength(50)
        self.txtEstadoClienteDestinatario.setObjectName(_fromUtf8("txtEstadoClienteDestinatario"))
        self.txtCepClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCepClienteDestinatario.setGeometry(QtCore.QRect(230, 169, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepClienteDestinatario.setPalette(palette)
        self.txtCepClienteDestinatario.setObjectName(_fromUtf8("txtCepClienteDestinatario"))
        self.txtBairroClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtBairroClienteDestinatario.setGeometry(QtCore.QRect(430, 123, 231, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroClienteDestinatario.setPalette(palette)
        self.txtBairroClienteDestinatario.setMaxLength(50)
        self.txtBairroClienteDestinatario.setObjectName(_fromUtf8("txtBairroClienteDestinatario"))
        self.lblEnderecoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEnderecoClienteDestinatario.setGeometry(QtCore.QRect(756, 59, 61, 16))
        self.lblEnderecoClienteDestinatario.setObjectName(_fromUtf8("lblEnderecoClienteDestinatario"))
        self.lblNumeroClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNumeroClienteDestinatario.setGeometry(QtCore.QRect(10, 104, 61, 16))
        self.lblNumeroClienteDestinatario.setObjectName(_fromUtf8("lblNumeroClienteDestinatario"))
        self.lblComplementoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblComplementoClienteDestinatario.setGeometry(QtCore.QRect(160, 104, 91, 16))
        self.lblComplementoClienteDestinatario.setObjectName(_fromUtf8("lblComplementoClienteDestinatario"))
        self.lblBairroClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblBairroClienteDestinatario.setGeometry(QtCore.QRect(430, 103, 61, 16))
        self.lblBairroClienteDestinatario.setObjectName(_fromUtf8("lblBairroClienteDestinatario"))
        self.lblCidadeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCidadeClienteDestinatario.setGeometry(QtCore.QRect(664, 103, 61, 16))
        self.lblCidadeClienteDestinatario.setObjectName(_fromUtf8("lblCidadeClienteDestinatario"))
        self.lblEstadoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEstadoClienteDestinatario.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.lblEstadoClienteDestinatario.setObjectName(_fromUtf8("lblEstadoClienteDestinatario"))
        self.lblCepClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCepClienteDestinatario.setGeometry(QtCore.QRect(230, 149, 61, 16))
        self.lblCepClienteDestinatario.setObjectName(_fromUtf8("lblCepClienteDestinatario"))
        self.txtInscricaoEstaduaClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtInscricaoEstaduaClienteDestinatario.setGeometry(QtCore.QRect(574, 79, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaClienteDestinatario.setPalette(palette)
        self.txtInscricaoEstaduaClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaClienteDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaClienteDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaClienteDestinatario"))
        self.txtRazaoSocialClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 79, 371, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialClienteDestinatario.setPalette(palette)
        self.txtRazaoSocialClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialClienteDestinatario.setMaxLength(70)
        self.txtRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("txtRazaoSocialClienteDestinatario"))
        self.lblRazaoSocialClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 59, 81, 19))
        self.lblRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("lblRazaoSocialClienteDestinatario"))
        self.lblCnpjClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCnpjClienteDestinatario.setGeometry(QtCore.QRect(386, 59, 41, 19))
        self.lblCnpjClienteDestinatario.setObjectName(_fromUtf8("lblCnpjClienteDestinatario"))
        self.lblInscricaoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setGeometry(QtCore.QRect(574, 59, 121, 19))
        self.lblInscricaoClienteDestinatario.setObjectName(_fromUtf8("lblInscricaoClienteDestinatario"))
        self.txtCnpjClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCnpjClienteDestinatario.setGeometry(QtCore.QRect(386, 79, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjClienteDestinatario.setPalette(palette)
        self.txtCnpjClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjClienteDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjClienteDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjClienteDestinatario.setObjectName(_fromUtf8("txtCnpjClienteDestinatario"))
        self.btnPesquisarClienteDestinatario = QtGui.QPushButton(self.grbDadosClienteDestinatario)
        self.btnPesquisarClienteDestinatario.setGeometry(QtCore.QRect(580, 37, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarClienteDestinatario.setFont(font)
        self.btnPesquisarClienteDestinatario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarClienteDestinatario.setText(_fromUtf8(""))
        self.btnPesquisarClienteDestinatario.setObjectName(_fromUtf8("btnPesquisarClienteDestinatario"))
        self.grbTipoOperacao = QtGui.QGroupBox(Dialog)
        self.grbTipoOperacao.setGeometry(QtCore.QRect(4, 0, 261, 41))
        self.grbTipoOperacao.setObjectName(_fromUtf8("grbTipoOperacao"))
        self.radbtnEntrouVazio = QtGui.QRadioButton(self.grbTipoOperacao)
        self.radbtnEntrouVazio.setGeometry(QtCore.QRect(4, 16, 101, 17))
        self.radbtnEntrouVazio.setObjectName(_fromUtf8("radbtnEntrouVazio"))
        self.radbtnEntrouCarregado = QtGui.QRadioButton(self.grbTipoOperacao)
        self.radbtnEntrouCarregado.setGeometry(QtCore.QRect(114, 16, 141, 17))
        self.radbtnEntrouCarregado.setObjectName(_fromUtf8("radbtnEntrouCarregado"))
        self.lblHoraSaida = QtGui.QLabel(Dialog)
        self.lblHoraSaida.setGeometry(QtCore.QRect(146, 146, 91, 16))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))
        self.txtData = QtGui.QDateEdit(Dialog)
        self.txtData.setGeometry(QtCore.QRect(16, 166, 110, 22))
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.btnPesquisarNotaFiscal = QtGui.QPushButton(Dialog)
        self.btnPesquisarNotaFiscal.setGeometry(QtCore.QRect(964, 20, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarNotaFiscal.setFont(font)
        self.btnPesquisarNotaFiscal.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarNotaFiscal.setText(_fromUtf8(""))
        self.btnPesquisarNotaFiscal.setObjectName(_fromUtf8("btnPesquisarNotaFiscal"))
        self.lblPesquisa = QtGui.QLabel(Dialog)
        self.lblPesquisa.setGeometry(QtCore.QRect(706, 0, 61, 16))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))
        self.txtHora = QtGui.QTimeEdit(Dialog)
        self.txtHora.setGeometry(QtCore.QRect(146, 166, 118, 22))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.lblDataSaida = QtGui.QLabel(Dialog)
        self.lblDataSaida.setGeometry(QtCore.QRect(16, 146, 101, 16))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))
        self.txtPesquisar = QtGui.QLineEdit(Dialog)
        self.txtPesquisar.setGeometry(QtCore.QRect(706, 20, 251, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisar.setPalette(palette)
        self.txtPesquisar.setMaxLength(70)
        self.txtPesquisar.setObjectName(_fromUtf8("txtPesquisar"))
        self.grbTipoPesquisa = QtGui.QGroupBox(Dialog)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(270, 0, 431, 41))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))
        self.radbtnModeloVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnModeloVeiculo.setGeometry(QtCore.QRect(90, 16, 121, 17))
        self.radbtnModeloVeiculo.setObjectName(_fromUtf8("radbtnModeloVeiculo"))
        self.radbtnMotorista = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnMotorista.setGeometry(QtCore.QRect(5, 16, 81, 17))
        self.radbtnMotorista.setObjectName(_fromUtf8("radbtnMotorista"))
        self.radbtnMarcaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnMarcaVeiculo.setGeometry(QtCore.QRect(210, 17, 121, 17))
        self.radbtnMarcaVeiculo.setObjectName(_fromUtf8("radbtnMarcaVeiculo"))
        self.radbtnPlacaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radbtnPlacaVeiculo.setGeometry(QtCore.QRect(322, 17, 111, 17))
        self.radbtnPlacaVeiculo.setObjectName(_fromUtf8("radbtnPlacaVeiculo"))
        self.tabPesquisa = QtGui.QTableWidget(Dialog)
        self.tabPesquisa.setGeometry(QtCore.QRect(5, 50, 991, 91))
        self.tabPesquisa.setObjectName(_fromUtf8("tabPesquisa"))
        self.tabPesquisa.setColumnCount(0)
        self.tabPesquisa.setRowCount(0)
        self.grbDadosEmpresaOrigem = QtGui.QGroupBox(Dialog)
        self.grbDadosEmpresaOrigem.setGeometry(QtCore.QRect(6, 493, 991, 111))
        self.grbDadosEmpresaOrigem.setObjectName(_fromUtf8("grbDadosEmpresaOrigem"))
        self.txtIdEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtIdEmpresaOrigem.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresaOrigem.setPalette(palette)
        self.txtIdEmpresaOrigem.setMaxLength(11)
        self.txtIdEmpresaOrigem.setObjectName(_fromUtf8("txtIdEmpresaOrigem"))
        self.txtNomeEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 35, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmpresaOrigem.setPalette(palette)
        self.txtNomeEmpresaOrigem.setMaxLength(70)
        self.txtNomeEmpresaOrigem.setObjectName(_fromUtf8("txtNomeEmpresaOrigem"))
        self.lblCodigoEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblCodigoEmpresaOrigem.setGeometry(QtCore.QRect(10, 15, 161, 21))
        self.lblCodigoEmpresaOrigem.setObjectName(_fromUtf8("lblCodigoEmpresaOrigem"))
        self.lblNomeEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 15, 221, 16))
        self.lblNomeEmpresaOrigem.setObjectName(_fromUtf8("lblNomeEmpresaOrigem"))
        self.txtInscricaoEstaduaEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtInscricaoEstaduaEmpresaOrigem.setGeometry(QtCore.QRect(808, 80, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmpresaOrigem.setPalette(palette)
        self.txtInscricaoEstaduaEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmpresaOrigem.setMaxLength(8)
        self.txtInscricaoEstaduaEmpresaOrigem.setObjectName(_fromUtf8("txtInscricaoEstaduaEmpresaOrigem"))
        self.txtRazaoSocialEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 80, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmpresaOrigem.setPalette(palette)
        self.txtRazaoSocialEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmpresaOrigem.setMaxLength(70)
        self.txtRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("txtRazaoSocialEmpresaOrigem"))
        self.lblRazaoSocialEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("lblRazaoSocialEmpresaOrigem"))
        self.lblCnpjEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblCnpjEmpresaOrigem.setGeometry(QtCore.QRect(620, 60, 41, 19))
        self.lblCnpjEmpresaOrigem.setObjectName(_fromUtf8("lblCnpjEmpresaOrigem"))
        self.lblInscricaoEstadualEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblInscricaoEstadualEmpresaOrigem.setGeometry(QtCore.QRect(808, 60, 121, 19))
        self.lblInscricaoEstadualEmpresaOrigem.setObjectName(_fromUtf8("lblInscricaoEstadualEmpresaOrigem"))
        self.txtCnpjEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtCnpjEmpresaOrigem.setGeometry(QtCore.QRect(620, 80, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmpresaOrigem.setPalette(palette)
        self.txtCnpjEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmpresaOrigem.setText(_fromUtf8("../-"))
        self.txtCnpjEmpresaOrigem.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmpresaOrigem.setObjectName(_fromUtf8("txtCnpjEmpresaOrigem"))
        self.btnPesquisarEmpresaOrigem = QtGui.QPushButton(self.grbDadosEmpresaOrigem)
        self.btnPesquisarEmpresaOrigem.setGeometry(QtCore.QRect(820, 40, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarEmpresaOrigem.setFont(font)
        self.btnPesquisarEmpresaOrigem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarEmpresaOrigem.setText(_fromUtf8(""))
        self.btnPesquisarEmpresaOrigem.setObjectName(_fromUtf8("btnPesquisarEmpresaOrigem"))
        self.lblMarcaMotorista.setBuddy(self.txtMarcaMotorista)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblModeloMotorista.setBuddy(self.txtModeloMotorista)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlacaMotorista.setBuddy(self.txtPlacaMotorista)
        self.label.setBuddy(self.txtTipoCarga)
        self.lblCodigoClienteDestinatario.setBuddy(self.txtIdClienteDestinatario)
        self.lblNomeClienteDestinatario.setBuddy(self.txtNomeClienteDestinatario)
        self.lblEnderecoClienteDestinatario.setBuddy(self.txtEnderecoClienteDestinatario)
        self.lblNumeroClienteDestinatario.setBuddy(self.txtNumeroClienteDestinatario)
        self.lblComplementoClienteDestinatario.setBuddy(self.txtComplementoClienteDestinatario)
        self.lblBairroClienteDestinatario.setBuddy(self.txtBairroClienteDestinatario)
        self.lblCidadeClienteDestinatario.setBuddy(self.txtCidadeClienteDestinatario)
        self.lblEstadoClienteDestinatario.setBuddy(self.txtEstadoClienteDestinatario)
        self.lblCepClienteDestinatario.setBuddy(self.txtCepClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setBuddy(self.txtRazaoSocialClienteDestinatario)
        self.lblCnpjClienteDestinatario.setBuddy(self.txtCnpjClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setBuddy(self.txtInscricaoEstaduaClienteDestinatario)
        self.lblHoraSaida.setBuddy(self.txtHora)
        self.lblPesquisa.setBuddy(self.txtPesquisar)
        self.lblDataSaida.setBuddy(self.txtData)
        self.lblCodigoEmpresaOrigem.setBuddy(self.txtIdEmpresaOrigem)
        self.lblNomeEmpresaOrigem.setBuddy(self.txtNomeEmpresaOrigem)
        self.lblRazaoSocialEmpresaOrigem.setBuddy(self.txtRazaoSocialEmpresaOrigem)
        self.lblCnpjEmpresaOrigem.setBuddy(self.txtCnpjEmpresaOrigem)
        self.lblInscricaoEstadualEmpresaOrigem.setBuddy(self.txtInscricaoEstaduaEmpresaOrigem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.radbtnEntrouVazio, self.radbtnEntrouCarregado)
        Dialog.setTabOrder(self.radbtnEntrouCarregado, self.radbtnMotorista)
        Dialog.setTabOrder(self.radbtnMotorista, self.radbtnModeloVeiculo)
        Dialog.setTabOrder(self.radbtnModeloVeiculo, self.radbtnMarcaVeiculo)
        Dialog.setTabOrder(self.radbtnMarcaVeiculo, self.radbtnPlacaVeiculo)
        Dialog.setTabOrder(self.radbtnPlacaVeiculo, self.txtPesquisar)
        Dialog.setTabOrder(self.txtPesquisar, self.tabPesquisa)
        Dialog.setTabOrder(self.tabPesquisa, self.txtData)
        Dialog.setTabOrder(self.txtData, self.txtHora)
        Dialog.setTabOrder(self.txtHora, self.txtidFuncionario)
        Dialog.setTabOrder(self.txtidFuncionario, self.txtNomeMotorista)
        Dialog.setTabOrder(self.txtNomeMotorista, self.txtModeloMotorista)
        Dialog.setTabOrder(self.txtModeloMotorista, self.txtMarcaMotorista)
        Dialog.setTabOrder(self.txtMarcaMotorista, self.txtPlacaMotorista)
        Dialog.setTabOrder(self.txtPlacaMotorista, self.txtTipoCarga)
        Dialog.setTabOrder(self.txtTipoCarga, self.txtIdClienteDestinatario)
        Dialog.setTabOrder(self.txtIdClienteDestinatario, self.txtNomeClienteDestinatario)
        Dialog.setTabOrder(self.txtNomeClienteDestinatario, self.txtRazaoSocialClienteDestinatario)
        Dialog.setTabOrder(self.txtRazaoSocialClienteDestinatario, self.txtCnpjClienteDestinatario)
        Dialog.setTabOrder(self.txtCnpjClienteDestinatario, self.txtInscricaoEstaduaClienteDestinatario)
        Dialog.setTabOrder(self.txtInscricaoEstaduaClienteDestinatario, self.txtEnderecoClienteDestinatario)
        Dialog.setTabOrder(self.txtEnderecoClienteDestinatario, self.txtNumeroClienteDestinatario)
        Dialog.setTabOrder(self.txtNumeroClienteDestinatario, self.txtComplementoClienteDestinatario)
        Dialog.setTabOrder(self.txtComplementoClienteDestinatario, self.txtBairroClienteDestinatario)
        Dialog.setTabOrder(self.txtBairroClienteDestinatario, self.txtCidadeClienteDestinatario)
        Dialog.setTabOrder(self.txtCidadeClienteDestinatario, self.txtEstadoClienteDestinatario)
        Dialog.setTabOrder(self.txtEstadoClienteDestinatario, self.txtCepClienteDestinatario)
        Dialog.setTabOrder(self.txtCepClienteDestinatario, self.txtIdEmpresaOrigem)
        Dialog.setTabOrder(self.txtIdEmpresaOrigem, self.txtNomeEmpresaOrigem)
        Dialog.setTabOrder(self.txtNomeEmpresaOrigem, self.txtRazaoSocialEmpresaOrigem)
        Dialog.setTabOrder(self.txtRazaoSocialEmpresaOrigem, self.txtCnpjEmpresaOrigem)
        Dialog.setTabOrder(self.txtCnpjEmpresaOrigem, self.txtInscricaoEstaduaEmpresaOrigem)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Saida de Veiculos Carregamento", None))
        self.grbBotoes.setWhatsThis(_translate("Dialog", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("Dialog", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("Dialog", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("Dialog", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("Dialog", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("Dialog", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("Dialog", "Salvar", None))
        self.grbDadosMotorista.setTitle(_translate("Dialog", "Motorista", None))
        self.txtModeloMotorista.setToolTip(_translate("Dialog", "Marca do Veiculo", None))
        self.txtModeloMotorista.setWhatsThis(_translate("Dialog", "Campo do nome do modelo do veiculo", None))
        self.lblMarcaMotorista.setText(_translate("Dialog", "Marca", None))
        self.txtMarcaMotorista.setToolTip(_translate("Dialog", "Marca do Veiculo", None))
        self.txtMarcaMotorista.setWhatsThis(_translate("Dialog", "Campo do nome da marca do veiculo", None))
        self.txtNomeMotorista.setToolTip(_translate("Dialog", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("Dialog", "Campo do nome do motorista", None))
        self.lblNomeMotorista.setText(_translate("Dialog", "Nome Motorista", None))
        self.txtPlacaMotorista.setToolTip(_translate("Dialog", "Placa do Veiculo", None))
        self.txtPlacaMotorista.setWhatsThis(_translate("Dialog", "Campo de identificação da placa do veiculo", None))
        self.txtPlacaMotorista.setInputMask(_translate("Dialog", "nnn-0000; ", None))
        self.txtPlacaMotorista.setText(_translate("Dialog", "-", None))
        self.lblModeloMotorista.setText(_translate("Dialog", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("Dialog", "Codigo Motorista", None))
        self.txtidFuncionario.setWhatsThis(_translate("Dialog", "Campo do Codigo de identificação do motorista", None))
        self.lblCodigoMotorista.setText(_translate("Dialog", "Codigo Motorista", None))
        self.lblPlacaMotorista.setText(_translate("Dialog", "Placa", None))
        self.txtTipoCarga.setToolTip(_translate("Dialog", "Tipo de Carga", None))
        self.txtTipoCarga.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de carga", None))
        self.label.setText(_translate("Dialog", "Tipo de Carga", None))
        self.grbDadosClienteDestinatario.setTitle(_translate("Dialog", "Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setToolTip(_translate("Dialog", "Codigo Emitente", None))
        self.txtIdClienteDestinatario.setWhatsThis(_translate("Dialog", "Campo do codigo de identificação do cliente destinatario", None))
        self.txtNomeClienteDestinatario.setToolTip(_translate("Dialog", "Nome Fantasia Cliente Destinatario", None))
        self.txtNomeClienteDestinatario.setWhatsThis(_translate("Dialog", "Campo do nome fantasia do cliente destinatario", None))
        self.lblCodigoClienteDestinatario.setText(_translate("Dialog", "Codigo Cliente Destinatario", None))
        self.lblNomeClienteDestinatario.setText(_translate("Dialog", "Nome Fantasia Cliente Destinatario", None))
        self.txtEnderecoClienteDestinatario.setToolTip(_translate("Dialog", "Endereço ", None))
        self.txtEnderecoClienteDestinatario.setWhatsThis(_translate("Dialog", "Endereço do cliente destinatario", None))
        self.txtNumeroClienteDestinatario.setToolTip(_translate("Dialog", "Numero ", None))
        self.txtNumeroClienteDestinatario.setWhatsThis(_translate("Dialog", "Numero referente ao endereço do cliente destinatario", None))
        self.txtComplementoClienteDestinatario.setToolTip(_translate("Dialog", "Complemento", None))
        self.txtComplementoClienteDestinatario.setWhatsThis(_translate("Dialog", "Complemento do endereço do cliente destinatario", None))
        self.txtCidadeClienteDestinatario.setToolTip(_translate("Dialog", "Cidade", None))
        self.txtCidadeClienteDestinatario.setWhatsThis(_translate("Dialog", "Nome da cidade onde o cliente destinatario reside", None))
        self.txtEstadoClienteDestinatario.setToolTip(_translate("Dialog", "Estado", None))
        self.txtEstadoClienteDestinatario.setWhatsThis(_translate("Dialog", "Nome do estado onde fica localizado a cidade do cliente destinatario", None))
        self.txtCepClienteDestinatario.setToolTip(_translate("Dialog", "CEP ", None))
        self.txtCepClienteDestinatario.setWhatsThis(_translate("Dialog", "Codigo do CEP referente a cidade do cliente destinatario", None))
        self.txtCepClienteDestinatario.setInputMask(_translate("Dialog", "00000-000; ", None))
        self.txtBairroClienteDestinatario.setToolTip(_translate("Dialog", "Bairro", None))
        self.txtBairroClienteDestinatario.setWhatsThis(_translate("Dialog", "Nome do bairro localizado o endereço do cliente destinatario", None))
        self.lblEnderecoClienteDestinatario.setText(_translate("Dialog", "Endereço", None))
        self.lblNumeroClienteDestinatario.setText(_translate("Dialog", "Numero", None))
        self.lblComplementoClienteDestinatario.setText(_translate("Dialog", "Complemento", None))
        self.lblBairroClienteDestinatario.setText(_translate("Dialog", "Bairro", None))
        self.lblCidadeClienteDestinatario.setText(_translate("Dialog", "Cidade", None))
        self.lblEstadoClienteDestinatario.setText(_translate("Dialog", "Estado", None))
        self.lblCepClienteDestinatario.setText(_translate("Dialog", "CEP", None))
        self.txtInscricaoEstaduaClienteDestinatario.setToolTip(_translate("Dialog", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaClienteDestinatario.setWhatsThis(_translate("Dialog", "Campo do numero do inscrição estadual do cliente destinatario", None))
        self.txtRazaoSocialClienteDestinatario.setToolTip(_translate("Dialog", "Razão Social ", None))
        self.txtRazaoSocialClienteDestinatario.setWhatsThis(_translate("Dialog", "Campo do nome da razão social do cliente destinatario", None))
        self.lblRazaoSocialClienteDestinatario.setText(_translate("Dialog", "Razão Social", None))
        self.lblCnpjClienteDestinatario.setText(_translate("Dialog", "CNPJ", None))
        self.lblInscricaoClienteDestinatario.setText(_translate("Dialog", "Incrição Estadual", None))
        self.txtCnpjClienteDestinatario.setToolTip(_translate("Dialog", "CNPJ ", None))
        self.txtCnpjClienteDestinatario.setWhatsThis(_translate("Dialog", "Campo do numero do CNPJ do cliente destinatario", None))
        self.txtCnpjClienteDestinatario.setInputMask(_translate("Dialog", "00.000.000/0000-00; ", None))
        self.grbTipoOperacao.setTitle(_translate("Dialog", "Tipo de Operação", None))
        self.radbtnEntrouVazio.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de operação que sera por entrou vazio ", None))
        self.radbtnEntrouVazio.setText(_translate("Dialog", "Entrou Vazio", None))
        self.radbtnEntrouCarregado.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de operação que sera por entrou carregado", None))
        self.radbtnEntrouCarregado.setText(_translate("Dialog", "Entrou Carregado", None))
        self.lblHoraSaida.setText(_translate("Dialog", "Hora Saida", None))
        self.txtData.setToolTip(_translate("Dialog", "Data Saida", None))
        self.txtData.setWhatsThis(_translate("Dialog", "Campo da data de saida", None))
        self.lblPesquisa.setText(_translate("Dialog", "Pesquisa", None))
        self.txtHora.setToolTip(_translate("Dialog", "Hora Saida", None))
        self.txtHora.setWhatsThis(_translate("Dialog", "Campo da hora de saida", None))
        self.lblDataSaida.setText(_translate("Dialog", "Data Saida", None))
        self.txtPesquisar.setToolTip(_translate("Dialog", "Pesquisa", None))
        self.txtPesquisar.setWhatsThis(_translate("Dialog", "Campo de pesquisa", None))
        self.grbTipoPesquisa.setTitle(_translate("Dialog", "Tipo de pesquisa", None))
        self.radbtnModeloVeiculo.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de pesquisa por modelo veiculo", None))
        self.radbtnModeloVeiculo.setText(_translate("Dialog", "Modelo Veiculo", None))
        self.radbtnMotorista.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de pesquisa por motorista", None))
        self.radbtnMotorista.setText(_translate("Dialog", "Motorista", None))
        self.radbtnMarcaVeiculo.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de pesquisa por marca veiculo", None))
        self.radbtnMarcaVeiculo.setText(_translate("Dialog", "Marca Veiculo", None))
        self.radbtnPlacaVeiculo.setWhatsThis(_translate("Dialog", "Campo de escolha do tipo de pesquisa por placa veiculo", None))
        self.radbtnPlacaVeiculo.setText(_translate("Dialog", "Placa Veiculo", None))
        self.tabPesquisa.setWhatsThis(_translate("Dialog", "Tabela de resultados da pesquisa", None))
        self.grbDadosEmpresaOrigem.setTitle(_translate("Dialog", "Empresa Origem", None))
        self.txtIdEmpresaOrigem.setToolTip(_translate("Dialog", "Codigo Empresa Origem", None))
        self.txtIdEmpresaOrigem.setWhatsThis(_translate("Dialog", "Campo do codigo de identificação da empresa origem", None))
        self.txtNomeEmpresaOrigem.setToolTip(_translate("Dialog", "Nome Fantasia Empresa Origem", None))
        self.txtNomeEmpresaOrigem.setWhatsThis(_translate("Dialog", "Campo do nome fantasia da empresa origem", None))
        self.lblCodigoEmpresaOrigem.setText(_translate("Dialog", "Codigo Empresa Origem", None))
        self.lblNomeEmpresaOrigem.setText(_translate("Dialog", "Nome Fantasia Empresa Origem", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setToolTip(_translate("Dialog", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setWhatsThis(_translate("Dialog", "Campo do numero do inscrição estadual do empresa origem", None))
        self.txtRazaoSocialEmpresaOrigem.setToolTip(_translate("Dialog", "Razão Social ", None))
        self.txtRazaoSocialEmpresaOrigem.setWhatsThis(_translate("Dialog", "Campo do nome da razão social do empresa origem", None))
        self.lblRazaoSocialEmpresaOrigem.setText(_translate("Dialog", "Razão Social", None))
        self.lblCnpjEmpresaOrigem.setText(_translate("Dialog", "CNPJ", None))
        self.lblInscricaoEstadualEmpresaOrigem.setText(_translate("Dialog", "Incrição Estadual", None))
        self.txtCnpjEmpresaOrigem.setToolTip(_translate("Dialog", "CNPJ ", None))
        self.txtCnpjEmpresaOrigem.setWhatsThis(_translate("Dialog", "Campo do numero do CNPJ do empresa origem", None))
        self.txtCnpjEmpresaOrigem.setInputMask(_translate("Dialog", "00.000.000/0000-00; ", None))

