# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaVeiculosTerceiros.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaVeiculosTerceiros(object):
    def setupUi(self, frmSaidaVeiculosTerceiros):
        frmSaidaVeiculosTerceiros.setObjectName(_fromUtf8("frmSaidaVeiculosTerceiros"))
        frmSaidaVeiculosTerceiros.resize(879, 686)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmSaidaVeiculosTerceiros.setFont(font)
        frmSaidaVeiculosTerceiros.setModal(True)
        self.lblObservacao = QtGui.QLabel(frmSaidaVeiculosTerceiros)
        self.lblObservacao.setGeometry(QtCore.QRect(20, 480, 91, 16))
        self.lblObservacao.setObjectName(_fromUtf8("lblObservacao"))
        self.txtObservacao = QtGui.QTextEdit(frmSaidaVeiculosTerceiros)
        self.txtObservacao.setEnabled(False)
        self.txtObservacao.setGeometry(QtCore.QRect(20, 500, 841, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtObservacao.setPalette(palette)
        self.txtObservacao.setObjectName(_fromUtf8("txtObservacao"))
        self.grbDadosEmpresaDestino = QtGui.QGroupBox(frmSaidaVeiculosTerceiros)
        self.grbDadosEmpresaDestino.setEnabled(False)
        self.grbDadosEmpresaDestino.setGeometry(QtCore.QRect(10, 410, 861, 71))
        self.grbDadosEmpresaDestino.setObjectName(_fromUtf8("grbDadosEmpresaDestino"))
        self.txtIdEmpresaDestino = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtIdEmpresaDestino.setEnabled(False)
        self.txtIdEmpresaDestino.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresaDestino.setPalette(palette)
        self.txtIdEmpresaDestino.setMaxLength(11)
        self.txtIdEmpresaDestino.setObjectName(_fromUtf8("txtIdEmpresaDestino"))
        self.txtNomeEmpresaDestino = QtGui.QLineEdit(self.grbDadosEmpresaDestino)
        self.txtNomeEmpresaDestino.setEnabled(False)
        self.txtNomeEmpresaDestino.setGeometry(QtCore.QRect(201, 35, 401, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmpresaDestino.setPalette(palette)
        self.txtNomeEmpresaDestino.setMaxLength(70)
        self.txtNomeEmpresaDestino.setObjectName(_fromUtf8("txtNomeEmpresaDestino"))
        self.lblCodigoEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblCodigoEmpresaOrigem.setGeometry(QtCore.QRect(10, 15, 161, 21))
        self.lblCodigoEmpresaOrigem.setObjectName(_fromUtf8("lblCodigoEmpresaOrigem"))
        self.lblNomeEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 15, 221, 16))
        self.lblNomeEmpresaOrigem.setObjectName(_fromUtf8("lblNomeEmpresaOrigem"))
        self.lblSetor = QtGui.QLabel(self.grbDadosEmpresaDestino)
        self.lblSetor.setGeometry(QtCore.QRect(610, 15, 41, 16))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        self.txtSetor = QtGui.QComboBox(self.grbDadosEmpresaDestino)
        self.txtSetor.setEnabled(False)
        self.txtSetor.setGeometry(QtCore.QRect(610, 35, 241, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetor.setPalette(palette)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        self.grbLugarOrigem = QtGui.QGroupBox(frmSaidaVeiculosTerceiros)
        self.grbLugarOrigem.setEnabled(False)
        self.grbLugarOrigem.setGeometry(QtCore.QRect(10, 340, 861, 71))
        self.grbLugarOrigem.setObjectName(_fromUtf8("grbLugarOrigem"))
        self.lblCep = QtGui.QLabel(self.grbLugarOrigem)
        self.lblCep.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.lblCep.setObjectName(_fromUtf8("lblCep"))
        self.txtEstado = QtGui.QLineEdit(self.grbLugarOrigem)
        self.txtEstado.setEnabled(False)
        self.txtEstado.setGeometry(QtCore.QRect(610, 37, 243, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstado.setPalette(palette)
        self.txtEstado.setMaxLength(50)
        self.txtEstado.setObjectName(_fromUtf8("txtEstado"))
        self.tctCep = QtGui.QLineEdit(self.grbLugarOrigem)
        self.tctCep.setEnabled(False)
        self.tctCep.setGeometry(QtCore.QRect(10, 37, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tctCep.setPalette(palette)
        self.tctCep.setObjectName(_fromUtf8("tctCep"))
        self.txtCidade = QtGui.QLineEdit(self.grbLugarOrigem)
        self.txtCidade.setEnabled(False)
        self.txtCidade.setGeometry(QtCore.QRect(200, 37, 401, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidade.setPalette(palette)
        self.txtCidade.setMaxLength(70)
        self.txtCidade.setObjectName(_fromUtf8("txtCidade"))
        self.lblCidade = QtGui.QLabel(self.grbLugarOrigem)
        self.lblCidade.setGeometry(QtCore.QRect(200, 20, 51, 16))
        self.lblCidade.setObjectName(_fromUtf8("lblCidade"))
        self.lblEstado = QtGui.QLabel(self.grbLugarOrigem)
        self.lblEstado.setGeometry(QtCore.QRect(610, 20, 51, 16))
        self.lblEstado.setObjectName(_fromUtf8("lblEstado"))
        self.grbDadosCondutor = QtGui.QGroupBox(frmSaidaVeiculosTerceiros)
        self.grbDadosCondutor.setEnabled(False)
        self.grbDadosCondutor.setGeometry(QtCore.QRect(10, 280, 861, 63))
        self.grbDadosCondutor.setObjectName(_fromUtf8("grbDadosCondutor"))
        self.lblPlacaVeiculo = QtGui.QLabel(self.grbDadosCondutor)
        self.lblPlacaVeiculo.setGeometry(QtCore.QRect(720, 14, 111, 16))
        self.lblPlacaVeiculo.setObjectName(_fromUtf8("lblPlacaVeiculo"))
        self.lblMarcaVeiculo = QtGui.QLabel(self.grbDadosCondutor)
        self.lblMarcaVeiculo.setGeometry(QtCore.QRect(306, 14, 111, 16))
        self.lblMarcaVeiculo.setObjectName(_fromUtf8("lblMarcaVeiculo"))
        self.lblModeloVeiculo = QtGui.QLabel(self.grbDadosCondutor)
        self.lblModeloVeiculo.setGeometry(QtCore.QRect(525, 14, 111, 16))
        self.lblModeloVeiculo.setObjectName(_fromUtf8("lblModeloVeiculo"))
        self.txtMarcaVeiculo = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtMarcaVeiculo.setEnabled(False)
        self.txtMarcaVeiculo.setGeometry(QtCore.QRect(306, 32, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarcaVeiculo.setPalette(palette)
        self.txtMarcaVeiculo.setMaxLength(50)
        self.txtMarcaVeiculo.setObjectName(_fromUtf8("txtMarcaVeiculo"))
        self.txtNomeCondutor = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtNomeCondutor.setEnabled(False)
        self.txtNomeCondutor.setGeometry(QtCore.QRect(10, 32, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeCondutor.setPalette(palette)
        self.txtNomeCondutor.setMaxLength(70)
        self.txtNomeCondutor.setObjectName(_fromUtf8("txtNomeCondutor"))
        self.txtPlacaVeiculo = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtPlacaVeiculo.setGeometry(QtCore.QRect(720, 32, 131, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlacaVeiculo.setPalette(palette)
        self.txtPlacaVeiculo.setObjectName(_fromUtf8("txtPlacaVeiculo"))
        self.txtModeloVeiculo = QtGui.QLineEdit(self.grbDadosCondutor)
        self.txtModeloVeiculo.setEnabled(False)
        self.txtModeloVeiculo.setGeometry(QtCore.QRect(525, 32, 190, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModeloVeiculo.setPalette(palette)
        self.txtModeloVeiculo.setMaxLength(50)
        self.txtModeloVeiculo.setObjectName(_fromUtf8("txtModeloVeiculo"))
        self.lblNomeCondutor = QtGui.QLabel(self.grbDadosCondutor)
        self.lblNomeCondutor.setGeometry(QtCore.QRect(10, 15, 111, 16))
        self.lblNomeCondutor.setObjectName(_fromUtf8("lblNomeCondutor"))
        self.grbDadosEntrada = QtGui.QGroupBox(frmSaidaVeiculosTerceiros)
        self.grbDadosEntrada.setEnabled(False)
        self.grbDadosEntrada.setGeometry(QtCore.QRect(10, 210, 861, 71))
        self.grbDadosEntrada.setObjectName(_fromUtf8("grbDadosEntrada"))
        self.txtHora = QtGui.QTimeEdit(self.grbDadosEntrada)
        self.txtHora.setGeometry(QtCore.QRect(140, 40, 118, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtHora.setPalette(palette)
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.lblHoraSaida = QtGui.QLabel(self.grbDadosEntrada)
        self.lblHoraSaida.setGeometry(QtCore.QRect(140, 20, 91, 16))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))
        self.lblTipoAfazer = QtGui.QLabel(self.grbDadosEntrada)
        self.lblTipoAfazer.setGeometry(QtCore.QRect(280, 20, 101, 16))
        self.lblTipoAfazer.setObjectName(_fromUtf8("lblTipoAfazer"))
        self.txtTipoAfzer = QtGui.QComboBox(self.grbDadosEntrada)
        self.txtTipoAfzer.setEnabled(False)
        self.txtTipoAfzer.setGeometry(QtCore.QRect(280, 40, 241, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTipoAfzer.setPalette(palette)
        self.txtTipoAfzer.setObjectName(_fromUtf8("txtTipoAfzer"))
        self.txtData = QtGui.QDateEdit(self.grbDadosEntrada)
        self.txtData.setGeometry(QtCore.QRect(10, 40, 110, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtData.setPalette(palette)
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.lblDataSaida = QtGui.QLabel(self.grbDadosEntrada)
        self.lblDataSaida.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))
        self.grbBotoes = QtGui.QGroupBox(frmSaidaVeiculosTerceiros)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 600, 851, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(740, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(440, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(340, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(640, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(540, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))
        self.grbTipoPesquisa = QtGui.QGroupBox(frmSaidaVeiculosTerceiros)
        self.grbTipoPesquisa.setEnabled(False)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(10, 0, 281, 81))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))
        self.radBtnNomeCondutor = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnNomeCondutor.setGeometry(QtCore.QRect(10, 16, 121, 23))
        self.radBtnNomeCondutor.setObjectName(_fromUtf8("radBtnNomeCondutor"))
        self.radBtnMarcaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnMarcaVeiculo.setGeometry(QtCore.QRect(10, 36, 109, 23))
        self.radBtnMarcaVeiculo.setObjectName(_fromUtf8("radBtnMarcaVeiculo"))
        self.radBtnModeloVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnModeloVeiculo.setGeometry(QtCore.QRect(10, 56, 121, 23))
        self.radBtnModeloVeiculo.setObjectName(_fromUtf8("radBtnModeloVeiculo"))
        self.radBtnPlaca = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnPlaca.setGeometry(QtCore.QRect(140, 17, 109, 23))
        self.radBtnPlaca.setObjectName(_fromUtf8("radBtnPlaca"))
        self.radBtnCidade = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnCidade.setGeometry(QtCore.QRect(140, 37, 109, 23))
        self.radBtnCidade.setObjectName(_fromUtf8("radBtnCidade"))
        self.radBtnEmpresaDestino = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnEmpresaDestino.setGeometry(QtCore.QRect(140, 57, 131, 23))
        self.radBtnEmpresaDestino.setObjectName(_fromUtf8("radBtnEmpresaDestino"))
        self.txtPesquisa = QtGui.QLineEdit(frmSaidaVeiculosTerceiros)
        self.txtPesquisa.setEnabled(False)
        self.txtPesquisa.setGeometry(QtCore.QRect(300, 30, 401, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisa.setPalette(palette)
        self.txtPesquisa.setObjectName(_fromUtf8("txtPesquisa"))
        self.btnPesquisa = QtGui.QPushButton(frmSaidaVeiculosTerceiros)
        self.btnPesquisa.setEnabled(False)
        self.btnPesquisa.setGeometry(QtCore.QRect(710, 29, 31, 28))
        self.btnPesquisa.setText(_fromUtf8(""))
        self.btnPesquisa.setObjectName(_fromUtf8("btnPesquisa"))
        self.lblPesquisa = QtGui.QLabel(frmSaidaVeiculosTerceiros)
        self.lblPesquisa.setGeometry(QtCore.QRect(300, 10, 66, 19))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))
        self.tableWidget = QtGui.QTableWidget(frmSaidaVeiculosTerceiros)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 841, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lblObservacao.setBuddy(self.txtObservacao)
        self.lblCodigoEmpresaOrigem.setBuddy(self.txtIdEmpresaDestino)
        self.lblNomeEmpresaOrigem.setBuddy(self.txtNomeEmpresaDestino)
        self.lblSetor.setBuddy(self.txtTipoAfzer)
        self.lblCep.setBuddy(self.tctCep)
        self.lblCidade.setBuddy(self.txtCidade)
        self.lblEstado.setBuddy(self.txtEstado)
        self.lblPlacaVeiculo.setBuddy(self.txtPlacaVeiculo)
        self.lblMarcaVeiculo.setBuddy(self.txtMarcaVeiculo)
        self.lblModeloVeiculo.setBuddy(self.txtModeloVeiculo)
        self.lblNomeCondutor.setBuddy(self.txtNomeCondutor)
        self.lblHoraSaida.setBuddy(self.txtHora)
        self.lblTipoAfazer.setBuddy(self.txtTipoAfzer)
        self.lblDataSaida.setBuddy(self.txtData)

        self.retranslateUi(frmSaidaVeiculosTerceiros)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaVeiculosTerceiros)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtData, self.txtHora)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtHora, self.txtTipoAfzer)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtTipoAfzer, self.txtNomeCondutor)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtNomeCondutor, self.txtMarcaVeiculo)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtMarcaVeiculo, self.txtModeloVeiculo)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtModeloVeiculo, self.txtPlacaVeiculo)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtPlacaVeiculo, self.tctCep)
        frmSaidaVeiculosTerceiros.setTabOrder(self.tctCep, self.txtCidade)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtCidade, self.txtEstado)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtEstado, self.txtIdEmpresaDestino)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtIdEmpresaDestino, self.txtNomeEmpresaDestino)
        frmSaidaVeiculosTerceiros.setTabOrder(self.txtNomeEmpresaDestino, self.txtObservacao)

    def retranslateUi(self, frmSaidaVeiculosTerceiros):
        frmSaidaVeiculosTerceiros.setWindowTitle(_translate("frmSaidaVeiculosTerceiros", "Saida Veiculos Terceiros", None))
        self.lblObservacao.setText(_translate("frmSaidaVeiculosTerceiros", "Observações", None))
        self.txtObservacao.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Observação", None))
        self.txtObservacao.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo de observações", None))
        self.grbDadosEmpresaDestino.setTitle(_translate("frmSaidaVeiculosTerceiros", "Empresa Destino", None))
        self.txtIdEmpresaDestino.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Codigo Empresa Origem", None))
        self.txtIdEmpresaDestino.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do codigo de identificação da empresa origem", None))
        self.txtNomeEmpresaDestino.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Nome Fantasia Empresa Origem", None))
        self.txtNomeEmpresaDestino.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do nome fantasia da empresa de origem", None))
        self.lblCodigoEmpresaOrigem.setText(_translate("frmSaidaVeiculosTerceiros", "Codigo Empresa Destino", None))
        self.lblNomeEmpresaOrigem.setText(_translate("frmSaidaVeiculosTerceiros", "Nome Fantasia Empresa Destino", None))
        self.lblSetor.setText(_translate("frmSaidaVeiculosTerceiros", "Setor", None))
        self.txtSetor.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Setor", None))
        self.txtSetor.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo de descrição do setor", None))
        self.grbLugarOrigem.setTitle(_translate("frmSaidaVeiculosTerceiros", "Lugar Origem", None))
        self.lblCep.setText(_translate("frmSaidaVeiculosTerceiros", "CEP", None))
        self.txtEstado.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Estado", None))
        self.txtEstado.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do nome do estado", None))
        self.tctCep.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Cep", None))
        self.tctCep.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do numero do CEP da cidade", None))
        self.tctCep.setInputMask(_translate("frmSaidaVeiculosTerceiros", "00000-000; ", None))
        self.txtCidade.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Cidade", None))
        self.txtCidade.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do nome da cidade", None))
        self.lblCidade.setText(_translate("frmSaidaVeiculosTerceiros", "Cidade", None))
        self.lblEstado.setText(_translate("frmSaidaVeiculosTerceiros", "Estado", None))
        self.grbDadosCondutor.setTitle(_translate("frmSaidaVeiculosTerceiros", "Dados Condutor", None))
        self.lblPlacaVeiculo.setText(_translate("frmSaidaVeiculosTerceiros", "Placa Veiculo", None))
        self.lblMarcaVeiculo.setText(_translate("frmSaidaVeiculosTerceiros", "Marca Veiculo", None))
        self.lblModeloVeiculo.setText(_translate("frmSaidaVeiculosTerceiros", "Modelo Veiculo", None))
        self.txtMarcaVeiculo.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Marca Veiculo", None))
        self.txtNomeCondutor.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Nome Condutor", None))
        self.txtNomeCondutor.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do nome do condutor", None))
        self.txtPlacaVeiculo.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Placa Veiculo", None))
        self.txtPlacaVeiculo.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo de identificação da placa do Veiculo", None))
        self.txtPlacaVeiculo.setInputMask(_translate("frmSaidaVeiculosTerceiros", "nnn-0000; ", None))
        self.txtModeloVeiculo.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Modelo Veiculo", None))
        self.txtModeloVeiculo.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo do nome do modelo do veiculo", None))
        self.lblNomeCondutor.setText(_translate("frmSaidaVeiculosTerceiros", "Nome Condutor", None))
        self.grbDadosEntrada.setTitle(_translate("frmSaidaVeiculosTerceiros", "Dados Saída", None))
        self.txtHora.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Hora Entrada", None))
        self.txtHora.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo da hora de entrada", None))
        self.lblHoraSaida.setText(_translate("frmSaidaVeiculosTerceiros", "Hora Saida", None))
        self.lblTipoAfazer.setText(_translate("frmSaidaVeiculosTerceiros", "Tipo de Afazer", None))
        self.txtTipoAfzer.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Tipo de Afazer", None))
        self.txtData.setToolTip(_translate("frmSaidaVeiculosTerceiros", "Data Entrada", None))
        self.txtData.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Campo da data de entrda", None))
        self.lblDataSaida.setText(_translate("frmSaidaVeiculosTerceiros", "Data Saida", None))
        self.grbBotoes.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Grupo de botões referente as suas funções", None))
        self.btnDeletar.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmSaidaVeiculosTerceiros", "Deletar", None))
        self.btnSalvar.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmSaidaVeiculosTerceiros", "Salvar", None))
        self.btnNovo.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmSaidaVeiculosTerceiros", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmSaidaVeiculosTerceiros", "Cancelar", None))
        self.btnEditar.setWhatsThis(_translate("frmSaidaVeiculosTerceiros", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmSaidaVeiculosTerceiros", "Editar", None))
        self.grbTipoPesquisa.setTitle(_translate("frmSaidaVeiculosTerceiros", "Tipo Pesquisa", None))
        self.radBtnNomeCondutor.setText(_translate("frmSaidaVeiculosTerceiros", "Nome Condutor", None))
        self.radBtnMarcaVeiculo.setText(_translate("frmSaidaVeiculosTerceiros", "Marca Veiculo", None))
        self.radBtnModeloVeiculo.setText(_translate("frmSaidaVeiculosTerceiros", "Modelo Veiculo", None))
        self.radBtnPlaca.setText(_translate("frmSaidaVeiculosTerceiros", "Placa", None))
        self.radBtnCidade.setText(_translate("frmSaidaVeiculosTerceiros", "Cidade", None))
        self.radBtnEmpresaDestino.setText(_translate("frmSaidaVeiculosTerceiros", "Empresa Destino", None))
        self.lblPesquisa.setText(_translate("frmSaidaVeiculosTerceiros", "Pesquisa", None))

