# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSaidaCaminhaoEmpresa.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmSaidaCaminhoaEmpresa(object):
    def setupUi(self, frmSaidaCaminhoaEmpresa):
        frmSaidaCaminhoaEmpresa.setObjectName(_fromUtf8("frmSaidaCaminhoaEmpresa"))
        frmSaidaCaminhoaEmpresa.resize(899, 686)
        frmSaidaCaminhoaEmpresa.setMinimumSize(QtCore.QSize(899, 686))
        frmSaidaCaminhoaEmpresa.setMaximumSize(QtCore.QSize(899, 686))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmSaidaCaminhoaEmpresa.setFont(font)
        frmSaidaCaminhoaEmpresa.setModal(True)
        self.grbBotoes = QtGui.QGroupBox(frmSaidaCaminhoaEmpresa)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 600, 851, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))

        self.btnDeletar = QtGui.QPushButton(self.grbBotoes)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(740, 10, 81, 61))
        self.btnDeletar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDeletar.setObjectName(_fromUtf8("btnDeletar"))

        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(440, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))

        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(340, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))

        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(640, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))

        self.btnEditar = QtGui.QPushButton(self.grbBotoes)
        self.btnEditar.setEnabled(False)
        self.btnEditar.setGeometry(QtCore.QRect(540, 10, 81, 61))
        self.btnEditar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEditar.setObjectName(_fromUtf8("btnEditar"))

        self.grbTipoPesquisa = QtGui.QGroupBox(frmSaidaCaminhoaEmpresa)
        self.grbTipoPesquisa.setEnabled(False)
        self.grbTipoPesquisa.setGeometry(QtCore.QRect(10, 0, 281, 81))
        self.grbTipoPesquisa.setObjectName(_fromUtf8("grbTipoPesquisa"))

        self.radBtnNomeMotorista = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnNomeMotorista.setGeometry(QtCore.QRect(10, 16, 124, 23))
        self.radBtnNomeMotorista.setObjectName(_fromUtf8("radBtnNomeMotorista"))

        self.radBtnMarcaVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnMarcaVeiculo.setGeometry(QtCore.QRect(10, 36, 109, 23))
        self.radBtnMarcaVeiculo.setObjectName(_fromUtf8("radBtnMarcaVeiculo"))

        self.radBtnModeloVeiculo = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnModeloVeiculo.setGeometry(QtCore.QRect(10, 56, 121, 23))
        self.radBtnModeloVeiculo.setObjectName(_fromUtf8("radBtnModeloVeiculo"))

        self.radBtnPlaca = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnPlaca.setGeometry(QtCore.QRect(140, 17, 109, 23))
        self.radBtnPlaca.setObjectName(_fromUtf8("radBtnPlaca"))

        self.radBtnCidade = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnCidade.setGeometry(QtCore.QRect(140, 37, 109, 23))
        self.radBtnCidade.setObjectName(_fromUtf8("radBtnCidade"))

        self.radBtnTipoAfazer = QtGui.QRadioButton(self.grbTipoPesquisa)
        self.radBtnTipoAfazer.setGeometry(QtCore.QRect(140, 57, 131, 23))
        self.radBtnTipoAfazer.setObjectName(_fromUtf8("radBtnTipoAfazer"))

        self.txtPesquisa = QtGui.QLineEdit(frmSaidaCaminhoaEmpresa)
        self.txtPesquisa.setEnabled(False)
        self.txtPesquisa.setGeometry(QtCore.QRect(300, 30, 401, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPesquisa.setPalette(palette)
        self.txtPesquisa.setObjectName(_fromUtf8("txtPesquisa"))

        self.btnPesquisa = QtGui.QPushButton(frmSaidaCaminhoaEmpresa)
        self.btnPesquisa.setEnabled(False)
        self.btnPesquisa.setGeometry(QtCore.QRect(710, 29, 31, 28))
        self.btnPesquisa.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./imagens/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisa.setIcon(icon)
        self.btnPesquisa.setObjectName(_fromUtf8("btnPesquisa"))

        self.lblPesquisa = QtGui.QLabel(frmSaidaCaminhoaEmpresa)
        self.lblPesquisa.setGeometry(QtCore.QRect(300, 10, 66, 19))
        self.lblPesquisa.setObjectName(_fromUtf8("lblPesquisa"))

        self.tableWidget = QtGui.QTableWidget(frmSaidaCaminhoaEmpresa)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 861, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.grbDadosExtra = QtGui.QGroupBox(frmSaidaCaminhoaEmpresa)
        self.grbDadosExtra.setEnabled(False)
        self.grbDadosExtra.setGeometry(QtCore.QRect(20, 530, 871, 81))
        self.grbDadosExtra.setObjectName(_fromUtf8("grbDadosExtra"))

        self.txtTipoCarga = QtGui.QComboBox(self.grbDadosExtra)
        self.txtTipoCarga.setEnabled(False)
        self.txtTipoCarga.setGeometry(QtCore.QRect(280, 42, 241, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTipoCarga.setPalette(palette)
        self.txtTipoCarga.setObjectName(_fromUtf8("txtTipoCarga"))

        self.lblDataSaida = QtGui.QLabel(self.grbDadosExtra)
        self.lblDataSaida.setGeometry(QtCore.QRect(10, 22, 101, 16))
        self.lblDataSaida.setObjectName(_fromUtf8("lblDataSaida"))

        self.lblHoraSaida = QtGui.QLabel(self.grbDadosExtra)
        self.lblHoraSaida.setGeometry(QtCore.QRect(140, 22, 91, 16))
        self.lblHoraSaida.setObjectName(_fromUtf8("lblHoraSaida"))

        self.txtHora = QtGui.QTimeEdit(self.grbDadosExtra)
        self.txtHora.setEnabled(False)
        self.txtHora.setGeometry(QtCore.QRect(140, 42, 118, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtHora.setPalette(palette)
        self.txtHora.setObjectName(_fromUtf8("txtHora"))

        self.txtProduto = QtGui.QComboBox(self.grbDadosExtra)
        self.txtProduto.setEnabled(False)
        self.txtProduto.setGeometry(QtCore.QRect(530, 42, 241, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtProduto.setPalette(palette)
        self.txtProduto.setObjectName(_fromUtf8("txtProduto"))

        self.txtData = QtGui.QDateEdit(self.grbDadosExtra)
        self.txtData.setEnabled(False)
        self.txtData.setGeometry(QtCore.QRect(10, 42, 110, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtData.setPalette(palette)
        self.txtData.setCalendarPopup(True)
        self.txtData.setObjectName(_fromUtf8("txtData"))

        self.lblTipoCarga = QtGui.QLabel(self.grbDadosExtra)
        self.lblTipoCarga.setGeometry(QtCore.QRect(280, 20, 101, 16))
        self.lblTipoCarga.setObjectName(_fromUtf8("lblTipoCarga"))

        self.lblProduto = QtGui.QLabel(self.grbDadosExtra)
        self.lblProduto.setGeometry(QtCore.QRect(530, 20, 51, 16))
        self.lblProduto.setObjectName(_fromUtf8("lblProduto"))

        self.grbDadosMotorista = QtGui.QGroupBox(frmSaidaCaminhoaEmpresa)
        self.grbDadosMotorista.setEnabled(False)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(20, 220, 871, 114))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))

        self.txtModeloMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModeloMotorista.setEnabled(False)
        self.txtModeloMotorista.setGeometry(QtCore.QRect(10, 80, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModeloMotorista.setPalette(palette)
        self.txtModeloMotorista.setMaxLength(50)
        self.txtModeloMotorista.setObjectName(_fromUtf8("txtModeloMotorista"))

        self.lblMarcaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarcaMotorista.setGeometry(QtCore.QRect(310, 62, 51, 19))
        self.lblMarcaMotorista.setObjectName(_fromUtf8("lblMarcaMotorista"))

        self.txtMarcaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarcaMotorista.setEnabled(False)
        self.txtMarcaMotorista.setGeometry(QtCore.QRect(310, 82, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarcaMotorista.setPalette(palette)
        self.txtMarcaMotorista.setMaxLength(50)
        self.txtMarcaMotorista.setObjectName(_fromUtf8("txtMarcaMotorista"))

        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(180, 36, 681, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMotorista.setPalette(palette)
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))

        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 16, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtPlacaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlacaMotorista.setEnabled(False)
        self.txtPlacaMotorista.setGeometry(QtCore.QRect(650, 82, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlacaMotorista.setPalette(palette)
        self.txtPlacaMotorista.setObjectName(_fromUtf8("txtPlacaMotorista"))
        self.lblModeloMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModeloMotorista.setGeometry(QtCore.QRect(10, 60, 51, 19))
        self.lblModeloMotorista.setObjectName(_fromUtf8("lblModeloMotorista"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setEnabled(False)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 36, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 16, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblPlacaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlacaMotorista.setGeometry(QtCore.QRect(650, 62, 51, 19))
        self.lblPlacaMotorista.setObjectName(_fromUtf8("lblPlacaMotorista"))
        self.grbDadosOrigem = QtGui.QGroupBox(frmSaidaCaminhoaEmpresa)
        self.grbDadosOrigem.setEnabled(False)
        self.grbDadosOrigem.setGeometry(QtCore.QRect(20, 340, 871, 121))
        self.grbDadosOrigem.setObjectName(_fromUtf8("grbDadosOrigem"))
        self.lblEstadosCliente = QtGui.QLabel(self.grbDadosOrigem)
        self.lblEstadosCliente.setGeometry(QtCore.QRect(12, 69, 51, 19))
        self.lblEstadosCliente.setObjectName(_fromUtf8("lblEstadosCliente"))
        self.txtEstadosCliente = QtGui.QLineEdit(self.grbDadosOrigem)
        self.txtEstadosCliente.setEnabled(False)
        self.txtEstadosCliente.setGeometry(QtCore.QRect(10, 90, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadosCliente.setPalette(palette)
        self.txtEstadosCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstadosCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstadosCliente.setMaxLength(50)
        self.txtEstadosCliente.setObjectName(_fromUtf8("txtEstadosCliente"))
        self.lblCepCliente = QtGui.QLabel(self.grbDadosOrigem)
        self.lblCepCliente.setGeometry(QtCore.QRect(6, 20, 31, 19))
        self.lblCepCliente.setObjectName(_fromUtf8("lblCepCliente"))
        self.txtCidadesCliente = QtGui.QLineEdit(self.grbDadosOrigem)
        self.txtCidadesCliente.setEnabled(False)
        self.txtCidadesCliente.setGeometry(QtCore.QRect(180, 40, 681, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadesCliente.setPalette(palette)
        self.txtCidadesCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidadesCliente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidadesCliente.setMaxLength(70)
        self.txtCidadesCliente.setObjectName(_fromUtf8("txtCidadesCliente"))
        self.lblCidadesCliente = QtGui.QLabel(self.grbDadosOrigem)
        self.lblCidadesCliente.setGeometry(QtCore.QRect(180, 20, 51, 19))
        self.lblCidadesCliente.setObjectName(_fromUtf8("lblCidadesCliente"))
        self.txtCepCliente = QtGui.QLineEdit(self.grbDadosOrigem)
        self.txtCepCliente.setEnabled(False)
        self.txtCepCliente.setGeometry(QtCore.QRect(10, 40, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepCliente.setPalette(palette)
        self.txtCepCliente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCepCliente.setInputMask(_fromUtf8("00000-000; "))
        self.txtCepCliente.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCepCliente.setObjectName(_fromUtf8("txtCepCliente"))
        self.grbDadosDestino = QtGui.QGroupBox(frmSaidaCaminhoaEmpresa)
        self.grbDadosDestino.setEnabled(False)
        self.grbDadosDestino.setGeometry(QtCore.QRect(20, 460, 871, 71))
        self.grbDadosDestino.setObjectName(_fromUtf8("grbDadosDestino"))
        self.txtSetor = QtGui.QComboBox(self.grbDadosDestino)
        self.txtSetor.setEnabled(False)
        self.txtSetor.setGeometry(QtCore.QRect(300, 40, 281, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtSetor.setPalette(palette)
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        self.lblSetor = QtGui.QLabel(self.grbDadosDestino)
        self.lblSetor.setGeometry(QtCore.QRect(300, 20, 46, 13))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        self.txtTipoAfazer = QtGui.QComboBox(self.grbDadosDestino)
        self.txtTipoAfazer.setEnabled(False)
        self.txtTipoAfazer.setGeometry(QtCore.QRect(10, 40, 281, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtTipoAfazer.setPalette(palette)
        self.txtTipoAfazer.setObjectName(_fromUtf8("txtTipoAfazer"))
        self.lblTipoAfazer = QtGui.QLabel(self.grbDadosDestino)
        self.lblTipoAfazer.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.lblTipoAfazer.setObjectName(_fromUtf8("lblTipoAfazer"))
        self.lblDataSaida.setBuddy(self.txtData)
        self.lblHoraSaida.setBuddy(self.txtHora)
        self.lblTipoCarga.setBuddy(self.txtTipoCarga)
        self.lblProduto.setBuddy(self.txtTipoCarga)
        self.lblMarcaMotorista.setBuddy(self.txtMarcaMotorista)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblModeloMotorista.setBuddy(self.txtModeloMotorista)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlacaMotorista.setBuddy(self.txtPlacaMotorista)
        self.lblEstadosCliente.setBuddy(self.txtEstadosCliente)
        self.lblCepCliente.setBuddy(self.txtCepCliente)
        self.lblCidadesCliente.setBuddy(self.txtCidadesCliente)

        self.retranslateUi(frmSaidaCaminhoaEmpresa)
        QtCore.QMetaObject.connectSlotsByName(frmSaidaCaminhoaEmpresa)

    def retranslateUi(self, frmSaidaCaminhoaEmpresa):
        frmSaidaCaminhoaEmpresa.setWindowTitle(_translate("frmSaidaCaminhoaEmpresa", "Saida Caminhões Empresa", None))
        self.grbBotoes.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Grupo de botões referente as suas funções", None))
        self.btnDeletar.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Botão de deleção de um registro existente", None))
        self.btnDeletar.setText(_translate("frmSaidaCaminhoaEmpresa", "Deletar", None))
        self.btnSalvar.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmSaidaCaminhoaEmpresa", "Salvar", None))
        self.btnNovo.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmSaidaCaminhoaEmpresa", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmSaidaCaminhoaEmpresa", "Cancelar", None))
        self.btnEditar.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Botão para salvar edição de um registro existente", None))
        self.btnEditar.setText(_translate("frmSaidaCaminhoaEmpresa", "Editar", None))
        self.grbTipoPesquisa.setTitle(_translate("frmSaidaCaminhoaEmpresa", "Tipo Pesquisa", None))
        self.radBtnNomeMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "Nome Motorista", None))
        self.radBtnMarcaVeiculo.setText(_translate("frmSaidaCaminhoaEmpresa", "Marca Veiculo", None))
        self.radBtnModeloVeiculo.setText(_translate("frmSaidaCaminhoaEmpresa", "Modelo Veiculo", None))
        self.radBtnPlaca.setText(_translate("frmSaidaCaminhoaEmpresa", "Placa", None))
        self.radBtnCidade.setText(_translate("frmSaidaCaminhoaEmpresa", "Cidade", None))
        self.radBtnTipoAfazer.setText(_translate("frmSaidaCaminhoaEmpresa", "Tipo de Afazer", None))
        self.lblPesquisa.setText(_translate("frmSaidaCaminhoaEmpresa", "Pesquisa", None))
        self.grbDadosExtra.setTitle(_translate("frmSaidaCaminhoaEmpresa", "Dados Extra", None))
        self.txtTipoCarga.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Tipo de Carga", None))
        self.lblDataSaida.setText(_translate("frmSaidaCaminhoaEmpresa", "Data Saida", None))
        self.lblHoraSaida.setText(_translate("frmSaidaCaminhoaEmpresa", "Hora Saida", None))
        self.txtHora.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Hora Entrada", None))
        self.txtProduto.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Tipo de Carga", None))
        self.txtData.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Data Entrada", None))
        self.lblTipoCarga.setText(_translate("frmSaidaCaminhoaEmpresa", "Tipo de Carga", None))
        self.lblProduto.setText(_translate("frmSaidaCaminhoaEmpresa", "Produto", None))
        self.grbDadosMotorista.setTitle(_translate("frmSaidaCaminhoaEmpresa", "Motorista", None))
        self.txtModeloMotorista.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Marca do Veiculo", None))
        self.txtModeloMotorista.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo de identicação do modelo do veiculo", None))
        self.lblMarcaMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "Marca", None))
        self.txtMarcaMotorista.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Marca do Veiculo", None))
        self.txtMarcaMotorista.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo do nome da marca do veiculo", None))
        self.txtNomeMotorista.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo do nome do Motorista", None))
        self.lblNomeMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "Nome Motorista", None))
        self.txtPlacaMotorista.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Placa do Veiculo", None))
        self.txtPlacaMotorista.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo de identificação da placa do veiculo", None))
        self.txtPlacaMotorista.setInputMask(_translate("frmSaidaCaminhoaEmpresa", "nnn-0000; ", None))
        self.txtPlacaMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "-", None))
        self.lblModeloMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Codigo Motorista", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo do Codigo de identificação do Motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "Codigo Motorista", None))
        self.lblPlacaMotorista.setText(_translate("frmSaidaCaminhoaEmpresa", "Placa", None))
        self.grbDadosOrigem.setTitle(_translate("frmSaidaCaminhoaEmpresa", "Dados Origem", None))
        self.lblEstadosCliente.setText(_translate("frmSaidaCaminhoaEmpresa", "Estado", None))
        self.txtEstadosCliente.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Estado Cliente", None))
        self.txtEstadosCliente.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo do nome do estado de localização do endereço", None))
        self.lblCepCliente.setText(_translate("frmSaidaCaminhoaEmpresa", "CEP", None))
        self.txtCidadesCliente.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "Cidade Cliente", None))
        self.txtCidadesCliente.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblCidadesCliente.setText(_translate("frmSaidaCaminhoaEmpresa", "Cidade", None))
        self.txtCepCliente.setToolTip(_translate("frmSaidaCaminhoaEmpresa", "CEP Cliente", None))
        self.txtCepCliente.setWhatsThis(_translate("frmSaidaCaminhoaEmpresa", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.grbDadosDestino.setTitle(_translate("frmSaidaCaminhoaEmpresa", "Dados Destino", None))
        self.lblSetor.setText(_translate("frmSaidaCaminhoaEmpresa", "Setor", None))
        self.lblTipoAfazer.setText(_translate("frmSaidaCaminhoaEmpresa", "Tipo de Afazer", None))

