# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCadastroFuncionario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmCadastroFuncionario(object):
    def setupUi(self, frmCadastroFuncionario):
        frmCadastroFuncionario.setObjectName(_fromUtf8("frmCadastroFuncionario"))
        frmCadastroFuncionario.resize(685, 653)
        font = QtGui.QFont()
        font.setPointSize(11)
        frmCadastroFuncionario.setFont(font)
        frmCadastroFuncionario.setModal(True)
        self.txtIdEmpresa = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtIdEmpresa.setEnabled(False)
        self.txtIdEmpresa.setGeometry(QtCore.QRect(12, 22, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresa.setPalette(palette)
        self.txtIdEmpresa.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdEmpresa.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdEmpresa.setMaxLength(11)
        self.txtIdEmpresa.setObjectName(_fromUtf8("txtIdEmpresa"))
        self.lblNomeFantasia = QtGui.QLabel(frmCadastroFuncionario)
        self.lblNomeFantasia.setGeometry(QtCore.QRect(162, 2, 101, 19))
        self.lblNomeFantasia.setObjectName(_fromUtf8("lblNomeFantasia"))
        self.lblRazaoSocial = QtGui.QLabel(frmCadastroFuncionario)
        self.lblRazaoSocial.setGeometry(QtCore.QRect(12, 47, 91, 19))
        self.lblRazaoSocial.setObjectName(_fromUtf8("lblRazaoSocial"))
        self.txtInscricaoEstadua = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtInscricaoEstadua.setEnabled(False)
        self.txtInscricaoEstadua.setGeometry(QtCore.QRect(12, 113, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstadua.setPalette(palette)
        self.txtInscricaoEstadua.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstadua.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtInscricaoEstadua.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstadua.setMaxLength(8)
        self.txtInscricaoEstadua.setObjectName(_fromUtf8("txtInscricaoEstadua"))
        self.lblInscricaoEstadual = QtGui.QLabel(frmCadastroFuncionario)
        self.lblInscricaoEstadual.setGeometry(QtCore.QRect(12, 93, 121, 19))
        self.lblInscricaoEstadual.setObjectName(_fromUtf8("lblInscricaoEstadual"))
        self.lblCodigoEmpresa = QtGui.QLabel(frmCadastroFuncionario)
        self.lblCodigoEmpresa.setGeometry(QtCore.QRect(12, 2, 111, 19))
        self.lblCodigoEmpresa.setObjectName(_fromUtf8("lblCodigoEmpresa"))
        self.lblCnpj = QtGui.QLabel(frmCadastroFuncionario)
        self.lblCnpj.setGeometry(QtCore.QRect(474, 47, 41, 19))
        self.lblCnpj.setObjectName(_fromUtf8("lblCnpj"))
        self.txtCnpj = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtCnpj.setEnabled(False)
        self.txtCnpj.setGeometry(QtCore.QRect(472, 67, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpj.setPalette(palette)
        self.txtCnpj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpj.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtCnpj.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpj.setText(_fromUtf8("../-"))
        self.txtCnpj.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpj.setObjectName(_fromUtf8("txtCnpj"))
        self.txtRazaoSocial = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtRazaoSocial.setEnabled(False)
        self.txtRazaoSocial.setGeometry(QtCore.QRect(12, 67, 451, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocial.setPalette(palette)
        self.txtRazaoSocial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocial.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtRazaoSocial.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocial.setMaxLength(70)
        self.txtRazaoSocial.setObjectName(_fromUtf8("txtRazaoSocial"))
        self.txtFantasia = QtGui.QLineEdit(frmCadastroFuncionario)
        self.txtFantasia.setGeometry(QtCore.QRect(162, 22, 471, 25))
        self.txtFantasia.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasia.setMaxLength(70)
        self.txtFantasia.setObjectName(_fromUtf8("txtFantasia"))
        self.btnPesquisar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnPesquisar.setGeometry(QtCore.QRect(644, 22, 31, 27))
        self.btnPesquisar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisar.setText(_fromUtf8(""))
        self.btnPesquisar.setObjectName(_fromUtf8("btnPesquisar"))
        self.grbFuncionario = QtGui.QGroupBox(frmCadastroFuncionario)
        self.grbFuncionario.setGeometry(QtCore.QRect(5, 164, 675, 391))
        self.grbFuncionario.setTitle(_fromUtf8(""))
        self.grbFuncionario.setObjectName(_fromUtf8("grbFuncionario"))
        self.lblNomeFuncionario = QtGui.QLabel(self.grbFuncionario)
        self.lblNomeFuncionario.setGeometry(QtCore.QRect(178, 6, 121, 19))
        self.lblNomeFuncionario.setObjectName(_fromUtf8("lblNomeFuncionario"))
        self.txtNomeMae = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomeMae.setGeometry(QtCore.QRect(8, 118, 321, 25))
        self.txtNomeMae.setMaxLength(70)
        self.txtNomeMae.setObjectName(_fromUtf8("txtNomeMae"))
        self.txtExpeditor = QtGui.QLineEdit(self.grbFuncionario)
        self.txtExpeditor.setGeometry(QtCore.QRect(216, 72, 113, 25))
        self.txtExpeditor.setMaxLength(5)
        self.txtExpeditor.setObjectName(_fromUtf8("txtExpeditor"))
        self.txtRg = QtGui.QLineEdit(self.grbFuncionario)
        self.txtRg.setGeometry(QtCore.QRect(6, 72, 201, 25))
        self.txtRg.setObjectName(_fromUtf8("txtRg"))
        self.lblDataNascimento = QtGui.QLabel(self.grbFuncionario)
        self.lblDataNascimento.setGeometry(QtCore.QRect(548, 52, 111, 19))
        self.lblDataNascimento.setObjectName(_fromUtf8("lblDataNascimento"))
        self.txtDataNascimento = QtGui.QDateEdit(self.grbFuncionario)
        self.txtDataNascimento.setGeometry(QtCore.QRect(548, 72, 119, 25))
        self.txtDataNascimento.setObjectName(_fromUtf8("txtDataNascimento"))
        self.lblCep = QtGui.QLabel(self.grbFuncionario)
        self.lblCep.setGeometry(QtCore.QRect(8, 236, 31, 19))
        self.lblCep.setObjectName(_fromUtf8("lblCep"))
        self.txtComplemento = QtGui.QLineEdit(self.grbFuncionario)
        self.txtComplemento.setGeometry(QtCore.QRect(8, 210, 291, 25))
        self.txtComplemento.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtComplemento.setMaxLength(50)
        self.txtComplemento.setObjectName(_fromUtf8("txtComplemento"))
        self.lblNomePai = QtGui.QLabel(self.grbFuncionario)
        self.lblNomePai.setGeometry(QtCore.QRect(338, 98, 71, 19))
        self.lblNomePai.setObjectName(_fromUtf8("lblNomePai"))
        self.txtCidades = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCidades.setEnabled(False)
        self.txtCidades.setGeometry(QtCore.QRect(168, 256, 341, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidades.setPalette(palette)
        self.txtCidades.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCidades.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCidades.setMaxLength(70)
        self.txtCidades.setObjectName(_fromUtf8("txtCidades"))
        self.lblCpf = QtGui.QLabel(self.grbFuncionario)
        self.lblCpf.setGeometry(QtCore.QRect(338, 52, 31, 19))
        self.lblCpf.setObjectName(_fromUtf8("lblCpf"))
        self.txtNomePai = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomePai.setGeometry(QtCore.QRect(338, 118, 329, 25))
        self.txtNomePai.setMaxLength(70)
        self.txtNomePai.setObjectName(_fromUtf8("txtNomePai"))
        self.txtEstados = QtGui.QLineEdit(self.grbFuncionario)
        self.txtEstados.setEnabled(False)
        self.txtEstados.setGeometry(QtCore.QRect(516, 256, 151, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstados.setPalette(palette)
        self.txtEstados.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtEstados.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhUppercaseOnly)
        self.txtEstados.setMaxLength(50)
        self.txtEstados.setObjectName(_fromUtf8("txtEstados"))
        self.txtEndereco = QtGui.QLineEdit(self.grbFuncionario)
        self.txtEndereco.setGeometry(QtCore.QRect(8, 164, 491, 25))
        self.txtEndereco.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtEndereco.setMaxLength(50)
        self.txtEndereco.setObjectName(_fromUtf8("txtEndereco"))
        self.lblExpeditor = QtGui.QLabel(self.grbFuncionario)
        self.lblExpeditor.setGeometry(QtCore.QRect(216, 52, 66, 19))
        self.lblExpeditor.setObjectName(_fromUtf8("lblExpeditor"))
        self.txtNumero = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNumero.setGeometry(QtCore.QRect(508, 164, 161, 25))
        self.txtNumero.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtNumero.setMaxLength(11)
        self.txtNumero.setObjectName(_fromUtf8("txtNumero"))
        self.lblRg = QtGui.QLabel(self.grbFuncionario)
        self.lblRg.setGeometry(QtCore.QRect(6, 52, 31, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))
        self.lblTelefoene = QtGui.QLabel(self.grbFuncionario)
        self.lblTelefoene.setGeometry(QtCore.QRect(8, 282, 61, 19))
        self.lblTelefoene.setObjectName(_fromUtf8("lblTelefoene"))
        self.txtBairro = QtGui.QLineEdit(self.grbFuncionario)
        self.txtBairro.setGeometry(QtCore.QRect(308, 210, 361, 25))
        self.txtBairro.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtBairro.setMaxLength(50)
        self.txtBairro.setObjectName(_fromUtf8("txtBairro"))
        self.txtCelular = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCelular.setGeometry(QtCore.QRect(208, 302, 191, 25))
        self.txtCelular.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCelular.setObjectName(_fromUtf8("txtCelular"))
        self.txtNomeFuncionario = QtGui.QLineEdit(self.grbFuncionario)
        self.txtNomeFuncionario.setGeometry(QtCore.QRect(178, 26, 488, 25))
        self.txtNomeFuncionario.setMaxLength(70)
        self.txtNomeFuncionario.setObjectName(_fromUtf8("txtNomeFuncionario"))
        self.lblComplemento = QtGui.QLabel(self.grbFuncionario)
        self.lblComplemento.setGeometry(QtCore.QRect(8, 190, 101, 16))
        self.lblComplemento.setObjectName(_fromUtf8("lblComplemento"))
        self.lblEstados = QtGui.QLabel(self.grbFuncionario)
        self.lblEstados.setGeometry(QtCore.QRect(518, 236, 51, 19))
        self.lblEstados.setObjectName(_fromUtf8("lblEstados"))
        self.txtCpf = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCpf.setGeometry(QtCore.QRect(338, 72, 201, 25))
        self.txtCpf.setObjectName(_fromUtf8("txtCpf"))
        self.lblBairro = QtGui.QLabel(self.grbFuncionario)
        self.lblBairro.setGeometry(QtCore.QRect(308, 190, 41, 19))
        self.lblBairro.setObjectName(_fromUtf8("lblBairro"))
        self.lblCerlular = QtGui.QLabel(self.grbFuncionario)
        self.lblCerlular.setGeometry(QtCore.QRect(208, 282, 61, 19))
        self.lblCerlular.setObjectName(_fromUtf8("lblCerlular"))
        self.lblNumero = QtGui.QLabel(self.grbFuncionario)
        self.lblNumero.setGeometry(QtCore.QRect(508, 144, 51, 19))
        self.lblNumero.setObjectName(_fromUtf8("lblNumero"))
        self.lblCidades = QtGui.QLabel(self.grbFuncionario)
        self.lblCidades.setGeometry(QtCore.QRect(168, 236, 51, 19))
        self.lblCidades.setObjectName(_fromUtf8("lblCidades"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbFuncionario)
        self.txtidFuncionario.setEnabled(False)
        self.txtidFuncionario.setGeometry(QtCore.QRect(6, 26, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidFuncionario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoFuncionario = QtGui.QLabel(self.grbFuncionario)
        self.lblCodigoFuncionario.setGeometry(QtCore.QRect(6, 6, 121, 19))
        self.lblCodigoFuncionario.setObjectName(_fromUtf8("lblCodigoFuncionario"))
        self.lblEndereco = QtGui.QLabel(self.grbFuncionario)
        self.lblEndereco.setGeometry(QtCore.QRect(8, 144, 66, 19))
        self.lblEndereco.setObjectName(_fromUtf8("lblEndereco"))
        self.txtCep = QtGui.QLineEdit(self.grbFuncionario)
        self.txtCep.setGeometry(QtCore.QRect(8, 256, 151, 25))
        self.txtCep.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCep.setInputMask(_fromUtf8("00000-000; "))
        self.txtCep.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCep.setObjectName(_fromUtf8("txtCep"))
        self.lblNomeMae = QtGui.QLabel(self.grbFuncionario)
        self.lblNomeMae.setGeometry(QtCore.QRect(8, 98, 81, 19))
        self.lblNomeMae.setObjectName(_fromUtf8("lblNomeMae"))
        self.txtTelefone = QtGui.QLineEdit(self.grbFuncionario)
        self.txtTelefone.setGeometry(QtCore.QRect(8, 302, 191, 25))
        self.txtTelefone.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtTelefone.setObjectName(_fromUtf8("txtTelefone"))
        self.txtSetor = QtGui.QComboBox(self.grbFuncionario)
        self.txtSetor.setGeometry(QtCore.QRect(10, 350, 231, 25))
        self.txtSetor.setObjectName(_fromUtf8("txtSetor"))
        self.txtCargo = QtGui.QComboBox(self.grbFuncionario)
        self.txtCargo.setGeometry(QtCore.QRect(250, 350, 231, 25))
        self.txtCargo.setObjectName(_fromUtf8("txtCargo"))
        self.lblSetor = QtGui.QLabel(self.grbFuncionario)
        self.lblSetor.setGeometry(QtCore.QRect(10, 330, 66, 19))
        self.lblSetor.setObjectName(_fromUtf8("lblSetor"))
        self.lblCargo = QtGui.QLabel(self.grbFuncionario)
        self.lblCargo.setGeometry(QtCore.QRect(250, 330, 66, 19))
        self.lblCargo.setObjectName(_fromUtf8("lblCargo"))
        self.btnCadSetoresCancelar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadSetoresCancelar.setGeometry(QtCore.QRect(480, 570, 81, 61))
        self.btnCadSetoresCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresCancelar.setObjectName(_fromUtf8("btnCadSetoresCancelar"))
        self.btnCadSetoresEditar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadSetoresEditar.setGeometry(QtCore.QRect(380, 570, 81, 61))
        self.btnCadSetoresEditar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresEditar.setObjectName(_fromUtf8("btnCadSetoresEditar"))
        self.btnCadSetoresDeletar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadSetoresDeletar.setGeometry(QtCore.QRect(580, 570, 81, 61))
        self.btnCadSetoresDeletar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresDeletar.setObjectName(_fromUtf8("btnCadSetoresDeletar"))
        self.btnCadSetoresSalvar = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadSetoresSalvar.setGeometry(QtCore.QRect(280, 570, 81, 61))
        self.btnCadSetoresSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresSalvar.setObjectName(_fromUtf8("btnCadSetoresSalvar"))
        self.btnCadSetoresNovo = QtGui.QPushButton(frmCadastroFuncionario)
        self.btnCadSetoresNovo.setGeometry(QtCore.QRect(180, 570, 81, 61))
        self.btnCadSetoresNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCadSetoresNovo.setObjectName(_fromUtf8("btnCadSetoresNovo"))
        self.lblNomeFantasia.setBuddy(self.txtFantasia)
        self.lblRazaoSocial.setBuddy(self.txtRazaoSocial)
        self.lblInscricaoEstadual.setBuddy(self.txtInscricaoEstadua)
        self.lblCodigoEmpresa.setBuddy(self.txtIdEmpresa)
        self.lblCnpj.setBuddy(self.txtCnpj)
        self.lblNomeFuncionario.setBuddy(self.txtNomeFuncionario)
        self.lblDataNascimento.setBuddy(self.txtDataNascimento)
        self.lblCep.setBuddy(self.txtCep)
        self.lblNomePai.setBuddy(self.txtNomePai)
        self.lblCpf.setBuddy(self.txtCpf)
        self.lblExpeditor.setBuddy(self.txtExpeditor)
        self.lblRg.setBuddy(self.txtRg)
        self.lblTelefoene.setBuddy(self.txtTelefone)
        self.lblComplemento.setBuddy(self.txtComplemento)
        self.lblEstados.setBuddy(self.txtEstados)
        self.lblBairro.setBuddy(self.txtBairro)
        self.lblCerlular.setBuddy(self.txtCelular)
        self.lblNumero.setBuddy(self.txtNumero)
        self.lblCidades.setBuddy(self.txtCidades)
        self.lblCodigoFuncionario.setBuddy(self.txtidFuncionario)
        self.lblEndereco.setBuddy(self.txtEndereco)
        self.lblNomeMae.setBuddy(self.txtNomeMae)
        self.lblSetor.setBuddy(self.txtSetor)
        self.lblCargo.setBuddy(self.txtCargo)

        self.retranslateUi(frmCadastroFuncionario)
        QtCore.QMetaObject.connectSlotsByName(frmCadastroFuncionario)
        frmCadastroFuncionario.setTabOrder(self.txtIdEmpresa, self.txtFantasia)
        frmCadastroFuncionario.setTabOrder(self.txtFantasia, self.txtNomeFuncionario)
        frmCadastroFuncionario.setTabOrder(self.txtNomeFuncionario, self.txtRg)
        frmCadastroFuncionario.setTabOrder(self.txtRg, self.txtExpeditor)
        frmCadastroFuncionario.setTabOrder(self.txtExpeditor, self.txtCpf)
        frmCadastroFuncionario.setTabOrder(self.txtCpf, self.txtDataNascimento)
        frmCadastroFuncionario.setTabOrder(self.txtDataNascimento, self.txtNomeMae)
        frmCadastroFuncionario.setTabOrder(self.txtNomeMae, self.txtNomePai)
        frmCadastroFuncionario.setTabOrder(self.txtNomePai, self.txtEndereco)
        frmCadastroFuncionario.setTabOrder(self.txtEndereco, self.txtNumero)
        frmCadastroFuncionario.setTabOrder(self.txtNumero, self.txtComplemento)
        frmCadastroFuncionario.setTabOrder(self.txtComplemento, self.txtBairro)
        frmCadastroFuncionario.setTabOrder(self.txtBairro, self.txtCep)
        frmCadastroFuncionario.setTabOrder(self.txtCep, self.txtCidades)
        frmCadastroFuncionario.setTabOrder(self.txtCidades, self.txtEstados)
        frmCadastroFuncionario.setTabOrder(self.txtEstados, self.txtTelefone)
        frmCadastroFuncionario.setTabOrder(self.txtTelefone, self.txtCelular)
        frmCadastroFuncionario.setTabOrder(self.txtCelular, self.txtSetor)
        frmCadastroFuncionario.setTabOrder(self.txtSetor, self.txtCargo)
        frmCadastroFuncionario.setTabOrder(self.txtCargo, self.btnCadSetoresNovo)
        frmCadastroFuncionario.setTabOrder(self.btnCadSetoresNovo, self.btnCadSetoresSalvar)
        frmCadastroFuncionario.setTabOrder(self.btnCadSetoresSalvar, self.btnCadSetoresEditar)
        frmCadastroFuncionario.setTabOrder(self.btnCadSetoresEditar, self.btnCadSetoresCancelar)
        frmCadastroFuncionario.setTabOrder(self.btnCadSetoresCancelar, self.btnCadSetoresDeletar)

    def retranslateUi(self, frmCadastroFuncionario):
        frmCadastroFuncionario.setWindowTitle(_translate("frmCadastroFuncionario", "Cadastro de Funcionario", None))
        self.txtIdEmpresa.setToolTip(_translate("frmCadastroFuncionario", "Codigo", None))
        self.txtIdEmpresa.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do codigo de identificação da empresa", None))
        self.lblNomeFantasia.setText(_translate("frmCadastroFuncionario", "Nome Fantasia", None))
        self.lblRazaoSocial.setText(_translate("frmCadastroFuncionario", "Razão Social", None))
        self.txtInscricaoEstadua.setToolTip(_translate("frmCadastroFuncionario", "Inscrição Estadual", None))
        self.txtInscricaoEstadua.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do inscrição estadual da empresa", None))
        self.lblInscricaoEstadual.setText(_translate("frmCadastroFuncionario", "Incrição Estadual", None))
        self.lblCodigoEmpresa.setText(_translate("frmCadastroFuncionario", "Codigo Empresa", None))
        self.lblCnpj.setText(_translate("frmCadastroFuncionario", "CNPJ", None))
        self.txtCnpj.setToolTip(_translate("frmCadastroFuncionario", "CNPJ", None))
        self.txtCnpj.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do CNPJ da empresa", None))
        self.txtCnpj.setInputMask(_translate("frmCadastroFuncionario", "00.000.000/0000-00; ", None))
        self.txtRazaoSocial.setToolTip(_translate("frmCadastroFuncionario", "Razão Social", None))
        self.txtRazaoSocial.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da razão social da empresa", None))
        self.txtFantasia.setToolTip(_translate("frmCadastroFuncionario", "Nome Fantasia", None))
        self.txtFantasia.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome fantasia da empresa", None))
        self.lblNomeFuncionario.setText(_translate("frmCadastroFuncionario", "Nome Funcionario", None))
        self.txtNomeMae.setToolTip(_translate("frmCadastroFuncionario", "Nome Mãe", None))
        self.txtNomeMae.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da mãe do funcionario", None))
        self.txtExpeditor.setToolTip(_translate("frmCadastroFuncionario", "Expeditor", None))
        self.txtExpeditor.setWhatsThis(_translate("frmCadastroFuncionario", "<html><head/><body><p>Campo do orgão expeditor do RG</p></body></html>", None))
        self.txtRg.setToolTip(_translate("frmCadastroFuncionario", "Rg", None))
        self.txtRg.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do RG do funcionario", None))
        self.txtRg.setInputMask(_translate("frmCadastroFuncionario", "000000-0; ", None))
        self.lblDataNascimento.setText(_translate("frmCadastroFuncionario", "Data Nascimento", None))
        self.txtDataNascimento.setToolTip(_translate("frmCadastroFuncionario", "Data Nascimento", None))
        self.txtDataNascimento.setWhatsThis(_translate("frmCadastroFuncionario", "Campo da data de nacimento do funcionario", None))
        self.lblCep.setText(_translate("frmCadastroFuncionario", "CEP", None))
        self.txtComplemento.setToolTip(_translate("frmCadastroFuncionario", "Complemento", None))
        self.txtComplemento.setWhatsThis(_translate("frmCadastroFuncionario", "Campo complementar do endereço", None))
        self.lblNomePai.setText(_translate("frmCadastroFuncionario", "Nome Pai", None))
        self.txtCidades.setToolTip(_translate("frmCadastroFuncionario", "Cidade", None))
        self.txtCidades.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome da cidade referente a localização do endereço dentro do estado", None))
        self.lblCpf.setText(_translate("frmCadastroFuncionario", "CPF", None))
        self.txtNomePai.setToolTip(_translate("frmCadastroFuncionario", "Nome Pai", None))
        self.txtNomePai.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do pai do funcionario", None))
        self.txtEstados.setToolTip(_translate("frmCadastroFuncionario", "Estado", None))
        self.txtEstados.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do estado de localização do endereço", None))
        self.txtEndereco.setToolTip(_translate("frmCadastroFuncionario", "Endereço", None))
        self.txtEndereco.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de descrição do endereço", None))
        self.lblExpeditor.setText(_translate("frmCadastroFuncionario", "Expeditor", None))
        self.txtNumero.setToolTip(_translate("frmCadastroFuncionario", "Numero", None))
        self.txtNumero.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de numero referente ao numero do endereço", None))
        self.lblRg.setText(_translate("frmCadastroFuncionario", "RG", None))
        self.lblTelefoene.setText(_translate("frmCadastroFuncionario", "Telefone", None))
        self.txtBairro.setToolTip(_translate("frmCadastroFuncionario", "Bairro", None))
        self.txtBairro.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do bairro referente ao endereço", None))
        self.txtCelular.setToolTip(_translate("frmCadastroFuncionario", "Celular", None))
        self.txtCelular.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero de cantato de celular do funcionario", None))
        self.txtCelular.setInputMask(_translate("frmCadastroFuncionario", "(00) 00000-0000; ", None))
        self.txtNomeFuncionario.setToolTip(_translate("frmCadastroFuncionario", "Nome Funcionario", None))
        self.txtNomeFuncionario.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do nome do funcionario", None))
        self.lblComplemento.setText(_translate("frmCadastroFuncionario", "Complemento", None))
        self.lblEstados.setText(_translate("frmCadastroFuncionario", "Estado", None))
        self.txtCpf.setToolTip(_translate("frmCadastroFuncionario", "CPF", None))
        self.txtCpf.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero do CPF do funcionario", None))
        self.txtCpf.setInputMask(_translate("frmCadastroFuncionario", "000.000.000-00; ", None))
        self.lblBairro.setText(_translate("frmCadastroFuncionario", "Bairro", None))
        self.lblCerlular.setText(_translate("frmCadastroFuncionario", "Celular", None))
        self.lblNumero.setText(_translate("frmCadastroFuncionario", "Numero", None))
        self.lblCidades.setText(_translate("frmCadastroFuncionario", "Cidade", None))
        self.txtidFuncionario.setToolTip(_translate("frmCadastroFuncionario", "Codigo Funcionario", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do Codigo de identificação do Funcionario", None))
        self.lblCodigoFuncionario.setText(_translate("frmCadastroFuncionario", "Codigo Funcionario", None))
        self.lblEndereco.setText(_translate("frmCadastroFuncionario", "Endereço", None))
        self.txtCep.setToolTip(_translate("frmCadastroFuncionario", "CEP", None))
        self.txtCep.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de CEP referente a identificação da cidade e qual estado pertence", None))
        self.lblNomeMae.setText(_translate("frmCadastroFuncionario", "Nome Mãe", None))
        self.txtTelefone.setToolTip(_translate("frmCadastroFuncionario", "Telefone", None))
        self.txtTelefone.setWhatsThis(_translate("frmCadastroFuncionario", "Campo do numero de cantato de telefone da funcionario", None))
        self.txtTelefone.setInputMask(_translate("frmCadastroFuncionario", "(00) 0000-0000; ", None))
        self.txtSetor.setToolTip(_translate("frmCadastroFuncionario", "Setor", None))
        self.txtSetor.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de escolha do setor de trabalho do funcionario", None))
        self.txtCargo.setToolTip(_translate("frmCadastroFuncionario", "Cargo", None))
        self.txtCargo.setWhatsThis(_translate("frmCadastroFuncionario", "Campo de escolha do cargo de trabalho do funcionario", None))
        self.lblSetor.setText(_translate("frmCadastroFuncionario", "Setor", None))
        self.lblCargo.setText(_translate("frmCadastroFuncionario", "Cargo", None))
        self.btnCadSetoresCancelar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão de cancelar a operação iniciada", None))
        self.btnCadSetoresCancelar.setText(_translate("frmCadastroFuncionario", "Cancelar", None))
        self.btnCadSetoresEditar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão para salvar edição de um registro existente", None))
        self.btnCadSetoresEditar.setText(_translate("frmCadastroFuncionario", "Editar", None))
        self.btnCadSetoresDeletar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão de deleção de um registro existente", None))
        self.btnCadSetoresDeletar.setText(_translate("frmCadastroFuncionario", "Deletar", None))
        self.btnCadSetoresSalvar.setWhatsThis(_translate("frmCadastroFuncionario", "Botão para salvar um novo registro", None))
        self.btnCadSetoresSalvar.setText(_translate("frmCadastroFuncionario", "Salvar", None))
        self.btnCadSetoresNovo.setWhatsThis(_translate("frmCadastroFuncionario", "Botão de Criação de um novo registro", None))
        self.btnCadSetoresNovo.setText(_translate("frmCadastroFuncionario", "Novo", None))

