# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaNotas.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaNota(object):
    def setupUi(self, frmEntradaNota):
        frmEntradaNota.setObjectName(_fromUtf8("frmEntradaNota"))
        frmEntradaNota.resize(1005, 689)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmEntradaNota.setFont(font)
        self.grbDadosEmitente = QtGui.QGroupBox(frmEntradaNota)
        self.grbDadosEmitente.setGeometry(QtCore.QRect(6, -1, 991, 205))
        self.grbDadosEmitente.setObjectName(_fromUtf8("grbDadosEmitente"))
        self.txtIdEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtIdEmitente.setGeometry(QtCore.QRect(14, 35, 181, 25))
        self.txtIdEmitente.setMaxLength(11)
        self.txtIdEmitente.setObjectName(_fromUtf8("txtIdEmitente"))
        self.txtNomeEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtNomeEmitente.setGeometry(QtCore.QRect(207, 35, 461, 25))
        self.txtNomeEmitente.setMaxLength(70)
        self.txtNomeEmitente.setObjectName(_fromUtf8("txtNomeEmitente"))
        self.btnPesquisarEmitente = QtGui.QPushButton(self.grbDadosEmitente)
        self.btnPesquisarEmitente.setGeometry(QtCore.QRect(685, 35, 31, 25))
        self.btnPesquisarEmitente.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarEmitente.setText(_fromUtf8(""))
        self.btnPesquisarEmitente.setObjectName(_fromUtf8("btnPesquisarEmitente"))
        self.lblCodigoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCodigoEmitente.setGeometry(QtCore.QRect(14, 15, 131, 21))
        self.lblCodigoEmitente.setObjectName(_fromUtf8("lblCodigoEmitente"))
        self.lblNomeEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblNomeEmitente.setGeometry(QtCore.QRect(207, 15, 161, 16))
        self.lblNomeEmitente.setObjectName(_fromUtf8("lblNomeEmitente"))
        self.txtEnderecoEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtEnderecoEmitente.setEnabled(False)
        self.txtEnderecoEmitente.setGeometry(QtCore.QRect(700, 80, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoEmitente.setPalette(palette)
        self.txtEnderecoEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtEnderecoEmitente.setMaxLength(50)
        self.txtEnderecoEmitente.setObjectName(_fromUtf8("txtEnderecoEmitente"))
        self.txtNumeroEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtNumeroEmitente.setEnabled(False)
        self.txtNumeroEmitente.setGeometry(QtCore.QRect(14, 126, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroEmitente.setPalette(palette)
        self.txtNumeroEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtNumeroEmitente.setMaxLength(11)
        self.txtNumeroEmitente.setObjectName(_fromUtf8("txtNumeroEmitente"))
        self.txtComplementoEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtComplementoEmitente.setEnabled(False)
        self.txtComplementoEmitente.setGeometry(QtCore.QRect(165, 126, 239, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoEmitente.setPalette(palette)
        self.txtComplementoEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtComplementoEmitente.setMaxLength(50)
        self.txtComplementoEmitente.setObjectName(_fromUtf8("txtComplementoEmitente"))
        self.txtCidadeEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCidadeEmitente.setEnabled(False)
        self.txtCidadeEmitente.setGeometry(QtCore.QRect(700, 126, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadeEmitente.setPalette(palette)
        self.txtCidadeEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCidadeEmitente.setMaxLength(70)
        self.txtCidadeEmitente.setObjectName(_fromUtf8("txtCidadeEmitente"))
        self.txtEstadoEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtEstadoEmitente.setEnabled(False)
        self.txtEstadoEmitente.setGeometry(QtCore.QRect(14, 172, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadoEmitente.setPalette(palette)
        self.txtEstadoEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtEstadoEmitente.setMaxLength(50)
        self.txtEstadoEmitente.setObjectName(_fromUtf8("txtEstadoEmitente"))
        self.txtCepEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCepEmitente.setEnabled(False)
        self.txtCepEmitente.setGeometry(QtCore.QRect(204, 172, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepEmitente.setPalette(palette)
        self.txtCepEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCepEmitente.setObjectName(_fromUtf8("txtCepEmitente"))
        self.txtBairroEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtBairroEmitente.setEnabled(False)
        self.txtBairroEmitente.setGeometry(QtCore.QRect(410, 126, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroEmitente.setPalette(palette)
        self.txtBairroEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtBairroEmitente.setMaxLength(50)
        self.txtBairroEmitente.setObjectName(_fromUtf8("txtBairroEmitente"))
        self.lblEnderecoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblEnderecoEmitente.setGeometry(QtCore.QRect(700, 60, 61, 16))
        self.lblEnderecoEmitente.setObjectName(_fromUtf8("lblEnderecoEmitente"))
        self.lblNumeroEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblNumeroEmitente.setGeometry(QtCore.QRect(14, 106, 61, 16))
        self.lblNumeroEmitente.setObjectName(_fromUtf8("lblNumeroEmitente"))
        self.lblComplementoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblComplementoEmitente.setGeometry(QtCore.QRect(165, 106, 91, 16))
        self.lblComplementoEmitente.setObjectName(_fromUtf8("lblComplementoEmitente"))
        self.lblBairroEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblBairroEmitente.setGeometry(QtCore.QRect(410, 106, 61, 16))
        self.lblBairroEmitente.setObjectName(_fromUtf8("lblBairroEmitente"))
        self.lblCidadeEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCidadeEmitente.setGeometry(QtCore.QRect(700, 106, 61, 16))
        self.lblCidadeEmitente.setObjectName(_fromUtf8("lblCidadeEmitente"))
        self.lblEstadoEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblEstadoEmitente.setGeometry(QtCore.QRect(14, 152, 61, 16))
        self.lblEstadoEmitente.setObjectName(_fromUtf8("lblEstadoEmitente"))
        self.lblCepEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCepEmitente.setGeometry(QtCore.QRect(204, 152, 61, 16))
        self.lblCepEmitente.setObjectName(_fromUtf8("lblCepEmitente"))
        self.txtInscricaoEstaduaEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtInscricaoEstaduaEmitente.setEnabled(False)
        self.txtInscricaoEstaduaEmitente.setGeometry(QtCore.QRect(518, 80, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmitente.setPalette(palette)
        self.txtInscricaoEstaduaEmitente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstaduaEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtInscricaoEstaduaEmitente.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmitente.setMaxLength(8)
        self.txtInscricaoEstaduaEmitente.setObjectName(_fromUtf8("txtInscricaoEstaduaEmitente"))
        self.txtRazaoSocialEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtRazaoSocialEmitente.setEnabled(False)
        self.txtRazaoSocialEmitente.setGeometry(QtCore.QRect(13, 80, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmitente.setPalette(palette)
        self.txtRazaoSocialEmitente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocialEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRazaoSocialEmitente.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmitente.setMaxLength(70)
        self.txtRazaoSocialEmitente.setObjectName(_fromUtf8("txtRazaoSocialEmitente"))
        self.lblRazaoSocialEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblRazaoSocialEmitente.setGeometry(QtCore.QRect(13, 60, 81, 19))
        self.lblRazaoSocialEmitente.setObjectName(_fromUtf8("lblRazaoSocialEmitente"))
        self.lblCnpjEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblCnpjEmitente.setGeometry(QtCore.QRect(330, 60, 41, 19))
        self.lblCnpjEmitente.setObjectName(_fromUtf8("lblCnpjEmitente"))
        self.lblInscricaoEstadualEmitente = QtGui.QLabel(self.grbDadosEmitente)
        self.lblInscricaoEstadualEmitente.setGeometry(QtCore.QRect(518, 60, 121, 19))
        self.lblInscricaoEstadualEmitente.setObjectName(_fromUtf8("lblInscricaoEstadualEmitente"))
        self.txtCnpjEmitente = QtGui.QLineEdit(self.grbDadosEmitente)
        self.txtCnpjEmitente.setEnabled(False)
        self.txtCnpjEmitente.setGeometry(QtCore.QRect(330, 80, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmitente.setPalette(palette)
        self.txtCnpjEmitente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpjEmitente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCnpjEmitente.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmitente.setText(_fromUtf8("../-"))
        self.txtCnpjEmitente.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmitente.setObjectName(_fromUtf8("txtCnpjEmitente"))
        self.grbDadosDestinatario = QtGui.QGroupBox(frmEntradaNota)
        self.grbDadosDestinatario.setGeometry(QtCore.QRect(6, 202, 991, 210))
        self.grbDadosDestinatario.setObjectName(_fromUtf8("grbDadosDestinatario"))
        self.txtCnpjDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCnpjDestinatario.setEnabled(False)
        self.txtCnpjDestinatario.setGeometry(QtCore.QRect(330, 85, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjDestinatario.setPalette(palette)
        self.txtCnpjDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtCnpjDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCnpjDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjDestinatario.setObjectName(_fromUtf8("txtCnpjDestinatario"))
        self.lblCodigoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCodigoDestinatario.setGeometry(QtCore.QRect(13, 20, 151, 19))
        self.lblCodigoDestinatario.setObjectName(_fromUtf8("lblCodigoDestinatario"))
        self.lblNomeFantasiaDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblNomeFantasiaDestinatario.setGeometry(QtCore.QRect(210, 20, 181, 19))
        self.lblNomeFantasiaDestinatario.setObjectName(_fromUtf8("lblNomeFantasiaDestinatario"))
        self.lblCnpjDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCnpjDestinatario.setGeometry(QtCore.QRect(330, 65, 41, 19))
        self.lblCnpjDestinatario.setObjectName(_fromUtf8("lblCnpjDestinatario"))
        self.txtFantasiaDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtFantasiaDestinatario.setGeometry(QtCore.QRect(210, 40, 461, 25))
        self.txtFantasiaDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtFantasiaDestinatario.setMaxLength(70)
        self.txtFantasiaDestinatario.setObjectName(_fromUtf8("txtFantasiaDestinatario"))
        self.txtRazaoSocialDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtRazaoSocialDestinatario.setEnabled(False)
        self.txtRazaoSocialDestinatario.setGeometry(QtCore.QRect(13, 85, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialDestinatario.setPalette(palette)
        self.txtRazaoSocialDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtRazaoSocialDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRazaoSocialDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialDestinatario.setMaxLength(70)
        self.txtRazaoSocialDestinatario.setObjectName(_fromUtf8("txtRazaoSocialDestinatario"))
        self.lblRazaoSocialDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblRazaoSocialDestinatario.setGeometry(QtCore.QRect(13, 65, 81, 19))
        self.lblRazaoSocialDestinatario.setObjectName(_fromUtf8("lblRazaoSocialDestinatario"))
        self.txtIdDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtIdDestinatario.setEnabled(True)
        self.txtIdDestinatario.setGeometry(QtCore.QRect(13, 40, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdDestinatario.setPalette(palette)
        self.txtIdDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtIdDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtIdDestinatario.setMaxLength(11)
        self.txtIdDestinatario.setObjectName(_fromUtf8("txtIdDestinatario"))
        self.txtInscricaoEstaduaDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtInscricaoEstaduaDestinatario.setEnabled(False)
        self.txtInscricaoEstaduaDestinatario.setGeometry(QtCore.QRect(518, 85, 178, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaDestinatario.setPalette(palette)
        self.txtInscricaoEstaduaDestinatario.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtInscricaoEstaduaDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtInscricaoEstaduaDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaDestinatario"))
        self.lblInscricaoEstadualDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblInscricaoEstadualDestinatario.setGeometry(QtCore.QRect(518, 65, 121, 19))
        self.lblInscricaoEstadualDestinatario.setObjectName(_fromUtf8("lblInscricaoEstadualDestinatario"))
        self.btnPesquisarDestinatario = QtGui.QPushButton(self.grbDadosDestinatario)
        self.btnPesquisarDestinatario.setGeometry(QtCore.QRect(690, 40, 31, 27))
        self.btnPesquisarDestinatario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarDestinatario.setText(_fromUtf8(""))
        self.btnPesquisarDestinatario.setObjectName(_fromUtf8("btnPesquisarDestinatario"))
        self.lblCepDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCepDestinatario.setGeometry(QtCore.QRect(205, 157, 61, 16))
        self.lblCepDestinatario.setObjectName(_fromUtf8("lblCepDestinatario"))
        self.lblComplementoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblComplementoDestinatario.setGeometry(QtCore.QRect(165, 111, 91, 16))
        self.lblComplementoDestinatario.setObjectName(_fromUtf8("lblComplementoDestinatario"))
        self.txtComplementoDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtComplementoDestinatario.setEnabled(False)
        self.txtComplementoDestinatario.setGeometry(QtCore.QRect(165, 131, 239, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoDestinatario.setPalette(palette)
        self.txtComplementoDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtComplementoDestinatario.setMaxLength(50)
        self.txtComplementoDestinatario.setObjectName(_fromUtf8("txtComplementoDestinatario"))
        self.lblCidadeDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblCidadeDestinatario.setGeometry(QtCore.QRect(700, 111, 61, 16))
        self.lblCidadeDestinatario.setObjectName(_fromUtf8("lblCidadeDestinatario"))
        self.txtEnderecoDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtEnderecoDestinatario.setEnabled(False)
        self.txtEnderecoDestinatario.setGeometry(QtCore.QRect(700, 85, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoDestinatario.setPalette(palette)
        self.txtEnderecoDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtEnderecoDestinatario.setMaxLength(50)
        self.txtEnderecoDestinatario.setObjectName(_fromUtf8("txtEnderecoDestinatario"))
        self.txtNumeroDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtNumeroDestinatario.setEnabled(False)
        self.txtNumeroDestinatario.setGeometry(QtCore.QRect(14, 131, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroDestinatario.setPalette(palette)
        self.txtNumeroDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtNumeroDestinatario.setMaxLength(11)
        self.txtNumeroDestinatario.setObjectName(_fromUtf8("txtNumeroDestinatario"))
        self.lblEnderecoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblEnderecoDestinatario.setGeometry(QtCore.QRect(700, 65, 61, 16))
        self.lblEnderecoDestinatario.setObjectName(_fromUtf8("lblEnderecoDestinatario"))
        self.txtBairroDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtBairroDestinatario.setEnabled(False)
        self.txtBairroDestinatario.setGeometry(QtCore.QRect(407, 131, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroDestinatario.setPalette(palette)
        self.txtBairroDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtBairroDestinatario.setMaxLength(50)
        self.txtBairroDestinatario.setObjectName(_fromUtf8("txtBairroDestinatario"))
        self.txtCidadeDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCidadeDestinatario.setEnabled(False)
        self.txtCidadeDestinatario.setGeometry(QtCore.QRect(700, 131, 281, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadeDestinatario.setPalette(palette)
        self.txtCidadeDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCidadeDestinatario.setMaxLength(70)
        self.txtCidadeDestinatario.setObjectName(_fromUtf8("txtCidadeDestinatario"))
        self.lblNumeroDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblNumeroDestinatario.setGeometry(QtCore.QRect(14, 111, 61, 16))
        self.lblNumeroDestinatario.setObjectName(_fromUtf8("lblNumeroDestinatario"))
        self.txtEstadoDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtEstadoDestinatario.setEnabled(False)
        self.txtEstadoDestinatario.setGeometry(QtCore.QRect(15, 177, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadoDestinatario.setPalette(palette)
        self.txtEstadoDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtEstadoDestinatario.setMaxLength(50)
        self.txtEstadoDestinatario.setObjectName(_fromUtf8("txtEstadoDestinatario"))
        self.txtCepDestinatario = QtGui.QLineEdit(self.grbDadosDestinatario)
        self.txtCepDestinatario.setEnabled(False)
        self.txtCepDestinatario.setGeometry(QtCore.QRect(205, 177, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepDestinatario.setPalette(palette)
        self.txtCepDestinatario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCepDestinatario.setObjectName(_fromUtf8("txtCepDestinatario"))
        self.lblBairroDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblBairroDestinatario.setGeometry(QtCore.QRect(407, 111, 61, 16))
        self.lblBairroDestinatario.setObjectName(_fromUtf8("lblBairroDestinatario"))
        self.lblEstadoDestinatario = QtGui.QLabel(self.grbDadosDestinatario)
        self.lblEstadoDestinatario.setGeometry(QtCore.QRect(15, 157, 61, 16))
        self.lblEstadoDestinatario.setObjectName(_fromUtf8("lblEstadoDestinatario"))
        self.grbBotoes = QtGui.QGroupBox(frmEntradaNota)
        self.grbBotoes.setGeometry(QtCore.QRect(8, 605, 991, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(670, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setGeometry(QtCore.QRect(870, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setGeometry(QtCore.QRect(770, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.grbDadosNotaFiscal = QtGui.QGroupBox(frmEntradaNota)
        self.grbDadosNotaFiscal.setGeometry(QtCore.QRect(6, 410, 541, 71))
        self.grbDadosNotaFiscal.setObjectName(_fromUtf8("grbDadosNotaFiscal"))
        self.lblTipoProdutoEmitente = QtGui.QLabel(self.grbDadosNotaFiscal)
        self.lblTipoProdutoEmitente.setGeometry(QtCore.QRect(200, 20, 111, 16))
        self.lblTipoProdutoEmitente.setObjectName(_fromUtf8("lblTipoProdutoEmitente"))
        self.txtTipoProduto = QtGui.QComboBox(self.grbDadosNotaFiscal)
        self.txtTipoProduto.setGeometry(QtCore.QRect(200, 40, 211, 25))
        self.txtTipoProduto.setObjectName(_fromUtf8("txtTipoProduto"))
        self.lblNumeroNotaFiscal = QtGui.QLabel(self.grbDadosNotaFiscal)
        self.lblNumeroNotaFiscal.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.lblNumeroNotaFiscal.setObjectName(_fromUtf8("lblNumeroNotaFiscal"))
        self.txtNumeroNotaFiscal = QtGui.QLineEdit(self.grbDadosNotaFiscal)
        self.txtNumeroNotaFiscal.setGeometry(QtCore.QRect(10, 40, 181, 25))
        self.txtNumeroNotaFiscal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtNumeroNotaFiscal.setMaxLength(11)
        self.txtNumeroNotaFiscal.setObjectName(_fromUtf8("txtNumeroNotaFiscal"))
        self.txtCertificada = QtGui.QCheckBox(self.grbDadosNotaFiscal)
        self.txtCertificada.setGeometry(QtCore.QRect(440, 40, 91, 17))
        self.txtCertificada.setToolTip(_fromUtf8(""))
        self.txtCertificada.setObjectName(_fromUtf8("txtCertificada"))
        self.grbDadosMotorista = QtGui.QGroupBox(frmEntradaNota)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(7, 480, 991, 121))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))
        self.txtidMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidMotorista.setGeometry(QtCore.QRect(10, 40, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidMotorista.setPalette(palette)
        self.txtidMotorista.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtidMotorista.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtidMotorista.setMaxLength(11)
        self.txtidMotorista.setObjectName(_fromUtf8("txtidMotorista"))
        self.txtCpf = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtCpf.setEnabled(False)
        self.txtCpf.setGeometry(QtCore.QRect(200, 86, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCpf.setPalette(palette)
        self.txtCpf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtCpf.setObjectName(_fromUtf8("txtCpf"))
        self.txtRg = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtRg.setEnabled(False)
        self.txtRg.setGeometry(QtCore.QRect(10, 86, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRg.setPalette(palette)
        self.txtRg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtRg.setObjectName(_fromUtf8("txtRg"))
        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(210, 20, 121, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(210, 40, 488, 25))
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))
        self.lblRg = QtGui.QLabel(self.grbDadosMotorista)
        self.lblRg.setGeometry(QtCore.QRect(10, 66, 31, 19))
        self.lblRg.setObjectName(_fromUtf8("lblRg"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 20, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblCpfMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCpfMotorista.setGeometry(QtCore.QRect(200, 66, 31, 19))
        self.lblCpfMotorista.setObjectName(_fromUtf8("lblCpfMotorista"))
        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(710, 40, 31, 27))
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        self.lblMarca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarca.setGeometry(QtCore.QRect(390, 67, 51, 19))
        self.lblMarca.setObjectName(_fromUtf8("lblMarca"))
        self.txtMarca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarca.setEnabled(False)
        self.txtMarca.setGeometry(QtCore.QRect(390, 87, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarca.setPalette(palette)
        self.txtMarca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtMarca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtMarca.setMaxLength(50)
        self.txtMarca.setObjectName(_fromUtf8("txtMarca"))
        self.lblModelo = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModelo.setGeometry(QtCore.QRect(600, 66, 51, 19))
        self.lblModelo.setObjectName(_fromUtf8("lblModelo"))
        self.txtModelo = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModelo.setEnabled(False)
        self.txtModelo.setGeometry(QtCore.QRect(600, 86, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModelo.setPalette(palette)
        self.txtModelo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtModelo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtModelo.setMaxLength(50)
        self.txtModelo.setObjectName(_fromUtf8("txtModelo"))
        self.lblPlaca = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlaca.setGeometry(QtCore.QRect(810, 66, 51, 19))
        self.lblPlaca.setObjectName(_fromUtf8("lblPlaca"))
        self.txtPlaca = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlaca.setEnabled(False)
        self.txtPlaca.setGeometry(QtCore.QRect(811, 86, 168, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlaca.setPalette(palette)
        self.txtPlaca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtPlaca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))
        self.grbDadosRomaneio = QtGui.QGroupBox(frmEntradaNota)
        self.grbDadosRomaneio.setGeometry(QtCore.QRect(560, 410, 438, 71))
        self.grbDadosRomaneio.setObjectName(_fromUtf8("grbDadosRomaneio"))
        self.txtNumeroRomaneio = QtGui.QLineEdit(self.grbDadosRomaneio)
        self.txtNumeroRomaneio.setGeometry(QtCore.QRect(10, 40, 201, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroRomaneio.setPalette(palette)
        self.txtNumeroRomaneio.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtNumeroRomaneio.setMaxLength(11)
        self.txtNumeroRomaneio.setObjectName(_fromUtf8("txtNumeroRomaneio"))
        self.lblNumeroRomaneio = QtGui.QLabel(self.grbDadosRomaneio)
        self.lblNumeroRomaneio.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.lblNumeroRomaneio.setObjectName(_fromUtf8("lblNumeroRomaneio"))
        self.txtMetragemMadeira = QtGui.QComboBox(self.grbDadosRomaneio)
        self.txtMetragemMadeira.setGeometry(QtCore.QRect(220, 40, 207, 25))
        self.txtMetragemMadeira.setObjectName(_fromUtf8("txtMetragemMadeira"))
        self.lblMetragemMadeira = QtGui.QLabel(self.grbDadosRomaneio)
        self.lblMetragemMadeira.setGeometry(QtCore.QRect(220, 20, 131, 16))
        self.lblMetragemMadeira.setObjectName(_fromUtf8("lblMetragemMadeira"))
        self.lblCodigoEmitente.setBuddy(self.txtIdEmitente)
        self.lblNomeEmitente.setBuddy(self.txtNomeEmitente)
        self.lblEnderecoEmitente.setBuddy(self.txtEnderecoEmitente)
        self.lblNumeroEmitente.setBuddy(self.txtNumeroEmitente)
        self.lblComplementoEmitente.setBuddy(self.txtComplementoEmitente)
        self.lblBairroEmitente.setBuddy(self.txtBairroEmitente)
        self.lblCidadeEmitente.setBuddy(self.txtCidadeEmitente)
        self.lblEstadoEmitente.setBuddy(self.txtEstadoEmitente)
        self.lblCepEmitente.setBuddy(self.txtCepEmitente)
        self.lblRazaoSocialEmitente.setBuddy(self.txtRazaoSocialEmitente)
        self.lblCnpjEmitente.setBuddy(self.txtCnpjEmitente)
        self.lblInscricaoEstadualEmitente.setBuddy(self.txtInscricaoEstaduaEmitente)
        self.lblCodigoDestinatario.setBuddy(self.txtIdDestinatario)
        self.lblNomeFantasiaDestinatario.setBuddy(self.txtFantasiaDestinatario)
        self.lblCnpjDestinatario.setBuddy(self.txtCnpjDestinatario)
        self.lblRazaoSocialDestinatario.setBuddy(self.txtRazaoSocialDestinatario)
        self.lblInscricaoEstadualDestinatario.setBuddy(self.txtInscricaoEstaduaDestinatario)
        self.lblCepDestinatario.setBuddy(self.txtCepDestinatario)
        self.lblComplementoDestinatario.setBuddy(self.txtComplementoDestinatario)
        self.lblCidadeDestinatario.setBuddy(self.txtCidadeDestinatario)
        self.lblEnderecoDestinatario.setBuddy(self.txtEnderecoDestinatario)
        self.lblNumeroDestinatario.setBuddy(self.txtNumeroDestinatario)
        self.lblBairroDestinatario.setBuddy(self.txtBairroDestinatario)
        self.lblEstadoDestinatario.setBuddy(self.txtEstadoDestinatario)
        self.lblTipoProdutoEmitente.setBuddy(self.txtTipoProduto)
        self.lblNumeroNotaFiscal.setBuddy(self.txtNumeroNotaFiscal)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblRg.setBuddy(self.txtRg)
        self.lblCodigoMotorista.setBuddy(self.txtidMotorista)
        self.lblCpfMotorista.setBuddy(self.txtCpf)
        self.lblMarca.setBuddy(self.txtMarca)
        self.lblModelo.setBuddy(self.txtModelo)
        self.lblPlaca.setBuddy(self.txtPlaca)
        self.lblNumeroRomaneio.setBuddy(self.txtNumeroRomaneio)
        self.lblMetragemMadeira.setBuddy(self.txtMetragemMadeira)

        self.retranslateUi(frmEntradaNota)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaNota)
        frmEntradaNota.setTabOrder(self.txtIdEmitente, self.txtNomeEmitente)
        frmEntradaNota.setTabOrder(self.txtNomeEmitente, self.txtIdDestinatario)
        frmEntradaNota.setTabOrder(self.txtIdDestinatario, self.txtFantasiaDestinatario)
        frmEntradaNota.setTabOrder(self.txtFantasiaDestinatario, self.txtNumeroNotaFiscal)
        frmEntradaNota.setTabOrder(self.txtNumeroNotaFiscal, self.txtTipoProduto)
        frmEntradaNota.setTabOrder(self.txtTipoProduto, self.txtCertificada)
        frmEntradaNota.setTabOrder(self.txtCertificada, self.txtNumeroRomaneio)
        frmEntradaNota.setTabOrder(self.txtNumeroRomaneio, self.txtMetragemMadeira)
        frmEntradaNota.setTabOrder(self.txtMetragemMadeira, self.txtidMotorista)
        frmEntradaNota.setTabOrder(self.txtidMotorista, self.txtNomeMotorista)

    def retranslateUi(self, frmEntradaNota):
        frmEntradaNota.setWindowTitle(_translate("frmEntradaNota", "Entrada de Notas Fiscais", None))
        self.grbDadosEmitente.setTitle(_translate("frmEntradaNota", "Dados do Emitente", None))
        self.txtIdEmitente.setToolTip(_translate("frmEntradaNota", "Codigo Emitente", None))
        self.txtIdEmitente.setWhatsThis(_translate("frmEntradaNota", "Campo do codigo de identificação do emitente", None))
        self.txtNomeEmitente.setToolTip(_translate("frmEntradaNota", "Nome Fantasia Emitente", None))
        self.txtNomeEmitente.setWhatsThis(_translate("frmEntradaNota", "Campo do nome fantasia  do emitente", None))
        self.lblCodigoEmitente.setText(_translate("frmEntradaNota", "Codigo Emitente", None))
        self.lblNomeEmitente.setText(_translate("frmEntradaNota", "Nome Fantasia Emitente", None))
        self.txtEnderecoEmitente.setToolTip(_translate("frmEntradaNota", "Endereço ", None))
        self.txtEnderecoEmitente.setWhatsThis(_translate("frmEntradaNota", "Endereço do emitente", None))
        self.txtNumeroEmitente.setToolTip(_translate("frmEntradaNota", "Numero ", None))
        self.txtNumeroEmitente.setWhatsThis(_translate("frmEntradaNota", "Numero referente ao endereço do emitente", None))
        self.txtComplementoEmitente.setToolTip(_translate("frmEntradaNota", "Complemento", None))
        self.txtComplementoEmitente.setWhatsThis(_translate("frmEntradaNota", "Complemento do endereço do emitente", None))
        self.txtCidadeEmitente.setToolTip(_translate("frmEntradaNota", "Cidade", None))
        self.txtCidadeEmitente.setWhatsThis(_translate("frmEntradaNota", "Nome da cidade onde o emitente reside", None))
        self.txtEstadoEmitente.setToolTip(_translate("frmEntradaNota", "Estado", None))
        self.txtEstadoEmitente.setWhatsThis(_translate("frmEntradaNota", "Nome do estado onde fica localizado a cidade do emitente", None))
        self.txtCepEmitente.setToolTip(_translate("frmEntradaNota", "CEP ", None))
        self.txtCepEmitente.setWhatsThis(_translate("frmEntradaNota", "Codigo do CEP referente a cidade do emitente", None))
        self.txtCepEmitente.setInputMask(_translate("frmEntradaNota", "00000-000; ", None))
        self.txtBairroEmitente.setToolTip(_translate("frmEntradaNota", "Bairro", None))
        self.txtBairroEmitente.setWhatsThis(_translate("frmEntradaNota", "Nome do bairro localizado o endereço do emitente", None))
        self.lblEnderecoEmitente.setText(_translate("frmEntradaNota", "Endereço", None))
        self.lblNumeroEmitente.setText(_translate("frmEntradaNota", "Numero", None))
        self.lblComplementoEmitente.setText(_translate("frmEntradaNota", "Complemento", None))
        self.lblBairroEmitente.setText(_translate("frmEntradaNota", "Bairro", None))
        self.lblCidadeEmitente.setText(_translate("frmEntradaNota", "Cidade", None))
        self.lblEstadoEmitente.setText(_translate("frmEntradaNota", "Estado", None))
        self.lblCepEmitente.setText(_translate("frmEntradaNota", "CEP", None))
        self.txtInscricaoEstaduaEmitente.setToolTip(_translate("frmEntradaNota", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmitente.setWhatsThis(_translate("frmEntradaNota", "Campo do numero do inscrição estadual do emitente", None))
        self.txtRazaoSocialEmitente.setToolTip(_translate("frmEntradaNota", "Razão Social ", None))
        self.txtRazaoSocialEmitente.setWhatsThis(_translate("frmEntradaNota", "Campo do nome da razão social do emitente", None))
        self.lblRazaoSocialEmitente.setText(_translate("frmEntradaNota", "Razão Social", None))
        self.lblCnpjEmitente.setText(_translate("frmEntradaNota", "CNPJ", None))
        self.lblInscricaoEstadualEmitente.setText(_translate("frmEntradaNota", "Incrição Estadual", None))
        self.txtCnpjEmitente.setToolTip(_translate("frmEntradaNota", "CNPJ ", None))
        self.txtCnpjEmitente.setWhatsThis(_translate("frmEntradaNota", "Campo do numero do CNPJ do emitente", None))
        self.txtCnpjEmitente.setInputMask(_translate("frmEntradaNota", "00.000.000/0000-00; ", None))
        self.grbDadosDestinatario.setTitle(_translate("frmEntradaNota", "Dados Destinatario", None))
        self.txtCnpjDestinatario.setToolTip(_translate("frmEntradaNota", "CNPJ ", None))
        self.txtCnpjDestinatario.setWhatsThis(_translate("frmEntradaNota", "Campo do numero do CNPJ do destinatario", None))
        self.txtCnpjDestinatario.setInputMask(_translate("frmEntradaNota", "00.000.000/0000-00; ", None))
        self.lblCodigoDestinatario.setText(_translate("frmEntradaNota", "Codigo do Destinatario", None))
        self.lblNomeFantasiaDestinatario.setText(_translate("frmEntradaNota", "Nome Fantasia Destinatario", None))
        self.lblCnpjDestinatario.setText(_translate("frmEntradaNota", "CNPJ", None))
        self.txtFantasiaDestinatario.setToolTip(_translate("frmEntradaNota", "Nome Fantasia Destinatario", None))
        self.txtFantasiaDestinatario.setWhatsThis(_translate("frmEntradaNota", "Campo do nome fantasia do destinatario", None))
        self.txtRazaoSocialDestinatario.setToolTip(_translate("frmEntradaNota", "Razão Social ", None))
        self.txtRazaoSocialDestinatario.setWhatsThis(_translate("frmEntradaNota", "Campo do nome da razão social do destinatario", None))
        self.lblRazaoSocialDestinatario.setText(_translate("frmEntradaNota", "Razão Social", None))
        self.txtIdDestinatario.setToolTip(_translate("frmEntradaNota", "Codigo Destinatario", None))
        self.txtIdDestinatario.setWhatsThis(_translate("frmEntradaNota", "Campo do codigo de identificação do destinatario", None))
        self.txtInscricaoEstaduaDestinatario.setToolTip(_translate("frmEntradaNota", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaDestinatario.setWhatsThis(_translate("frmEntradaNota", "Campo do numero do inscrição estadual do destinatario", None))
        self.lblInscricaoEstadualDestinatario.setText(_translate("frmEntradaNota", "Incrição Estadual", None))
        self.lblCepDestinatario.setText(_translate("frmEntradaNota", "CEP", None))
        self.lblComplementoDestinatario.setText(_translate("frmEntradaNota", "Complemento", None))
        self.txtComplementoDestinatario.setToolTip(_translate("frmEntradaNota", "Complemento", None))
        self.txtComplementoDestinatario.setWhatsThis(_translate("frmEntradaNota", "Complemento do endereço do destinatario", None))
        self.lblCidadeDestinatario.setText(_translate("frmEntradaNota", "Cidade", None))
        self.txtEnderecoDestinatario.setToolTip(_translate("frmEntradaNota", "Endereço", None))
        self.txtEnderecoDestinatario.setWhatsThis(_translate("frmEntradaNota", "Endereço do destinatario", None))
        self.txtNumeroDestinatario.setToolTip(_translate("frmEntradaNota", "Numero", None))
        self.txtNumeroDestinatario.setWhatsThis(_translate("frmEntradaNota", "Numero referente ao endereço do destinatario", None))
        self.lblEnderecoDestinatario.setText(_translate("frmEntradaNota", "Endereço", None))
        self.txtBairroDestinatario.setToolTip(_translate("frmEntradaNota", "Bairro", None))
        self.txtBairroDestinatario.setWhatsThis(_translate("frmEntradaNota", "Nome do bairro localizado o endereço do destinatario", None))
        self.txtCidadeDestinatario.setToolTip(_translate("frmEntradaNota", "Cidade", None))
        self.txtCidadeDestinatario.setWhatsThis(_translate("frmEntradaNota", "Nome da cidade onde destinatario reside", None))
        self.lblNumeroDestinatario.setText(_translate("frmEntradaNota", "Numero", None))
        self.txtEstadoDestinatario.setToolTip(_translate("frmEntradaNota", "Estado", None))
        self.txtEstadoDestinatario.setWhatsThis(_translate("frmEntradaNota", "Nome do estado onde fica localizado a cidade do destinatario", None))
        self.txtCepDestinatario.setToolTip(_translate("frmEntradaNota", "Cep", None))
        self.txtCepDestinatario.setWhatsThis(_translate("frmEntradaNota", "Codigo do CEP referente a cidade do destinatario", None))
        self.txtCepDestinatario.setInputMask(_translate("frmEntradaNota", "00000-000; ", None))
        self.lblBairroDestinatario.setText(_translate("frmEntradaNota", "Bairro", None))
        self.lblEstadoDestinatario.setText(_translate("frmEntradaNota", "Estado", None))
        self.grbBotoes.setWhatsThis(_translate("frmEntradaNota", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaNota", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmEntradaNota", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaNota", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmEntradaNota", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaNota", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmEntradaNota", "Salvar", None))
        self.grbDadosNotaFiscal.setTitle(_translate("frmEntradaNota", "Dados Nota Fiscal", None))
        self.lblTipoProdutoEmitente.setText(_translate("frmEntradaNota", "Tipo de Produto", None))
        self.txtTipoProduto.setToolTip(_translate("frmEntradaNota", "Tipo do Produto", None))
        self.txtTipoProduto.setWhatsThis(_translate("frmEntradaNota", "Tipo de produto descrito na Nota-Fiscal", None))
        self.lblNumeroNotaFiscal.setText(_translate("frmEntradaNota", "Numero Nota Fiscal", None))
        self.txtNumeroNotaFiscal.setToolTip(_translate("frmEntradaNota", "Numero Nota Fical", None))
        self.txtNumeroNotaFiscal.setWhatsThis(_translate("frmEntradaNota", "Codigo de identificação do numero da Nota Fiscal", None))
        self.txtCertificada.setWhatsThis(_translate("frmEntradaNota", "Campo de identificação se o produto é certificado", None))
        self.txtCertificada.setText(_translate("frmEntradaNota", "Certificada", None))
        self.grbDadosMotorista.setTitle(_translate("frmEntradaNota", "Dados Motorista", None))
        self.txtidMotorista.setToolTip(_translate("frmEntradaNota", "Codigo Motorista", None))
        self.txtidMotorista.setWhatsThis(_translate("frmEntradaNota", "Campo do Codigo de identificação do Motorista", None))
        self.txtCpf.setToolTip(_translate("frmEntradaNota", "CPF", None))
        self.txtCpf.setWhatsThis(_translate("frmEntradaNota", "Campo do numero do CPF do Motorista", None))
        self.txtCpf.setInputMask(_translate("frmEntradaNota", "000.000.000-00; ", None))
        self.txtRg.setToolTip(_translate("frmEntradaNota", "Rg", None))
        self.txtRg.setWhatsThis(_translate("frmEntradaNota", "Campo do numero do RG do Motorista", None))
        self.txtRg.setInputMask(_translate("frmEntradaNota", "000000-0; ", None))
        self.lblNomeMotorista.setText(_translate("frmEntradaNota", "Nome Motorista", None))
        self.txtNomeMotorista.setToolTip(_translate("frmEntradaNota", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmEntradaNota", "Campo do nome do Motorista", None))
        self.lblRg.setText(_translate("frmEntradaNota", "RG", None))
        self.lblCodigoMotorista.setText(_translate("frmEntradaNota", "Codigo Motorista", None))
        self.lblCpfMotorista.setText(_translate("frmEntradaNota", "CPF", None))
        self.lblMarca.setText(_translate("frmEntradaNota", "Marca", None))
        self.txtMarca.setToolTip(_translate("frmEntradaNota", "Marca", None))
        self.txtMarca.setWhatsThis(_translate("frmEntradaNota", "Campo do nome da marca do veiculo", None))
        self.lblModelo.setText(_translate("frmEntradaNota", "Modelo", None))
        self.txtModelo.setToolTip(_translate("frmEntradaNota", "Modelo", None))
        self.txtModelo.setWhatsThis(_translate("frmEntradaNota", "Campo do nome do modelo do veiculo", None))
        self.lblPlaca.setText(_translate("frmEntradaNota", "Placa", None))
        self.txtPlaca.setToolTip(_translate("frmEntradaNota", "Placa", None))
        self.txtPlaca.setWhatsThis(_translate("frmEntradaNota", "Campo de identificação da placa do veiculo", None))
        self.txtPlaca.setInputMask(_translate("frmEntradaNota", "nnn-0000; ", None))
        self.grbDadosRomaneio.setTitle(_translate("frmEntradaNota", "Dados Romaneio", None))
        self.txtNumeroRomaneio.setToolTip(_translate("frmEntradaNota", "Numero Romaneio", None))
        self.txtNumeroRomaneio.setWhatsThis(_translate("frmEntradaNota", "Codigo de identificação do numero do romaneio", None))
        self.lblNumeroRomaneio.setText(_translate("frmEntradaNota", "Numero Romaneio", None))
        self.txtMetragemMadeira.setToolTip(_translate("frmEntradaNota", "Metragem Madeira", None))
        self.txtMetragemMadeira.setWhatsThis(_translate("frmEntradaNota", "Campo de escolha do tipo de metragem madeira", None))
        self.lblMetragemMadeira.setText(_translate("frmEntradaNota", "Metragem Madeira", None))

