# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEntradaVeiculosCarregamentos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEntradaVeiculosCarregamento(object):
    def setupUi(self, frmEntradaVeiculosCarregamento):
        frmEntradaVeiculosCarregamento.setObjectName(_fromUtf8("frmEntradaVeiculosCarregamento"))
        frmEntradaVeiculosCarregamento.resize(890, 615)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmEntradaVeiculosCarregamento.setFont(font)
        self.grbDadosMotorista = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbDadosMotorista.setGeometry(QtCore.QRect(10, 50, 871, 114))
        self.grbDadosMotorista.setObjectName(_fromUtf8("grbDadosMotorista"))
        self.txtModeloMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtModeloMotorista.setGeometry(QtCore.QRect(10, 80, 291, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtModeloMotorista.setPalette(palette)
        self.txtModeloMotorista.setMaxLength(50)
        self.txtModeloMotorista.setObjectName(_fromUtf8("txtModeloMotorista"))
        self.lblMarcaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblMarcaMotorista.setGeometry(QtCore.QRect(310, 62, 51, 19))
        self.lblMarcaMotorista.setObjectName(_fromUtf8("lblMarcaMotorista"))
        self.txtMarcaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtMarcaMotorista.setGeometry(QtCore.QRect(310, 82, 331, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtMarcaMotorista.setPalette(palette)
        self.txtMarcaMotorista.setMaxLength(50)
        self.txtMarcaMotorista.setObjectName(_fromUtf8("txtMarcaMotorista"))
        self.txtNomeMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(180, 36, 621, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeMotorista.setPalette(palette)
        self.txtNomeMotorista.setMaxLength(70)
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))
        self.lblNomeMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblNomeMotorista.setGeometry(QtCore.QRect(180, 16, 151, 19))
        self.lblNomeMotorista.setObjectName(_fromUtf8("lblNomeMotorista"))
        self.txtPlacaMotorista = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtPlacaMotorista.setGeometry(QtCore.QRect(650, 82, 211, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtPlacaMotorista.setPalette(palette)
        self.txtPlacaMotorista.setObjectName(_fromUtf8("txtPlacaMotorista"))
        self.lblModeloMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblModeloMotorista.setGeometry(QtCore.QRect(10, 60, 51, 19))
        self.lblModeloMotorista.setObjectName(_fromUtf8("lblModeloMotorista"))
        self.txtidFuncionario = QtGui.QLineEdit(self.grbDadosMotorista)
        self.txtidFuncionario.setGeometry(QtCore.QRect(10, 36, 161, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtidFuncionario.setPalette(palette)
        self.txtidFuncionario.setMaxLength(11)
        self.txtidFuncionario.setObjectName(_fromUtf8("txtidFuncionario"))
        self.lblCodigoMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblCodigoMotorista.setGeometry(QtCore.QRect(10, 16, 121, 19))
        self.lblCodigoMotorista.setObjectName(_fromUtf8("lblCodigoMotorista"))
        self.lblPlacaMotorista = QtGui.QLabel(self.grbDadosMotorista)
        self.lblPlacaMotorista.setGeometry(QtCore.QRect(650, 62, 51, 19))
        self.lblPlacaMotorista.setObjectName(_fromUtf8("lblPlacaMotorista"))
        self.btnPesquisarMotorista = QtGui.QPushButton(self.grbDadosMotorista)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(820, 40, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarMotorista.setFont(font)
        self.btnPesquisarMotorista.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarMotorista.setText(_fromUtf8(""))
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        self.grbDadosClienteDestinatario = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbDadosClienteDestinatario.setGeometry(QtCore.QRect(10, 165, 871, 252))
        self.grbDadosClienteDestinatario.setObjectName(_fromUtf8("grbDadosClienteDestinatario"))
        self.txtIdClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtIdClienteDestinatario.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdClienteDestinatario.setPalette(palette)
        self.txtIdClienteDestinatario.setMaxLength(11)
        self.txtIdClienteDestinatario.setObjectName(_fromUtf8("txtIdClienteDestinatario"))
        self.txtNomeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 35, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeClienteDestinatario.setPalette(palette)
        self.txtNomeClienteDestinatario.setMaxLength(70)
        self.txtNomeClienteDestinatario.setObjectName(_fromUtf8("txtNomeClienteDestinatario"))
        self.lblCodigoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCodigoClienteDestinatario.setGeometry(QtCore.QRect(10, 15, 171, 21))
        self.lblCodigoClienteDestinatario.setObjectName(_fromUtf8("lblCodigoClienteDestinatario"))
        self.lblNomeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNomeClienteDestinatario.setGeometry(QtCore.QRect(201, 15, 231, 16))
        self.lblNomeClienteDestinatario.setObjectName(_fromUtf8("lblNomeClienteDestinatario"))
        self.txtEnderecoClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEnderecoClienteDestinatario.setGeometry(QtCore.QRect(10, 130, 381, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEnderecoClienteDestinatario.setPalette(palette)
        self.txtEnderecoClienteDestinatario.setMaxLength(50)
        self.txtEnderecoClienteDestinatario.setObjectName(_fromUtf8("txtEnderecoClienteDestinatario"))
        self.txtNumeroClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtNumeroClienteDestinatario.setGeometry(QtCore.QRect(400, 130, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNumeroClienteDestinatario.setPalette(palette)
        self.txtNumeroClienteDestinatario.setMaxLength(11)
        self.txtNumeroClienteDestinatario.setObjectName(_fromUtf8("txtNumeroClienteDestinatario"))
        self.txtComplementoClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtComplementoClienteDestinatario.setGeometry(QtCore.QRect(550, 130, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtComplementoClienteDestinatario.setPalette(palette)
        self.txtComplementoClienteDestinatario.setMaxLength(50)
        self.txtComplementoClienteDestinatario.setObjectName(_fromUtf8("txtComplementoClienteDestinatario"))
        self.txtCidadeClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCidadeClienteDestinatario.setGeometry(QtCore.QRect(328, 177, 311, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCidadeClienteDestinatario.setPalette(palette)
        self.txtCidadeClienteDestinatario.setMaxLength(70)
        self.txtCidadeClienteDestinatario.setObjectName(_fromUtf8("txtCidadeClienteDestinatario"))
        self.txtEstadoClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtEstadoClienteDestinatario.setGeometry(QtCore.QRect(647, 177, 214, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEstadoClienteDestinatario.setPalette(palette)
        self.txtEstadoClienteDestinatario.setMaxLength(50)
        self.txtEstadoClienteDestinatario.setObjectName(_fromUtf8("txtEstadoClienteDestinatario"))
        self.txtCepClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCepClienteDestinatario.setGeometry(QtCore.QRect(10, 220, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCepClienteDestinatario.setPalette(palette)
        self.txtCepClienteDestinatario.setObjectName(_fromUtf8("txtCepClienteDestinatario"))
        self.txtBairroClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtBairroClienteDestinatario.setGeometry(QtCore.QRect(10, 177, 301, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtBairroClienteDestinatario.setPalette(palette)
        self.txtBairroClienteDestinatario.setMaxLength(50)
        self.txtBairroClienteDestinatario.setObjectName(_fromUtf8("txtBairroClienteDestinatario"))
        self.lblEnderecoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEnderecoClienteDestinatario.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.lblEnderecoClienteDestinatario.setObjectName(_fromUtf8("lblEnderecoClienteDestinatario"))
        self.lblNumeroClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblNumeroClienteDestinatario.setGeometry(QtCore.QRect(400, 110, 61, 16))
        self.lblNumeroClienteDestinatario.setObjectName(_fromUtf8("lblNumeroClienteDestinatario"))
        self.lblComplementoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblComplementoClienteDestinatario.setGeometry(QtCore.QRect(550, 110, 91, 16))
        self.lblComplementoClienteDestinatario.setObjectName(_fromUtf8("lblComplementoClienteDestinatario"))
        self.lblBairroClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblBairroClienteDestinatario.setGeometry(QtCore.QRect(10, 157, 61, 16))
        self.lblBairroClienteDestinatario.setObjectName(_fromUtf8("lblBairroClienteDestinatario"))
        self.lblCidadeClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCidadeClienteDestinatario.setGeometry(QtCore.QRect(326, 157, 61, 16))
        self.lblCidadeClienteDestinatario.setObjectName(_fromUtf8("lblCidadeClienteDestinatario"))
        self.lblEstadoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblEstadoClienteDestinatario.setGeometry(QtCore.QRect(647, 157, 61, 16))
        self.lblEstadoClienteDestinatario.setObjectName(_fromUtf8("lblEstadoClienteDestinatario"))
        self.lblCepClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCepClienteDestinatario.setGeometry(QtCore.QRect(10, 200, 61, 16))
        self.lblCepClienteDestinatario.setObjectName(_fromUtf8("lblCepClienteDestinatario"))
        self.txtInscricaoEstaduaClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtInscricaoEstaduaClienteDestinatario.setGeometry(QtCore.QRect(688, 80, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaClienteDestinatario.setPalette(palette)
        self.txtInscricaoEstaduaClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaClienteDestinatario.setMaxLength(8)
        self.txtInscricaoEstaduaClienteDestinatario.setObjectName(_fromUtf8("txtInscricaoEstaduaClienteDestinatario"))
        self.txtRazaoSocialClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 80, 481, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialClienteDestinatario.setPalette(palette)
        self.txtRazaoSocialClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialClienteDestinatario.setMaxLength(70)
        self.txtRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("txtRazaoSocialClienteDestinatario"))
        self.lblRazaoSocialClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialClienteDestinatario.setObjectName(_fromUtf8("lblRazaoSocialClienteDestinatario"))
        self.lblCnpjClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblCnpjClienteDestinatario.setGeometry(QtCore.QRect(500, 60, 41, 19))
        self.lblCnpjClienteDestinatario.setObjectName(_fromUtf8("lblCnpjClienteDestinatario"))
        self.lblInscricaoClienteDestinatario = QtGui.QLabel(self.grbDadosClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setGeometry(QtCore.QRect(688, 60, 121, 19))
        self.lblInscricaoClienteDestinatario.setObjectName(_fromUtf8("lblInscricaoClienteDestinatario"))
        self.txtCnpjClienteDestinatario = QtGui.QLineEdit(self.grbDadosClienteDestinatario)
        self.txtCnpjClienteDestinatario.setGeometry(QtCore.QRect(500, 80, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjClienteDestinatario.setPalette(palette)
        self.txtCnpjClienteDestinatario.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjClienteDestinatario.setText(_fromUtf8("../-"))
        self.txtCnpjClienteDestinatario.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjClienteDestinatario.setObjectName(_fromUtf8("txtCnpjClienteDestinatario"))
        self.btnPesquisarClienteDestinatario = QtGui.QPushButton(self.grbDadosClienteDestinatario)
        self.btnPesquisarClienteDestinatario.setGeometry(QtCore.QRect(820, 40, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarClienteDestinatario.setFont(font)
        self.btnPesquisarClienteDestinatario.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarClienteDestinatario.setText(_fromUtf8(""))
        self.btnPesquisarClienteDestinatario.setObjectName(_fromUtf8("btnPesquisarClienteDestinatario"))
        self.lblHoraEntrada = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.lblHoraEntrada.setGeometry(QtCore.QRect(150, 6, 91, 16))
        self.lblHoraEntrada.setObjectName(_fromUtf8("lblHoraEntrada"))
        self.txtData = QtGui.QDateEdit(frmEntradaVeiculosCarregamento)
        self.txtData.setGeometry(QtCore.QRect(20, 26, 110, 25))
        self.txtData.setObjectName(_fromUtf8("txtData"))
        self.txtHora = QtGui.QTimeEdit(frmEntradaVeiculosCarregamento)
        self.txtHora.setGeometry(QtCore.QRect(150, 26, 118, 25))
        self.txtHora.setObjectName(_fromUtf8("txtHora"))
        self.lblDataEntrada = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.lblDataEntrada.setGeometry(QtCore.QRect(20, 6, 101, 16))
        self.lblDataEntrada.setObjectName(_fromUtf8("lblDataEntrada"))
        self.grbDadosEmpresaOrigem = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbDadosEmpresaOrigem.setGeometry(QtCore.QRect(10, 416, 871, 111))
        self.grbDadosEmpresaOrigem.setObjectName(_fromUtf8("grbDadosEmpresaOrigem"))
        self.txtIdEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtIdEmpresaOrigem.setGeometry(QtCore.QRect(10, 35, 181, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtIdEmpresaOrigem.setPalette(palette)
        self.txtIdEmpresaOrigem.setMaxLength(11)
        self.txtIdEmpresaOrigem.setObjectName(_fromUtf8("txtIdEmpresaOrigem"))
        self.txtNomeEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 35, 601, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtNomeEmpresaOrigem.setPalette(palette)
        self.txtNomeEmpresaOrigem.setMaxLength(70)
        self.txtNomeEmpresaOrigem.setObjectName(_fromUtf8("txtNomeEmpresaOrigem"))
        self.lblCodigoEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblCodigoEmpresaOrigem.setGeometry(QtCore.QRect(10, 15, 161, 21))
        self.lblCodigoEmpresaOrigem.setObjectName(_fromUtf8("lblCodigoEmpresaOrigem"))
        self.lblNomeEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblNomeEmpresaOrigem.setGeometry(QtCore.QRect(201, 15, 211, 16))
        self.lblNomeEmpresaOrigem.setObjectName(_fromUtf8("lblNomeEmpresaOrigem"))
        self.txtInscricaoEstaduaEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtInscricaoEstaduaEmpresaOrigem.setGeometry(QtCore.QRect(688, 80, 173, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtInscricaoEstaduaEmpresaOrigem.setPalette(palette)
        self.txtInscricaoEstaduaEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtInscricaoEstaduaEmpresaOrigem.setMaxLength(8)
        self.txtInscricaoEstaduaEmpresaOrigem.setObjectName(_fromUtf8("txtInscricaoEstaduaEmpresaOrigem"))
        self.txtRazaoSocialEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 80, 481, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtRazaoSocialEmpresaOrigem.setPalette(palette)
        self.txtRazaoSocialEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtRazaoSocialEmpresaOrigem.setMaxLength(70)
        self.txtRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("txtRazaoSocialEmpresaOrigem"))
        self.lblRazaoSocialEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblRazaoSocialEmpresaOrigem.setGeometry(QtCore.QRect(10, 60, 81, 19))
        self.lblRazaoSocialEmpresaOrigem.setObjectName(_fromUtf8("lblRazaoSocialEmpresaOrigem"))
        self.lblCnpjEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblCnpjEmpresaOrigem.setGeometry(QtCore.QRect(500, 60, 41, 19))
        self.lblCnpjEmpresaOrigem.setObjectName(_fromUtf8("lblCnpjEmpresaOrigem"))
        self.lblInscricaoEstadualEmpresaOrigem = QtGui.QLabel(self.grbDadosEmpresaOrigem)
        self.lblInscricaoEstadualEmpresaOrigem.setGeometry(QtCore.QRect(688, 60, 121, 19))
        self.lblInscricaoEstadualEmpresaOrigem.setObjectName(_fromUtf8("lblInscricaoEstadualEmpresaOrigem"))
        self.txtCnpjEmpresaOrigem = QtGui.QLineEdit(self.grbDadosEmpresaOrigem)
        self.txtCnpjEmpresaOrigem.setGeometry(QtCore.QRect(500, 80, 182, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtCnpjEmpresaOrigem.setPalette(palette)
        self.txtCnpjEmpresaOrigem.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.txtCnpjEmpresaOrigem.setText(_fromUtf8("../-"))
        self.txtCnpjEmpresaOrigem.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.txtCnpjEmpresaOrigem.setObjectName(_fromUtf8("txtCnpjEmpresaOrigem"))
        self.btnPesquisarEmpresaOrigem = QtGui.QPushButton(self.grbDadosEmpresaOrigem)
        self.btnPesquisarEmpresaOrigem.setGeometry(QtCore.QRect(820, 40, 31, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPesquisarEmpresaOrigem.setFont(font)
        self.btnPesquisarEmpresaOrigem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPesquisarEmpresaOrigem.setText(_fromUtf8(""))
        self.btnPesquisarEmpresaOrigem.setObjectName(_fromUtf8("btnPesquisarEmpresaOrigem"))
        self.grbBotoes = QtGui.QGroupBox(frmEntradaVeiculosCarregamento)
        self.grbBotoes.setGeometry(QtCore.QRect(10, 530, 871, 80))
        self.grbBotoes.setTitle(_fromUtf8(""))
        self.grbBotoes.setObjectName(_fromUtf8("grbBotoes"))
        self.btnNovo = QtGui.QPushButton(self.grbBotoes)
        self.btnNovo.setGeometry(QtCore.QRect(580, 10, 81, 61))
        self.btnNovo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNovo.setObjectName(_fromUtf8("btnNovo"))
        self.btnCancelar = QtGui.QPushButton(self.grbBotoes)
        self.btnCancelar.setGeometry(QtCore.QRect(780, 10, 81, 61))
        self.btnCancelar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.btnSalvar = QtGui.QPushButton(self.grbBotoes)
        self.btnSalvar.setGeometry(QtCore.QRect(680, 10, 81, 61))
        self.btnSalvar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.txtTipoCarga = QtGui.QComboBox(frmEntradaVeiculosCarregamento)
        self.txtTipoCarga.setGeometry(QtCore.QRect(290, 26, 241, 25))
        self.txtTipoCarga.setObjectName(_fromUtf8("txtTipoCarga"))
        self.label = QtGui.QLabel(frmEntradaVeiculosCarregamento)
        self.label.setGeometry(QtCore.QRect(290, 4, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lblMarcaMotorista.setBuddy(self.txtMarcaMotorista)
        self.lblNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lblModeloMotorista.setBuddy(self.txtModeloMotorista)
        self.lblCodigoMotorista.setBuddy(self.txtidFuncionario)
        self.lblPlacaMotorista.setBuddy(self.txtPlacaMotorista)
        self.lblCodigoClienteDestinatario.setBuddy(self.txtIdClienteDestinatario)
        self.lblNomeClienteDestinatario.setBuddy(self.txtNomeClienteDestinatario)
        self.lblEnderecoClienteDestinatario.setBuddy(self.txtEnderecoClienteDestinatario)
        self.lblNumeroClienteDestinatario.setBuddy(self.txtNumeroClienteDestinatario)
        self.lblComplementoClienteDestinatario.setBuddy(self.txtComplementoClienteDestinatario)
        self.lblBairroClienteDestinatario.setBuddy(self.txtBairroClienteDestinatario)
        self.lblCidadeClienteDestinatario.setBuddy(self.txtCidadeClienteDestinatario)
        self.lblEstadoClienteDestinatario.setBuddy(self.txtEstadoClienteDestinatario)
        self.lblCepClienteDestinatario.setBuddy(self.txtCepClienteDestinatario)
        self.lblRazaoSocialClienteDestinatario.setBuddy(self.txtRazaoSocialClienteDestinatario)
        self.lblCnpjClienteDestinatario.setBuddy(self.txtCnpjClienteDestinatario)
        self.lblInscricaoClienteDestinatario.setBuddy(self.txtInscricaoEstaduaClienteDestinatario)
        self.lblHoraEntrada.setBuddy(self.txtHora)
        self.lblDataEntrada.setBuddy(self.txtData)
        self.lblCodigoEmpresaOrigem.setBuddy(self.txtIdClienteDestinatario)
        self.lblNomeEmpresaOrigem.setBuddy(self.txtNomeClienteDestinatario)
        self.lblRazaoSocialEmpresaOrigem.setBuddy(self.txtRazaoSocialClienteDestinatario)
        self.lblCnpjEmpresaOrigem.setBuddy(self.txtCnpjClienteDestinatario)
        self.lblInscricaoEstadualEmpresaOrigem.setBuddy(self.txtInscricaoEstaduaClienteDestinatario)
        self.label.setBuddy(self.txtTipoCarga)

        self.retranslateUi(frmEntradaVeiculosCarregamento)
        QtCore.QMetaObject.connectSlotsByName(frmEntradaVeiculosCarregamento)

    def retranslateUi(self, frmEntradaVeiculosCarregamento):
        frmEntradaVeiculosCarregamento.setWindowTitle(_translate("frmEntradaVeiculosCarregamento", "Entrada de Veiculos Carregamentos", None))
        self.grbDadosMotorista.setTitle(_translate("frmEntradaVeiculosCarregamento", "Motorista", None))
        self.txtModeloMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtModeloMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo de identicação do modelo do veiculo", None))
        self.lblMarcaMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Marca", None))
        self.txtMarcaMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Marca do Veiculo", None))
        self.txtMarcaMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome da marca do veiculo", None))
        self.txtNomeMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Nome Motorista", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome do Motorista", None))
        self.lblNomeMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Nome Motorista", None))
        self.txtPlacaMotorista.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Placa do Veiculo", None))
        self.txtPlacaMotorista.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo de identificação da placa do veiculo", None))
        self.txtPlacaMotorista.setInputMask(_translate("frmEntradaVeiculosCarregamento", "nnn-0000; ", None))
        self.txtPlacaMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "-", None))
        self.lblModeloMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Modelo", None))
        self.txtidFuncionario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Codigo Motorista", None))
        self.txtidFuncionario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do Codigo de identificação do Motorista", None))
        self.lblCodigoMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Codigo Motorista", None))
        self.lblPlacaMotorista.setText(_translate("frmEntradaVeiculosCarregamento", "Placa", None))
        self.grbDadosClienteDestinatario.setTitle(_translate("frmEntradaVeiculosCarregamento", "Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.txtIdClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do codigo de identificação do cliente destinatario", None))
        self.txtNomeClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Nome Cliente Destinatario", None))
        self.txtNomeClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome do cliente destinatario", None))
        self.lblCodigoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Codigo Cliente Destinatario", None))
        self.lblNomeClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Nome Fantasia Cliente Destinatario", None))
        self.txtEnderecoClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Endereço ", None))
        self.txtEnderecoClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Endereço do cliente destinatario", None))
        self.txtNumeroClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Numero ", None))
        self.txtNumeroClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Numero referente ao endereço do cliente destinatario", None))
        self.txtComplementoClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Complemento", None))
        self.txtComplementoClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Complemento do endereço do cliente destinatario", None))
        self.txtCidadeClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Cidade", None))
        self.txtCidadeClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Nome da cidade onde o cliente destinatario reside", None))
        self.txtEstadoClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Estado", None))
        self.txtEstadoClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Nome do estado onde fica localizado a cidade do cliente destinatario", None))
        self.txtCepClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "CEP ", None))
        self.txtCepClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Codigo do CEP referente a cidade do cliente destinatario", None))
        self.txtCepClienteDestinatario.setInputMask(_translate("frmEntradaVeiculosCarregamento", "00000-000; ", None))
        self.txtBairroClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Bairro", None))
        self.txtBairroClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Nome do bairro localizado o endereço do cliente destinatario", None))
        self.lblEnderecoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Endereço", None))
        self.lblNumeroClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Numero", None))
        self.lblComplementoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Complemento", None))
        self.lblBairroClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Bairro", None))
        self.lblCidadeClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Cidade", None))
        self.lblEstadoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Estado", None))
        self.lblCepClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "CEP", None))
        self.txtInscricaoEstaduaClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do numero do inscrição estadual do cliente destinatario", None))
        self.txtRazaoSocialClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Razão Social ", None))
        self.txtRazaoSocialClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome da razão social do cliente destinatario", None))
        self.lblRazaoSocialClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Razão Social", None))
        self.lblCnpjClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "CNPJ", None))
        self.lblInscricaoClienteDestinatario.setText(_translate("frmEntradaVeiculosCarregamento", "Incrição Estadual", None))
        self.txtCnpjClienteDestinatario.setToolTip(_translate("frmEntradaVeiculosCarregamento", "CNPJ ", None))
        self.txtCnpjClienteDestinatario.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do numero do CNPJ docliente destinatario", None))
        self.txtCnpjClienteDestinatario.setInputMask(_translate("frmEntradaVeiculosCarregamento", "00.000.000/0000-00; ", None))
        self.lblHoraEntrada.setText(_translate("frmEntradaVeiculosCarregamento", "Hora Entrada", None))
        self.txtData.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Data Entrada", None))
        self.txtHora.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Hora Entrada", None))
        self.lblDataEntrada.setText(_translate("frmEntradaVeiculosCarregamento", "Data Entrada", None))
        self.grbDadosEmpresaOrigem.setTitle(_translate("frmEntradaVeiculosCarregamento", "Empresa Origem", None))
        self.txtIdEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Codigo Empresa Origem", None))
        self.txtIdEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do codigo de identificação da empresa origem", None))
        self.txtNomeEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Nome Empresa Origem", None))
        self.txtNomeEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome da empresa de origem", None))
        self.lblCodigoEmpresaOrigem.setText(_translate("frmEntradaVeiculosCarregamento", "Codigo Empresa Origem", None))
        self.lblNomeEmpresaOrigem.setText(_translate("frmEntradaVeiculosCarregamento", "Nome Fantasia Empresa Origem", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Inscrição Estadual ", None))
        self.txtInscricaoEstaduaEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do numero do inscrição estadual da  empresa origem", None))
        self.txtRazaoSocialEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Razão Social ", None))
        self.txtRazaoSocialEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do nome da razão social do empresa origem", None))
        self.lblRazaoSocialEmpresaOrigem.setText(_translate("frmEntradaVeiculosCarregamento", "Razão Social", None))
        self.lblCnpjEmpresaOrigem.setText(_translate("frmEntradaVeiculosCarregamento", "CNPJ", None))
        self.lblInscricaoEstadualEmpresaOrigem.setText(_translate("frmEntradaVeiculosCarregamento", "Incrição Estadual", None))
        self.txtCnpjEmpresaOrigem.setToolTip(_translate("frmEntradaVeiculosCarregamento", "CNPJ ", None))
        self.txtCnpjEmpresaOrigem.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Campo do numero do CNPJ da empresa origem", None))
        self.txtCnpjEmpresaOrigem.setInputMask(_translate("frmEntradaVeiculosCarregamento", "00.000.000/0000-00; ", None))
        self.grbBotoes.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Grupo de botões referente as suas funções", None))
        self.btnNovo.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Botão de Criação de um novo registro", None))
        self.btnNovo.setText(_translate("frmEntradaVeiculosCarregamento", "Novo", None))
        self.btnCancelar.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Botão de cancelar a operação iniciada", None))
        self.btnCancelar.setText(_translate("frmEntradaVeiculosCarregamento", "Cancelar", None))
        self.btnSalvar.setWhatsThis(_translate("frmEntradaVeiculosCarregamento", "Botão para salvar um novo registro", None))
        self.btnSalvar.setText(_translate("frmEntradaVeiculosCarregamento", "Salvar", None))
        self.txtTipoCarga.setToolTip(_translate("frmEntradaVeiculosCarregamento", "Tipo de Carga", None))
        self.label.setText(_translate("frmEntradaVeiculosCarregamento", "Tipo de Carga", None))

