# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pesagem.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmPesagem(object):
    def setupUi(self, frmPesagem):
        frmPesagem.setObjectName(_fromUtf8("frmPesagem"))
        frmPesagem.resize(580, 495)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPesagem.sizePolicy().hasHeightForWidth())
        frmPesagem.setSizePolicy(sizePolicy)
        frmPesagem.setMaximumSize(QtCore.QSize(580, 495))
        frmPesagem.setSizeIncrement(QtCore.QSize(580, 495))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        frmPesagem.setFont(font)
        frmPesagem.setModal(True)
        self.lbNomeMotorista = QtGui.QLabel(frmPesagem)
        self.lbNomeMotorista.setGeometry(QtCore.QRect(13, 242, 135, 15))
        self.lbNomeMotorista.setObjectName(_fromUtf8("lbNomeMotorista"))
        self.txtNomeMotorista = QtGui.QLineEdit(frmPesagem)
        self.txtNomeMotorista.setGeometry(QtCore.QRect(10, 260, 235, 28))
        self.txtNomeMotorista.setObjectName(_fromUtf8("txtNomeMotorista"))
        self.lbVeiculo = QtGui.QLabel(frmPesagem)
        self.lbVeiculo.setGeometry(QtCore.QRect(253, 242, 63, 16))
        self.lbVeiculo.setObjectName(_fromUtf8("lbVeiculo"))
        self.txtVeiculo = QtGui.QLineEdit(frmPesagem)
        self.txtVeiculo.setGeometry(QtCore.QRect(250, 260, 155, 28))
        self.txtVeiculo.setObjectName(_fromUtf8("txtVeiculo"))
        self.lbPlacaVeiculo = QtGui.QLabel(frmPesagem)
        self.lbPlacaVeiculo.setGeometry(QtCore.QRect(413, 242, 110, 15))
        self.lbPlacaVeiculo.setObjectName(_fromUtf8("lbPlacaVeiculo"))
        self.txtPlacaVeiculo = QtGui.QLineEdit(frmPesagem)
        self.txtPlacaVeiculo.setGeometry(QtCore.QRect(410, 260, 111, 28))
        self.txtPlacaVeiculo.setObjectName(_fromUtf8("txtPlacaVeiculo"))
        self.btnPesquisarMotorista = QtGui.QPushButton(frmPesagem)
        self.btnPesquisarMotorista.setGeometry(QtCore.QRect(386, 300, 136, 31))
        self.btnPesquisarMotorista.setObjectName(_fromUtf8("btnPesquisarMotorista"))
        self.lbBruto = QtGui.QLabel(frmPesagem)
        self.lbBruto.setGeometry(QtCore.QRect(123, 343, 41, 16))
        self.lbBruto.setObjectName(_fromUtf8("lbBruto"))
        self.txtBruto = QtGui.QLineEdit(frmPesagem)
        self.txtBruto.setGeometry(QtCore.QRect(120, 361, 155, 28))
        self.txtBruto.setObjectName(_fromUtf8("txtBruto"))
        self.gbPeso = QtGui.QGroupBox(frmPesagem)
        self.gbPeso.setGeometry(QtCore.QRect(10, 321, 101, 71))
        self.gbPeso.setTitle(_fromUtf8(""))
        self.gbPeso.setObjectName(_fromUtf8("gbPeso"))
        self.rbTara = QtGui.QRadioButton(self.gbPeso)
        self.rbTara.setGeometry(QtCore.QRect(15, 11, 82, 17))
        self.rbTara.setObjectName(_fromUtf8("rbTara"))
        self.rbBruto = QtGui.QRadioButton(self.gbPeso)
        self.rbBruto.setGeometry(QtCore.QRect(15, 41, 82, 17))
        self.rbBruto.setObjectName(_fromUtf8("rbBruto"))
        self.btnSalvar = QtGui.QPushButton(frmPesagem)
        self.btnSalvar.setGeometry(QtCore.QRect(220, 440, 114, 33))
        self.btnSalvar.setObjectName(_fromUtf8("btnSalvar"))
        self.btnImprimir = QtGui.QPushButton(frmPesagem)
        self.btnImprimir.setGeometry(QtCore.QRect(340, 440, 114, 33))
        self.btnImprimir.setObjectName(_fromUtf8("btnImprimir"))
        self.btnCancelar = QtGui.QPushButton(frmPesagem)
        self.btnCancelar.setGeometry(QtCore.QRect(460, 440, 114, 33))
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.tableView = QtGui.QTableView(frmPesagem)
        self.tableView.setGeometry(QtCore.QRect(9, 80, 561, 141))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.lbPesquisarNomeMotorista = QtGui.QLabel(frmPesagem)
        self.lbPesquisarNomeMotorista.setGeometry(QtCore.QRect(13, 20, 221, 16))
        self.lbPesquisarNomeMotorista.setObjectName(_fromUtf8("lbPesquisarNomeMotorista"))
        self.txtPesquisarNomeMotorista = QtGui.QLineEdit(frmPesagem)
        self.txtPesquisarNomeMotorista.setGeometry(QtCore.QRect(10, 38, 235, 28))
        self.txtPesquisarNomeMotorista.setText(_fromUtf8(""))
        self.txtPesquisarNomeMotorista.setObjectName(_fromUtf8("txtPesquisarNomeMotorista"))
        self.btnPesquisarPesagem = QtGui.QPushButton(frmPesagem)
        self.btnPesquisarPesagem.setGeometry(QtCore.QRect(250, 36, 136, 31))
        self.btnPesquisarPesagem.setObjectName(_fromUtf8("btnPesquisarPesagem"))
        self.lbNomeMotorista.setBuddy(self.txtNomeMotorista)
        self.lbVeiculo.setBuddy(self.txtVeiculo)
        self.lbPlacaVeiculo.setBuddy(self.txtPlacaVeiculo)
        self.lbBruto.setBuddy(self.txtBruto)
        self.lbPesquisarNomeMotorista.setBuddy(self.txtPesquisarNomeMotorista)

        self.retranslateUi(frmPesagem)
        QtCore.QObject.connect(self.tableView, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), frmPesagem.open)
        QtCore.QObject.connect(self.txtNomeMotorista, QtCore.SIGNAL(_fromUtf8("cursorPositionChanged(int,int)")), self.txtVeiculo.undo)
        QtCore.QObject.connect(self.txtVeiculo, QtCore.SIGNAL(_fromUtf8("cursorPositionChanged(int,int)")), self.txtPlacaVeiculo.undo)
        QtCore.QMetaObject.connectSlotsByName(frmPesagem)
        frmPesagem.setTabOrder(self.txtPesquisarNomeMotorista, self.btnPesquisarPesagem)
        frmPesagem.setTabOrder(self.btnPesquisarPesagem, self.tableView)
        frmPesagem.setTabOrder(self.tableView, self.txtNomeMotorista)
        frmPesagem.setTabOrder(self.txtNomeMotorista, self.txtVeiculo)
        frmPesagem.setTabOrder(self.txtVeiculo, self.txtPlacaVeiculo)
        frmPesagem.setTabOrder(self.txtPlacaVeiculo, self.btnPesquisarMotorista)
        frmPesagem.setTabOrder(self.btnPesquisarMotorista, self.rbTara)
        frmPesagem.setTabOrder(self.rbTara, self.rbBruto)
        frmPesagem.setTabOrder(self.rbBruto, self.txtBruto)
        frmPesagem.setTabOrder(self.txtBruto, self.btnSalvar)
        frmPesagem.setTabOrder(self.btnSalvar, self.btnImprimir)
        frmPesagem.setTabOrder(self.btnImprimir, self.btnCancelar)

    def retranslateUi(self, frmPesagem):
        frmPesagem.setWindowTitle(_translate("frmPesagem", "Pesagem", None))
        self.lbNomeMotorista.setText(_translate("frmPesagem", "NOME MOTORISTA", None))
        self.txtNomeMotorista.setWhatsThis(_translate("frmPesagem", "campo a inserção do nome no motorista", None))
        self.lbVeiculo.setText(_translate("frmPesagem", "VEICULO", None))
        self.txtVeiculo.setWhatsThis(_translate("frmPesagem", "Campo para a inserção do nome do veiculo", None))
        self.lbPlacaVeiculo.setText(_translate("frmPesagem", "PLACA VEICULO", None))
        self.txtPlacaVeiculo.setWhatsThis(_translate("frmPesagem", "Campo para a inserção das letras e numeros que contem a na placa do veiculo", None))
        self.txtPlacaVeiculo.setInputMask(_translate("frmPesagem", "aaa-0000; ", None))
        self.btnPesquisarMotorista.setWhatsThis(_translate("frmPesagem", "Botão para pesquisar o motorista", None))
        self.btnPesquisarMotorista.setText(_translate("frmPesagem", "PESQUISAR", None))
        self.lbBruto.setText(_translate("frmPesagem", "PESO", None))
        self.txtBruto.setWhatsThis(_translate("frmPesagem", "Campo para inserção do peso do veiculo", None))
        self.rbTara.setWhatsThis(_translate("frmPesagem", "Selecione este campo se o peso for a Tara do veiculo", None))
        self.rbTara.setText(_translate("frmPesagem", "TARA", None))
        self.rbBruto.setWhatsThis(_translate("frmPesagem", "Selecione este campo se o peso for o Bruto do veiculo", None))
        self.rbBruto.setText(_translate("frmPesagem", "BRUTO", None))
        self.btnSalvar.setWhatsThis(_translate("frmPesagem", "Botão para salvar a pesagem", None))
        self.btnSalvar.setText(_translate("frmPesagem", "SALVAR", None))
        self.btnImprimir.setWhatsThis(_translate("frmPesagem", "Botão para imprimir a pesagem", None))
        self.btnImprimir.setText(_translate("frmPesagem", "IMPRIMIR", None))
        self.btnCancelar.setWhatsThis(_translate("frmPesagem", "Botão para cancelar a pesagem", None))
        self.btnCancelar.setText(_translate("frmPesagem", "CANCELAR", None))
        self.tableView.setWhatsThis(_translate("frmPesagem", "Tabela do campo de pesquisa", None))
        self.lbPesquisarNomeMotorista.setText(_translate("frmPesagem", "PESQUISAR NOME MOTORISTA", None))
        self.txtPesquisarNomeMotorista.setWhatsThis(_translate("frmPesagem", "Campo para a inserção do nome do motorista para pesquisar", None))
        self.btnPesquisarPesagem.setWhatsThis(_translate("frmPesagem", "botão para pesquisar o nome do motorista", None))
        self.btnPesquisarPesagem.setText(_translate("frmPesagem", "PESQUISAR", None))

